In [3]:
from rdkit import Chem
from rdkit.Chem import Descriptors
import pandas as pd

def read_sdf_to_dataframe(sdf_file):
    molecules = []
    
    # Read SDF file with strict=False to prevent crashes
    suppl = Chem.SDMolSupplier(sdf_file, sanitize=False, removeHs=False)

    for idx, mol in enumerate(suppl):
        if mol is None:
            print(f"Skipping molecule at index {idx} due to structure issues.")
            continue  # Skip invalid molecules
        
        try:
            mol_data = {}
            
            # Attempt to sanitize the molecule
            Chem.SanitizeMol(mol, sanitizeOps=Chem.SanitizeFlags.SANITIZE_ALL)
            
            # Extract molecular properties
            mol_data["SMILES"] = Chem.MolToSmiles(mol)  # Convert to SMILES
            mol_data["Molecular Weight"] = Descriptors.ExactMolWt(mol)  # Molecular weight
            
            # Extract all available properties in the SDF file
            for prop in mol.GetPropNames():
                mol_data[prop] = mol.GetProp(prop)
            
            molecules.append(mol_data)

        except Exception as e:
            print(f"Skipping molecule at index {idx} due to error: {e}")

    # Convert the list to a Pandas DataFrame
    df = pd.DataFrame(molecules)
    return df

# Example usage
sdf_file_1 = "FLP_datasetp1.sd"
sdf_file_2 = "FLP_datasetp2.sd"
df1 = read_sdf_to_dataframe(sdf_file_1)
df2 = read_sdf_to_dataframe(sdf_file_2)

[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:28:59] Explicit valence for atom # 9 C, 6, is greater than permitted
[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] Explicit valence for atom # 72 B, 4, is greater than permitted
[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] Explicit valence for atom # 1 B, 4, is greater than permitted
[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] Explicit valence for atom # 0 B, 4, is greater than permitted
[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] Explicit valence for atom # 153 Si, 5, is greater than permitted
[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] Explicit valence for atom # 0 Si, 7, is greater than permitted
[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:28:59] Explicit valence for atom # 0 C, 6, is greater than permitted
[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] Explicit valence for atom # 0 Si, 5, is greater than permitted
[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] Explicit valence for atom # 32 N, 4, is greater than permitted
[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] Explicit valence for atom # 12 N, 4, is greater than permitted
[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] Conflicting single bond directions around double bond at index 4.
[10:28:59]   BondStereo set to STEREONONE and single bond directions set to NONE.
[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:28:59] Explicit valence for atom # 7 B, 6, is greater than permitted
[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:28:59] Can't kekulize mol.  Unkekulized atoms: 4 19 20 22 24 26 28 29 30 32 33 35 68 69 70 72 73 75
[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] Explicit valence for atom # 1 B, 4, is greater than permitted
[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:28:59] Explicit valence for atom # 6 B, 6, is greater than permitted
[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] Explicit valence for atom # 49 B, 4, is greater than permitted
[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] Explicit valence for atom # 4 N, 4, is greater than permitted
[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] Explicit valence for atom # 4 N, 4, is greater than permitted
[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:28:59] Explicit valence for atom # 0 Ga, 5, is greater than permitted
[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] Explicit valence for atom # 1 Ga, 4, is greater than permitted
[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] Explicit valence for atom # 0 In, 4, is greater than permitted
[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] Explicit valence for atom # 0 Ga, 4, is greater than permitted
[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] Explicit valence for atom # 1 H, 3, is greater than permitted
[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] Explicit valence for atom # 1 H, 3, is greater than permitted
[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] Explicit valence for atom # 1 H, 3, is greater than permitted
[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] Explicit valence for atom # 1 H, 3, is greater than permitted
[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] Explicit valence for atom # 1 H, 3, is greater than permitted
[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] Explicit valence for atom # 1 H, 3, is greater than permitted
[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] Explicit valence for atom # 21 B, 4, is greater than permitted
[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] Explicit valence for atom # 81 B, 4, is greater than permitted
[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] Explicit valence for atom # 81 B, 4, is greater than permitted
[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] Explicit valence for atom # 81 B, 4, is greater than permitted
[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] Explicit valence for atom # 81 B, 4, is greater than permitted
[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] Explicit valence for atom # 81 B, 4, is greater than permitted
[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] Explicit valence for atom # 81 B, 4, is greater than permitted
[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] Explicit valence for atom # 78 B, 4, is greater than permitted
[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] Explicit valence for atom # 113 B, 4, is greater than permitted
[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] Explicit valence for atom # 119 B, 4, is greater than permitted
[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] Explicit valence for atom # 3 N, 4, is greater than permitted
[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] Explicit valence for atom # 6 N, 4, is greater than permitted
[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] Explicit valence for atom # 6 N, 4, is greater than permitted
[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] Explicit valence for atom # 7 N, 4, is greater than permitted
[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] Explicit valence for atom # 10 N, 4, is greater than permitted
[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] Explicit valence for atom # 6 N, 4, is greater than permitted
[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] Explicit valence for atom # 9 N, 4, is greater than permitted
[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:28:59] Explicit valence for atom # 0 B, 6, is greater than permitted
[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:28:59] Explicit valence for atom # 0 B, 6, is greater than permitted
[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:28:59] Explicit valence for atom # 0 B, 6, is greater than permitted
[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:28:59] Explicit valence for atom # 0 B, 6, is greater than permitted
[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:28:59] Explicit valence for atom # 1 C, 5, is greater than permitted
[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:28:59] Explicit valence for atom # 0 C, 5, is greater than permitted
[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.

Skipping molecule at index 0 due to error: Explicit valence for atom # 9 C, 6, is greater than permitted
Skipping molecule at index 2 due to error: Explicit valence for atom # 72 B, 4, is greater than permitted
Skipping molecule at index 5 due to error: Explicit valence for atom # 1 B, 4, is greater than permitted
Skipping molecule at index 6 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 8 due to error: Explicit valence for atom # 153 Si, 5, is greater than permitted
Skipping molecule at index 12 due to error: Explicit valence for atom # 0 Si, 7, is greater than permitted
Skipping molecule at index 18 due to error: Explicit valence for atom # 0 C, 6, is greater than permitted
Skipping molecule at index 25 due to error: Explicit valence for atom # 0 Si, 5, is greater than permitted
Skipping molecule at index 29 due to error: Explicit valence for atom # 32 N, 4, is greater than permitted
Skipping molecule at index 30 due to error: Explicit valence for atom # 12 N, 4, is greater than permitted
Skipping molecule at index 37 due to error: Explicit valence for atom # 7 B, 6, is greater than permitted
Skipping molecule at index 40 due to error: Can't kekulize mol.  Unkekulized atoms: 4 19 20 22 24 26 28 29 30 32 33 35 68 69 70 72 73 75
Skipping molecule at index 43 due to error: Explicit valence for atom # 1 B, 4, is greater than permitted
Skipping molecule at index 48 due to error: Explicit valence for atom # 6 B, 6, is greater than permitted
Skipping molecule at index 50 due to error: Explicit valence for atom # 49 B, 4, is greater than permitted
Skipping molecule at index 52 due to error: Explicit valence for atom # 4 N, 4, is greater than permitted
Skipping molecule at index 53 due to error: Explicit valence for atom # 4 N, 4, is greater than permitted
Skipping molecule at index 55 due to error: Explicit valence for atom # 0 Ga, 5, is greater than permitted
Skipping molecule at index 60 due to error: Explicit valence for atom # 1 Ga, 4, is greater than permitted
Skipping molecule at index 61 due to error: Explicit valence for atom # 0 In, 4, is greater than permitted
Skipping molecule at index 62 due to error: Explicit valence for atom # 0 Ga, 4, is greater than permitted
Skipping molecule at index 64 due to error: Explicit valence for atom # 1 H, 3, is greater than permitted
Skipping molecule at index 65 due to error: Explicit valence for atom # 1 H, 3, is greater than permitted
Skipping molecule at index 66 due to error: Explicit valence for atom # 1 H, 3, is greater than permitted
Skipping molecule at index 67 due to error: Explicit valence for atom # 1 H, 3, is greater than permitted
Skipping molecule at index 68 due to error: Explicit valence for atom # 1 H, 3, is greater than permitted
Skipping molecule at index 69 due to error: Explicit valence for atom # 1 H, 3, is greater than permitted
Skipping molecule at index 70 due to error: Explicit valence for atom # 21 B, 4, is greater than permitted
Skipping molecule at index 71 due to error: Explicit valence for atom # 81 B, 4, is greater than permitted
Skipping molecule at index 72 due to error: Explicit valence for atom # 81 B, 4, is greater than permitted
Skipping molecule at index 73 due to error: Explicit valence for atom # 81 B, 4, is greater than permitted
Skipping molecule at index 74 due to error: Explicit valence for atom # 81 B, 4, is greater than permitted
Skipping molecule at index 75 due to error: Explicit valence for atom # 81 B, 4, is greater than permitted
Skipping molecule at index 76 due to error: Explicit valence for atom # 81 B, 4, is greater than permitted
Skipping molecule at index 77 due to error: Explicit valence for atom # 78 B, 4, is greater than permitted
Skipping molecule at index 80 due to error: Explicit valence for atom # 113 B, 4, is greater than permitted
Skipping molecule at index 81 due to error: Explicit valence for atom # 119 B, 4, is greater than permitted
Skipping molecule at index 83 due to error: Explicit valence for atom # 3 N, 4, is greater than permitted
Skipping molecule at index 84 due to error: Explicit valence for atom # 6 N, 4, is greater than permitted
Skipping molecule at index 86 due to error: Explicit valence for atom # 6 N, 4, is greater than permitted
Skipping molecule at index 87 due to error: Explicit valence for atom # 7 N, 4, is greater than permitted
Skipping molecule at index 88 due to error: Explicit valence for atom # 10 N, 4, is greater than permitted
Skipping molecule at index 89 due to error: Explicit valence for atom # 6 N, 4, is greater than permitted
Skipping molecule at index 90 due to error: Explicit valence for atom # 9 N, 4, is greater than permitted
Skipping molecule at index 91 due to error: Explicit valence for atom # 0 B, 6, is greater than permitted
Skipping molecule at index 92 due to error: Explicit valence for atom # 0 B, 6, is greater than permitted
Skipping molecule at index 93 due to error: Explicit valence for atom # 0 B, 6, is greater than permitted
Skipping molecule at index 94 due to error: Explicit valence for atom # 0 B, 6, is greater than permitted
Skipping molecule at index 95 due to error: Explicit valence for atom # 1 C, 5, is greater than permitted
Skipping molecule at index 96 due to error: Explicit valence for atom # 0 C, 5, is greater than permitted

[10:28:59] Explicit valence for atom # 0 B, 6, is greater than permitted
[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] Explicit valence for atom # 7 N, 4, is greater than permitted
[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] Explicit valence for atom # 75 B, 4, is greater than permitted
[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] Explicit valence for atom # 89 B, 4, is greater than permitted
[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] Explicit valence for atom # 40 B, 4, is greater than permitted
[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:28:59] Explicit valence for atom # 92 C, 6, is greater than permitted
[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:28:59] Explicit valence for atom # 68 C, 6, is greater than permitted
[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:28:59] Explicit valence for atom # 75 C, 6, is greater than permitted
[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:28:59] Explicit valence for atom # 76 C, 6, is greater than permitted
[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:28:59] Explicit valence for atom # 41 C, 6, is greater than permitted
[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:28:59] Explicit valence for atom # 76 C, 5, is greater than permitted
[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:28:59] Explicit valence for atom # 98 C, 5, is greater than permitted
[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:28:59] Explicit valence for atom # 113 C, 5, is greater than permitted
[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:28:59] Explicit valence for atom # 95 C, 5, is greater than permitted
[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:28:59] Explicit valence for atom # 66 C, 5, is greater than permitted
[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:28:59] Explicit valence for atom # 70 C, 6, is greater than permitted
[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:28:59] Explicit valence for atom # 97 C, 6, is greater than permitted
[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:28:59] Explicit valence for atom # 56 C, 6, is greater than permitted
[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:28:59] Explicit valence for atom # 73 C, 6, is greater than permitted
[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] Explicit valence for atom # 44 B, 4, is greater than permitted
[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] Explicit valence for atom # 0 B, 4, is greater than permitted
[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] Explicit valence for atom # 11 N, 4, is greater than permitted
[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] Explicit valence for atom # 2 N, 4, is greater than permitted
[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] Explicit valence for atom # 5 O, 3, is greater than permitted
[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] Explicit valence for atom # 6 N, 4, is greater than permitted
[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] Explicit valence for atom # 8 N, 4, is greater than permitted
[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] Explicit valence for atom # 21 B, 4, is greater than permitted
[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] Explicit valence for atom # 21 B, 4, is greater than permitted
[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] Explicit valence for atom # 21 B, 4, is greater than permitted
[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] Explicit valence for atom # 21 B, 4, is greater than permitted
[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] Explicit valence for atom # 21 B, 4, is greater than permitted
[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] Explicit valence for atom # 21 B, 4, is greater than permitted
[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] Explicit valence for atom # 21 B, 4, is greater than permitted
[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] Explicit valence for atom # 21 B, 4, is greater than permitted
[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] Explicit valence for atom # 21 B, 4, is greater than permitted
[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] Explicit valence for atom # 27 B, 4, is greater than permitted
[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] Explicit valence for atom # 60 B, 4, is greater than permitted
[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] Explicit valence for atom # 29 B, 4, is greater than permitted
[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] Explicit valence for atom # 61 B, 4, is greater than permitted
[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] Explicit valence for atom # 149 B, 4, is greater than permitted
[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] Explicit valence for atom # 2 B, 4, is greater than permitted
[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] Explicit valence for atom # 4 B, 4, is greater than permitted
[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] Explicit valence for atom # 4 B, 4, is greater than permitted
[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] Explicit valence for atom # 2 B, 4, is greater than permitted
[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:28:59] Explicit valence for atom # 5 C, 6, is greater than permitted
[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] Explicit valence for atom # 0 B, 4, is greater than permitted
[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] Explicit valence for atom # 0 B, 4, is greater than permitted
[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] Explicit valence for atom # 8 N, 4, is greater than permitted
[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] Explicit valence for atom # 2 N, 4, is greater than permitted
[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] Explicit valence for atom # 4 F, 2, is greater than permitted
[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] Explicit valence for atom # 0 B, 4, is greater than permitted
[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] Explicit valence for atom # 27 B, 4, is greater than permitted
[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] Explicit valence for atom # 1 B, 4, is greater than permitted
[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] Explicit valence for atom # 2 B, 4, is greater than permitted
[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] Explicit valence for atom # 2 B, 4, is greater than permitted
[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] Explicit valence for atom # 30 B, 4, is greater than permitted
[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] Explicit valence for atom # 39 B, 4, is greater than permitted
[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] Explicit valence for atom # 29 B, 4, is greater than permitted
[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] Explicit valence for atom # 56 B, 4, is greater than permitted
[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] Explicit valence for atom # 2 N, 4, is greater than permitted
[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] Explicit valence for atom # 4 N, 4, is greater than permitted
[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] Explicit valence for atom # 75 B, 4, is greater than permitted
[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] Explicit valence for atom # 69 B, 4, is greater than permitted
[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] Explicit valence for atom # 69 B, 4, is greater than permitted
[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] Explicit valence for atom # 48 B, 4, is greater than permitted
[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] Explicit valence for atom # 65 B, 4, is greater than permitted
[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] Explicit valence for atom # 67 B, 4, is greater than permitted
[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] Explicit valence for atom # 69 B, 4, is greater than permitted
[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] Explicit valence for atom # 69 B, 4, is greater than permitted
[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] Explicit valence for atom # 69 B, 4, is greater than permitted
[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] Explicit valence for atom # 54 B, 4, is greater than permitted
[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] Explicit valence for atom # 62 B, 4, is greater than permitted
[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] Explicit valence for atom # 9 B, 4, is greater than permitted
[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] Explicit valence for atom # 18 B, 4, is greater than permitted
[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:28:59] Explicit valence for atom # 6 C, 6, is greater than permitted
[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] Explicit valence for atom # 7 B, 4, is greater than permitted
[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] Explicit valence for atom # 6 B, 4, is greater than permitted
[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] Explicit valence for atom # 17 B, 4, is greater than permitted
[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] Explicit valence for atom # 2 N, 4, is greater than permitted
[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:28:59] Explicit valence for atom # 7 C, 6, is greater than permitted
[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:28:59] Explicit valence for atom # 6 C, 6, is greater than permitted
[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:28:59] Explicit valence for atom # 3 C, 6, is greater than permitted
[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:28:59] Explicit valence for atom # 6 B, 6, is greater than permitted
[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] Explicit valence for atom # 1 N, 4, is greater than permitted
[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.

Skipping molecule at index 98 due to error: Explicit valence for atom # 0 B, 6, is greater than permitted
Skipping molecule at index 100 due to error: Explicit valence for atom # 7 N, 4, is greater than permitted
Skipping molecule at index 101 due to error: Explicit valence for atom # 75 B, 4, is greater than permitted
Skipping molecule at index 102 due to error: Explicit valence for atom # 89 B, 4, is greater than permitted
Skipping molecule at index 103 due to error: Explicit valence for atom # 40 B, 4, is greater than permitted
Skipping molecule at index 105 due to error: Explicit valence for atom # 92 C, 6, is greater than permitted
Skipping molecule at index 106 due to error: Explicit valence for atom # 68 C, 6, is greater than permitted
Skipping molecule at index 107 due to error: Explicit valence for atom # 75 C, 6, is greater than permitted
Skipping molecule at index 108 due to error: Explicit valence for atom # 76 C, 6, is greater than permitted
Skipping molecule at index 109 due to error: Explicit valence for atom # 41 C, 6, is greater than permitted
Skipping molecule at index 110 due to error: Explicit valence for atom # 76 C, 5, is greater than permitted
Skipping molecule at index 111 due to error: Explicit valence for atom # 98 C, 5, is greater than permitted
Skipping molecule at index 112 due to error: Explicit valence for atom # 113 C, 5, is greater than permitted
Skipping molecule at index 113 due to error: Explicit valence for atom # 95 C, 5, is greater than permitted
Skipping molecule at index 114 due to error: Explicit valence for atom # 66 C, 5, is greater than permitted
Skipping molecule at index 115 due to error: Explicit valence for atom # 70 C, 6, is greater than permitted
Skipping molecule at index 116 due to error: Explicit valence for atom # 97 C, 6, is greater than permitted
Skipping molecule at index 117 due to error: Explicit valence for atom # 56 C, 6, is greater than permitted
Skipping molecule at index 118 due to error: Explicit valence for atom # 73 C, 6, is greater than permitted
Skipping molecule at index 119 due to error: Explicit valence for atom # 44 B, 4, is greater than permitted
Skipping molecule at index 120 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 121 due to error: Explicit valence for atom # 11 N, 4, is greater than permitted
Skipping molecule at index 122 due to error: Explicit valence for atom # 2 N, 4, is greater than permitted
Skipping molecule at index 124 due to error: Explicit valence for atom # 5 O, 3, is greater than permitted
Skipping molecule at index 125 due to error: Explicit valence for atom # 6 N, 4, is greater than permitted
Skipping molecule at index 126 due to error: Explicit valence for atom # 8 N, 4, is greater than permitted
Skipping molecule at index 127 due to error: Explicit valence for atom # 21 B, 4, is greater than permitted
Skipping molecule at index 128 due to error: Explicit valence for atom # 21 B, 4, is greater than permitted
Skipping molecule at index 129 due to error: Explicit valence for atom # 21 B, 4, is greater than permitted
Skipping molecule at index 130 due to error: Explicit valence for atom # 21 B, 4, is greater than permitted
Skipping molecule at index 131 due to error: Explicit valence for atom # 21 B, 4, is greater than permitted
Skipping molecule at index 132 due to error: Explicit valence for atom # 21 B, 4, is greater than permitted
Skipping molecule at index 133 due to error: Explicit valence for atom # 21 B, 4, is greater than permitted
Skipping molecule at index 134 due to error: Explicit valence for atom # 21 B, 4, is greater than permitted
Skipping molecule at index 135 due to error: Explicit valence for atom # 21 B, 4, is greater than permitted
Skipping molecule at index 136 due to error: Explicit valence for atom # 27 B, 4, is greater than permitted
Skipping molecule at index 137 due to error: Explicit valence for atom # 60 B, 4, is greater than permitted
Skipping molecule at index 138 due to error: Explicit valence for atom # 29 B, 4, is greater than permitted
Skipping molecule at index 139 due to error: Explicit valence for atom # 61 B, 4, is greater than permitted
Skipping molecule at index 141 due to error: Explicit valence for atom # 149 B, 4, is greater than permitted
Skipping molecule at index 142 due to error: Explicit valence for atom # 2 B, 4, is greater than permitted
Skipping molecule at index 143 due to error: Explicit valence for atom # 4 B, 4, is greater than permitted
Skipping molecule at index 144 due to error: Explicit valence for atom # 4 B, 4, is greater than permitted
Skipping molecule at index 152 due to error: Explicit valence for atom # 2 B, 4, is greater than permitted
Skipping molecule at index 154 due to error: Explicit valence for atom # 5 C, 6, is greater than permitted
Skipping molecule at index 156 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 157 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 158 due to error: Explicit valence for atom # 8 N, 4, is greater than permitted
Skipping molecule at index 159 due to error: Explicit valence for atom # 2 N, 4, is greater than permitted
Skipping molecule at index 160 due to error: Explicit valence for atom # 4 F, 2, is greater than permitted
Skipping molecule at index 161 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 162 due to error: Explicit valence for atom # 27 B, 4, is greater than permitted
Skipping molecule at index 163 due to error: Explicit valence for atom # 1 B, 4, is greater than permitted
Skipping molecule at index 164 due to error: Explicit valence for atom # 2 B, 4, is greater than permitted
Skipping molecule at index 165 due to error: Explicit valence for atom # 2 B, 4, is greater than permitted
Skipping molecule at index 166 due to error: Explicit valence for atom # 30 B, 4, is greater than permitted
Skipping molecule at index 167 due to error: Explicit valence for atom # 39 B, 4, is greater than permitted
Skipping molecule at index 168 due to error: Explicit valence for atom # 29 B, 4, is greater than permitted
Skipping molecule at index 169 due to error: Explicit valence for atom # 56 B, 4, is greater than permitted
Skipping molecule at index 170 due to error: Explicit valence for atom # 2 N, 4, is greater than permitted
Skipping molecule at index 171 due to error: Explicit valence for atom # 4 N, 4, is greater than permitted
Skipping molecule at index 172 due to error: Explicit valence for atom # 75 B, 4, is greater than permitted
Skipping molecule at index 173 due to error: Explicit valence for atom # 69 B, 4, is greater than permitted
Skipping molecule at index 174 due to error: Explicit valence for atom # 69 B, 4, is greater than permitted
Skipping molecule at index 175 due to error: Explicit valence for atom # 48 B, 4, is greater than permitted
Skipping molecule at index 176 due to error: Explicit valence for atom # 65 B, 4, is greater than permitted
Skipping molecule at index 177 due to error: Explicit valence for atom # 67 B, 4, is greater than permitted
Skipping molecule at index 178 due to error: Explicit valence for atom # 69 B, 4, is greater than permitted
Skipping molecule at index 179 due to error: Explicit valence for atom # 69 B, 4, is greater than permitted
Skipping molecule at index 180 due to error: Explicit valence for atom # 69 B, 4, is greater than permitted
Skipping molecule at index 181 due to error: Explicit valence for atom # 54 B, 4, is greater than permitted
Skipping molecule at index 182 due to error: Explicit valence for atom # 62 B, 4, is greater than permitted
Skipping molecule at index 184 due to error: Explicit valence for atom # 9 B, 4, is greater than permitted
Skipping molecule at index 185 due to error: Explicit valence for atom # 18 B, 4, is greater than permitted
Skipping molecule at index 187 due to error: Explicit valence for atom # 6 C, 6, is greater than permitted
Skipping molecule at index 189 due to error: Explicit valence for atom # 7 B, 4, is greater than permitted
Skipping molecule at index 190 due to error: Explicit valence for atom # 6 B, 4, is greater than permitted
Skipping molecule at index 191 due to error: Explicit valence for atom # 17 B, 4, is greater than permitted
Skipping molecule at index 192 due to error: Explicit valence for atom # 2 N, 4, is greater than permitted
Skipping molecule at index 196 due to error: Explicit valence for atom # 7 C, 6, is greater than permitted
Skipping molecule at index 197 due to error: Explicit valence for atom # 6 C, 6, is greater than permitted
Skipping molecule at index 198 due to error: Explicit valence for atom # 3 C, 6, is greater than permitted
Skipping molecule at index 199 due to error: Explicit valence for atom # 6 B, 6, is greater than permitted
Skipping molecule at index 201 due to error: Explicit valence for atom # 1 N, 4, is greater than permitted
Skipping molecule at index 203 due to error: Explicit valence for atom # 16 C, 5, is greater than permitted
Skipping molecule at index 204 due to error: Explicit valence for atom # 20 C, 6, is greater than permitted
Skipping molecule at index 205 due to error: Explicit valence for atom # 6 C, 6, is greater than permitted
Skipping molecule at index 206 due to error: Explicit valence for atom # 2 C, 6, is greater than permitted
Skipping molecule at index 207 due to error: Explicit valence for atom # 6 C, 6, is greater than permitted
Skipping molecule at index 208 due to error: Explicit valence for atom # 2 O, 3, is greater than permitted
Skipping molecule at index 211 due to error: Explicit valence for atom # 3 C, 6, is greater than permitted
Skipping molecule at index 213 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 214 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted

[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:28:59] Explicit valence for atom # 3 C, 6, is greater than permitted
[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] Explicit valence for atom # 0 B, 4, is greater than permitted
[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] Explicit valence for atom # 0 B, 4, is greater than permitted
[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] Explicit valence for atom # 70 B, 4, is greater than permitted
[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] Explicit valence for atom # 61 B, 4, is greater than permitted
[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] Explicit valence for atom # 58 B, 4, is greater than permitted
[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] Explicit valence for atom # 70 B, 4, is greater than permitted
[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] Explicit valence for atom # 61 B, 4, is greater than permitted
[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] Explicit valence for atom # 58 B, 4, is greater than permitted
[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] Explicit valence for atom # 3 N, 4, is greater than permitted
[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] Can't kekulize mol.  Unkekulized atoms: 13 14 16 18 20 22 23 25 27 29 31 32 34 36 38
[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] Explicit valence for atom # 25 B, 4, is greater than permitted
[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] Explicit valence for atom # 25 B, 4, is greater than permitted
[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] Explicit valence for atom # 25 B, 4, is greater than permitted
[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] Explicit valence for atom # 25 B, 4, is greater than permitted
[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:28:59] Explicit valence for atom # 25 B, 4, is greater than permitted
[10:28:59] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 67 B, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 21 B, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 26 B, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:00] Explicit valence for atom # 0 B, 6, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 1 B, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 0 B, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 32 O, 3, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:00] Explicit valence for atom # 36 C, 6, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:00] Explicit valence for atom # 7 C, 6, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 0 B, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 0 B, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 0 B, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 3 N, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 104 N, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 6 O, 3, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 0 B, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:00] Explicit valence for atom # 6 C, 5, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 1 O, 3, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 2 O, 3, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 1 O, 3, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 12 B, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 33 B, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:00] Explicit valence for atom # 2 C, 6, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 4 B, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 4 B, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 4 B, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 4 B, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 27 B, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:00] Explicit valence for atom # 9 C, 6, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:00] Explicit valence for atom # 5 C, 6, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 1 B, 5, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 2 O, 5, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 40 B, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 60 B, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 72 B, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 70 B, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 27 B, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 3 B, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 4 B, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Can't kekulize mol.  Unkekulized atoms: 72 73 75 77 78 93 94 95 97 99 100
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Can't kekulize mol.  Unkekulized atoms: 53 54 55 57 59 60 75 77 79 81 82
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Can't kekulize mol.  Unkekulized atoms: 53 55 57 59 60 75 76 77 79 81 82
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Can't kekulize mol.  Unkekulized atoms: 61 62 63 65 67 68 84 85 87 89 90
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 4 H, 2, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 31 B, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 2 B, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Can't kekulize mol.  Unkekulized atoms: 12 13 15 66 67
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 179 N, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 4 O, 3, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 49 F, 2, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 2 B, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 7 N, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 122 B, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 7 N, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 9 O, 3, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 2 O, 3, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 2 B, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 9 B, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 3 B, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 3 N, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 9 B, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:00] Explicit valence for atom # 4 B, 6, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:00] Explicit valence for atom # 4 B, 6, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 9 N, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 2 N, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 0 B, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 15 O, 3, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 3 O, 3, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 15 O, 3, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 71 F, 2, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Can't kekulize mol.  Unkekulized atoms: 121 122 124 126 128
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 51 B, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 57 B, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 1 N, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:00] Explicit valence for atom # 7 C, 6, is greater than permitted

Skipping molecule at index 216 due to error: Explicit valence for atom # 70 B, 4, is greater than permitted
Skipping molecule at index 217 due to error: Explicit valence for atom # 61 B, 4, is greater than permitted
Skipping molecule at index 218 due to error: Explicit valence for atom # 58 B, 4, is greater than permitted
Skipping molecule at index 219 due to error: Explicit valence for atom # 70 B, 4, is greater than permitted
Skipping molecule at index 220 due to error: Explicit valence for atom # 61 B, 4, is greater than permitted
Skipping molecule at index 221 due to error: Explicit valence for atom # 58 B, 4, is greater than permitted
Skipping molecule at index 222 due to error: Explicit valence for atom # 3 N, 4, is greater than permitted
Skipping molecule at index 223 due to error: Can't kekulize mol.  Unkekulized atoms: 13 14 16 18 20 22 23 25 27 29 31 32 34 36 38
Skipping molecule at index 225 due to error: Explicit valence for atom # 25 B, 4, is greater than permitted
Skipping molecule at index 226 due to error: Explicit valence for atom # 25 B, 4, is greater than permitted
Skipping molecule at index 227 due to error: Explicit valence for atom # 25 B, 4, is greater than permitted
Skipping molecule at index 229 due to error: Explicit valence for atom # 25 B, 4, is greater than permitted
Skipping molecule at index 230 due to error: Explicit valence for atom # 25 B, 4, is greater than permitted
Skipping molecule at index 231 due to error: Explicit valence for atom # 67 B, 4, is greater than permitted
Skipping molecule at index 232 due to error: Explicit valence for atom # 21 B, 4, is greater than permitted
Skipping molecule at index 233 due to error: Explicit valence for atom # 26 B, 4, is greater than permitted
Skipping molecule at index 234 due to error: Explicit valence for atom # 0 B, 6, is greater than permitted
Skipping molecule at index 235 due to error: Explicit valence for atom # 1 B, 4, is greater than permitted
Skipping molecule at index 239 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 240 due to error: Explicit valence for atom # 32 O, 3, is greater than permitted
Skipping molecule at index 241 due to error: Explicit valence for atom # 36 C, 6, is greater than permitted
Skipping molecule at index 242 due to error: Explicit valence for atom # 7 C, 6, is greater than permitted
Skipping molecule at index 243 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 244 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 245 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 246 due to error: Explicit valence for atom # 3 N, 4, is greater than permitted
Skipping molecule at index 248 due to error: Explicit valence for atom # 104 N, 4, is greater than permitted
Skipping molecule at index 249 due to error: Explicit valence for atom # 6 O, 3, is greater than permitted
Skipping molecule at index 250 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 253 due to error: Explicit valence for atom # 6 C, 5, is greater than permitted
Skipping molecule at index 254 due to error: Explicit valence for atom # 1 O, 3, is greater than permitted
Skipping molecule at index 255 due to error: Explicit valence for atom # 2 O, 3, is greater than permitted
Skipping molecule at index 256 due to error: Explicit valence for atom # 1 O, 3, is greater than permitted
Skipping molecule at index 259 due to error: Explicit valence for atom # 12 B, 4, is greater than permitted
Skipping molecule at index 260 due to error: Explicit valence for atom # 33 B, 4, is greater than permitted
Skipping molecule at index 262 due to error: Explicit valence for atom # 2 C, 6, is greater than permitted
Skipping molecule at index 263 due to error: Explicit valence for atom # 4 B, 4, is greater than permitted
Skipping molecule at index 264 due to error: Explicit valence for atom # 4 B, 4, is greater than permitted
Skipping molecule at index 265 due to error: Explicit valence for atom # 4 B, 4, is greater than permitted
Skipping molecule at index 266 due to error: Explicit valence for atom # 4 B, 4, is greater than permitted
Skipping molecule at index 267 due to error: Explicit valence for atom # 27 B, 4, is greater than permitted
Skipping molecule at index 268 due to error: Explicit valence for atom # 9 C, 6, is greater than permitted
Skipping molecule at index 269 due to error: Explicit valence for atom # 5 C, 6, is greater than permitted
Skipping molecule at index 270 due to error: Explicit valence for atom # 1 B, 5, is greater than permitted
Skipping molecule at index 271 due to error: Explicit valence for atom # 2 O, 5, is greater than permitted
Skipping molecule at index 272 due to error: Explicit valence for atom # 40 B, 4, is greater than permitted
Skipping molecule at index 273 due to error: Explicit valence for atom # 60 B, 4, is greater than permitted
Skipping molecule at index 274 due to error: Explicit valence for atom # 72 B, 4, is greater than permitted
Skipping molecule at index 275 due to error: Explicit valence for atom # 70 B, 4, is greater than permitted
Skipping molecule at index 276 due to error: Explicit valence for atom # 27 B, 4, is greater than permitted
Skipping molecule at index 277 due to error: Explicit valence for atom # 3 B, 4, is greater than permitted
Skipping molecule at index 278 due to error: Explicit valence for atom # 4 B, 4, is greater than permitted
Skipping molecule at index 279 due to error: Can't kekulize mol.  Unkekulized atoms: 72 73 75 77 78 93 94 95 97 99 100
Skipping molecule at index 280 due to error: Can't kekulize mol.  Unkekulized atoms: 53 54 55 57 59 60 75 77 79 81 82
Skipping molecule at index 281 due to error: Can't kekulize mol.  Unkekulized atoms: 53 55 57 59 60 75 76 77 79 81 82
Skipping molecule at index 282 due to error: Can't kekulize mol.  Unkekulized atoms: 61 62 63 65 67 68 84 85 87 89 90
Skipping molecule at index 283 due to error: Explicit valence for atom # 4 H, 2, is greater than permitted
Skipping molecule at index 284 due to error: Explicit valence for atom # 31 B, 4, is greater than permitted
Skipping molecule at index 285 due to error: Explicit valence for atom # 2 B, 4, is greater than permitted
Skipping molecule at index 287 due to error: Can't kekulize mol.  Unkekulized atoms: 12 13 15 66 67
Skipping molecule at index 288 due to error: Explicit valence for atom # 179 N, 4, is greater than permitted
Skipping molecule at index 289 due to error: Explicit valence for atom # 4 O, 3, is greater than permitted
Skipping molecule at index 290 due to error: Explicit valence for atom # 49 F, 2, is greater than permitted
Skipping molecule at index 291 due to error: Explicit valence for atom # 2 B, 4, is greater than permitted
Skipping molecule at index 292 due to error: Explicit valence for atom # 7 N, 4, is greater than permitted
Skipping molecule at index 293 due to error: Explicit valence for atom # 122 B, 4, is greater than permitted
Skipping molecule at index 294 due to error: Explicit valence for atom # 7 N, 4, is greater than permitted
Skipping molecule at index 296 due to error: Explicit valence for atom # 9 O, 3, is greater than permitted
Skipping molecule at index 297 due to error: Explicit valence for atom # 2 O, 3, is greater than permitted
Skipping molecule at index 303 due to error: Explicit valence for atom # 2 B, 4, is greater than permitted
Skipping molecule at index 304 due to error: Explicit valence for atom # 9 B, 4, is greater than permitted
Skipping molecule at index 305 due to error: Explicit valence for atom # 3 B, 4, is greater than permitted
Skipping molecule at index 306 due to error: Explicit valence for atom # 3 N, 4, is greater than permitted
Skipping molecule at index 307 due to error: Explicit valence for atom # 9 B, 4, is greater than permitted
Skipping molecule at index 308 due to error: Explicit valence for atom # 4 B, 6, is greater than permitted
Skipping molecule at index 309 due to error: Explicit valence for atom # 4 B, 6, is greater than permitted
Skipping molecule at index 310 due to error: Explicit valence for atom # 9 N, 4, is greater than permitted
Skipping molecule at index 311 due to error: Explicit valence for atom # 2 N, 4, is greater than permitted
Skipping molecule at index 312 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 313 due to error: Explicit valence for atom # 15 O, 3, is greater than permitted
Skipping molecule at index 314 due to error: Explicit valence for atom # 3 O, 3, is greater than permitted
Skipping molecule at index 315 due to error: Explicit valence for atom # 15 O, 3, is greater than permitted
Skipping molecule at index 316 due to error: Explicit valence for atom # 71 F, 2, is greater than permitted
Skipping molecule at index 318 due to error: Can't kekulize mol.  Unkekulized atoms: 121 122 124 126 128
Skipping molecule at index 319 due to error: Explicit valence for atom # 51 B, 4, is greater than permitted
Skipping molecule at index 320 due to error: Explicit valence for atom # 57 B, 4, is greater than permitted
Skipping molecule at index 321 due to error: Explicit valence for atom # 1 N, 4, is greater than permitted
Skipping molecule at index 325 due to error: Explicit valence for atom # 7 C, 6, is greater than permitted
Skipping molecule at index 326 due to error: Explicit valence for atom # 9 B, 4, is greater than permitted
Skipping molecule at index 328 due to error: Explicit valence for atom # 3 B, 4, is greater than permitted
Skipping molecule at index 329 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 330 due to error: Explicit valence for atom # 1 B, 4, is greater than permitted
Skipping molecule at index 331 due to error: Explicit valence for atom # 0 Sn, 6, is greater than permitted
Skipping molecule at index 332 due to error: Explicit valence for atom # 0 Sn, 6, is greater than permitted
Skipping molecule at index 333 due to error: Can't kekulize mol.  Unkekulized atoms: 6 8 10 12 14
Skipping molecule at index 334 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 336 due to error: Explicit valence for atom # 2 B, 4, is greater than permitted
Skipping molecule at index 337 due to error: Explicit valence for atom # 2 B, 4, is greater than permitted
Skipping molecule at index 338 due to error: Can't kekulize mol.  Unkekulized atoms: 10 12 14 18 20 22
Skipping molecule at index 339 due to error: Can't kekulize mol.  Unkekulized atoms: 10 12 14 18 20 22
Skipping molecule at index 340 due to error: Explicit valence for atom # 2 B, 4, is greater than permitted
Skipping molecule at index 341 due to error: Explicit valence for atom # 34 B, 4, is greater than permitted
Skipping molecule at index 343 due to error: Explicit valence for atom # 6 C, 6, is greater than permitted
Skipping molecule at index 345 due to error: Explicit valence for atom # 11 C, 6, is greater than permitted
Skipping molecule at index 346 due to error: Explicit valence for atom # 6 C, 6, is greater than permitted
Skipping molecule at index 349 due to error: Explicit valence for atom # 12 C, 6, is greater than permitted
Skipping molecule at index 351 due to error: Explicit valence for atom # 1 B, 4, is greater than permitted
Skipping molecule at index 352 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 354 due to error: Explicit valence for atom # 1 B, 4, is greater than permitted
Skipping molecule at index 355 due to error: Explicit valence for atom # 2 B, 4, is greater than permitted
Skipping molecule at index 356 due to error: Explicit valence for atom # 2 B, 4, is greater than permitted
Skipping molecule at index 357 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 358 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 359 due to error: Explicit valence for atom # 0 Si, 7, is greater than permitted
Skipping molecule at index 360 due to error: Explicit valence for atom # 10 C, 6, is greater than permitted
Skipping molecule at index 361 due to error: Explicit valence for atom # 44 B, 4, is greater than permitted
Skipping molecule at index 367 due to error: Explicit valence for atom # 2 N, 4, is greater than permitted
Skipping molecule at index 368 due to error: Explicit valence for atom # 15 N, 4, is greater than permitted
Skipping molecule at index 369 due to error: Explicit valence for atom # 7 C, 6, is greater than permitted
Skipping molecule at index 370 due to error: Explicit valence for atom # 5 F, 2, is greater than permitted
Skipping molecule at index 371 due to error: Explicit valence for atom # 33 F, 2, is greater than permitted
Skipping molecule at index 372 due to error: Explicit valence for atom # 9 B, 4, is greater than permitted
Skipping molecule at index 374 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 375 due to error: Explicit valence for atom # 1 O, 3, is greater than permitted
Skipping molecule at index 376 due to error: Explicit valence for atom # 6 B, 4, is greater than permitted
Skipping molecule at index 377 due to error: Explicit valence for atom # 6 B, 6, is greater than permitted
Skipping molecule at index 378 due to error: Explicit valence for atom # 4 B, 6, is greater than permitted
Skipping molecule at index 379 due to error: Explicit valence for atom # 4 B, 6, is greater than permitted
Skipping molecule at index 380 due to error: Explicit valence for atom # 8 C, 6, is greater than permitted
Skipping molecule at index 381 due to error: Explicit valence for atom # 6 B, 6, is greater than permitted
Skipping molecule at index 382 due to error: Explicit valence for atom # 10 C, 6, is greater than permitted
Skipping molecule at index 383 due to error: Explicit valence for atom # 6 B, 6, is greater than permitted
Skipping molecule at index 384 due to error: Explicit valence for atom # 3 B, 6, is greater than permitted
Skipping molecule at index 385 due to error: Explicit valence for atom # 95 B, 4, is greater than permitted
Skipping molecule at index 387 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 389 due to error: Explicit valence for atom # 13 N, 4, is greater than permitted
Skipping molecule at index 390 due to error: Explicit valence for atom # 3 C, 6, is greater than permitted
Skipping molecule at index 391 due to error: Explicit valence for atom # 5 B, 6, is greater than permitted
Skipping molecule at index 392 due to error: Explicit valence for atom # 7 C, 6, is greater than permitted
Skipping molecule at index 393 due to error: Explicit valence for atom # 8 C, 6, is greater than permitted
Skipping molecule at index 394 due to error: Explicit valence for atom # 2 C, 6, is greater than permitted
Skipping molecule at index 395 due to error: Explicit valence for atom # 9 C, 6, is greater than permitted
Skipping molecule at index 399 due to error: Explicit valence for atom # 6 C, 6, is greater than permitted
Skipping molecule at index 401 due to error: Explicit valence for atom # 6 C, 6, is greater than permitted
Skipping molecule at index 403 due to error: Explicit valence for atom # 6 C, 5, is greater than permitted
Skipping molecule at index 405 due to error: Explicit valence for atom # 27 C, 6, is greater than permitted

[10:29:00] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:00] Explicit valence for atom # 4 B, 6, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:00] Explicit valence for atom # 4 B, 6, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:00] Explicit valence for atom # 8 C, 6, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:00] Explicit valence for atom # 6 B, 6, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:00] Explicit valence for atom # 10 C, 6, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:00] Explicit valence for atom # 6 B, 6, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:00] Explicit valence for atom # 3 B, 6, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 95 B, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 0 B, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 13 N, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:00] Explicit valence for atom # 3 C, 6, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:00] Explicit valence for atom # 5 B, 6, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:00] Explicit valence for atom # 7 C, 6, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:00] Explicit valence for atom # 8 C, 6, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:00] Explicit valence for atom # 2 C, 6, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:00] Explicit valence for atom # 9 C, 6, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:00] Explicit valence for atom # 6 C, 6, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:00] Explicit valence for atom # 6 C, 6, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:00] Explicit valence for atom # 6 C, 5, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:00] Explicit valence for atom # 27 C, 6, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 81 B, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 11 B, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 11 B, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 39 O, 3, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 3 O, 3, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 1 O, 3, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 1 O, 3, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:00] Explicit valence for atom # 2 C, 6, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:00] Explicit valence for atom # 3 O, 3, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Can't kekulize mol.  Unkekulized atoms: 8 10 12 14 15 16 18 19 21 26 27 29 31 32 34
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 4 N, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 57 B, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 0 Al, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 0 Al, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 4 N, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 94 H, 3, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 92 H, 3, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 94 H, 2, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:00] Explicit valence for atom # 4 B, 5, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:00] Explicit valence for atom # 42 B, 6, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 0 B, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 0 B, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 37 O, 3, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 0 B, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 18 B, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 14 B, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 1 O, 3, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 4 B, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Can't kekulize mol.  Unkekulized atoms: 20 21 23 32 33 35 44 45 47 56 57 59
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 40 B, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 2 B, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 17 B, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 12 O, 3, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 12 O, 3, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 2 O, 3, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 3 O, 3, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 0 Cl, 2, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 2 O, 3, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 7 B, 5, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 0 B, 5, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 52 B, 5, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 2 O, 3, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 0 B, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 0 B, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 0 B, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 1 H, 2, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 69 H, 2, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 69 H, 2, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 2 B, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 31 B, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 8 B, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 7 N, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 9 B, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:00] Explicit valence for atom # 1 C, 5, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 28 B, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.

Skipping molecule at index 411 due to error: Explicit valence for atom # 81 B, 4, is greater than permitted
Skipping molecule at index 412 due to error: Explicit valence for atom # 11 B, 4, is greater than permitted
Skipping molecule at index 413 due to error: Explicit valence for atom # 11 B, 4, is greater than permitted
Skipping molecule at index 415 due to error: Explicit valence for atom # 39 O, 3, is greater than permitted
Skipping molecule at index 426 due to error: Explicit valence for atom # 3 O, 3, is greater than permitted
Skipping molecule at index 428 due to error: Explicit valence for atom # 1 O, 3, is greater than permitted
Skipping molecule at index 429 due to error: Explicit valence for atom # 1 O, 3, is greater than permitted
Skipping molecule at index 430 due to error: Explicit valence for atom # 2 C, 6, is greater than permitted
Skipping molecule at index 431 due to error: Explicit valence for atom # 3 O, 3, is greater than permitted
Skipping molecule at index 432 due to error: Can't kekulize mol.  Unkekulized atoms: 8 10 12 14 15 16 18 19 21 26 27 29 31 32 34
Skipping molecule at index 435 due to error: Explicit valence for atom # 4 N, 4, is greater than permitted
Skipping molecule at index 437 due to error: Explicit valence for atom # 57 B, 4, is greater than permitted
Skipping molecule at index 438 due to error: Explicit valence for atom # 0 Al, 4, is greater than permitted
Skipping molecule at index 439 due to error: Explicit valence for atom # 0 Al, 4, is greater than permitted
Skipping molecule at index 440 due to error: Explicit valence for atom # 4 N, 4, is greater than permitted
Skipping molecule at index 441 due to error: Explicit valence for atom # 94 H, 3, is greater than permitted
Skipping molecule at index 442 due to error: Explicit valence for atom # 92 H, 3, is greater than permitted
Skipping molecule at index 443 due to error: Explicit valence for atom # 94 H, 2, is greater than permitted
Skipping molecule at index 444 due to error: Explicit valence for atom # 4 B, 5, is greater than permitted
Skipping molecule at index 445 due to error: Explicit valence for atom # 42 B, 6, is greater than permitted
Skipping molecule at index 446 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 447 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 448 due to error: Explicit valence for atom # 37 O, 3, is greater than permitted
Skipping molecule at index 449 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 450 due to error: Explicit valence for atom # 18 B, 4, is greater than permitted
Skipping molecule at index 454 due to error: Explicit valence for atom # 14 B, 4, is greater than permitted
Skipping molecule at index 455 due to error: Explicit valence for atom # 1 O, 3, is greater than permitted
Skipping molecule at index 457 due to error: Explicit valence for atom # 4 B, 4, is greater than permitted
Skipping molecule at index 458 due to error: Can't kekulize mol.  Unkekulized atoms: 20 21 23 32 33 35 44 45 47 56 57 59
Skipping molecule at index 459 due to error: Explicit valence for atom # 40 B, 4, is greater than permitted
Skipping molecule at index 460 due to error: Explicit valence for atom # 2 B, 4, is greater than permitted
Skipping molecule at index 461 due to error: Explicit valence for atom # 17 B, 4, is greater than permitted
Skipping molecule at index 462 due to error: Explicit valence for atom # 12 O, 3, is greater than permitted
Skipping molecule at index 463 due to error: Explicit valence for atom # 12 O, 3, is greater than permitted
Skipping molecule at index 464 due to error: Explicit valence for atom # 2 O, 3, is greater than permitted
Skipping molecule at index 465 due to error: Explicit valence for atom # 3 O, 3, is greater than permitted
Skipping molecule at index 466 due to error: Explicit valence for atom # 0 Cl, 2, is greater than permitted
Skipping molecule at index 467 due to error: Explicit valence for atom # 2 O, 3, is greater than permitted
Skipping molecule at index 470 due to error: Explicit valence for atom # 7 B, 5, is greater than permitted
Skipping molecule at index 471 due to error: Explicit valence for atom # 0 B, 5, is greater than permitted
Skipping molecule at index 472 due to error: Explicit valence for atom # 52 B, 5, is greater than permitted
Skipping molecule at index 473 due to error: Explicit valence for atom # 2 O, 3, is greater than permitted
Skipping molecule at index 474 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 475 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 476 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 477 due to error: Explicit valence for atom # 1 H, 2, is greater than permitted
Skipping molecule at index 478 due to error: Explicit valence for atom # 69 H, 2, is greater than permitted
Skipping molecule at index 479 due to error: Explicit valence for atom # 69 H, 2, is greater than permitted
Skipping molecule at index 481 due to error: Explicit valence for atom # 2 B, 4, is greater than permitted
Skipping molecule at index 482 due to error: Explicit valence for atom # 31 B, 4, is greater than permitted
Skipping molecule at index 484 due to error: Explicit valence for atom # 8 B, 4, is greater than permitted
Skipping molecule at index 485 due to error: Explicit valence for atom # 7 N, 4, is greater than permitted
Skipping molecule at index 486 due to error: Explicit valence for atom # 9 B, 4, is greater than permitted
Skipping molecule at index 487 due to error: Explicit valence for atom # 1 C, 5, is greater than permitted
Skipping molecule at index 488 due to error: Explicit valence for atom # 28 B, 4, is greater than permitted
Skipping molecule at index 490 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 492 due to error: Explicit valence for atom # 2 B, 4, is greater than permitted
Skipping molecule at index 494 due to error: Explicit valence for atom # 7 N, 5, is greater than permitted
Skipping molecule at index 495 due to error: Explicit valence for atom # 16 C, 6, is greater than permitted
Skipping molecule at index 497 due to error: Explicit valence for atom # 63 C, 6, is greater than permitted
Skipping molecule at index 499 due to error: Explicit valence for atom # 3 C, 6, is greater than permitted
Skipping molecule at index 501 due to error: Explicit valence for atom # 62 B, 4, is greater than permitted
Skipping molecule at index 502 due to error: Explicit valence for atom # 73 B, 4, is greater than permitted
Skipping molecule at index 503 due to error: Explicit valence for atom # 61 B, 4, is greater than permitted
Skipping molecule at index 504 due to error: Can't kekulize mol.  Unkekulized atoms: 4 6 8 10 12
Skipping molecule at index 505 due to error: Explicit valence for atom # 3 B, 4, is greater than permitted
Skipping molecule at index 507 due to error: Explicit valence for atom # 4 C, 6, is greater than permitted
Skipping molecule at index 509 due to error: Explicit valence for atom # 6 B, 6, is greater than permitted
Skipping molecule at index 511 due to error: Explicit valence for atom # 8 N, 4, is greater than permitted
Skipping molecule at index 516 due to error: Explicit valence for atom # 2 F, 2, is greater than permitted
Skipping molecule at index 521 due to error: Explicit valence for atom # 0 Sn, 5, is greater than permitted
Skipping molecule at index 522 due to error: Explicit valence for atom # 38 B, 4, is greater than permitted
Skipping molecule at index 526 due to error: Explicit valence for atom # 0 C, 6, is greater than permitted
Skipping molecule at index 527 due to error: Explicit valence for atom # 5 C, 6, is greater than permitted
Skipping molecule at index 528 due to error: Explicit valence for atom # 6 C, 6, is greater than permitted
Skipping molecule at index 529 due to error: Explicit valence for atom # 8 C, 6, is greater than permitted
Skipping molecule at index 530 due to error: Explicit valence for atom # 5 C, 6, is greater than permitted
Skipping molecule at index 531 due to error: Explicit valence for atom # 5 C, 6, is greater than permitted
Skipping molecule at index 532 due to error: Explicit valence for atom # 59 C, 5, is greater than permitted
Skipping molecule at index 533 due to error: Explicit valence for atom # 33 C, 5, is greater than permitted
Skipping molecule at index 534 due to error: Explicit valence for atom # 6 C, 6, is greater than permitted
Skipping molecule at index 535 due to error: Explicit valence for atom # 16 C, 6, is greater than permitted
Skipping molecule at index 536 due to error: Explicit valence for atom # 8 C, 6, is greater than permitted
Skipping molecule at index 537 due to error: Explicit valence for atom # 6 C, 6, is greater than permitted
Skipping molecule at index 538 due to error: Explicit valence for atom # 6 C, 6, is greater than permitted
Skipping molecule at index 542 due to error: Explicit valence for atom # 6 C, 6, is greater than permitted
Skipping molecule at index 543 due to error: Explicit valence for atom # 2 C, 6, is greater than permitted
Skipping molecule at index 544 due to error: Explicit valence for atom # 4 N, 4, is greater than permitted
Skipping molecule at index 545 due to error: Explicit valence for atom # 35 B, 4, is greater than permitted
Skipping molecule at index 546 due to error: Explicit valence for atom # 64 B, 4, is greater than permitted
Skipping molecule at index 547 due to error: Explicit valence for atom # 1 N, 4, is greater than permitted
Skipping molecule at index 549 due to error: Explicit valence for atom # 2 N, 4, is greater than permitted
Skipping molecule at index 550 due to error: Explicit valence for atom # 2 N, 4, is greater than permitted
Skipping molecule at index 551 due to error: Explicit valence for atom # 3 B, 4, is greater than permitted
Skipping molecule at index 553 due to error: Explicit valence for atom # 0 B, 3, is greater than permitted
Skipping molecule at index 558 due to error: Explicit valence for atom # 79 O, 3, is greater than permitted

[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:00] Explicit valence for atom # 6 C, 6, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:00] Explicit valence for atom # 2 C, 6, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 4 N, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 35 B, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 64 B, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 1 N, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 2 N, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 2 N, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 3 B, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 0 B, 3, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 79 O, 3, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 5 B, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 4 B, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:00] Explicit valence for atom # 10 C, 6, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 5 O, 3, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 1 O, 3, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 4 O, 3, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 3 O, 3, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 13 N, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:00] Explicit valence for atom # 5 B, 6, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:00] Explicit valence for atom # 5 B, 6, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 9 B, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 82 B, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 55 B, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 29 B, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 1 N, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 0 Ga, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 37 B, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 75 B, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 156 B, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 148 B, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:00] Explicit valence for atom # 6 C, 5, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:00] Explicit valence for atom # 6 C, 5, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 0 B, 5, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 68 B, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 54 B, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 6 H, 2, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 92 B, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:00] Explicit valence for atom # 6 C, 6, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 33 B, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 33 B, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 6 B, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 33 B, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 33 B, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 33 B, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 22 B, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 33 B, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 3 O, 3, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 2 O, 3, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 8 B, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 1 B, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 2 B, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 98 N, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Can't kekulize mol.  Unkekulized atoms: 7 9 11 12 14
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 1 B, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 19 B, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 6 N, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 75 O, 3, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 11 N, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 77 O, 3, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 77 O, 3, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 64 O, 3, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 2 O, 3, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 2 O, 3, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 2 O, 3, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 18 B, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 18 B, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 2 B, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 0 S, 7, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 76 B, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 80 N, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 3 B, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:00] Explicit valence for atom # 3 Al, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:00] Explicit valence for atom # 3 Al, 5, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:00] Explicit valence for atom # 5 C, 6, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 12 B, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 3 B, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 55 B, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 55 B, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 1 B, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 55 B, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 55 B, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 116 B, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 70 O, 3, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 63 B, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 8 B, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 22 B, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 15 B, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 11 B, 4, is greater than permitted

Skipping molecule at index 563 due to error: Explicit valence for atom # 5 B, 4, is greater than permitted
Skipping molecule at index 564 due to error: Explicit valence for atom # 4 B, 4, is greater than permitted
Skipping molecule at index 565 due to error: Explicit valence for atom # 10 C, 6, is greater than permitted
Skipping molecule at index 567 due to error: Explicit valence for atom # 5 O, 3, is greater than permitted
Skipping molecule at index 568 due to error: Explicit valence for atom # 1 O, 3, is greater than permitted
Skipping molecule at index 569 due to error: Explicit valence for atom # 4 O, 3, is greater than permitted
Skipping molecule at index 570 due to error: Explicit valence for atom # 3 O, 3, is greater than permitted
Skipping molecule at index 571 due to error: Explicit valence for atom # 13 N, 4, is greater than permitted
Skipping molecule at index 572 due to error: Explicit valence for atom # 5 B, 6, is greater than permitted
Skipping molecule at index 573 due to error: Explicit valence for atom # 5 B, 6, is greater than permitted
Skipping molecule at index 574 due to error: Explicit valence for atom # 9 B, 4, is greater than permitted
Skipping molecule at index 575 due to error: Explicit valence for atom # 82 B, 4, is greater than permitted
Skipping molecule at index 576 due to error: Explicit valence for atom # 55 B, 4, is greater than permitted
Skipping molecule at index 577 due to error: Explicit valence for atom # 29 B, 4, is greater than permitted
Skipping molecule at index 579 due to error: Explicit valence for atom # 1 N, 4, is greater than permitted
Skipping molecule at index 580 due to error: Explicit valence for atom # 0 Ga, 4, is greater than permitted
Skipping molecule at index 581 due to error: Explicit valence for atom # 37 B, 4, is greater than permitted
Skipping molecule at index 582 due to error: Explicit valence for atom # 75 B, 4, is greater than permitted
Skipping molecule at index 583 due to error: Explicit valence for atom # 156 B, 4, is greater than permitted
Skipping molecule at index 584 due to error: Explicit valence for atom # 148 B, 4, is greater than permitted
Skipping molecule at index 585 due to error: Explicit valence for atom # 6 C, 5, is greater than permitted
Skipping molecule at index 586 due to error: Explicit valence for atom # 6 C, 5, is greater than permitted
Skipping molecule at index 587 due to error: Explicit valence for atom # 0 B, 5, is greater than permitted
Skipping molecule at index 589 due to error: Explicit valence for atom # 68 B, 4, is greater than permitted
Skipping molecule at index 590 due to error: Explicit valence for atom # 54 B, 4, is greater than permitted
Skipping molecule at index 591 due to error: Explicit valence for atom # 6 H, 2, is greater than permitted
Skipping molecule at index 592 due to error: Explicit valence for atom # 92 B, 4, is greater than permitted
Skipping molecule at index 593 due to error: Explicit valence for atom # 6 C, 6, is greater than permitted
Skipping molecule at index 594 due to error: Explicit valence for atom # 33 B, 4, is greater than permitted
Skipping molecule at index 595 due to error: Explicit valence for atom # 33 B, 4, is greater than permitted
Skipping molecule at index 596 due to error: Explicit valence for atom # 6 B, 4, is greater than permitted
Skipping molecule at index 597 due to error: Explicit valence for atom # 33 B, 4, is greater than permitted
Skipping molecule at index 598 due to error: Explicit valence for atom # 33 B, 4, is greater than permitted
Skipping molecule at index 599 due to error: Explicit valence for atom # 33 B, 4, is greater than permitted
Skipping molecule at index 600 due to error: Explicit valence for atom # 22 B, 4, is greater than permitted
Skipping molecule at index 601 due to error: Explicit valence for atom # 33 B, 4, is greater than permitted
Skipping molecule at index 602 due to error: Explicit valence for atom # 3 O, 3, is greater than permitted
Skipping molecule at index 603 due to error: Explicit valence for atom # 2 O, 3, is greater than permitted
Skipping molecule at index 604 due to error: Explicit valence for atom # 8 B, 4, is greater than permitted
Skipping molecule at index 605 due to error: Explicit valence for atom # 1 B, 4, is greater than permitted
Skipping molecule at index 606 due to error: Explicit valence for atom # 2 B, 4, is greater than permitted
Skipping molecule at index 608 due to error: Explicit valence for atom # 98 N, 4, is greater than permitted
Skipping molecule at index 609 due to error: Can't kekulize mol.  Unkekulized atoms: 7 9 11 12 14
Skipping molecule at index 610 due to error: Explicit valence for atom # 1 B, 4, is greater than permitted
Skipping molecule at index 612 due to error: Explicit valence for atom # 19 B, 4, is greater than permitted
Skipping molecule at index 614 due to error: Explicit valence for atom # 6 N, 4, is greater than permitted
Skipping molecule at index 616 due to error: Explicit valence for atom # 75 O, 3, is greater than permitted
Skipping molecule at index 617 due to error: Explicit valence for atom # 11 N, 4, is greater than permitted
Skipping molecule at index 618 due to error: Explicit valence for atom # 77 O, 3, is greater than permitted
Skipping molecule at index 619 due to error: Explicit valence for atom # 77 O, 3, is greater than permitted
Skipping molecule at index 620 due to error: Explicit valence for atom # 64 O, 3, is greater than permitted
Skipping molecule at index 622 due to error: Explicit valence for atom # 2 O, 3, is greater than permitted
Skipping molecule at index 623 due to error: Explicit valence for atom # 2 O, 3, is greater than permitted
Skipping molecule at index 624 due to error: Explicit valence for atom # 2 O, 3, is greater than permitted
Skipping molecule at index 625 due to error: Explicit valence for atom # 18 B, 4, is greater than permitted
Skipping molecule at index 626 due to error: Explicit valence for atom # 18 B, 4, is greater than permitted
Skipping molecule at index 627 due to error: Explicit valence for atom # 2 B, 4, is greater than permitted
Skipping molecule at index 629 due to error: Explicit valence for atom # 0 S, 7, is greater than permitted
Skipping molecule at index 630 due to error: Explicit valence for atom # 76 B, 4, is greater than permitted
Skipping molecule at index 632 due to error: Explicit valence for atom # 80 N, 4, is greater than permitted
Skipping molecule at index 633 due to error: Explicit valence for atom # 3 B, 4, is greater than permitted
Skipping molecule at index 635 due to error: Explicit valence for atom # 3 Al, 4, is greater than permitted
Skipping molecule at index 636 due to error: Explicit valence for atom # 3 Al, 5, is greater than permitted
Skipping molecule at index 637 due to error: Explicit valence for atom # 5 C, 6, is greater than permitted
Skipping molecule at index 638 due to error: Explicit valence for atom # 12 B, 4, is greater than permitted
Skipping molecule at index 639 due to error: Explicit valence for atom # 3 B, 4, is greater than permitted
Skipping molecule at index 640 due to error: Explicit valence for atom # 55 B, 4, is greater than permitted
Skipping molecule at index 642 due to error: Explicit valence for atom # 55 B, 4, is greater than permitted
Skipping molecule at index 643 due to error: Explicit valence for atom # 1 B, 4, is greater than permitted
Skipping molecule at index 644 due to error: Explicit valence for atom # 55 B, 4, is greater than permitted
Skipping molecule at index 645 due to error: Explicit valence for atom # 55 B, 4, is greater than permitted
Skipping molecule at index 646 due to error: Explicit valence for atom # 116 B, 4, is greater than permitted
Skipping molecule at index 647 due to error: Explicit valence for atom # 70 O, 3, is greater than permitted
Skipping molecule at index 649 due to error: Explicit valence for atom # 63 B, 4, is greater than permitted
Skipping molecule at index 650 due to error: Explicit valence for atom # 8 B, 4, is greater than permitted
Skipping molecule at index 651 due to error: Explicit valence for atom # 22 B, 4, is greater than permitted
Skipping molecule at index 652 due to error: Explicit valence for atom # 15 B, 4, is greater than permitted
Skipping molecule at index 654 due to error: Explicit valence for atom # 11 B, 4, is greater than permitted
Skipping molecule at index 655 due to error: Explicit valence for atom # 3 H, 2, is greater than permitted
Skipping molecule at index 656 due to error: Explicit valence for atom # 236 B, 4, is greater than permitted
Skipping molecule at index 657 due to error: Explicit valence for atom # 22 B, 4, is greater than permitted
Skipping molecule at index 658 due to error: Explicit valence for atom # 13 O, 3, is greater than permitted
Skipping molecule at index 661 due to error: Explicit valence for atom # 16 B, 4, is greater than permitted
Skipping molecule at index 662 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 663 due to error: Explicit valence for atom # 3 N, 4, is greater than permitted
Skipping molecule at index 664 due to error: Explicit valence for atom # 14 C, 6, is greater than permitted
Skipping molecule at index 666 due to error: Explicit valence for atom # 47 B, 4, is greater than permitted
Skipping molecule at index 667 due to error: Explicit valence for atom # 14 O, 3, is greater than permitted
Skipping molecule at index 668 due to error: Explicit valence for atom # 0 O, 3, is greater than permitted
Skipping molecule at index 669 due to error: Explicit valence for atom # 2 O, 3, is greater than permitted
Skipping molecule at index 670 due to error: Explicit valence for atom # 5 O, 3, is greater than permitted
Skipping molecule at index 671 due to error: Explicit valence for atom # 14 N, 4, is greater than permitted
Skipping molecule at index 673 due to error: Explicit valence for atom # 15 C, 6, is greater than permitted
Skipping molecule at index 674 due to error: Explicit valence for atom # 2 N, 4, is greater than permitted
Skipping molecule at index 675 due to error: Explicit valence for atom # 0 O, 3, is greater than permitted
Skipping molecule at index 676 due to error: Explicit valence for atom # 3 N, 4, is greater than permitted
Skipping molecule at index 677 due to error: Explicit valence for atom # 3 N, 4, is greater than permitted
Skipping molecule at index 678 due to error: Explicit valence for atom # 12 H, 3, is greater than permitted
Skipping molecule at index 679 due to error: Explicit valence for atom # 11 B, 4, is greater than permitted
Skipping molecule at index 680 due to error: Explicit valence for atom # 5 B, 4, is greater than permitted
Skipping molecule at index 681 due to error: Explicit valence for atom # 13 N, 5, is greater than permitted
Skipping molecule at index 682 due to error: Explicit valence for atom # 3 B, 4, is greater than permitted
Skipping molecule at index 683 due to error: Explicit valence for atom # 24 C, 6, is greater than permitted
Skipping molecule at index 685 due to error: Explicit valence for atom # 3 C, 6, is greater than permitted
Skipping molecule at index 686 due to error: Explicit valence for atom # 2 C, 6, is greater than permitted
Skipping molecule at index 687 due to error: Explicit valence for atom # 1 N, 4, is greater than permitted
Skipping molecule at index 688 due to error: Explicit valence for atom # 1 B, 4, is greater than permitted
Skipping molecule at index 689 due to error: Explicit valence for atom # 1 B, 4, is greater than permitted
Skipping molecule at index 690 due to error: Can't kekulize mol.  Unkekulized atoms: 5 7 9 37 39 41 45 47 49
Skipping molecule at index 691 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 692 due to error: Explicit valence for atom # 334 B, 4, is greater than permitted
Skipping molecule at index 693 due to error: Explicit valence for atom # 327 B, 4, is greater than permitted
Skipping molecule at index 694 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 695 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 696 due to error: Explicit valence for atom # 81 B, 4, is greater than permitted
Skipping molecule at index 697 due to error: Explicit valence for atom # 66 B, 4, is greater than permitted
Skipping molecule at index 698 due to error: Explicit valence for atom # 72 B, 4, is greater than permitted
Skipping molecule at index 699 due to error: Explicit valence for atom # 2 B, 4, is greater than permitted
Skipping molecule at index 700 due to error: Explicit valence for atom # 2 B, 4, is greater than permitted
Skipping molecule at index 702 due to error: Explicit valence for atom # 0 C, 5, is greater than permitted
Skipping molecule at index 703 due to error: Explicit valence for atom # 41 B, 4, is greater than permitted
Skipping molecule at index 704 due to error: Explicit valence for atom # 9 B, 4, is greater than permitted
Skipping molecule at index 705 due to error: Explicit valence for atom # 65 B, 4, is greater than permitted
Skipping molecule at index 706 due to error: Explicit valence for atom # 1 O, 3, is greater than permitted
Skipping molecule at index 707 due to error: Explicit valence for atom # 1 O, 3, is greater than permitted
Skipping molecule at index 708 due to error: Explicit valence for atom # 12 B, 5, is greater than permitted
Skipping molecule at index 709 due to error: Explicit valence for atom # 1 O, 3, is greater than permitted
Skipping molecule at index 710 due to error: Explicit valence for atom # 1 O, 3, is greater than permitted
Skipping molecule at index 711 due to error: Explicit valence for atom # 11 C, 6, is greater than permitted
Skipping molecule at index 712 due to error: Explicit valence for atom # 7 C, 6, is greater than permitted
Skipping molecule at index 713 due to error: Explicit valence for atom # 6 C, 6, is greater than permitted
Skipping molecule at index 715 due to error: Explicit valence for atom # 67 Be, 3, is greater than permitted
Skipping molecule at index 716 due to error: Explicit valence for atom # 123 B, 4, is greater than permitted
Skipping molecule at index 717 due to error: Explicit valence for atom # 92 B, 4, is greater than permitted
Skipping molecule at index 718 due to error: Explicit valence for atom # 52 B, 4, is greater than permitted
Skipping molecule at index 719 due to error: Can't kekulize mol.  Unkekulized atoms: 9 12 16 21 30
Skipping molecule at index 720 due to error: Explicit valence for atom # 38 B, 4, is greater than permitted
Skipping molecule at index 724 due to error: Explicit valence for atom # 36 B, 4, is greater than permitted
Skipping molecule at index 725 due to error: Explicit valence for atom # 27 N, 4, is greater than permitted
Skipping molecule at index 726 due to error: Explicit valence for atom # 3 N, 4, is greater than permitted
Skipping molecule at index 728 due to error: Explicit valence for atom # 9 C, 6, is greater than permitted
Skipping molecule at index 729 due to error: Explicit valence for atom # 8 C, 6, is greater than permitted
Skipping molecule at index 730 due to error: Explicit valence for atom # 37 B, 4, is greater than permitted
Skipping molecule at index 731 due to error: Explicit valence for atom # 19 B, 4, is greater than permitted
Skipping molecule at index 733 due to error: Explicit valence for atom # 77 B, 4, is greater than permitted
Skipping molecule at index 736 due to error: Explicit valence for atom # 41 B, 4, is greater than permitted
Skipping molecule at index 737 due to error: Explicit valence for atom # 5 B, 4, is greater than permitted
Skipping molecule at index 738 due to error: Explicit valence for atom # 2 N, 4, is greater than permitted
Skipping molecule at index 739 due to error: Explicit valence for atom # 31 B, 4, is greater than permitted
Skipping molecule at index 740 due to error: Explicit valence for atom # 94 B, 4, is greater than permitted
Skipping molecule at index 741 due to error: Explicit valence for atom # 39 B, 4, is greater than permitted
Skipping molecule at index 742 due to error: Explicit valence for atom # 2 B, 4, is greater than permitted
Skipping molecule at index 743 due to error: Explicit valence for atom # 31 B, 4, is greater than permitted
Skipping molecule at index 744 due to error: Explicit valence for atom # 52 B, 4, is greater than permitted
Skipping molecule at index 745 due to error: Explicit valence for atom # 94 B, 4, is greater than permitted
Skipping molecule at index 746 due to error: Explicit valence for atom # 30 B, 4, is greater than permitted

[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 65 B, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 1 O, 3, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 1 O, 3, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 12 B, 5, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 1 O, 3, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 1 O, 3, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:00] Explicit valence for atom # 11 C, 6, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:00] Explicit valence for atom # 7 C, 6, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:00] Explicit valence for atom # 6 C, 6, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 67 Be, 3, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 123 B, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 92 B, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 52 B, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Can't kekulize mol.  Unkekulized atoms: 9 12 16 21 30
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 38 B, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 36 B, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 27 N, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 3 N, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:00] Explicit valence for atom # 9 C, 6, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:00] Explicit valence for atom # 8 C, 6, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 37 B, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 19 B, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 77 B, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 41 B, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 5 B, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 2 N, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 31 B, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 94 B, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 39 B, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 2 B, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 31 B, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 52 B, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 94 B, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 30 B, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 6 B, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 3 B, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 124 B, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 67 B, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 134 B, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 134 B, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 104 B, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 39 B, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 12 B, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:00] Explicit valence for atom # 4 B, 6, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:00] Explicit valence for atom # 15 C, 6, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 7 N, 3, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:00] Explicit valence for atom # 24 C, 6, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 82 B, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Can't kekulize mol.  Unkekulized atoms: 197 199 201 203 205
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 22 O, 3, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 6 O, 3, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 1 B, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:00] Explicit valence for atom # 7 C, 6, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:00] Explicit valence for atom # 1 O, 3, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:00] Explicit valence for atom # 4 C, 6, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 1 N, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 1 B, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Can't kekulize mol.  Unkekulized atoms: 15 16 17 18 19 20 21 22 23 24
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 5 N, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 107 B, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 3 N, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 2 N, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:00] Explicit valence for atom # 1 B, 6, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 4 B, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 50 N, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 0 B, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 4 N, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 0 B, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:00] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:00] Can't kekulize mol.  Unkekulized atoms: 8 10 11 109 110
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:00] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:00] Can't kekulize mol.  Unkekulized atoms: 2 4 5 7 8
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 73 B, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 1 B, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 159 B, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 73 B, 6, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:00] Explicit valence for atom # 16 C, 6, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:00] Explicit valence for atom # 7 C, 6, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:00] Explicit valence for atom # 18 B, 6, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 13 O, 3, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.

Skipping molecule at index 747 due to error: Explicit valence for atom # 6 B, 4, is greater than permitted
Skipping molecule at index 748 due to error: Explicit valence for atom # 3 B, 4, is greater than permitted
Skipping molecule at index 749 due to error: Explicit valence for atom # 124 B, 4, is greater than permitted
Skipping molecule at index 750 due to error: Explicit valence for atom # 67 B, 4, is greater than permitted
Skipping molecule at index 751 due to error: Explicit valence for atom # 134 B, 4, is greater than permitted
Skipping molecule at index 752 due to error: Explicit valence for atom # 134 B, 4, is greater than permitted
Skipping molecule at index 753 due to error: Explicit valence for atom # 104 B, 4, is greater than permitted
Skipping molecule at index 754 due to error: Explicit valence for atom # 39 B, 4, is greater than permitted
Skipping molecule at index 755 due to error: Explicit valence for atom # 12 B, 4, is greater than permitted
Skipping molecule at index 756 due to error: Explicit valence for atom # 4 B, 6, is greater than permitted
Skipping molecule at index 757 due to error: Explicit valence for atom # 15 C, 6, is greater than permitted
Skipping molecule at index 758 due to error: Explicit valence for atom # 7 N, 3, is greater than permitted
Skipping molecule at index 759 due to error: Explicit valence for atom # 24 C, 6, is greater than permitted
Skipping molecule at index 760 due to error: Explicit valence for atom # 82 B, 4, is greater than permitted
Skipping molecule at index 761 due to error: Can't kekulize mol.  Unkekulized atoms: 197 199 201 203 205
Skipping molecule at index 764 due to error: Explicit valence for atom # 22 O, 3, is greater than permitted
Skipping molecule at index 765 due to error: Explicit valence for atom # 6 O, 3, is greater than permitted
Skipping molecule at index 771 due to error: Explicit valence for atom # 1 B, 4, is greater than permitted
Skipping molecule at index 772 due to error: Explicit valence for atom # 7 C, 6, is greater than permitted
Skipping molecule at index 773 due to error: Explicit valence for atom # 1 O, 3, is greater than permitted
Skipping molecule at index 774 due to error: Explicit valence for atom # 4 C, 6, is greater than permitted
Skipping molecule at index 775 due to error: Explicit valence for atom # 1 N, 4, is greater than permitted
Skipping molecule at index 777 due to error: Explicit valence for atom # 1 B, 4, is greater than permitted
Skipping molecule at index 778 due to error: Can't kekulize mol.  Unkekulized atoms: 15 16 17 18 19 20 21 22 23 24
Skipping molecule at index 786 due to error: Explicit valence for atom # 5 N, 4, is greater than permitted
Skipping molecule at index 788 due to error: Explicit valence for atom # 107 B, 4, is greater than permitted
Skipping molecule at index 789 due to error: Explicit valence for atom # 3 N, 4, is greater than permitted
Skipping molecule at index 790 due to error: Explicit valence for atom # 2 N, 4, is greater than permitted
Skipping molecule at index 791 due to error: Explicit valence for atom # 1 B, 6, is greater than permitted
Skipping molecule at index 792 due to error: Explicit valence for atom # 4 B, 4, is greater than permitted
Skipping molecule at index 793 due to error: Explicit valence for atom # 50 N, 4, is greater than permitted
Skipping molecule at index 795 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 796 due to error: Explicit valence for atom # 4 N, 4, is greater than permitted
Skipping molecule at index 799 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 802 due to error: Can't kekulize mol.  Unkekulized atoms: 8 10 11 109 110
Skipping molecule at index 803 due to error: Can't kekulize mol.  Unkekulized atoms: 2 4 5 7 8
Skipping molecule at index 804 due to error: Explicit valence for atom # 73 B, 4, is greater than permitted
Skipping molecule at index 805 due to error: Explicit valence for atom # 1 B, 4, is greater than permitted
Skipping molecule at index 806 due to error: Explicit valence for atom # 159 B, 4, is greater than permitted
Skipping molecule at index 807 due to error: Explicit valence for atom # 73 B, 6, is greater than permitted
Skipping molecule at index 808 due to error: Explicit valence for atom # 16 C, 6, is greater than permitted
Skipping molecule at index 809 due to error: Explicit valence for atom # 7 C, 6, is greater than permitted
Skipping molecule at index 810 due to error: Explicit valence for atom # 18 B, 6, is greater than permitted
Skipping molecule at index 811 due to error: Explicit valence for atom # 13 O, 3, is greater than permitted
Skipping molecule at index 813 due to error: Explicit valence for atom # 48 B, 4, is greater than permitted
Skipping molecule at index 814 due to error: Explicit valence for atom # 35 B, 4, is greater than permitted
Skipping molecule at index 815 due to error: Explicit valence for atom # 80 B, 4, is greater than permitted
Skipping molecule at index 816 due to error: Explicit valence for atom # 72 B, 4, is greater than permitted
Skipping molecule at index 817 due to error: Explicit valence for atom # 72 B, 4, is greater than permitted
Skipping molecule at index 820 due to error: Explicit valence for atom # 6 C, 6, is greater than permitted
Skipping molecule at index 823 due to error: Explicit valence for atom # 194 B, 4, is greater than permitted
Skipping molecule at index 824 due to error: Explicit valence for atom # 95 B, 4, is greater than permitted
Skipping molecule at index 825 due to error: Explicit valence for atom # 5 C, 6, is greater than permitted
Skipping molecule at index 826 due to error: Explicit valence for atom # 8 C, 6, is greater than permitted
Skipping molecule at index 827 due to error: Explicit valence for atom # 8 C, 6, is greater than permitted
Skipping molecule at index 828 due to error: Explicit valence for atom # 13 C, 6, is greater than permitted
Skipping molecule at index 829 due to error: Explicit valence for atom # 1 B, 6, is greater than permitted
Skipping molecule at index 830 due to error: Explicit valence for atom # 6 B, 6, is greater than permitted
Skipping molecule at index 831 due to error: Explicit valence for atom # 69 C, 6, is greater than permitted
Skipping molecule at index 832 due to error: Explicit valence for atom # 69 C, 6, is greater than permitted
Skipping molecule at index 833 due to error: Explicit valence for atom # 6 B, 6, is greater than permitted
Skipping molecule at index 834 due to error: Explicit valence for atom # 7 B, 6, is greater than permitted
Skipping molecule at index 835 due to error: Explicit valence for atom # 6 B, 6, is greater than permitted
Skipping molecule at index 843 due to error: Explicit valence for atom # 21 B, 4, is greater than permitted
Skipping molecule at index 844 due to error: Explicit valence for atom # 1 B, 4, is greater than permitted
Skipping molecule at index 845 due to error: Explicit valence for atom # 2 B, 4, is greater than permitted
Skipping molecule at index 846 due to error: Explicit valence for atom # 2 B, 4, is greater than permitted
Skipping molecule at index 847 due to error: Can't kekulize mol.  Unkekulized atoms: 9 11 13 17 19 21
Skipping molecule at index 848 due to error: Explicit valence for atom # 2 B, 4, is greater than permitted
Skipping molecule at index 849 due to error: Can't kekulize mol.  Unkekulized atoms: 9 11 13 17 19 21
Skipping molecule at index 852 due to error: Explicit valence for atom # 5 O, 3, is greater than permitted
Skipping molecule at index 853 due to error: Explicit valence for atom # 117 B, 4, is greater than permitted
Skipping molecule at index 854 due to error: Explicit valence for atom # 2 Cl, 2, is greater than permitted
Skipping molecule at index 855 due to error: Explicit valence for atom # 5 Cl, 2, is greater than permitted
Skipping molecule at index 856 due to error: Explicit valence for atom # 1 Si, 5, is greater than permitted
Skipping molecule at index 857 due to error: Explicit valence for atom # 1 Si, 5, is greater than permitted
Skipping molecule at index 858 due to error: Explicit valence for atom # 0 Si, 5, is greater than permitted
Skipping molecule at index 859 due to error: Explicit valence for atom # 1 Si, 5, is greater than permitted
Skipping molecule at index 860 due to error: Explicit valence for atom # 1 Si, 5, is greater than permitted
Skipping molecule at index 863 due to error: Explicit valence for atom # 3 N, 4, is greater than permitted
Skipping molecule at index 864 due to error: Explicit valence for atom # 23 B, 4, is greater than permitted
Skipping molecule at index 865 due to error: Explicit valence for atom # 33 B, 4, is greater than permitted
Skipping molecule at index 867 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 878 due to error: Explicit valence for atom # 55 B, 4, is greater than permitted
Skipping molecule at index 879 due to error: Explicit valence for atom # 3 B, 6, is greater than permitted
Skipping molecule at index 880 due to error: Explicit valence for atom # 2 B, 4, is greater than permitted
Skipping molecule at index 887 due to error: Explicit valence for atom # 1 O, 3, is greater than permitted
Skipping molecule at index 888 due to error: Explicit valence for atom # 3 O, 3, is greater than permitted
Skipping molecule at index 889 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 893 due to error: Explicit valence for atom # 16 B, 4, is greater than permitted
Skipping molecule at index 894 due to error: Explicit valence for atom # 55 B, 4, is greater than permitted
Skipping molecule at index 895 due to error: Explicit valence for atom # 1 N, 4, is greater than permitted
Skipping molecule at index 896 due to error: Explicit valence for atom # 2 B, 4, is greater than permitted
Skipping molecule at index 897 due to error: Explicit valence for atom # 3 B, 4, is greater than permitted
Skipping molecule at index 898 due to error: Explicit valence for atom # 27 B, 4, is greater than permitted
Skipping molecule at index 900 due to error: Explicit valence for atom # 25 B, 4, is greater than permitted
Skipping molecule at index 901 due to error: Explicit valence for atom # 25 B, 4, is greater than permitted
Skipping molecule at index 902 due to error: Explicit valence for atom # 4 C, 6, is greater than permitted
Skipping molecule at index 903 due to error: Explicit valence for atom # 29 B, 4, is greater than permitted
Skipping molecule at index 904 due to error: Explicit valence for atom # 58 B, 4, is greater than permitted
Skipping molecule at index 905 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 906 due to error: Explicit valence for atom # 70 B, 4, is greater than permitted

[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 3 N, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 23 B, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 33 B, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 0 B, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:00] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:00] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 55 B, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:00] Explicit valence for atom # 3 B, 6, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 2 B, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 1 O, 3, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 3 O, 3, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 0 B, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 16 B, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 55 B, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 1 N, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 2 B, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 3 B, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 27 B, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 25 B, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 25 B, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:00] Explicit valence for atom # 4 C, 6, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 29 B, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 58 B, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 0 B, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 70 B, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 52 B, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 33 B, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 33 B, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 33 B, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 6 B, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 5 B, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 88 B, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 10 N, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 35 B, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 11 B, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:00] Explicit valence for atom # 33 C, 6, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:00] Explicit valence for atom # 33 C, 6, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:00] Explicit valence for atom # 16 B, 6, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 26 O, 3, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:00] Explicit valence for atom # 19 C, 6, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 2 N, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 2 N, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 1 N, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 1 B, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 4 N, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 1 B, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 91 B, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 71 B, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Can't kekulize mol.  Unkekulized atoms: 57 72 89 105 127 135 143 150 175 177
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 53 B, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 8 O, 3, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 77 B, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:00] Explicit valence for atom # 4 O, 3, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 2 O, 3, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:00] Explicit valence for atom # 3 C, 6, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 65 B, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 57 B, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 73 B, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 7 N, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Can't kekulize mol.  Unkekulized atoms: 22 27 28 35 37
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:00] Explicit valence for atom # 62 B, 5, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 0 B, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 7 N, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 1 B, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 3 N, 4, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 1 F, 3, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:00] Explicit valence for atom # 1 Cl, 2, is greater than permitted
[10:29:00] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 8 B, 4, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 33 B, 4, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 5 O, 3, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:01] Explicit valence for atom # 5 B, 6, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:01] Explicit valence for atom # 6 N, 6, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:01] Explicit valence for atom # 0 Pb, 6, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 1 O, 3, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.

Skipping molecule at index 907 due to error: Explicit valence for atom # 52 B, 4, is greater than permitted
Skipping molecule at index 908 due to error: Explicit valence for atom # 33 B, 4, is greater than permitted
Skipping molecule at index 909 due to error: Explicit valence for atom # 33 B, 4, is greater than permitted
Skipping molecule at index 910 due to error: Explicit valence for atom # 33 B, 4, is greater than permitted
Skipping molecule at index 911 due to error: Explicit valence for atom # 6 B, 4, is greater than permitted
Skipping molecule at index 912 due to error: Explicit valence for atom # 5 B, 4, is greater than permitted
Skipping molecule at index 913 due to error: Explicit valence for atom # 88 B, 4, is greater than permitted
Skipping molecule at index 915 due to error: Explicit valence for atom # 10 N, 4, is greater than permitted
Skipping molecule at index 916 due to error: Explicit valence for atom # 35 B, 4, is greater than permitted
Skipping molecule at index 917 due to error: Explicit valence for atom # 11 B, 4, is greater than permitted
Skipping molecule at index 918 due to error: Explicit valence for atom # 33 C, 6, is greater than permitted
Skipping molecule at index 919 due to error: Explicit valence for atom # 33 C, 6, is greater than permitted
Skipping molecule at index 920 due to error: Explicit valence for atom # 16 B, 6, is greater than permitted
Skipping molecule at index 922 due to error: Explicit valence for atom # 26 O, 3, is greater than permitted
Skipping molecule at index 923 due to error: Explicit valence for atom # 19 C, 6, is greater than permitted
Skipping molecule at index 924 due to error: Explicit valence for atom # 2 N, 4, is greater than permitted
Skipping molecule at index 925 due to error: Explicit valence for atom # 2 N, 4, is greater than permitted
Skipping molecule at index 926 due to error: Explicit valence for atom # 1 N, 4, is greater than permitted
Skipping molecule at index 927 due to error: Explicit valence for atom # 1 B, 4, is greater than permitted
Skipping molecule at index 928 due to error: Explicit valence for atom # 4 N, 4, is greater than permitted
Skipping molecule at index 934 due to error: Explicit valence for atom # 1 B, 4, is greater than permitted
Skipping molecule at index 935 due to error: Explicit valence for atom # 91 B, 4, is greater than permitted
Skipping molecule at index 936 due to error: Explicit valence for atom # 71 B, 4, is greater than permitted
Skipping molecule at index 937 due to error: Can't kekulize mol.  Unkekulized atoms: 57 72 89 105 127 135 143 150 175 177
Skipping molecule at index 938 due to error: Explicit valence for atom # 53 B, 4, is greater than permitted
Skipping molecule at index 939 due to error: Explicit valence for atom # 8 O, 3, is greater than permitted
Skipping molecule at index 940 due to error: Explicit valence for atom # 77 B, 4, is greater than permitted
Skipping molecule at index 942 due to error: Explicit valence for atom # 4 O, 3, is greater than permitted
Skipping molecule at index 944 due to error: Explicit valence for atom # 2 O, 3, is greater than permitted
Skipping molecule at index 949 due to error: Explicit valence for atom # 3 C, 6, is greater than permitted
Skipping molecule at index 953 due to error: Explicit valence for atom # 65 B, 4, is greater than permitted
Skipping molecule at index 954 due to error: Explicit valence for atom # 57 B, 4, is greater than permitted
Skipping molecule at index 955 due to error: Explicit valence for atom # 73 B, 4, is greater than permitted
Skipping molecule at index 956 due to error: Explicit valence for atom # 7 N, 4, is greater than permitted
Skipping molecule at index 957 due to error: Can't kekulize mol.  Unkekulized atoms: 22 27 28 35 37
Skipping molecule at index 958 due to error: Explicit valence for atom # 62 B, 5, is greater than permitted
Skipping molecule at index 959 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 960 due to error: Explicit valence for atom # 7 N, 4, is greater than permitted
Skipping molecule at index 961 due to error: Explicit valence for atom # 1 B, 4, is greater than permitted
Skipping molecule at index 962 due to error: Explicit valence for atom # 3 N, 4, is greater than permitted
Skipping molecule at index 963 due to error: Explicit valence for atom # 1 F, 3, is greater than permitted
Skipping molecule at index 966 due to error: Explicit valence for atom # 1 Cl, 2, is greater than permitted
Skipping molecule at index 969 due to error: Explicit valence for atom # 8 B, 4, is greater than permitted
Skipping molecule at index 970 due to error: Explicit valence for atom # 33 B, 4, is greater than permitted
Skipping molecule at index 971 due to error: Explicit valence for atom # 5 O, 3, is greater than permitted
Skipping molecule at index 972 due to error: Explicit valence for atom # 5 B, 6, is greater than permitted
Skipping molecule at index 973 due to error: Explicit valence for atom # 6 N, 6, is greater than permitted
Skipping molecule at index 974 due to error: Explicit valence for atom # 0 Pb, 6, is greater than permitted
Skipping molecule at index 976 due to error: Explicit valence for atom # 1 O, 3, is greater than permitted
Skipping molecule at index 977 due to error: Explicit valence for atom # 4 C, 5, is greater than permitted
Skipping molecule at index 978 due to error: Explicit valence for atom # 1 O, 3, is greater than permitted
Skipping molecule at index 979 due to error: Explicit valence for atom # 56 O, 3, is greater than permitted
Skipping molecule at index 980 due to error: Explicit valence for atom # 1 O, 3, is greater than permitted
Skipping molecule at index 981 due to error: Can't kekulize mol.  Unkekulized atoms: 18 19 21 23 25
Skipping molecule at index 982 due to error: Explicit valence for atom # 2 O, 3, is greater than permitted
Skipping molecule at index 983 due to error: Explicit valence for atom # 94 B, 4, is greater than permitted
Skipping molecule at index 984 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 987 due to error: Explicit valence for atom # 1 B, 4, is greater than permitted
Skipping molecule at index 988 due to error: Explicit valence for atom # 1 B, 4, is greater than permitted
Skipping molecule at index 989 due to error: Explicit valence for atom # 1 B, 4, is greater than permitted
Skipping molecule at index 990 due to error: Can't kekulize mol.  Unkekulized atoms: 3 4 5 6 7 8 10 11 12 14 15 16 18 20 22 24 25 26 28 29 30 32 33 34 36 38 40
Skipping molecule at index 991 due to error: Explicit valence for atom # 42 B, 4, is greater than permitted
Skipping molecule at index 992 due to error: Explicit valence for atom # 3 N, 4, is greater than permitted
Skipping molecule at index 993 due to error: Explicit valence for atom # 3 B, 4, is greater than permitted
Skipping molecule at index 994 due to error: Explicit valence for atom # 8 N, 4, is greater than permitted
Skipping molecule at index 996 due to error: Explicit valence for atom # 111 B, 4, is greater than permitted
Skipping molecule at index 997 due to error: Explicit valence for atom # 73 B, 4, is greater than permitted
Skipping molecule at index 998 due to error: Explicit valence for atom # 90 B, 4, is greater than permitted
Skipping molecule at index 999 due to error: Explicit valence for atom # 73 B, 4, is greater than permitted
Skipping molecule at index 1001 due to error: Explicit valence for atom # 2 B, 4, is greater than permitted
Skipping molecule at index 1002 due to error: Explicit valence for atom # 0 Bi, 6, is greater than permitted
Skipping molecule at index 1004 due to error: Explicit valence for atom # 57 B, 4, is greater than permitted
Skipping molecule at index 1005 due to error: Explicit valence for atom # 49 B, 4, is greater than permitted
Skipping molecule at index 1006 due to error: Explicit valence for atom # 21 B, 4, is greater than permitted
Skipping molecule at index 1007 due to error: Explicit valence for atom # 9 O, 3, is greater than permitted
Skipping molecule at index 1008 due to error: Explicit valence for atom # 8 O, 3, is greater than permitted
Skipping molecule at index 1009 due to error: Explicit valence for atom # 31 B, 4, is greater than permitted
Skipping molecule at index 1010 due to error: Explicit valence for atom # 31 B, 4, is greater than permitted
Skipping molecule at index 1011 due to error: Explicit valence for atom # 15 B, 4, is greater than permitted
Skipping molecule at index 1012 due to error: Explicit valence for atom # 15 B, 4, is greater than permitted
Skipping molecule at index 1013 due to error: Explicit valence for atom # 40 B, 4, is greater than permitted
Skipping molecule at index 1014 due to error: Explicit valence for atom # 11 O, 3, is greater than permitted
Skipping molecule at index 1017 due to error: Explicit valence for atom # 21 O, 5, is greater than permitted
Skipping molecule at index 1018 due to error: Explicit valence for atom # 8 C, 6, is greater than permitted
Skipping molecule at index 1019 due to error: Explicit valence for atom # 11 C, 6, is greater than permitted
Skipping molecule at index 1020 due to error: Explicit valence for atom # 78 C, 6, is greater than permitted
Skipping molecule at index 1021 due to error: Explicit valence for atom # 7 B, 4, is greater than permitted
Skipping molecule at index 1022 due to error: Explicit valence for atom # 63 C, 5, is greater than permitted
Skipping molecule at index 1023 due to error: Explicit valence for atom # 63 C, 5, is greater than permitted
Skipping molecule at index 1024 due to error: Explicit valence for atom # 13 C, 6, is greater than permitted
Skipping molecule at index 1025 due to error: Explicit valence for atom # 17 C, 5, is greater than permitted
Skipping molecule at index 1026 due to error: Explicit valence for atom # 2 N, 4, is greater than permitted
Skipping molecule at index 1027 due to error: Explicit valence for atom # 15 N, 4, is greater than permitted
Skipping molecule at index 1028 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 1029 due to error: Explicit valence for atom # 4 B, 4, is greater than permitted
Skipping molecule at index 1030 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 1035 due to error: Explicit valence for atom # 2 B, 4, is greater than permitted
Skipping molecule at index 1036 due to error: Explicit valence for atom # 1 O, 3, is greater than permitted
Skipping molecule at index 1038 due to error: Explicit valence for atom # 134 N, 4, is greater than permitted
Skipping molecule at index 1039 due to error: Explicit valence for atom # 4 B, 4, is greater than permitted
Skipping molecule at index 1040 due to error: Explicit valence for atom # 6 N, 4, is greater than permitted
Skipping molecule at index 1041 due to error: Explicit valence for atom # 3 O, 3, is greater than permitted
Skipping molecule at index 1042 due to error: Explicit valence for atom # 3 O, 3, is greater than permitted
Skipping molecule at index 1043 due to error: Explicit valence for atom # 3 O, 3, is greater than permitted
Skipping molecule at index 1046 due to error: Explicit valence for atom # 4 B, 4, is greater than permitted

[10:29:01] Explicit valence for atom # 17 C, 5, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 2 N, 4, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 15 N, 4, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 0 B, 4, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 4 B, 4, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 0 B, 4, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 2 B, 4, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 1 O, 3, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 134 N, 4, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 4 B, 4, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 6 N, 4, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 3 O, 3, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 3 O, 3, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 3 O, 3, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 4 B, 4, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:01] Explicit valence for atom # 0 C, 6, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:01] Explicit valence for atom # 0 C, 5, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:01] Explicit valence for atom # 0 C, 5, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:01] Explicit valence for atom # 0 C, 5, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 4 B, 4, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 16 B, 4, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 0 B, 4, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 0 B, 4, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 42 B, 4, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 40 B, 4, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 42 B, 4, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 6 B, 4, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 6 B, 4, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 0 Ga, 5, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 0 Ga, 5, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 49 B, 4, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 21 O, 3, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 17 O, 3, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 2 B, 4, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 2 N, 4, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 0 B, 4, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 3 B, 4, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 1 B, 4, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Can't kekulize mol.  Unkekulized atoms: 11 13 15 16 18 19 20 22 23 25
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 0 B, 4, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 74 B, 4, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 72 B, 4, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 1 O, 3, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 1 O, 3, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 0 B, 4, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 0 B, 5, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 61 B, 4, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:01] Explicit valence for atom # 6 C, 6, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:01] Explicit valence for atom # 3 C, 6, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 3 N, 4, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 3 O, 3, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 2 O, 3, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 63 F, 3, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 4 N, 4, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 76 B, 4, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 5 N, 4, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:01] Explicit valence for atom # 13 C, 7, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:01] Explicit valence for atom # 38 B, 6, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:01] Explicit valence for atom # 0 B, 6, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:01] Explicit valence for atom # 0 C, 6, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 0 C, 5, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:01] Explicit valence for atom # 2 C, 5, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:01] Explicit valence for atom # 24 B, 6, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 8 O, 3, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 9 O, 3, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 7 N, 4, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 1 B, 4, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 1 B, 4, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Can't kekulize mol.  Unkekulized atoms: 17 18 19 20 21 22 23 24 25
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Can't kekulize mol.  Unkekulized atoms: 17 18 19 20 21 22 23 24 25
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 2 F, 2, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:01] Explicit valence for atom # 4 C, 6, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:01] Explicit valence for atom # 12 C, 5, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:01] Explicit valence for atom # 7 C, 6, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:01] Explicit valence for atom # 6 C, 6, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:01] Explicit valence for atom # 5 C, 6, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:01] Explicit valence for atom # 3 C, 6, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:01] Explicit valence for atom # 4 C, 6, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:01] Explicit valence for atom # 4 C, 6, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 8 N, 4, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 8 N, 4, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 137 N, 3, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 10 N, 4, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 22 N, 4, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 2 B, 4, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 52 B, 4, is greater than permitted

Skipping molecule at index 1049 due to error: Explicit valence for atom # 0 C, 6, is greater than permitted
Skipping molecule at index 1050 due to error: Explicit valence for atom # 0 C, 5, is greater than permitted
Skipping molecule at index 1051 due to error: Explicit valence for atom # 0 C, 5, is greater than permitted
Skipping molecule at index 1052 due to error: Explicit valence for atom # 0 C, 5, is greater than permitted
Skipping molecule at index 1053 due to error: Explicit valence for atom # 4 B, 4, is greater than permitted
Skipping molecule at index 1054 due to error: Explicit valence for atom # 16 B, 4, is greater than permitted
Skipping molecule at index 1055 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 1056 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 1058 due to error: Explicit valence for atom # 42 B, 4, is greater than permitted
Skipping molecule at index 1059 due to error: Explicit valence for atom # 40 B, 4, is greater than permitted
Skipping molecule at index 1060 due to error: Explicit valence for atom # 42 B, 4, is greater than permitted
Skipping molecule at index 1062 due to error: Explicit valence for atom # 6 B, 4, is greater than permitted
Skipping molecule at index 1063 due to error: Explicit valence for atom # 6 B, 4, is greater than permitted
Skipping molecule at index 1064 due to error: Explicit valence for atom # 0 Ga, 5, is greater than permitted
Skipping molecule at index 1065 due to error: Explicit valence for atom # 0 Ga, 5, is greater than permitted
Skipping molecule at index 1066 due to error: Explicit valence for atom # 49 B, 4, is greater than permitted
Skipping molecule at index 1067 due to error: Explicit valence for atom # 21 O, 3, is greater than permitted
Skipping molecule at index 1068 due to error: Explicit valence for atom # 17 O, 3, is greater than permitted
Skipping molecule at index 1069 due to error: Explicit valence for atom # 2 B, 4, is greater than permitted
Skipping molecule at index 1070 due to error: Explicit valence for atom # 2 N, 4, is greater than permitted
Skipping molecule at index 1071 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 1072 due to error: Explicit valence for atom # 3 B, 4, is greater than permitted
Skipping molecule at index 1074 due to error: Explicit valence for atom # 1 B, 4, is greater than permitted
Skipping molecule at index 1075 due to error: Can't kekulize mol.  Unkekulized atoms: 11 13 15 16 18 19 20 22 23 25
Skipping molecule at index 1076 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 1077 due to error: Explicit valence for atom # 74 B, 4, is greater than permitted
Skipping molecule at index 1078 due to error: Explicit valence for atom # 72 B, 4, is greater than permitted
Skipping molecule at index 1079 due to error: Explicit valence for atom # 1 O, 3, is greater than permitted
Skipping molecule at index 1080 due to error: Explicit valence for atom # 1 O, 3, is greater than permitted
Skipping molecule at index 1083 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 1084 due to error: Explicit valence for atom # 0 B, 5, is greater than permitted
Skipping molecule at index 1085 due to error: Explicit valence for atom # 61 B, 4, is greater than permitted
Skipping molecule at index 1086 due to error: Explicit valence for atom # 6 C, 6, is greater than permitted
Skipping molecule at index 1087 due to error: Explicit valence for atom # 3 C, 6, is greater than permitted
Skipping molecule at index 1088 due to error: Explicit valence for atom # 3 N, 4, is greater than permitted
Skipping molecule at index 1089 due to error: Explicit valence for atom # 3 O, 3, is greater than permitted
Skipping molecule at index 1090 due to error: Explicit valence for atom # 2 O, 3, is greater than permitted
Skipping molecule at index 1091 due to error: Explicit valence for atom # 63 F, 3, is greater than permitted
Skipping molecule at index 1092 due to error: Explicit valence for atom # 4 N, 4, is greater than permitted
Skipping molecule at index 1093 due to error: Explicit valence for atom # 76 B, 4, is greater than permitted
Skipping molecule at index 1094 due to error: Explicit valence for atom # 5 N, 4, is greater than permitted
Skipping molecule at index 1095 due to error: Explicit valence for atom # 13 C, 7, is greater than permitted
Skipping molecule at index 1097 due to error: Explicit valence for atom # 38 B, 6, is greater than permitted
Skipping molecule at index 1099 due to error: Explicit valence for atom # 0 B, 6, is greater than permitted
Skipping molecule at index 1100 due to error: Explicit valence for atom # 0 C, 6, is greater than permitted
Skipping molecule at index 1101 due to error: Explicit valence for atom # 0 C, 5, is greater than permitted
Skipping molecule at index 1102 due to error: Explicit valence for atom # 2 C, 5, is greater than permitted
Skipping molecule at index 1103 due to error: Explicit valence for atom # 24 B, 6, is greater than permitted
Skipping molecule at index 1105 due to error: Explicit valence for atom # 8 O, 3, is greater than permitted
Skipping molecule at index 1106 due to error: Explicit valence for atom # 9 O, 3, is greater than permitted
Skipping molecule at index 1107 due to error: Explicit valence for atom # 7 N, 4, is greater than permitted
Skipping molecule at index 1108 due to error: Explicit valence for atom # 1 B, 4, is greater than permitted
Skipping molecule at index 1109 due to error: Explicit valence for atom # 1 B, 4, is greater than permitted
Skipping molecule at index 1110 due to error: Can't kekulize mol.  Unkekulized atoms: 17 18 19 20 21 22 23 24 25
Skipping molecule at index 1111 due to error: Can't kekulize mol.  Unkekulized atoms: 17 18 19 20 21 22 23 24 25
Skipping molecule at index 1112 due to error: Explicit valence for atom # 2 F, 2, is greater than permitted
Skipping molecule at index 1114 due to error: Explicit valence for atom # 4 C, 6, is greater than permitted
Skipping molecule at index 1115 due to error: Explicit valence for atom # 12 C, 5, is greater than permitted
Skipping molecule at index 1116 due to error: Explicit valence for atom # 7 C, 6, is greater than permitted
Skipping molecule at index 1117 due to error: Explicit valence for atom # 6 C, 6, is greater than permitted
Skipping molecule at index 1118 due to error: Explicit valence for atom # 5 C, 6, is greater than permitted
Skipping molecule at index 1119 due to error: Explicit valence for atom # 3 C, 6, is greater than permitted
Skipping molecule at index 1120 due to error: Explicit valence for atom # 4 C, 6, is greater than permitted
Skipping molecule at index 1121 due to error: Explicit valence for atom # 4 C, 6, is greater than permitted
Skipping molecule at index 1123 due to error: Explicit valence for atom # 8 N, 4, is greater than permitted
Skipping molecule at index 1124 due to error: Explicit valence for atom # 8 N, 4, is greater than permitted
Skipping molecule at index 1125 due to error: Explicit valence for atom # 137 N, 3, is greater than permitted
Skipping molecule at index 1127 due to error: Explicit valence for atom # 10 N, 4, is greater than permitted
Skipping molecule at index 1128 due to error: Explicit valence for atom # 22 N, 4, is greater than permitted
Skipping molecule at index 1129 due to error: Explicit valence for atom # 2 B, 4, is greater than permitted
Skipping molecule at index 1130 due to error: Explicit valence for atom # 52 B, 4, is greater than permitted
Skipping molecule at index 1131 due to error: Explicit valence for atom # 1 O, 3, is greater than permitted
Skipping molecule at index 1132 due to error: Explicit valence for atom # 16 O, 3, is greater than permitted
Skipping molecule at index 1133 due to error: Explicit valence for atom # 2 O, 3, is greater than permitted
Skipping molecule at index 1137 due to error: Explicit valence for atom # 13 B, 4, is greater than permitted
Skipping molecule at index 1144 due to error: Explicit valence for atom # 0 Br, 1, is greater than permitted
Skipping molecule at index 1145 due to error: Explicit valence for atom # 72 B, 4, is greater than permitted
Skipping molecule at index 1146 due to error: Explicit valence for atom # 14 N, 4, is greater than permitted
Skipping molecule at index 1147 due to error: Explicit valence for atom # 14 N, 4, is greater than permitted
Skipping molecule at index 1148 due to error: Explicit valence for atom # 13 N, 4, is greater than permitted
Skipping molecule at index 1149 due to error: Explicit valence for atom # 17 N, 4, is greater than permitted
Skipping molecule at index 1150 due to error: Explicit valence for atom # 4 O, 3, is greater than permitted
Skipping molecule at index 1151 due to error: Explicit valence for atom # 5 N, 4, is greater than permitted
Skipping molecule at index 1152 due to error: Explicit valence for atom # 5 N, 4, is greater than permitted

[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 4 O, 3, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 5 N, 4, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 5 N, 4, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:01] Explicit valence for atom # 9 C, 5, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:01] Explicit valence for atom # 5 C, 6, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Can't kekulize mol.  Unkekulized atoms: 46 47 49 51 53
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 1 B, 4, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 85 B, 4, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 33 B, 4, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 33 B, 4, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 33 B, 4, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 5 B, 4, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 70 B, 4, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 76 B, 4, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 91 B, 4, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 20 B, 4, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:01] Explicit valence for atom # 3 B, 6, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Can't kekulize mol.  Unkekulized atoms: 1 3 5 7 9
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:01] Explicit valence for atom # 6 C, 6, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:01] Explicit valence for atom # 26 C, 6, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:01] Explicit valence for atom # 6 C, 6, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:01] Explicit valence for atom # 2 C, 6, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:01] Explicit valence for atom # 2 B, 6, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:01] Explicit valence for atom # 0 B, 6, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:01] Explicit valence for atom # 3 B, 6, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:01] Explicit valence for atom # 23 C, 6, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:01] Explicit valence for atom # 23 C, 6, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:01] Explicit valence for atom # 21 C, 6, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:01] Explicit valence for atom # 23 C, 6, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:01] Explicit valence for atom # 23 C, 6, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:01] Explicit valence for atom # 23 C, 6, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 2 B, 4, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 1 B, 4, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 65 B, 4, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 46 B, 4, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 63 B, 4, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 40 B, 4, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 10 H, 2, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Can't kekulize mol.  Unkekulized atoms: 13 14 15 16 17
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 0 B, 4, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 1 B, 4, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 2 B, 4, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 3 N, 5, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 16 O, 3, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 0 B, 4, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 0 B, 4, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 0 B, 4, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 0 B, 4, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 0 B, 4, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 0 B, 4, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 3 B, 4, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 91 B, 4, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 109 B, 4, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 25 B, 4, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 1 B, 4, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:01] Explicit valence for atom # 4 B, 5, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 3 N, 4, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:01] Explicit valence for atom # 3 C, 6, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:01] Explicit valence for atom # 1 N, 4, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 13 O, 3, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 2 O, 3, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 37 B, 4, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 14 N, 4, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 3 O, 3, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 3 O, 3, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 93 B, 4, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:01] Explicit valence for atom # 28 B, 6, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:01] Explicit valence for atom # 46 B, 5, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 4 B, 4, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 3 N, 4, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 3 N, 4, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 7 N, 4, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 10 N, 4, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 2 O, 3, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 3 O, 3, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 21 B, 4, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:01] Explicit valence for atom # 0 C, 6, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Can't kekulize mol.  Unkekulized atoms: 2 3
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 4 O, 3, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 2 O, 3, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 3 O, 3, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 3 B, 4, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 12 B, 4, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 40 B, 4, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:01] Explicit valence for atom # 0 C, 5, is greater than permitted

Skipping molecule at index 1156 due to error: Explicit valence for atom # 9 C, 5, is greater than permitted
Skipping molecule at index 1157 due to error: Explicit valence for atom # 5 C, 6, is greater than permitted
Skipping molecule at index 1158 due to error: Can't kekulize mol.  Unkekulized atoms: 46 47 49 51 53
Skipping molecule at index 1159 due to error: Explicit valence for atom # 1 B, 4, is greater than permitted
Skipping molecule at index 1160 due to error: Explicit valence for atom # 85 B, 4, is greater than permitted
Skipping molecule at index 1161 due to error: Explicit valence for atom # 33 B, 4, is greater than permitted
Skipping molecule at index 1162 due to error: Explicit valence for atom # 33 B, 4, is greater than permitted
Skipping molecule at index 1163 due to error: Explicit valence for atom # 33 B, 4, is greater than permitted
Skipping molecule at index 1164 due to error: Explicit valence for atom # 5 B, 4, is greater than permitted
Skipping molecule at index 1165 due to error: Explicit valence for atom # 70 B, 4, is greater than permitted
Skipping molecule at index 1166 due to error: Explicit valence for atom # 76 B, 4, is greater than permitted
Skipping molecule at index 1168 due to error: Explicit valence for atom # 91 B, 4, is greater than permitted
Skipping molecule at index 1170 due to error: Explicit valence for atom # 20 B, 4, is greater than permitted
Skipping molecule at index 1171 due to error: Explicit valence for atom # 3 B, 6, is greater than permitted
Skipping molecule at index 1172 due to error: Can't kekulize mol.  Unkekulized atoms: 1 3 5 7 9
Skipping molecule at index 1173 due to error: Explicit valence for atom # 6 C, 6, is greater than permitted
Skipping molecule at index 1174 due to error: Explicit valence for atom # 26 C, 6, is greater than permitted
Skipping molecule at index 1175 due to error: Explicit valence for atom # 6 C, 6, is greater than permitted
Skipping molecule at index 1176 due to error: Explicit valence for atom # 2 C, 6, is greater than permitted
Skipping molecule at index 1177 due to error: Explicit valence for atom # 2 B, 6, is greater than permitted
Skipping molecule at index 1178 due to error: Explicit valence for atom # 0 B, 6, is greater than permitted
Skipping molecule at index 1180 due to error: Explicit valence for atom # 3 B, 6, is greater than permitted
Skipping molecule at index 1181 due to error: Explicit valence for atom # 23 C, 6, is greater than permitted
Skipping molecule at index 1182 due to error: Explicit valence for atom # 23 C, 6, is greater than permitted
Skipping molecule at index 1183 due to error: Explicit valence for atom # 21 C, 6, is greater than permitted
Skipping molecule at index 1184 due to error: Explicit valence for atom # 23 C, 6, is greater than permitted
Skipping molecule at index 1185 due to error: Explicit valence for atom # 23 C, 6, is greater than permitted
Skipping molecule at index 1186 due to error: Explicit valence for atom # 23 C, 6, is greater than permitted
Skipping molecule at index 1187 due to error: Explicit valence for atom # 2 B, 4, is greater than permitted
Skipping molecule at index 1188 due to error: Explicit valence for atom # 1 B, 4, is greater than permitted
Skipping molecule at index 1189 due to error: Explicit valence for atom # 65 B, 4, is greater than permitted
Skipping molecule at index 1190 due to error: Explicit valence for atom # 46 B, 4, is greater than permitted
Skipping molecule at index 1191 due to error: Explicit valence for atom # 63 B, 4, is greater than permitted
Skipping molecule at index 1192 due to error: Explicit valence for atom # 40 B, 4, is greater than permitted
Skipping molecule at index 1193 due to error: Explicit valence for atom # 10 H, 2, is greater than permitted
Skipping molecule at index 1194 due to error: Can't kekulize mol.  Unkekulized atoms: 13 14 15 16 17
Skipping molecule at index 1196 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 1197 due to error: Explicit valence for atom # 1 B, 4, is greater than permitted
Skipping molecule at index 1198 due to error: Explicit valence for atom # 2 B, 4, is greater than permitted
Skipping molecule at index 1199 due to error: Explicit valence for atom # 3 N, 5, is greater than permitted
Skipping molecule at index 1200 due to error: Explicit valence for atom # 16 O, 3, is greater than permitted
Skipping molecule at index 1201 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 1202 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 1203 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 1204 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 1205 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 1206 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 1207 due to error: Explicit valence for atom # 3 B, 4, is greater than permitted
Skipping molecule at index 1208 due to error: Explicit valence for atom # 91 B, 4, is greater than permitted
Skipping molecule at index 1209 due to error: Explicit valence for atom # 109 B, 4, is greater than permitted
Skipping molecule at index 1210 due to error: Explicit valence for atom # 25 B, 4, is greater than permitted
Skipping molecule at index 1211 due to error: Explicit valence for atom # 1 B, 4, is greater than permitted
Skipping molecule at index 1212 due to error: Explicit valence for atom # 4 B, 5, is greater than permitted
Skipping molecule at index 1213 due to error: Explicit valence for atom # 3 N, 4, is greater than permitted
Skipping molecule at index 1214 due to error: Explicit valence for atom # 3 C, 6, is greater than permitted
Skipping molecule at index 1215 due to error: Explicit valence for atom # 1 N, 4, is greater than permitted
Skipping molecule at index 1216 due to error: Explicit valence for atom # 13 O, 3, is greater than permitted
Skipping molecule at index 1217 due to error: Explicit valence for atom # 2 O, 3, is greater than permitted
Skipping molecule at index 1218 due to error: Explicit valence for atom # 37 B, 4, is greater than permitted
Skipping molecule at index 1219 due to error: Explicit valence for atom # 14 N, 4, is greater than permitted
Skipping molecule at index 1220 due to error: Explicit valence for atom # 3 O, 3, is greater than permitted
Skipping molecule at index 1223 due to error: Explicit valence for atom # 3 O, 3, is greater than permitted
Skipping molecule at index 1224 due to error: Explicit valence for atom # 93 B, 4, is greater than permitted
Skipping molecule at index 1225 due to error: Explicit valence for atom # 28 B, 6, is greater than permitted
Skipping molecule at index 1226 due to error: Explicit valence for atom # 46 B, 5, is greater than permitted
Skipping molecule at index 1228 due to error: Explicit valence for atom # 4 B, 4, is greater than permitted
Skipping molecule at index 1229 due to error: Explicit valence for atom # 3 N, 4, is greater than permitted
Skipping molecule at index 1230 due to error: Explicit valence for atom # 3 N, 4, is greater than permitted
Skipping molecule at index 1231 due to error: Explicit valence for atom # 7 N, 4, is greater than permitted
Skipping molecule at index 1232 due to error: Explicit valence for atom # 10 N, 4, is greater than permitted
Skipping molecule at index 1234 due to error: Explicit valence for atom # 2 O, 3, is greater than permitted
Skipping molecule at index 1235 due to error: Explicit valence for atom # 3 O, 3, is greater than permitted
Skipping molecule at index 1236 due to error: Explicit valence for atom # 21 B, 4, is greater than permitted
Skipping molecule at index 1239 due to error: Explicit valence for atom # 0 C, 6, is greater than permitted
Skipping molecule at index 1243 due to error: Can't kekulize mol.  Unkekulized atoms: 2 3
Skipping molecule at index 1244 due to error: Explicit valence for atom # 4 O, 3, is greater than permitted
Skipping molecule at index 1245 due to error: Explicit valence for atom # 2 O, 3, is greater than permitted
Skipping molecule at index 1246 due to error: Explicit valence for atom # 3 O, 3, is greater than permitted
Skipping molecule at index 1247 due to error: Explicit valence for atom # 3 B, 4, is greater than permitted
Skipping molecule at index 1248 due to error: Explicit valence for atom # 12 B, 4, is greater than permitted
Skipping molecule at index 1249 due to error: Explicit valence for atom # 40 B, 4, is greater than permitted
Skipping molecule at index 1252 due to error: Explicit valence for atom # 0 C, 5, is greater than permitted
Skipping molecule at index 1253 due to error: Explicit valence for atom # 0 C, 5, is greater than permitted
Skipping molecule at index 1254 due to error: Explicit valence for atom # 236 B, 4, is greater than permitted
Skipping molecule at index 1257 due to error: Explicit valence for atom # 41 H, 2, is greater than permitted
Skipping molecule at index 1258 due to error: Explicit valence for atom # 2 B, 4, is greater than permitted
Skipping molecule at index 1261 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 1262 due to error: Explicit valence for atom # 43 B, 4, is greater than permitted
Skipping molecule at index 1263 due to error: Explicit valence for atom # 22 B, 4, is greater than permitted
Skipping molecule at index 1264 due to error: Explicit valence for atom # 22 B, 4, is greater than permitted
Skipping molecule at index 1265 due to error: Explicit valence for atom # 41 B, 4, is greater than permitted
Skipping molecule at index 1267 due to error: Explicit valence for atom # 1 B, 4, is greater than permitted
Skipping molecule at index 1268 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 1269 due to error: Explicit valence for atom # 0 Si, 5, is greater than permitted
Skipping molecule at index 1271 due to error: Explicit valence for atom # 3 O, 3, is greater than permitted
Skipping molecule at index 1272 due to error: Explicit valence for atom # 3 O, 3, is greater than permitted
Skipping molecule at index 1273 due to error: Explicit valence for atom # 3 O, 3, is greater than permitted
Skipping molecule at index 1274 due to error: Explicit valence for atom # 8 O, 3, is greater than permitted
Skipping molecule at index 1275 due to error: Explicit valence for atom # 3 O, 3, is greater than permitted
Skipping molecule at index 1276 due to error: Explicit valence for atom # 3 O, 3, is greater than permitted
Skipping molecule at index 1277 due to error: Explicit valence for atom # 3 O, 3, is greater than permitted
Skipping molecule at index 1278 due to error: Explicit valence for atom # 3 O, 3, is greater than permitted
Skipping molecule at index 1279 due to error: Explicit valence for atom # 36 B, 4, is greater than permitted
Skipping molecule at index 1280 due to error: Explicit valence for atom # 24 B, 4, is greater than permitted
Skipping molecule at index 1281 due to error: Explicit valence for atom # 1 C, 5, is greater than permitted
Skipping molecule at index 1282 due to error: Explicit valence for atom # 7 O, 3, is greater than permitted
Skipping molecule at index 1283 due to error: Explicit valence for atom # 80 B, 4, is greater than permitted
Skipping molecule at index 1284 due to error: Explicit valence for atom # 7 N, 4, is greater than permitted
Skipping molecule at index 1285 due to error: Explicit valence for atom # 1 B, 4, is greater than permitted
Skipping molecule at index 1286 due to error: Explicit valence for atom # 3 B, 4, is greater than permitted
Skipping molecule at index 1287 due to error: Explicit valence for atom # 2 B, 4, is greater than permitted
Skipping molecule at index 1289 due to error: Explicit valence for atom # 28 B, 4, is greater than permitted
Skipping molecule at index 1290 due to error: Explicit valence for atom # 41 B, 4, is greater than permitted
Skipping molecule at index 1291 due to error: Explicit valence for atom # 100 B, 4, is greater than permitted
Skipping molecule at index 1292 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 1293 due to error: Explicit valence for atom # 64 B, 4, is greater than permitted
Skipping molecule at index 1294 due to error: Explicit valence for atom # 71 B, 4, is greater than permitted
Skipping molecule at index 1295 due to error: Explicit valence for atom # 85 B, 4, is greater than permitted
Skipping molecule at index 1296 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 1298 due to error: Explicit valence for atom # 99 B, 4, is greater than permitted
Skipping molecule at index 1299 due to error: Explicit valence for atom # 55 B, 4, is greater than permitted
Skipping molecule at index 1300 due to error: Explicit valence for atom # 98 B, 4, is greater than permitted
Skipping molecule at index 1301 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 1302 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 1303 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 1304 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 1305 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 1306 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 1307 due to error: Explicit valence for atom # 58 B, 4, is greater than permitted
Skipping molecule at index 1308 due to error: Explicit valence for atom # 58 B, 4, is greater than permitted
Skipping molecule at index 1309 due to error: Explicit valence for atom # 7 N, 4, is greater than permitted
Skipping molecule at index 1310 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 1311 due to error: Explicit valence for atom # 0 B, 5, is greater than permitted
Skipping molecule at index 1312 due to error: Explicit valence for atom # 3 B, 4, is greater than permitted
Skipping molecule at index 1319 due to error: Explicit valence for atom # 4 O, 3, is greater than permitted
Skipping molecule at index 1320 due to error: Explicit valence for atom # 8 O, 3, is greater than permitted
Skipping molecule at index 1322 due to error: Explicit valence for atom # 3 C, 6, is greater than permitted
Skipping molecule at index 1323 due to error: Explicit valence for atom # 2 B, 4, is greater than permitted
Skipping molecule at index 1324 due to error: Can't kekulize mol.  Unkekulized atoms: 96 98 100 102 104
Skipping molecule at index 1325 due to error: Explicit valence for atom # 2 B, 4, is greater than permitted
Skipping molecule at index 1327 due to error: Explicit valence for atom # 7 B, 4, is greater than permitted
Skipping molecule at index 1328 due to error: Explicit valence for atom # 7 B, 4, is greater than permitted
Skipping molecule at index 1329 due to error: Explicit valence for atom # 137 B, 4, is greater than permitted
Skipping molecule at index 1330 due to error: Explicit valence for atom # 95 B, 4, is greater than permitted
Skipping molecule at index 1331 due to error: Explicit valence for atom # 2 O, 3, is greater than permitted
Skipping molecule at index 1332 due to error: Explicit valence for atom # 2 O, 3, is greater than permitted
Skipping molecule at index 1333 due to error: Explicit valence for atom # 62 B, 4, is greater than permitted
Skipping molecule at index 1334 due to error: Explicit valence for atom # 7 B, 4, is greater than permitted
Skipping molecule at index 1335 due to error: Explicit valence for atom # 11 C, 6, is greater than permitted
Skipping molecule at index 1336 due to error: Explicit valence for atom # 20 C, 6, is greater than permitted
Skipping molecule at index 1337 due to error: Explicit valence for atom # 102 B, 4, is greater than permitted
Skipping molecule at index 1341 due to error: Explicit valence for atom # 127 B, 4, is greater than permitted
Skipping molecule at index 1342 due to error: Explicit valence for atom # 2 O, 3, is greater than permitted
Skipping molecule at index 1343 due to error: Explicit valence for atom # 70 B, 4, is greater than permitted
Skipping molecule at index 1344 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 1345 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 1346 due to error: Explicit valence for atom # 0 N, 4, is greater than permitted

[10:29:01] Explicit valence for atom # 2 B, 4, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 7 B, 4, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 7 B, 4, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 137 B, 4, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 95 B, 4, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:01] Explicit valence for atom # 2 O, 3, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:01] Explicit valence for atom # 2 O, 3, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 62 B, 4, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 7 B, 4, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:01] Explicit valence for atom # 11 C, 6, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:01] Explicit valence for atom # 20 C, 6, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 102 B, 4, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 127 B, 4, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 2 O, 3, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 70 B, 4, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 0 B, 4, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 0 B, 4, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 0 N, 4, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:01] Explicit valence for atom # 32 C, 6, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:01] Explicit valence for atom # 32 C, 6, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 2 N, 4, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 7 N, 5, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 10 B, 4, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 2 B, 4, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 4 B, 4, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:01] Explicit valence for atom # 3 C, 6, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:01] Explicit valence for atom # 6 C, 6, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 28 N, 4, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 0 N, 4, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 10 O, 3, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 0 B, 4, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:01] Explicit valence for atom # 29 B, 6, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:01] Explicit valence for atom # 58 B, 5, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 0 B, 4, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 4 O, 3, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 8 O, 3, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 8 O, 3, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:01] Explicit valence for atom # 1 O, 3, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 0 B, 4, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 0 B, 4, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 0 B, 4, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 5 N, 4, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:01] Explicit valence for atom # 1 C, 6, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:01] Explicit valence for atom # 0 C, 6, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 12 O, 3, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 20 O, 3, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 174 B, 4, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 174 B, 4, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 157 B, 4, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 170 B, 4, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 201 B, 4, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 3 N, 4, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:01] Explicit valence for atom # 0 C, 6, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 0 B, 4, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:01] Explicit valence for atom # 4 C, 6, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 5 N, 4, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:01] Explicit valence for atom # 9 O, 3, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 3 O, 3, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Can't kekulize mol.  Unkekulized atoms: 156 157 159 161 163
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 207 B, 4, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 1 B, 4, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 0 B, 4, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 1 B, 4, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 1 B, 4, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 47 B, 4, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 47 B, 4, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 9 B, 4, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 9 B, 4, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 9 B, 4, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 9 B, 4, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 9 B, 4, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 71 B, 4, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 5 B, 4, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 17 O, 3, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:01] Explicit valence for atom # 13 C, 6, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 4 F, 2, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 70 B, 4, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 73 B, 4, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 1 B, 4, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 0 B, 4, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 82 B, 4, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 124 B, 4, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 142 B, 4, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Can't kekulize mol.  Unkekulized atoms: 38 39 41 43 45

Skipping molecule at index 1352 due to error: Explicit valence for atom # 32 C, 6, is greater than permitted
Skipping molecule at index 1354 due to error: Explicit valence for atom # 32 C, 6, is greater than permitted
Skipping molecule at index 1355 due to error: Explicit valence for atom # 2 N, 4, is greater than permitted
Skipping molecule at index 1357 due to error: Explicit valence for atom # 7 N, 5, is greater than permitted
Skipping molecule at index 1358 due to error: Explicit valence for atom # 10 B, 4, is greater than permitted
Skipping molecule at index 1359 due to error: Explicit valence for atom # 2 B, 4, is greater than permitted
Skipping molecule at index 1360 due to error: Explicit valence for atom # 4 B, 4, is greater than permitted
Skipping molecule at index 1361 due to error: Explicit valence for atom # 3 C, 6, is greater than permitted
Skipping molecule at index 1362 due to error: Explicit valence for atom # 6 C, 6, is greater than permitted
Skipping molecule at index 1367 due to error: Explicit valence for atom # 28 N, 4, is greater than permitted
Skipping molecule at index 1368 due to error: Explicit valence for atom # 0 N, 4, is greater than permitted
Skipping molecule at index 1369 due to error: Explicit valence for atom # 10 O, 3, is greater than permitted
Skipping molecule at index 1371 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 1372 due to error: Explicit valence for atom # 29 B, 6, is greater than permitted
Skipping molecule at index 1373 due to error: Explicit valence for atom # 58 B, 5, is greater than permitted
Skipping molecule at index 1374 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 1376 due to error: Explicit valence for atom # 4 O, 3, is greater than permitted
Skipping molecule at index 1377 due to error: Explicit valence for atom # 8 O, 3, is greater than permitted
Skipping molecule at index 1378 due to error: Explicit valence for atom # 8 O, 3, is greater than permitted
Skipping molecule at index 1379 due to error: Explicit valence for atom # 1 O, 3, is greater than permitted
Skipping molecule at index 1380 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 1381 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 1382 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 1383 due to error: Explicit valence for atom # 5 N, 4, is greater than permitted
Skipping molecule at index 1384 due to error: Explicit valence for atom # 1 C, 6, is greater than permitted
Skipping molecule at index 1385 due to error: Explicit valence for atom # 0 C, 6, is greater than permitted
Skipping molecule at index 1386 due to error: Explicit valence for atom # 12 O, 3, is greater than permitted
Skipping molecule at index 1387 due to error: Explicit valence for atom # 20 O, 3, is greater than permitted
Skipping molecule at index 1389 due to error: Explicit valence for atom # 174 B, 4, is greater than permitted
Skipping molecule at index 1390 due to error: Explicit valence for atom # 174 B, 4, is greater than permitted
Skipping molecule at index 1391 due to error: Explicit valence for atom # 157 B, 4, is greater than permitted
Skipping molecule at index 1392 due to error: Explicit valence for atom # 170 B, 4, is greater than permitted
Skipping molecule at index 1393 due to error: Explicit valence for atom # 201 B, 4, is greater than permitted
Skipping molecule at index 1396 due to error: Explicit valence for atom # 3 N, 4, is greater than permitted
Skipping molecule at index 1398 due to error: Explicit valence for atom # 0 C, 6, is greater than permitted
Skipping molecule at index 1399 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 1400 due to error: Explicit valence for atom # 4 C, 6, is greater than permitted
Skipping molecule at index 1403 due to error: Explicit valence for atom # 5 N, 4, is greater than permitted
Skipping molecule at index 1404 due to error: Explicit valence for atom # 9 O, 3, is greater than permitted
Skipping molecule at index 1405 due to error: Explicit valence for atom # 3 O, 3, is greater than permitted
Skipping molecule at index 1406 due to error: Can't kekulize mol.  Unkekulized atoms: 156 157 159 161 163
Skipping molecule at index 1407 due to error: Explicit valence for atom # 207 B, 4, is greater than permitted
Skipping molecule at index 1409 due to error: Explicit valence for atom # 1 B, 4, is greater than permitted
Skipping molecule at index 1410 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 1411 due to error: Explicit valence for atom # 1 B, 4, is greater than permitted
Skipping molecule at index 1412 due to error: Explicit valence for atom # 1 B, 4, is greater than permitted
Skipping molecule at index 1413 due to error: Explicit valence for atom # 47 B, 4, is greater than permitted
Skipping molecule at index 1414 due to error: Explicit valence for atom # 47 B, 4, is greater than permitted
Skipping molecule at index 1417 due to error: Explicit valence for atom # 9 B, 4, is greater than permitted
Skipping molecule at index 1418 due to error: Explicit valence for atom # 9 B, 4, is greater than permitted
Skipping molecule at index 1421 due to error: Explicit valence for atom # 9 B, 4, is greater than permitted
Skipping molecule at index 1422 due to error: Explicit valence for atom # 9 B, 4, is greater than permitted
Skipping molecule at index 1425 due to error: Explicit valence for atom # 9 B, 4, is greater than permitted
Skipping molecule at index 1427 due to error: Explicit valence for atom # 71 B, 4, is greater than permitted
Skipping molecule at index 1429 due to error: Explicit valence for atom # 5 B, 4, is greater than permitted
Skipping molecule at index 1430 due to error: Explicit valence for atom # 17 O, 3, is greater than permitted
Skipping molecule at index 1431 due to error: Explicit valence for atom # 13 C, 6, is greater than permitted
Skipping molecule at index 1432 due to error: Explicit valence for atom # 4 F, 2, is greater than permitted
Skipping molecule at index 1433 due to error: Explicit valence for atom # 70 B, 4, is greater than permitted
Skipping molecule at index 1434 due to error: Explicit valence for atom # 73 B, 4, is greater than permitted
Skipping molecule at index 1435 due to error: Explicit valence for atom # 1 B, 4, is greater than permitted
Skipping molecule at index 1437 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 1438 due to error: Explicit valence for atom # 82 B, 4, is greater than permitted
Skipping molecule at index 1439 due to error: Explicit valence for atom # 124 B, 4, is greater than permitted
Skipping molecule at index 1441 due to error: Explicit valence for atom # 142 B, 4, is greater than permitted
Skipping molecule at index 1442 due to error: Can't kekulize mol.  Unkekulized atoms: 38 39 41 43 45
Skipping molecule at index 1443 due to error: Explicit valence for atom # 16 B, 4, is greater than permitted
Skipping molecule at index 1444 due to error: Explicit valence for atom # 0 C, 5, is greater than permitted
Skipping molecule at index 1445 due to error: Explicit valence for atom # 0 C, 5, is greater than permitted
Skipping molecule at index 1446 due to error: Explicit valence for atom # 0 C, 5, is greater than permitted
Skipping molecule at index 1447 due to error: Explicit valence for atom # 1 C, 5, is greater than permitted
Skipping molecule at index 1448 due to error: Explicit valence for atom # 43 B, 4, is greater than permitted
Skipping molecule at index 1449 due to error: Explicit valence for atom # 41 B, 4, is greater than permitted
Skipping molecule at index 1451 due to error: Explicit valence for atom # 4 C, 5, is greater than permitted
Skipping molecule at index 1453 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 1454 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 1455 due to error: Explicit valence for atom # 33 B, 4, is greater than permitted
Skipping molecule at index 1456 due to error: Explicit valence for atom # 0 C, 6, is greater than permitted
Skipping molecule at index 1457 due to error: Explicit valence for atom # 0 C, 6, is greater than permitted
Skipping molecule at index 1458 due to error: Explicit valence for atom # 0 C, 6, is greater than permitted
Skipping molecule at index 1459 due to error: Explicit valence for atom # 3 B, 4, is greater than permitted
Skipping molecule at index 1460 due to error: Explicit valence for atom # 5 O, 3, is greater than permitted
Skipping molecule at index 1461 due to error: Explicit valence for atom # 4 O, 3, is greater than permitted
Skipping molecule at index 1462 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 1463 due to error: Explicit valence for atom # 31 B, 4, is greater than permitted
Skipping molecule at index 1464 due to error: Explicit valence for atom # 31 B, 4, is greater than permitted
Skipping molecule at index 1465 due to error: Explicit valence for atom # 78 B, 4, is greater than permitted
Skipping molecule at index 1466 due to error: Explicit valence for atom # 76 B, 4, is greater than permitted
Skipping molecule at index 1467 due to error: Explicit valence for atom # 2 N, 4, is greater than permitted
Skipping molecule at index 1468 due to error: Explicit valence for atom # 3 N, 4, is greater than permitted
Skipping molecule at index 1469 due to error: Explicit valence for atom # 75 B, 5, is greater than permitted
Skipping molecule at index 1470 due to error: Explicit valence for atom # 3 B, 4, is greater than permitted
Skipping molecule at index 1471 due to error: Explicit valence for atom # 2 B, 4, is greater than permitted
Skipping molecule at index 1472 due to error: Explicit valence for atom # 1 H, 2, is greater than permitted
Skipping molecule at index 1474 due to error: Explicit valence for atom # 4 N, 4, is greater than permitted
Skipping molecule at index 1475 due to error: Can't kekulize mol.  Unkekulized atoms: 11 13 15 17 19 21 22 24 25 27 28 29 31 33 35
Skipping molecule at index 1477 due to error: Explicit valence for atom # 3 F, 2, is greater than permitted
Skipping molecule at index 1478 due to error: Explicit valence for atom # 1 O, 3, is greater than permitted
Skipping molecule at index 1479 due to error: Explicit valence for atom # 8 N, 4, is greater than permitted
Skipping molecule at index 1480 due to error: Explicit valence for atom # 1 B, 4, is greater than permitted
Skipping molecule at index 1481 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 1482 due to error: Explicit valence for atom # 1 B, 4, is greater than permitted
Skipping molecule at index 1483 due to error: Explicit valence for atom # 4 N, 4, is greater than permitted
Skipping molecule at index 1484 due to error: Explicit valence for atom # 24 C, 6, is greater than permitted
Skipping molecule at index 1485 due to error: Explicit valence for atom # 6 C, 6, is greater than permitted
Skipping molecule at index 1486 due to error: Explicit valence for atom # 11 C, 6, is greater than permitted
Skipping molecule at index 1487 due to error: Explicit valence for atom # 14 C, 6, is greater than permitted
Skipping molecule at index 1488 due to error: Explicit valence for atom # 14 C, 5, is greater than permitted
Skipping molecule at index 1489 due to error: Explicit valence for atom # 8 C, 6, is greater than permitted
Skipping molecule at index 1490 due to error: Explicit valence for atom # 2 C, 6, is greater than permitted
Skipping molecule at index 1491 due to error: Explicit valence for atom # 9 B, 4, is greater than permitted
Skipping molecule at index 1492 due to error: Explicit valence for atom # 0 Al, 4, is greater than permitted
Skipping molecule at index 1493 due to error: Explicit valence for atom # 0 Al, 4, is greater than permitted
Skipping molecule at index 1494 due to error: Explicit valence for atom # 0 Al, 4, is greater than permitted
Skipping molecule at index 1495 due to error: Explicit valence for atom # 0 Al, 4, is greater than permitted
Skipping molecule at index 1496 due to error: Explicit valence for atom # 1 B, 4, is greater than permitted
Skipping molecule at index 1497 due to error: Explicit valence for atom # 0 O, 3, is greater than permitted
Skipping molecule at index 1501 due to error: Explicit valence for atom # 0 N, 4, is greater than permitted
Skipping molecule at index 1504 due to error: Explicit valence for atom # 6 N, 4, is greater than permitted
Skipping molecule at index 1505 due to error: Explicit valence for atom # 6 N, 4, is greater than permitted
Skipping molecule at index 1506 due to error: Explicit valence for atom # 7 N, 4, is greater than permitted
Skipping molecule at index 1507 due to error: Explicit valence for atom # 6 N, 4, is greater than permitted
Skipping molecule at index 1508 due to error: Explicit valence for atom # 1 O, 3, is greater than permitted
Skipping molecule at index 1509 due to error: Explicit valence for atom # 24 C, 6, is greater than permitted
Skipping molecule at index 1510 due to error: Explicit valence for atom # 7 C, 6, is greater than permitted
Skipping molecule at index 1511 due to error: Explicit valence for atom # 15 F, 2, is greater than permitted
Skipping molecule at index 1513 due to error: Explicit valence for atom # 0 B, 6, is greater than permitted
Skipping molecule at index 1515 due to error: Can't kekulize mol.  Unkekulized atoms: 43 44 45 46 47 48 49 50 51
Skipping molecule at index 1516 due to error: Explicit valence for atom # 8 C, 5, is greater than permitted
Skipping molecule at index 1517 due to error: Explicit valence for atom # 12 C, 5, is greater than permitted
Skipping molecule at index 1518 due to error: Explicit valence for atom # 0 C, 6, is greater than permitted
Skipping molecule at index 1519 due to error: Explicit valence for atom # 40 B, 4, is greater than permitted

[10:29:01] Explicit valence for atom # 1 B, 4, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 4 N, 4, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:01] Explicit valence for atom # 24 C, 6, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:01] Explicit valence for atom # 6 C, 6, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:01] Explicit valence for atom # 11 C, 6, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:01] Explicit valence for atom # 14 C, 6, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:01] Explicit valence for atom # 14 C, 5, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:01] Explicit valence for atom # 8 C, 6, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:01] Explicit valence for atom # 2 C, 6, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 9 B, 4, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 0 Al, 4, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 0 Al, 4, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 0 Al, 4, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 0 Al, 4, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:01] Explicit valence for atom # 1 B, 4, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 0 O, 3, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 0 N, 4, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 6 N, 4, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 6 N, 4, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 7 N, 4, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 6 N, 4, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 1 O, 3, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:01] Explicit valence for atom # 24 C, 6, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:01] Explicit valence for atom # 7 C, 6, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 15 F, 2, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:01] Explicit valence for atom # 0 B, 6, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Can't kekulize mol.  Unkekulized atoms: 43 44 45 46 47 48 49 50 51
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:01] Explicit valence for atom # 8 C, 5, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:01] Explicit valence for atom # 12 C, 5, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:01] Explicit valence for atom # 0 C, 6, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 40 B, 4, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:01] Explicit valence for atom # 14 C, 5, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:01] Explicit valence for atom # 0 B, 6, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 35 B, 4, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 26 B, 4, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 26 B, 4, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 26 B, 4, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 26 B, 4, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 26 B, 4, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 26 B, 4, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 26 B, 4, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 26 B, 4, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 1 B, 4, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 1 N, 4, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 1 B, 4, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 28 B, 4, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 0 B, 4, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 3 B, 4, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 2 B, 4, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 12 B, 4, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 2 B, 4, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 5 B, 4, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 23 B, 4, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 46 B, 4, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 1 H, 2, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:01] Explicit valence for atom # 0 C, 5, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 41 B, 4, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 21 B, 4, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 6 B, 4, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 1 O, 3, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 1 O, 3, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:01] Explicit valence for atom # 0 B, 6, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:01] Explicit valence for atom # 0 B, 6, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 1 B, 4, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:01] Explicit valence for atom # 0 C, 6, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 7 B, 4, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 74 B, 4, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 3 N, 4, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 42 B, 4, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 0 N, 4, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 85 B, 4, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 120 B, 4, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 134 B, 4, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 0 B, 4, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 111 B, 4, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 0 N, 4, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 91 B, 4, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 8 N, 4, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 37 B, 4, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:01] Explicit valence for atom # 3 B, 6, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:01] Explicit valence for atom # 10 B, 6, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:01] Explicit valence for atom # 3 B, 6, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:01] Explicit valence for atom # 16 C, 6, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:01] Explicit valence for atom # 1 B, 6, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:01] Explicit valence for atom # 2 B, 6, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:01] Explicit valence for atom # 2 B, 6, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.

Skipping molecule at index 1521 due to error: Explicit valence for atom # 14 C, 5, is greater than permitted
Skipping molecule at index 1522 due to error: Explicit valence for atom # 0 B, 6, is greater than permitted
Skipping molecule at index 1523 due to error: Explicit valence for atom # 35 B, 4, is greater than permitted
Skipping molecule at index 1524 due to error: Explicit valence for atom # 26 B, 4, is greater than permitted
Skipping molecule at index 1525 due to error: Explicit valence for atom # 26 B, 4, is greater than permitted
Skipping molecule at index 1526 due to error: Explicit valence for atom # 26 B, 4, is greater than permitted
Skipping molecule at index 1527 due to error: Explicit valence for atom # 26 B, 4, is greater than permitted
Skipping molecule at index 1528 due to error: Explicit valence for atom # 26 B, 4, is greater than permitted
Skipping molecule at index 1529 due to error: Explicit valence for atom # 26 B, 4, is greater than permitted
Skipping molecule at index 1530 due to error: Explicit valence for atom # 26 B, 4, is greater than permitted
Skipping molecule at index 1531 due to error: Explicit valence for atom # 26 B, 4, is greater than permitted
Skipping molecule at index 1532 due to error: Explicit valence for atom # 1 B, 4, is greater than permitted
Skipping molecule at index 1533 due to error: Explicit valence for atom # 1 N, 4, is greater than permitted
Skipping molecule at index 1535 due to error: Explicit valence for atom # 1 B, 4, is greater than permitted
Skipping molecule at index 1536 due to error: Explicit valence for atom # 28 B, 4, is greater than permitted
Skipping molecule at index 1537 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 1538 due to error: Explicit valence for atom # 3 B, 4, is greater than permitted
Skipping molecule at index 1539 due to error: Explicit valence for atom # 2 B, 4, is greater than permitted
Skipping molecule at index 1540 due to error: Explicit valence for atom # 12 B, 4, is greater than permitted
Skipping molecule at index 1541 due to error: Explicit valence for atom # 2 B, 4, is greater than permitted
Skipping molecule at index 1542 due to error: Explicit valence for atom # 5 B, 4, is greater than permitted
Skipping molecule at index 1543 due to error: Explicit valence for atom # 23 B, 4, is greater than permitted
Skipping molecule at index 1544 due to error: Explicit valence for atom # 46 B, 4, is greater than permitted
Skipping molecule at index 1545 due to error: Explicit valence for atom # 1 H, 2, is greater than permitted
Skipping molecule at index 1546 due to error: Explicit valence for atom # 0 C, 5, is greater than permitted
Skipping molecule at index 1547 due to error: Explicit valence for atom # 41 B, 4, is greater than permitted
Skipping molecule at index 1548 due to error: Explicit valence for atom # 21 B, 4, is greater than permitted
Skipping molecule at index 1549 due to error: Explicit valence for atom # 6 B, 4, is greater than permitted
Skipping molecule at index 1550 due to error: Explicit valence for atom # 1 O, 3, is greater than permitted
Skipping molecule at index 1551 due to error: Explicit valence for atom # 1 O, 3, is greater than permitted
Skipping molecule at index 1552 due to error: Explicit valence for atom # 0 B, 6, is greater than permitted
Skipping molecule at index 1553 due to error: Explicit valence for atom # 0 B, 6, is greater than permitted
Skipping molecule at index 1554 due to error: Explicit valence for atom # 1 B, 4, is greater than permitted
Skipping molecule at index 1555 due to error: Explicit valence for atom # 0 C, 6, is greater than permitted
Skipping molecule at index 1556 due to error: Explicit valence for atom # 7 B, 4, is greater than permitted
Skipping molecule at index 1557 due to error: Explicit valence for atom # 74 B, 4, is greater than permitted
Skipping molecule at index 1558 due to error: Explicit valence for atom # 3 N, 4, is greater than permitted
Skipping molecule at index 1559 due to error: Explicit valence for atom # 42 B, 4, is greater than permitted
Skipping molecule at index 1560 due to error: Explicit valence for atom # 0 N, 4, is greater than permitted
Skipping molecule at index 1561 due to error: Explicit valence for atom # 85 B, 4, is greater than permitted
Skipping molecule at index 1562 due to error: Explicit valence for atom # 120 B, 4, is greater than permitted
Skipping molecule at index 1563 due to error: Explicit valence for atom # 134 B, 4, is greater than permitted
Skipping molecule at index 1564 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 1565 due to error: Explicit valence for atom # 111 B, 4, is greater than permitted
Skipping molecule at index 1566 due to error: Explicit valence for atom # 0 N, 4, is greater than permitted
Skipping molecule at index 1567 due to error: Explicit valence for atom # 91 B, 4, is greater than permitted
Skipping molecule at index 1568 due to error: Explicit valence for atom # 8 N, 4, is greater than permitted
Skipping molecule at index 1569 due to error: Explicit valence for atom # 37 B, 4, is greater than permitted
Skipping molecule at index 1570 due to error: Explicit valence for atom # 3 B, 6, is greater than permitted
Skipping molecule at index 1571 due to error: Explicit valence for atom # 10 B, 6, is greater than permitted
Skipping molecule at index 1572 due to error: Explicit valence for atom # 3 B, 6, is greater than permitted
Skipping molecule at index 1573 due to error: Explicit valence for atom # 16 C, 6, is greater than permitted
Skipping molecule at index 1574 due to error: Explicit valence for atom # 1 B, 6, is greater than permitted
Skipping molecule at index 1575 due to error: Explicit valence for atom # 2 B, 6, is greater than permitted
Skipping molecule at index 1576 due to error: Explicit valence for atom # 2 B, 6, is greater than permitted
Skipping molecule at index 1577 due to error: Explicit valence for atom # 0 B, 6, is greater than permitted
Skipping molecule at index 1578 due to error: Explicit valence for atom # 138 B, 4, is greater than permitted
Skipping molecule at index 1579 due to error: Explicit valence for atom # 85 B, 4, is greater than permitted
Skipping molecule at index 1582 due to error: Explicit valence for atom # 4 B, 4, is greater than permitted
Skipping molecule at index 1584 due to error: Can't kekulize mol.  Unkekulized atoms: 12 13 22 26 34 37 39 43 45 53
Skipping molecule at index 1585 due to error: Can't kekulize mol.  Unkekulized atoms: 13 16 18 19 31 33 38 41 43 53
Skipping molecule at index 1586 due to error: Explicit valence for atom # 3 O, 3, is greater than permitted
Skipping molecule at index 1587 due to error: Explicit valence for atom # 61 B, 4, is greater than permitted
Skipping molecule at index 1588 due to error: Explicit valence for atom # 69 B, 4, is greater than permitted
Skipping molecule at index 1589 due to error: Explicit valence for atom # 1 H, 2, is greater than permitted
Skipping molecule at index 1590 due to error: Explicit valence for atom # 63 B, 4, is greater than permitted
Skipping molecule at index 1591 due to error: Explicit valence for atom # 61 B, 4, is greater than permitted
Skipping molecule at index 1592 due to error: Can't kekulize mol.  Unkekulized atoms: 9 13 16 18 20
Skipping molecule at index 1593 due to error: Explicit valence for atom # 5 B, 4, is greater than permitted
Skipping molecule at index 1594 due to error: Explicit valence for atom # 5 B, 4, is greater than permitted
Skipping molecule at index 1595 due to error: Explicit valence for atom # 5 O, 3, is greater than permitted
Skipping molecule at index 1596 due to error: Explicit valence for atom # 0 Si, 6, is greater than permitted
Skipping molecule at index 1597 due to error: Explicit valence for atom # 0 Si, 5, is greater than permitted
Skipping molecule at index 1598 due to error: Explicit valence for atom # 0 Si, 5, is greater than permitted
Skipping molecule at index 1599 due to error: Explicit valence for atom # 0 Si, 5, is greater than permitted
Skipping molecule at index 1600 due to error: Explicit valence for atom # 13 B, 4, is greater than permitted
Skipping molecule at index 1601 due to error: Explicit valence for atom # 13 B, 4, is greater than permitted
Skipping molecule at index 1602 due to error: Can't kekulize mol.  Unkekulized atoms: 22 23 24 31 32 33 40 41 42
Skipping molecule at index 1603 due to error: Explicit valence for atom # 25 B, 4, is greater than permitted
Skipping molecule at index 1604 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 1605 due to error: Explicit valence for atom # 0 N, 4, is greater than permitted
Skipping molecule at index 1606 due to error: Explicit valence for atom # 55 B, 4, is greater than permitted
Skipping molecule at index 1607 due to error: Explicit valence for atom # 55 B, 4, is greater than permitted
Skipping molecule at index 1608 due to error: Explicit valence for atom # 55 B, 4, is greater than permitted
Skipping molecule at index 1609 due to error: Explicit valence for atom # 55 B, 4, is greater than permitted
Skipping molecule at index 1610 due to error: Explicit valence for atom # 9 B, 4, is greater than permitted
Skipping molecule at index 1611 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 1612 due to error: Explicit valence for atom # 9 O, 3, is greater than permitted
Skipping molecule at index 1613 due to error: Explicit valence for atom # 3 O, 3, is greater than permitted
Skipping molecule at index 1614 due to error: Explicit valence for atom # 15 O, 3, is greater than permitted
Skipping molecule at index 1615 due to error: Explicit valence for atom # 13 O, 3, is greater than permitted
Skipping molecule at index 1616 due to error: Explicit valence for atom # 7 O, 3, is greater than permitted
Skipping molecule at index 1617 due to error: Explicit valence for atom # 118 B, 4, is greater than permitted
Skipping molecule at index 1620 due to error: Can't kekulize mol.  Unkekulized atoms: 29 30 31 32 33 34 35 36 37
Skipping molecule at index 1621 due to error: Explicit valence for atom # 31 B, 4, is greater than permitted
Skipping molecule at index 1626 due to error: Explicit valence for atom # 23 B, 4, is greater than permitted
Skipping molecule at index 1627 due to error: Explicit valence for atom # 2 N, 4, is greater than permitted
Skipping molecule at index 1628 due to error: Explicit valence for atom # 1 N, 4, is greater than permitted
Skipping molecule at index 1629 due to error: Explicit valence for atom # 11 B, 4, is greater than permitted
Skipping molecule at index 1630 due to error: Explicit valence for atom # 6 O, 3, is greater than permitted
Skipping molecule at index 1631 due to error: Explicit valence for atom # 5 O, 3, is greater than permitted
Skipping molecule at index 1632 due to error: Explicit valence for atom # 3 O, 3, is greater than permitted
Skipping molecule at index 1633 due to error: Explicit valence for atom # 6 O, 3, is greater than permitted
Skipping molecule at index 1634 due to error: Explicit valence for atom # 13 B, 4, is greater than permitted
Skipping molecule at index 1635 due to error: Explicit valence for atom # 42 B, 4, is greater than permitted
Skipping molecule at index 1636 due to error: Explicit valence for atom # 14 B, 6, is greater than permitted
Skipping molecule at index 1637 due to error: Explicit valence for atom # 0 B, 6, is greater than permitted
Skipping molecule at index 1638 due to error: Explicit valence for atom # 3 B, 4, is greater than permitted
Skipping molecule at index 1639 due to error: Explicit valence for atom # 3 B, 4, is greater than permitted
Skipping molecule at index 1641 due to error: Explicit valence for atom # 125 H, 2, is greater than permitted
Skipping molecule at index 1642 due to error: Explicit valence for atom # 3 B, 4, is greater than permitted
Skipping molecule at index 1643 due to error: Explicit valence for atom # 2 B, 4, is greater than permitted
Skipping molecule at index 1644 due to error: Explicit valence for atom # 3 B, 4, is greater than permitted
Skipping molecule at index 1645 due to error: Explicit valence for atom # 4 B, 4, is greater than permitted
Skipping molecule at index 1646 due to error: Explicit valence for atom # 1 B, 4, is greater than permitted
Skipping molecule at index 1647 due to error: Explicit valence for atom # 3 B, 4, is greater than permitted
Skipping molecule at index 1648 due to error: Explicit valence for atom # 3 B, 4, is greater than permitted
Skipping molecule at index 1649 due to error: Explicit valence for atom # 3 B, 4, is greater than permitted
Skipping molecule at index 1650 due to error: Explicit valence for atom # 6 B, 4, is greater than permitted
Skipping molecule at index 1651 due to error: Explicit valence for atom # 4 B, 4, is greater than permitted
Skipping molecule at index 1652 due to error: Explicit valence for atom # 2 B, 4, is greater than permitted
Skipping molecule at index 1653 due to error: Explicit valence for atom # 8 O, 3, is greater than permitted
Skipping molecule at index 1654 due to error: Explicit valence for atom # 6 N, 4, is greater than permitted
Skipping molecule at index 1655 due to error: Explicit valence for atom # 3 B, 4, is greater than permitted
Skipping molecule at index 1656 due to error: Explicit valence for atom # 6 O, 3, is greater than permitted
Skipping molecule at index 1657 due to error: Explicit valence for atom # 1 O, 3, is greater than permitted
Skipping molecule at index 1658 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 1659 due to error: Explicit valence for atom # 2 B, 4, is greater than permitted
Skipping molecule at index 1661 due to error: Explicit valence for atom # 12 B, 6, is greater than permitted
Skipping molecule at index 1663 due to error: Explicit valence for atom # 22 C, 6, is greater than permitted
Skipping molecule at index 1664 due to error: Explicit valence for atom # 27 B, 4, is greater than permitted
Skipping molecule at index 1665 due to error: Explicit valence for atom # 51 B, 4, is greater than permitted
Skipping molecule at index 1666 due to error: Explicit valence for atom # 51 B, 4, is greater than permitted
Skipping molecule at index 1667 due to error: Explicit valence for atom # 3 C, 6, is greater than permitted
Skipping molecule at index 1668 due to error: Explicit valence for atom # 0 B, 6, is greater than permitted

[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 3 B, 4, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 125 H, 2, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 3 B, 4, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 2 B, 4, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 3 B, 4, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 4 B, 4, is greater than permitted
[10:29:01] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:01] Explicit valence for atom # 1 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 3 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 3 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 3 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 6 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 4 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 2 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 8 O, 3, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 6 N, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 3 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 6 O, 3, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 1 O, 3, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 0 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 2 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:02] Explicit valence for atom # 12 B, 6, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:02] Explicit valence for atom # 22 C, 6, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 27 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 51 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 51 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:02] Explicit valence for atom # 3 C, 6, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:02] Explicit valence for atom # 0 B, 6, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:02] Explicit valence for atom # 0 C, 6, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 24 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 24 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 4 N, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 127 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 3 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 3 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:02] Explicit valence for atom # 11 B, 6, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:02] Explicit valence for atom # 7 B, 6, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 1 N, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Can't kekulize mol.  Unkekulized atoms: 12 13 14 21 22 23 30 31 32
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 8 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 27 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 61 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 35 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 34 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 16 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Can't kekulize mol.  Unkekulized atoms: 17 18 19 20 21 22 23 24 25
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Can't kekulize mol.  Unkekulized atoms: 17 18 19 20 21 22 23 24 25
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 1 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:02] Explicit valence for atom # 35 B, 6, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:02] Explicit valence for atom # 26 C, 6, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:02] Explicit valence for atom # 45 C, 6, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Can't kekulize mol.  Unkekulized atoms: 18 19 20 39 40 41
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 13 N, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 0 O, 3, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 79 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 0 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 0 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 33 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 0 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 33 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 33 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 16 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 0 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 0 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 0 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 0 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 33 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 66 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 8 N, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 48 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 12 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 68 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 82 O, 3, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 9 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 0 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 74 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 77 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 107 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 27 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 1 O, 3, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:02] Explicit valence for atom # 78 B, 6, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:02] Explicit valence for atom # 33 B, 6, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:02] Explicit valence for atom # 12 C, 6, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 0 Al, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 8 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 16 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.

Skipping molecule at index 1669 due to error: Explicit valence for atom # 0 C, 6, is greater than permitted
Skipping molecule at index 1670 due to error: Explicit valence for atom # 24 B, 4, is greater than permitted
Skipping molecule at index 1671 due to error: Explicit valence for atom # 24 B, 4, is greater than permitted
Skipping molecule at index 1672 due to error: Explicit valence for atom # 4 N, 4, is greater than permitted
Skipping molecule at index 1674 due to error: Explicit valence for atom # 127 B, 4, is greater than permitted
Skipping molecule at index 1675 due to error: Explicit valence for atom # 3 B, 4, is greater than permitted
Skipping molecule at index 1676 due to error: Explicit valence for atom # 3 B, 4, is greater than permitted
Skipping molecule at index 1677 due to error: Explicit valence for atom # 11 B, 6, is greater than permitted
Skipping molecule at index 1678 due to error: Explicit valence for atom # 7 B, 6, is greater than permitted
Skipping molecule at index 1679 due to error: Explicit valence for atom # 1 N, 4, is greater than permitted
Skipping molecule at index 1680 due to error: Can't kekulize mol.  Unkekulized atoms: 12 13 14 21 22 23 30 31 32
Skipping molecule at index 1681 due to error: Explicit valence for atom # 8 B, 4, is greater than permitted
Skipping molecule at index 1682 due to error: Explicit valence for atom # 27 B, 4, is greater than permitted
Skipping molecule at index 1683 due to error: Explicit valence for atom # 61 B, 4, is greater than permitted
Skipping molecule at index 1687 due to error: Explicit valence for atom # 35 B, 4, is greater than permitted
Skipping molecule at index 1688 due to error: Explicit valence for atom # 34 B, 4, is greater than permitted
Skipping molecule at index 1689 due to error: Explicit valence for atom # 16 B, 4, is greater than permitted
Skipping molecule at index 1690 due to error: Can't kekulize mol.  Unkekulized atoms: 17 18 19 20 21 22 23 24 25
Skipping molecule at index 1691 due to error: Can't kekulize mol.  Unkekulized atoms: 17 18 19 20 21 22 23 24 25
Skipping molecule at index 1692 due to error: Explicit valence for atom # 1 B, 4, is greater than permitted
Skipping molecule at index 1693 due to error: Explicit valence for atom # 35 B, 6, is greater than permitted
Skipping molecule at index 1694 due to error: Explicit valence for atom # 26 C, 6, is greater than permitted
Skipping molecule at index 1695 due to error: Explicit valence for atom # 45 C, 6, is greater than permitted
Skipping molecule at index 1696 due to error: Can't kekulize mol.  Unkekulized atoms: 18 19 20 39 40 41
Skipping molecule at index 1698 due to error: Explicit valence for atom # 13 N, 4, is greater than permitted
Skipping molecule at index 1699 due to error: Explicit valence for atom # 0 O, 3, is greater than permitted
Skipping molecule at index 1700 due to error: Explicit valence for atom # 79 B, 4, is greater than permitted
Skipping molecule at index 1701 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 1702 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 1703 due to error: Explicit valence for atom # 33 B, 4, is greater than permitted
Skipping molecule at index 1705 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 1707 due to error: Explicit valence for atom # 33 B, 4, is greater than permitted
Skipping molecule at index 1708 due to error: Explicit valence for atom # 33 B, 4, is greater than permitted
Skipping molecule at index 1709 due to error: Explicit valence for atom # 16 B, 4, is greater than permitted
Skipping molecule at index 1710 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 1711 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 1712 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 1713 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 1714 due to error: Explicit valence for atom # 33 B, 4, is greater than permitted
Skipping molecule at index 1715 due to error: Explicit valence for atom # 66 B, 4, is greater than permitted
Skipping molecule at index 1717 due to error: Explicit valence for atom # 8 N, 4, is greater than permitted
Skipping molecule at index 1718 due to error: Explicit valence for atom # 48 B, 4, is greater than permitted
Skipping molecule at index 1719 due to error: Explicit valence for atom # 12 B, 4, is greater than permitted
Skipping molecule at index 1721 due to error: Explicit valence for atom # 68 B, 4, is greater than permitted
Skipping molecule at index 1722 due to error: Explicit valence for atom # 82 O, 3, is greater than permitted
Skipping molecule at index 1723 due to error: Explicit valence for atom # 9 B, 4, is greater than permitted
Skipping molecule at index 1725 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 1726 due to error: Explicit valence for atom # 74 B, 4, is greater than permitted
Skipping molecule at index 1727 due to error: Explicit valence for atom # 77 B, 4, is greater than permitted
Skipping molecule at index 1728 due to error: Explicit valence for atom # 107 B, 4, is greater than permitted
Skipping molecule at index 1729 due to error: Explicit valence for atom # 27 B, 4, is greater than permitted
Skipping molecule at index 1730 due to error: Explicit valence for atom # 1 O, 3, is greater than permitted
Skipping molecule at index 1733 due to error: Explicit valence for atom # 78 B, 6, is greater than permitted
Skipping molecule at index 1734 due to error: Explicit valence for atom # 33 B, 6, is greater than permitted
Skipping molecule at index 1735 due to error: Explicit valence for atom # 12 C, 6, is greater than permitted
Skipping molecule at index 1736 due to error: Explicit valence for atom # 0 Al, 4, is greater than permitted
Skipping molecule at index 1737 due to error: Explicit valence for atom # 8 B, 4, is greater than permitted
Skipping molecule at index 1738 due to error: Explicit valence for atom # 16 B, 4, is greater than permitted
Skipping molecule at index 1743 due to error: Explicit valence for atom # 69 B, 4, is greater than permitted
Skipping molecule at index 1744 due to error: Explicit valence for atom # 9 C, 6, is greater than permitted
Skipping molecule at index 1745 due to error: Explicit valence for atom # 0 B, 6, is greater than permitted
Skipping molecule at index 1746 due to error: Explicit valence for atom # 94 B, 4, is greater than permitted
Skipping molecule at index 1748 due to error: Explicit valence for atom # 55 B, 4, is greater than permitted
Skipping molecule at index 1749 due to error: Explicit valence for atom # 55 B, 4, is greater than permitted
Skipping molecule at index 1750 due to error: Explicit valence for atom # 36 B, 4, is greater than permitted
Skipping molecule at index 1751 due to error: Explicit valence for atom # 1 B, 4, is greater than permitted
Skipping molecule at index 1752 due to error: Explicit valence for atom # 4 N, 4, is greater than permitted
Skipping molecule at index 1753 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 1754 due to error: Explicit valence for atom # 7 N, 4, is greater than permitted
Skipping molecule at index 1755 due to error: Explicit valence for atom # 132 B, 4, is greater than permitted
Skipping molecule at index 1756 due to error: Explicit valence for atom # 53 B, 4, is greater than permitted
Skipping molecule at index 1757 due to error: Explicit valence for atom # 128 B, 4, is greater than permitted
Skipping molecule at index 1758 due to error: Explicit valence for atom # 82 B, 4, is greater than permitted
Skipping molecule at index 1759 due to error: Explicit valence for atom # 3 B, 4, is greater than permitted
Skipping molecule at index 1760 due to error: Explicit valence for atom # 15 O, 3, is greater than permitted
Skipping molecule at index 1761 due to error: Explicit valence for atom # 5 F, 2, is greater than permitted
Skipping molecule at index 1763 due to error: Explicit valence for atom # 14 O, 3, is greater than permitted
Skipping molecule at index 1764 due to error: Explicit valence for atom # 5 O, 3, is greater than permitted
Skipping molecule at index 1765 due to error: Explicit valence for atom # 18 B, 4, is greater than permitted
Skipping molecule at index 1767 due to error: Explicit valence for atom # 33 B, 4, is greater than permitted
Skipping molecule at index 1768 due to error: Explicit valence for atom # 35 B, 4, is greater than permitted
Skipping molecule at index 1769 due to error: Explicit valence for atom # 78 B, 4, is greater than permitted
Skipping molecule at index 1771 due to error: Explicit valence for atom # 104 B, 5, is greater than permitted
Skipping molecule at index 1773 due to error: Explicit valence for atom # 16 B, 4, is greater than permitted
Skipping molecule at index 1774 due to error: Explicit valence for atom # 16 B, 4, is greater than permitted
Skipping molecule at index 1775 due to error: Explicit valence for atom # 26 B, 4, is greater than permitted
Skipping molecule at index 1776 due to error: Explicit valence for atom # 11 B, 4, is greater than permitted
Skipping molecule at index 1777 due to error: Explicit valence for atom # 85 B, 4, is greater than permitted
Skipping molecule at index 1778 due to error: Explicit valence for atom # 88 B, 4, is greater than permitted

[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 69 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:02] Explicit valence for atom # 9 C, 6, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:02] Explicit valence for atom # 0 B, 6, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 94 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 55 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 55 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 36 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 1 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 4 N, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 0 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 7 N, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 132 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 53 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 128 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 82 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 3 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 15 O, 3, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 5 F, 2, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 14 O, 3, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 5 O, 3, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 18 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 33 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 35 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 78 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 104 B, 5, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 16 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 16 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 26 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 11 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 85 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 88 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 2 Cl, 2, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 2 Cl, 2, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 2 Cl, 2, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 2 Cl, 2, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 2 Cl, 2, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 2 Cl, 2, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 2 Cl, 2, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 8 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 8 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 2 O, 3, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 91 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 2 N, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:02] Explicit valence for atom # 8 C, 6, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:02] Explicit valence for atom # 9 C, 6, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 5 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:02] Explicit valence for atom # 0 C, 6, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:02] Explicit valence for atom # 0 C, 6, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:02] Explicit valence for atom # 0 C, 6, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:02] Explicit valence for atom # 0 C, 6, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:02] Explicit valence for atom # 0 C, 6, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:02] Explicit valence for atom # 0 C, 6, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 5 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 2 O, 3, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 4 N, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:02] Explicit valence for atom # 4 C, 6, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 13 O, 2, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 3 O, 2, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:02] Explicit valence for atom # 2 B, 6, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 4 N, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 4 N, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 0 O, 3, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 0 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 8 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 4 N, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 1 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 55 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 1 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 55 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 43 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 78 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 48 O, 3, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:02] Explicit valence for atom # 10 C, 6, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:02] Explicit valence for atom # 6 C, 6, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:02] Explicit valence for atom # 6 C, 6, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 0 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Can't kekulize mol.  Unkekulized atoms: 9 10 12 14 16
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:02] Explicit valence for atom # 4 N, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 4 O, 3, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 47 O, 3, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:02] Explicit valence for atom # 3 C, 5, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:02] Explicit valence for atom # 6 C, 6, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:02] Explicit valence for atom # 25 C, 6, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.

Skipping molecule at index 1780 due to error: Explicit valence for atom # 2 Cl, 2, is greater than permitted
Skipping molecule at index 1781 due to error: Explicit valence for atom # 2 Cl, 2, is greater than permitted
Skipping molecule at index 1782 due to error: Explicit valence for atom # 2 Cl, 2, is greater than permitted
Skipping molecule at index 1783 due to error: Explicit valence for atom # 2 Cl, 2, is greater than permitted
Skipping molecule at index 1784 due to error: Explicit valence for atom # 2 Cl, 2, is greater than permitted
Skipping molecule at index 1785 due to error: Explicit valence for atom # 2 Cl, 2, is greater than permitted
Skipping molecule at index 1786 due to error: Explicit valence for atom # 2 Cl, 2, is greater than permitted
Skipping molecule at index 1787 due to error: Explicit valence for atom # 8 B, 4, is greater than permitted
Skipping molecule at index 1788 due to error: Explicit valence for atom # 8 B, 4, is greater than permitted
Skipping molecule at index 1791 due to error: Explicit valence for atom # 2 O, 3, is greater than permitted
Skipping molecule at index 1792 due to error: Explicit valence for atom # 91 B, 4, is greater than permitted
Skipping molecule at index 1794 due to error: Explicit valence for atom # 2 N, 4, is greater than permitted
Skipping molecule at index 1795 due to error: Explicit valence for atom # 8 C, 6, is greater than permitted
Skipping molecule at index 1796 due to error: Explicit valence for atom # 9 C, 6, is greater than permitted
Skipping molecule at index 1797 due to error: Explicit valence for atom # 5 B, 4, is greater than permitted
Skipping molecule at index 1798 due to error: Explicit valence for atom # 0 C, 6, is greater than permitted
Skipping molecule at index 1799 due to error: Explicit valence for atom # 0 C, 6, is greater than permitted
Skipping molecule at index 1800 due to error: Explicit valence for atom # 0 C, 6, is greater than permitted
Skipping molecule at index 1801 due to error: Explicit valence for atom # 0 C, 6, is greater than permitted
Skipping molecule at index 1802 due to error: Explicit valence for atom # 0 C, 6, is greater than permitted
Skipping molecule at index 1803 due to error: Explicit valence for atom # 0 C, 6, is greater than permitted
Skipping molecule at index 1804 due to error: Explicit valence for atom # 5 B, 4, is greater than permitted
Skipping molecule at index 1806 due to error: Explicit valence for atom # 2 O, 3, is greater than permitted
Skipping molecule at index 1807 due to error: Explicit valence for atom # 4 N, 4, is greater than permitted
Skipping molecule at index 1808 due to error: Explicit valence for atom # 4 C, 6, is greater than permitted
Skipping molecule at index 1811 due to error: Explicit valence for atom # 13 O, 2, is greater than permitted
Skipping molecule at index 1814 due to error: Explicit valence for atom # 3 O, 2, is greater than permitted
Skipping molecule at index 1818 due to error: Explicit valence for atom # 2 B, 6, is greater than permitted
Skipping molecule at index 1819 due to error: Explicit valence for atom # 4 N, 4, is greater than permitted
Skipping molecule at index 1820 due to error: Explicit valence for atom # 4 N, 4, is greater than permitted
Skipping molecule at index 1821 due to error: Explicit valence for atom # 0 O, 3, is greater than permitted
Skipping molecule at index 1822 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 1823 due to error: Explicit valence for atom # 8 B, 4, is greater than permitted
Skipping molecule at index 1825 due to error: Explicit valence for atom # 4 N, 4, is greater than permitted
Skipping molecule at index 1826 due to error: Explicit valence for atom # 1 B, 4, is greater than permitted
Skipping molecule at index 1827 due to error: Explicit valence for atom # 55 B, 4, is greater than permitted
Skipping molecule at index 1828 due to error: Explicit valence for atom # 1 B, 4, is greater than permitted
Skipping molecule at index 1829 due to error: Explicit valence for atom # 55 B, 4, is greater than permitted
Skipping molecule at index 1832 due to error: Explicit valence for atom # 43 B, 4, is greater than permitted
Skipping molecule at index 1833 due to error: Explicit valence for atom # 78 B, 4, is greater than permitted
Skipping molecule at index 1835 due to error: Explicit valence for atom # 48 O, 3, is greater than permitted
Skipping molecule at index 1836 due to error: Explicit valence for atom # 10 C, 6, is greater than permitted
Skipping molecule at index 1837 due to error: Explicit valence for atom # 6 C, 6, is greater than permitted
Skipping molecule at index 1838 due to error: Explicit valence for atom # 6 C, 6, is greater than permitted
Skipping molecule at index 1839 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 1840 due to error: Can't kekulize mol.  Unkekulized atoms: 9 10 12 14 16
Skipping molecule at index 1841 due to error: Explicit valence for atom # 4 N, 4, is greater than permitted
Skipping molecule at index 1842 due to error: Explicit valence for atom # 4 O, 3, is greater than permitted
Skipping molecule at index 1843 due to error: Explicit valence for atom # 47 O, 3, is greater than permitted
Skipping molecule at index 1844 due to error: Explicit valence for atom # 3 C, 5, is greater than permitted
Skipping molecule at index 1845 due to error: Explicit valence for atom # 6 C, 6, is greater than permitted
Skipping molecule at index 1846 due to error: Explicit valence for atom # 25 C, 6, is greater than permitted
Skipping molecule at index 1847 due to error: Explicit valence for atom # 2 O, 3, is greater than permitted
Skipping molecule at index 1848 due to error: Explicit valence for atom # 1 O, 3, is greater than permitted
Skipping molecule at index 1849 due to error: Explicit valence for atom # 3 B, 4, is greater than permitted
Skipping molecule at index 1850 due to error: Explicit valence for atom # 60 B, 4, is greater than permitted
Skipping molecule at index 1851 due to error: Explicit valence for atom # 22 B, 4, is greater than permitted
Skipping molecule at index 1852 due to error: Explicit valence for atom # 34 B, 4, is greater than permitted
Skipping molecule at index 1853 due to error: Explicit valence for atom # 67 B, 4, is greater than permitted
Skipping molecule at index 1854 due to error: Explicit valence for atom # 24 B, 4, is greater than permitted
Skipping molecule at index 1855 due to error: Explicit valence for atom # 37 B, 4, is greater than permitted
Skipping molecule at index 1856 due to error: Explicit valence for atom # 70 B, 4, is greater than permitted
Skipping molecule at index 1857 due to error: Explicit valence for atom # 189 B, 4, is greater than permitted
Skipping molecule at index 1858 due to error: Explicit valence for atom # 74 B, 4, is greater than permitted
Skipping molecule at index 1859 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 1860 due to error: Explicit valence for atom # 85 B, 4, is greater than permitted
Skipping molecule at index 1862 due to error: Explicit valence for atom # 3 O, 3, is greater than permitted
Skipping molecule at index 1863 due to error: Explicit valence for atom # 62 B, 4, is greater than permitted
Skipping molecule at index 1864 due to error: Explicit valence for atom # 44 B, 4, is greater than permitted
Skipping molecule at index 1865 due to error: Explicit valence for atom # 49 B, 4, is greater than permitted
Skipping molecule at index 1866 due to error: Explicit valence for atom # 1 P, 6, is greater than permitted
Skipping molecule at index 1867 due to error: Explicit valence for atom # 5 O, 3, is greater than permitted
Skipping molecule at index 1868 due to error: Explicit valence for atom # 49 B, 4, is greater than permitted
Skipping molecule at index 1869 due to error: Explicit valence for atom # 132 B, 4, is greater than permitted
Skipping molecule at index 1870 due to error: Explicit valence for atom # 114 B, 4, is greater than permitted
Skipping molecule at index 1871 due to error: Explicit valence for atom # 43 B, 4, is greater than permitted
Skipping molecule at index 1872 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 1874 due to error: Explicit valence for atom # 3 N, 4, is greater than permitted
Skipping molecule at index 1883 due to error: Explicit valence for atom # 3 B, 4, is greater than permitted
Skipping molecule at index 1884 due to error: Explicit valence for atom # 12 O, 3, is greater than permitted
Skipping molecule at index 1885 due to error: Explicit valence for atom # 6 N, 4, is greater than permitted
Skipping molecule at index 1886 due to error: Explicit valence for atom # 78 B, 4, is greater than permitted
Skipping molecule at index 1890 due to error: Explicit valence for atom # 66 B, 4, is greater than permitted
Skipping molecule at index 1891 due to error: Explicit valence for atom # 23 B, 4, is greater than permitted
Skipping molecule at index 1892 due to error: Explicit valence for atom # 12 B, 4, is greater than permitted
Skipping molecule at index 1893 due to error: Explicit valence for atom # 10 B, 4, is greater than permitted
Skipping molecule at index 1894 due to error: Explicit valence for atom # 1 B, 4, is greater than permitted
Skipping molecule at index 1895 due to error: Explicit valence for atom # 1 O, 3, is greater than permitted
Skipping molecule at index 1896 due to error: Can't kekulize mol.  Unkekulized atoms: 7 9 11
Skipping molecule at index 1897 due to error: Explicit valence for atom # 57 B, 4, is greater than permitted
Skipping molecule at index 1899 due to error: Explicit valence for atom # 1 N, 4, is greater than permitted
Skipping molecule at index 1900 due to error: Explicit valence for atom # 2 B, 4, is greater than permitted
Skipping molecule at index 1901 due to error: Explicit valence for atom # 74 C, 6, is greater than permitted
Skipping molecule at index 1902 due to error: Can't kekulize mol.  Unkekulized atoms: 6 7 9 11 13 15 16 18 20 22
Skipping molecule at index 1903 due to error: Explicit valence for atom # 3 B, 4, is greater than permitted
Skipping molecule at index 1904 due to error: Explicit valence for atom # 49 B, 4, is greater than permitted
Skipping molecule at index 1905 due to error: Explicit valence for atom # 117 B, 4, is greater than permitted
Skipping molecule at index 1906 due to error: Explicit valence for atom # 56 B, 4, is greater than permitted
Skipping molecule at index 1907 due to error: Explicit valence for atom # 2 B, 4, is greater than permitted
Skipping molecule at index 1908 due to error: Explicit valence for atom # 2 B, 4, is greater than permitted
Skipping molecule at index 1909 due to error: Explicit valence for atom # 1 B, 4, is greater than permitted
Skipping molecule at index 1910 due to error: Explicit valence for atom # 3 B, 4, is greater than permitted
Skipping molecule at index 1913 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 1914 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 1915 due to error: Explicit valence for atom # 70 B, 4, is greater than permitted
Skipping molecule at index 1916 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 1917 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 1918 due to error: Explicit valence for atom # 64 B, 4, is greater than permitted
Skipping molecule at index 1919 due to error: Explicit valence for atom # 1 B, 4, is greater than permitted
Skipping molecule at index 1920 due to error: Explicit valence for atom # 6 B, 4, is greater than permitted
Skipping molecule at index 1921 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 1922 due to error: Explicit valence for atom # 35 B, 5, is greater than permitted
Skipping molecule at index 1923 due to error: Explicit valence for atom # 0 Pb, 6, is greater than permitted
Skipping molecule at index 1924 due to error: Explicit valence for atom # 2 B, 4, is greater than permitted
Skipping molecule at index 1925 due to error: Explicit valence for atom # 39 F, 2, is greater than permitted
Skipping molecule at index 1926 due to error: Explicit valence for atom # 41 F, 2, is greater than permitted
Skipping molecule at index 1927 due to error: Explicit valence for atom # 2 O, 5, is greater than permitted
Skipping molecule at index 1928 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 1929 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 1930 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 1931 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 1932 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 1933 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 1934 due to error: Explicit valence for atom # 4 N, 4, is greater than permitted
Skipping molecule at index 1936 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 1939 due to error: Explicit valence for atom # 21 C, 6, is greater than permitted
Skipping molecule at index 1940 due to error: Explicit valence for atom # 1 B, 6, is greater than permitted
Skipping molecule at index 1941 due to error: Explicit valence for atom # 21 C, 6, is greater than permitted
Skipping molecule at index 1942 due to error: Explicit valence for atom # 23 C, 6, is greater than permitted
Skipping molecule at index 1943 due to error: Explicit valence for atom # 23 C, 6, is greater than permitted
Skipping molecule at index 1944 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 1945 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 1946 due to error: Explicit valence for atom # 44 B, 4, is greater than permitted
Skipping molecule at index 1947 due to error: Explicit valence for atom # 1 B, 4, is greater than permitted
Skipping molecule at index 1948 due to error: Explicit valence for atom # 6 B, 4, is greater than permitted
Skipping molecule at index 1949 due to error: Explicit valence for atom # 2 B, 4, is greater than permitted
Skipping molecule at index 1950 due to error: Explicit valence for atom # 2 B, 4, is greater than permitted
Skipping molecule at index 1951 due to error: Explicit valence for atom # 1 B, 4, is greater than permitted
Skipping molecule at index 1952 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 1953 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 1954 due to error: Explicit valence for atom # 59 B, 4, is greater than permitted
Skipping molecule at index 1955 due to error: Explicit valence for atom # 7 O, 3, is greater than permitted
Skipping molecule at index 1956 due to error: Explicit valence for atom # 2 O, 3, is greater than permitted
Skipping molecule at index 1957 due to error: Explicit valence for atom # 2 C, 6, is greater than permitted
Skipping molecule at index 1958 due to error: Explicit valence for atom # 0 Ga, 4, is greater than permitted
Skipping molecule at index 1959 due to error: Explicit valence for atom # 3 N, 4, is greater than permitted
Skipping molecule at index 1960 due to error: Explicit valence for atom # 1 B, 4, is greater than permitted
Skipping molecule at index 1961 due to error: Explicit valence for atom # 3 N, 4, is greater than permitted
Skipping molecule at index 1962 due to error: Explicit valence for atom # 2 N, 4, is greater than permitted
Skipping molecule at index 1963 due to error: Explicit valence for atom # 3 N, 4, is greater than permitted
Skipping molecule at index 1964 due to error: Explicit valence for atom # 3 N, 4, is greater than permitted
Skipping molecule at index 1965 due to error: Explicit valence for atom # 3 N, 4, is greater than permitted
Skipping molecule at index 1966 due to error: Explicit valence for atom # 7 N, 4, is greater than permitted
Skipping molecule at index 1968 due to error: Explicit valence for atom # 0 Br, 2, is greater than permitted

[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 0 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 0 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 70 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 0 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 0 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 64 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 1 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 6 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 0 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:02] Explicit valence for atom # 35 B, 5, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:02] Explicit valence for atom # 0 Pb, 6, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 2 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 39 F, 2, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 41 F, 2, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 2 O, 5, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 0 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 0 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 0 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 0 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 0 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 0 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:02] Explicit valence for atom # 4 N, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 0 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:02] Explicit valence for atom # 21 C, 6, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:02] Explicit valence for atom # 1 B, 6, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:02] Explicit valence for atom # 21 C, 6, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:02] Explicit valence for atom # 23 C, 6, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:02] Explicit valence for atom # 23 C, 6, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 0 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 0 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 44 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 1 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 6 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 2 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 2 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 1 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 0 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 0 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 59 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 7 O, 3, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 2 O, 3, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:02] Explicit valence for atom # 2 C, 6, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:02] Explicit valence for atom # 0 Ga, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 3 N, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 1 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 3 N, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 2 N, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 3 N, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 3 N, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 3 N, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 7 N, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 0 Br, 2, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 1 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:02] Explicit valence for atom # 36 C, 6, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:02] Explicit valence for atom # 81 C, 6, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 23 N, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 2 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 9 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 0 Al, 6, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 0 Al, 6, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 0 Al, 6, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 0 Al, 6, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 38 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 67 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 1 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 1 H, 2, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 4 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 2 F, 2, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 43 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 2 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 4 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 1 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 10 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 30 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 2 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 1 N, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 23 O, 3, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 0 B, 6, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 43 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 1 N, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 73 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:02] Explicit valence for atom # 9 C, 6, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:02] Explicit valence for atom # 8 C, 6, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 4 F, 2, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 64 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 62 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 62 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 71 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 71 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 134 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:02] Explicit valence for atom # 9 C, 6, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 98 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.

Skipping molecule at index 1971 due to error: Explicit valence for atom # 1 B, 4, is greater than permitted
Skipping molecule at index 1972 due to error: Explicit valence for atom # 36 C, 6, is greater than permitted
Skipping molecule at index 1973 due to error: Explicit valence for atom # 81 C, 6, is greater than permitted
Skipping molecule at index 1974 due to error: Explicit valence for atom # 23 N, 4, is greater than permitted
Skipping molecule at index 1975 due to error: Explicit valence for atom # 2 B, 4, is greater than permitted
Skipping molecule at index 1976 due to error: Explicit valence for atom # 9 B, 4, is greater than permitted
Skipping molecule at index 1977 due to error: Explicit valence for atom # 0 Al, 6, is greater than permitted
Skipping molecule at index 1978 due to error: Explicit valence for atom # 0 Al, 6, is greater than permitted
Skipping molecule at index 1979 due to error: Explicit valence for atom # 0 Al, 6, is greater than permitted
Skipping molecule at index 1980 due to error: Explicit valence for atom # 0 Al, 6, is greater than permitted
Skipping molecule at index 1981 due to error: Explicit valence for atom # 38 B, 4, is greater than permitted
Skipping molecule at index 1982 due to error: Explicit valence for atom # 67 B, 4, is greater than permitted
Skipping molecule at index 1983 due to error: Explicit valence for atom # 1 B, 4, is greater than permitted
Skipping molecule at index 1984 due to error: Explicit valence for atom # 1 H, 2, is greater than permitted
Skipping molecule at index 1985 due to error: Explicit valence for atom # 4 B, 4, is greater than permitted
Skipping molecule at index 1986 due to error: Explicit valence for atom # 2 F, 2, is greater than permitted
Skipping molecule at index 1987 due to error: Explicit valence for atom # 43 B, 4, is greater than permitted
Skipping molecule at index 1988 due to error: Explicit valence for atom # 2 B, 4, is greater than permitted
Skipping molecule at index 1989 due to error: Explicit valence for atom # 4 B, 4, is greater than permitted
Skipping molecule at index 1990 due to error: Explicit valence for atom # 1 B, 4, is greater than permitted
Skipping molecule at index 1991 due to error: Explicit valence for atom # 10 B, 4, is greater than permitted
Skipping molecule at index 1992 due to error: Explicit valence for atom # 30 B, 4, is greater than permitted
Skipping molecule at index 1993 due to error: Explicit valence for atom # 2 B, 4, is greater than permitted
Skipping molecule at index 1994 due to error: Explicit valence for atom # 1 N, 4, is greater than permitted
Skipping molecule at index 1995 due to error: Explicit valence for atom # 23 O, 3, is greater than permitted
Skipping molecule at index 1996 due to error: Explicit valence for atom # 0 B, 6, is greater than permitted
Skipping molecule at index 1999 due to error: Explicit valence for atom # 43 B, 4, is greater than permitted
Skipping molecule at index 2000 due to error: Explicit valence for atom # 1 N, 4, is greater than permitted
Skipping molecule at index 2001 due to error: Explicit valence for atom # 73 B, 4, is greater than permitted
Skipping molecule at index 2002 due to error: Explicit valence for atom # 9 C, 6, is greater than permitted
Skipping molecule at index 2003 due to error: Explicit valence for atom # 8 C, 6, is greater than permitted
Skipping molecule at index 2004 due to error: Explicit valence for atom # 4 F, 2, is greater than permitted
Skipping molecule at index 2006 due to error: Explicit valence for atom # 64 B, 4, is greater than permitted
Skipping molecule at index 2007 due to error: Explicit valence for atom # 62 B, 4, is greater than permitted
Skipping molecule at index 2008 due to error: Explicit valence for atom # 62 B, 4, is greater than permitted
Skipping molecule at index 2009 due to error: Explicit valence for atom # 71 B, 4, is greater than permitted
Skipping molecule at index 2010 due to error: Explicit valence for atom # 71 B, 4, is greater than permitted
Skipping molecule at index 2011 due to error: Explicit valence for atom # 134 B, 4, is greater than permitted
Skipping molecule at index 2012 due to error: Explicit valence for atom # 9 C, 6, is greater than permitted
Skipping molecule at index 2013 due to error: Explicit valence for atom # 98 B, 4, is greater than permitted
Skipping molecule at index 2014 due to error: Explicit valence for atom # 4 N, 4, is greater than permitted
Skipping molecule at index 2016 due to error: Explicit valence for atom # 1 N, 4, is greater than permitted
Skipping molecule at index 2017 due to error: Explicit valence for atom # 8 N, 4, is greater than permitted
Skipping molecule at index 2018 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 2019 due to error: Explicit valence for atom # 135 B, 4, is greater than permitted
Skipping molecule at index 2020 due to error: Explicit valence for atom # 0 Pb, 5, is greater than permitted
Skipping molecule at index 2021 due to error: Explicit valence for atom # 0 B, 6, is greater than permitted
Skipping molecule at index 2022 due to error: Explicit valence for atom # 4 B, 4, is greater than permitted
Skipping molecule at index 2023 due to error: Explicit valence for atom # 2 O, 3, is greater than permitted
Skipping molecule at index 2024 due to error: Explicit valence for atom # 3 O, 3, is greater than permitted
Skipping molecule at index 2025 due to error: Explicit valence for atom # 2 O, 3, is greater than permitted
Skipping molecule at index 2026 due to error: Explicit valence for atom # 4 O, 3, is greater than permitted
Skipping molecule at index 2027 due to error: Explicit valence for atom # 3 O, 3, is greater than permitted
Skipping molecule at index 2028 due to error: Explicit valence for atom # 66 O, 3, is greater than permitted
Skipping molecule at index 2029 due to error: Explicit valence for atom # 13 N, 4, is greater than permitted
Skipping molecule at index 2030 due to error: Explicit valence for atom # 12 N, 4, is greater than permitted
Skipping molecule at index 2031 due to error: Explicit valence for atom # 23 C, 6, is greater than permitted
Skipping molecule at index 2032 due to error: Explicit valence for atom # 7 O, 3, is greater than permitted
Skipping molecule at index 2034 due to error: Explicit valence for atom # 7 N, 4, is greater than permitted
Skipping molecule at index 2035 due to error: Explicit valence for atom # 3 B, 4, is greater than permitted
Skipping molecule at index 2036 due to error: Explicit valence for atom # 19 B, 4, is greater than permitted
Skipping molecule at index 2037 due to error: Explicit valence for atom # 6 B, 4, is greater than permitted
Skipping molecule at index 2038 due to error: Explicit valence for atom # 3 B, 6, is greater than permitted
Skipping molecule at index 2039 due to error: Explicit valence for atom # 3 O, 3, is greater than permitted
Skipping molecule at index 2041 due to error: Explicit valence for atom # 8 O, 3, is greater than permitted
Skipping molecule at index 2043 due to error: Explicit valence for atom # 10 N, 4, is greater than permitted
Skipping molecule at index 2045 due to error: Explicit valence for atom # 11 O, 3, is greater than permitted
Skipping molecule at index 2047 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 2048 due to error: Explicit valence for atom # 7 N, 4, is greater than permitted
Skipping molecule at index 2049 due to error: Explicit valence for atom # 13 N, 4, is greater than permitted
Skipping molecule at index 2050 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 2056 due to error: Explicit valence for atom # 6 B, 4, is greater than permitted
Skipping molecule at index 2057 due to error: Explicit valence for atom # 23 B, 4, is greater than permitted
Skipping molecule at index 2058 due to error: Explicit valence for atom # 23 B, 4, is greater than permitted
Skipping molecule at index 2059 due to error: Explicit valence for atom # 9 B, 4, is greater than permitted
Skipping molecule at index 2060 due to error: Explicit valence for atom # 46 B, 4, is greater than permitted
Skipping molecule at index 2061 due to error: Explicit valence for atom # 66 B, 4, is greater than permitted
Skipping molecule at index 2062 due to error: Explicit valence for atom # 29 B, 4, is greater than permitted
Skipping molecule at index 2065 due to error: Explicit valence for atom # 59 B, 4, is greater than permitted
Skipping molecule at index 2069 due to error: Explicit valence for atom # 10 C, 6, is greater than permitted
Skipping molecule at index 2070 due to error: Explicit valence for atom # 9 C, 6, is greater than permitted
Skipping molecule at index 2071 due to error: Explicit valence for atom # 6 C, 6, is greater than permitted
Skipping molecule at index 2072 due to error: Explicit valence for atom # 19 C, 6, is greater than permitted
Skipping molecule at index 2073 due to error: Explicit valence for atom # 4 C, 6, is greater than permitted
Skipping molecule at index 2074 due to error: Explicit valence for atom # 3 C, 5, is greater than permitted
Skipping molecule at index 2075 due to error: Explicit valence for atom # 79 H, 2, is greater than permitted
Skipping molecule at index 2076 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 2078 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 2079 due to error: Explicit valence for atom # 19 B, 4, is greater than permitted
Skipping molecule at index 2080 due to error: Explicit valence for atom # 6 B, 4, is greater than permitted
Skipping molecule at index 2081 due to error: Explicit valence for atom # 11 B, 4, is greater than permitted
Skipping molecule at index 2082 due to error: Explicit valence for atom # 6 B, 6, is greater than permitted
Skipping molecule at index 2083 due to error: Explicit valence for atom # 4 N, 4, is greater than permitted
Skipping molecule at index 2084 due to error: Explicit valence for atom # 68 B, 4, is greater than permitted
Skipping molecule at index 2086 due to error: Can't kekulize mol.  Unkekulized atoms: 3 5 7 9 11
Skipping molecule at index 2089 due to error: Explicit valence for atom # 2 H, 2, is greater than permitted
Skipping molecule at index 2090 due to error: Explicit valence for atom # 64 B, 4, is greater than permitted
Skipping molecule at index 2091 due to error: Explicit valence for atom # 73 B, 4, is greater than permitted
Skipping molecule at index 2092 due to error: Explicit valence for atom # 15 B, 4, is greater than permitted
Skipping molecule at index 2093 due to error: Explicit valence for atom # 29 B, 4, is greater than permitted
Skipping molecule at index 2094 due to error: Explicit valence for atom # 29 B, 4, is greater than permitted
Skipping molecule at index 2095 due to error: Explicit valence for atom # 29 B, 4, is greater than permitted
Skipping molecule at index 2096 due to error: Explicit valence for atom # 29 B, 4, is greater than permitted
Skipping molecule at index 2097 due to error: Explicit valence for atom # 29 B, 4, is greater than permitted
Skipping molecule at index 2098 due to error: Explicit valence for atom # 15 B, 4, is greater than permitted
Skipping molecule at index 2099 due to error: Explicit valence for atom # 15 B, 4, is greater than permitted
Skipping molecule at index 2100 due to error: Explicit valence for atom # 15 B, 4, is greater than permitted
Skipping molecule at index 2101 due to error: Explicit valence for atom # 15 B, 4, is greater than permitted
Skipping molecule at index 2102 due to error: Explicit valence for atom # 15 B, 4, is greater than permitted
Skipping molecule at index 2103 due to error: Explicit valence for atom # 15 B, 4, is greater than permitted
Skipping molecule at index 2104 due to error: Explicit valence for atom # 15 B, 4, is greater than permitted
Skipping molecule at index 2108 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 2109 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 2110 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 2111 due to error: Explicit valence for atom # 0 Ga, 4, is greater than permitted
Skipping molecule at index 2112 due to error: Explicit valence for atom # 3 O, 3, is greater than permitted
Skipping molecule at index 2113 due to error: Explicit valence for atom # 3 O, 3, is greater than permitted
Skipping molecule at index 2114 due to error: Explicit valence for atom # 3 O, 3, is greater than permitted
Skipping molecule at index 2115 due to error: Explicit valence for atom # 40 N, 4, is greater than permitted
Skipping molecule at index 2116 due to error: Explicit valence for atom # 47 N, 4, is greater than permitted
Skipping molecule at index 2119 due to error: Explicit valence for atom # 33 B, 4, is greater than permitted
Skipping molecule at index 2120 due to error: Explicit valence for atom # 33 B, 4, is greater than permitted
Skipping molecule at index 2121 due to error: Explicit valence for atom # 1 B, 4, is greater than permitted
Skipping molecule at index 2122 due to error: Explicit valence for atom # 4 N, 4, is greater than permitted
Skipping molecule at index 2123 due to error: Explicit valence for atom # 0 B, 3, is greater than permitted
Skipping molecule at index 2124 due to error: Explicit valence for atom # 3 B, 4, is greater than permitted
Skipping molecule at index 2125 due to error: Explicit valence for atom # 3 B, 4, is greater than permitted
Skipping molecule at index 2126 due to error: Explicit valence for atom # 3 B, 4, is greater than permitted
Skipping molecule at index 2127 due to error: Explicit valence for atom # 1 B, 4, is greater than permitted
Skipping molecule at index 2128 due to error: Explicit valence for atom # 1 N, 4, is greater than permitted
Skipping molecule at index 2129 due to error: Explicit valence for atom # 2 B, 4, is greater than permitted
Skipping molecule at index 2130 due to error: Explicit valence for atom # 76 B, 4, is greater than permitted
Skipping molecule at index 2131 due to error: Can't kekulize mol.  Unkekulized atoms: 138 139 141 143 145
Skipping molecule at index 2132 due to error: Explicit valence for atom # 8 C, 6, is greater than permitted
Skipping molecule at index 2134 due to error: Explicit valence for atom # 35 B, 4, is greater than permitted

[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 68 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Can't kekulize mol.  Unkekulized atoms: 3 5 7 9 11
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 2 H, 2, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 64 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 73 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 15 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 29 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 29 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 29 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 29 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 29 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 15 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 15 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 15 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 15 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 15 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 15 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 15 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 0 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 0 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 0 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 0 Ga, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 3 O, 3, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 3 O, 3, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 3 O, 3, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 40 N, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 47 N, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 33 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 33 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 1 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 4 N, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 0 B, 3, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 3 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 3 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 3 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 1 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 1 N, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 2 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 76 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Can't kekulize mol.  Unkekulized atoms: 138 139 141 143 145
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:02] Explicit valence for atom # 8 C, 6, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 35 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 13 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 4 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Can't kekulize mol.  Unkekulized atoms: 5 6 8 10 12
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 2 O, 3, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 7 O, 3, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 110 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 11 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 1 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Can't kekulize mol.  Unkekulized atoms: 39 41 43 45 47
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 20 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 3 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 4 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 1 N, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 2 N, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 2 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 53 H, 2, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 9 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Can't kekulize mol.  Unkekulized atoms: 1 6 8 10 12
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 12 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 12 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:02] Explicit valence for atom # 6 B, 6, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 35 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 28 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 3 O, 3, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 3 O, 3, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 6 O, 3, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 0 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 0 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 0 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 0 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 0 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 0 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:02] Explicit valence for atom # 3 B, 6, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 0 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 0 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 1 O, 3, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 3 O, 3, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 72 O, 3, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 3 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 109 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 107 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 121 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 182 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 55 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 121 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 4 O, 3, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 91 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Can't kekulize mol.  Unkekulized atoms: 3 7 10 13 16 20 21 25 27 29
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 12 O, 3, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 1 F, 2, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 1 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 1 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 1 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.

Skipping molecule at index 2136 due to error: Explicit valence for atom # 13 B, 4, is greater than permitted
Skipping molecule at index 2138 due to error: Explicit valence for atom # 4 B, 4, is greater than permitted
Skipping molecule at index 2140 due to error: Can't kekulize mol.  Unkekulized atoms: 5 6 8 10 12
Skipping molecule at index 2141 due to error: Explicit valence for atom # 2 O, 3, is greater than permitted
Skipping molecule at index 2142 due to error: Explicit valence for atom # 7 O, 3, is greater than permitted
Skipping molecule at index 2144 due to error: Explicit valence for atom # 110 B, 4, is greater than permitted
Skipping molecule at index 2145 due to error: Explicit valence for atom # 11 B, 4, is greater than permitted
Skipping molecule at index 2146 due to error: Explicit valence for atom # 1 B, 4, is greater than permitted
Skipping molecule at index 2147 due to error: Can't kekulize mol.  Unkekulized atoms: 39 41 43 45 47
Skipping molecule at index 2148 due to error: Explicit valence for atom # 20 B, 4, is greater than permitted
Skipping molecule at index 2149 due to error: Explicit valence for atom # 3 B, 4, is greater than permitted
Skipping molecule at index 2150 due to error: Explicit valence for atom # 4 B, 4, is greater than permitted
Skipping molecule at index 2151 due to error: Explicit valence for atom # 1 N, 4, is greater than permitted
Skipping molecule at index 2152 due to error: Explicit valence for atom # 2 N, 4, is greater than permitted
Skipping molecule at index 2153 due to error: Explicit valence for atom # 2 B, 4, is greater than permitted
Skipping molecule at index 2157 due to error: Explicit valence for atom # 53 H, 2, is greater than permitted
Skipping molecule at index 2158 due to error: Explicit valence for atom # 9 B, 4, is greater than permitted
Skipping molecule at index 2159 due to error: Can't kekulize mol.  Unkekulized atoms: 1 6 8 10 12
Skipping molecule at index 2161 due to error: Explicit valence for atom # 12 B, 4, is greater than permitted
Skipping molecule at index 2162 due to error: Explicit valence for atom # 12 B, 4, is greater than permitted
Skipping molecule at index 2163 due to error: Explicit valence for atom # 6 B, 6, is greater than permitted
Skipping molecule at index 2166 due to error: Explicit valence for atom # 35 B, 4, is greater than permitted
Skipping molecule at index 2167 due to error: Explicit valence for atom # 28 B, 4, is greater than permitted
Skipping molecule at index 2168 due to error: Explicit valence for atom # 3 O, 3, is greater than permitted
Skipping molecule at index 2169 due to error: Explicit valence for atom # 3 O, 3, is greater than permitted
Skipping molecule at index 2170 due to error: Explicit valence for atom # 6 O, 3, is greater than permitted
Skipping molecule at index 2171 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 2172 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 2173 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 2174 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 2175 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 2176 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 2177 due to error: Explicit valence for atom # 3 B, 6, is greater than permitted
Skipping molecule at index 2180 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 2181 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 2182 due to error: Explicit valence for atom # 1 O, 3, is greater than permitted
Skipping molecule at index 2183 due to error: Explicit valence for atom # 3 O, 3, is greater than permitted
Skipping molecule at index 2184 due to error: Explicit valence for atom # 72 O, 3, is greater than permitted
Skipping molecule at index 2185 due to error: Explicit valence for atom # 3 B, 4, is greater than permitted
Skipping molecule at index 2186 due to error: Explicit valence for atom # 109 B, 4, is greater than permitted
Skipping molecule at index 2187 due to error: Explicit valence for atom # 107 B, 4, is greater than permitted
Skipping molecule at index 2188 due to error: Explicit valence for atom # 121 B, 4, is greater than permitted
Skipping molecule at index 2189 due to error: Explicit valence for atom # 182 B, 4, is greater than permitted
Skipping molecule at index 2190 due to error: Explicit valence for atom # 55 B, 4, is greater than permitted
Skipping molecule at index 2191 due to error: Explicit valence for atom # 121 B, 4, is greater than permitted
Skipping molecule at index 2192 due to error: Explicit valence for atom # 4 O, 3, is greater than permitted
Skipping molecule at index 2193 due to error: Explicit valence for atom # 91 B, 4, is greater than permitted
Skipping molecule at index 2194 due to error: Can't kekulize mol.  Unkekulized atoms: 3 7 10 13 16 20 21 25 27 29
Skipping molecule at index 2195 due to error: Explicit valence for atom # 12 O, 3, is greater than permitted
Skipping molecule at index 2196 due to error: Explicit valence for atom # 1 F, 2, is greater than permitted
Skipping molecule at index 2197 due to error: Explicit valence for atom # 1 B, 4, is greater than permitted
Skipping molecule at index 2198 due to error: Explicit valence for atom # 1 B, 4, is greater than permitted
Skipping molecule at index 2199 due to error: Explicit valence for atom # 1 B, 4, is greater than permitted
Skipping molecule at index 2200 due to error: Explicit valence for atom # 1 B, 4, is greater than permitted
Skipping molecule at index 2201 due to error: Explicit valence for atom # 2 C, 6, is greater than permitted
Skipping molecule at index 2202 due to error: Explicit valence for atom # 4 N, 4, is greater than permitted
Skipping molecule at index 2203 due to error: Explicit valence for atom # 0 C, 6, is greater than permitted
Skipping molecule at index 2204 due to error: Explicit valence for atom # 2 B, 6, is greater than permitted
Skipping molecule at index 2205 due to error: Explicit valence for atom # 120 B, 4, is greater than permitted
Skipping molecule at index 2206 due to error: Explicit valence for atom # 121 B, 4, is greater than permitted
Skipping molecule at index 2207 due to error: Explicit valence for atom # 37 B, 4, is greater than permitted
Skipping molecule at index 2208 due to error: Explicit valence for atom # 14 B, 4, is greater than permitted
Skipping molecule at index 2209 due to error: Explicit valence for atom # 91 B, 4, is greater than permitted
Skipping molecule at index 2210 due to error: Explicit valence for atom # 99 B, 4, is greater than permitted
Skipping molecule at index 2211 due to error: Explicit valence for atom # 93 B, 4, is greater than permitted
Skipping molecule at index 2212 due to error: Explicit valence for atom # 94 B, 4, is greater than permitted
Skipping molecule at index 2213 due to error: Explicit valence for atom # 10 B, 4, is greater than permitted
Skipping molecule at index 2214 due to error: Explicit valence for atom # 3 B, 4, is greater than permitted
Skipping molecule at index 2215 due to error: Explicit valence for atom # 4 B, 4, is greater than permitted
Skipping molecule at index 2218 due to error: Explicit valence for atom # 0 O, 3, is greater than permitted
Skipping molecule at index 2219 due to error: Explicit valence for atom # 78 B, 4, is greater than permitted
Skipping molecule at index 2220 due to error: Explicit valence for atom # 2 B, 4, is greater than permitted
Skipping molecule at index 2221 due to error: Explicit valence for atom # 2 B, 4, is greater than permitted
Skipping molecule at index 2224 due to error: Explicit valence for atom # 2 B, 4, is greater than permitted
Skipping molecule at index 2225 due to error: Explicit valence for atom # 1 B, 4, is greater than permitted
Skipping molecule at index 2226 due to error: Explicit valence for atom # 1 B, 4, is greater than permitted
Skipping molecule at index 2227 due to error: Explicit valence for atom # 1 B, 4, is greater than permitted
Skipping molecule at index 2228 due to error: Explicit valence for atom # 1 N, 4, is greater than permitted
Skipping molecule at index 2229 due to error: Explicit valence for atom # 4 O, 3, is greater than permitted
Skipping molecule at index 2230 due to error: Explicit valence for atom # 0 C, 6, is greater than permitted
Skipping molecule at index 2232 due to error: Explicit valence for atom # 3 N, 4, is greater than permitted
Skipping molecule at index 2237 due to error: Explicit valence for atom # 63 B, 4, is greater than permitted
Skipping molecule at index 2238 due to error: Explicit valence for atom # 97 B, 4, is greater than permitted
Skipping molecule at index 2240 due to error: Explicit valence for atom # 3 N, 4, is greater than permitted
Skipping molecule at index 2242 due to error: Explicit valence for atom # 7 B, 4, is greater than permitted
Skipping molecule at index 2243 due to error: Explicit valence for atom # 7 B, 4, is greater than permitted
Skipping molecule at index 2244 due to error: Explicit valence for atom # 4 B, 4, is greater than permitted
Skipping molecule at index 2245 due to error: Explicit valence for atom # 13 O, 3, is greater than permitted
Skipping molecule at index 2246 due to error: Explicit valence for atom # 3 O, 3, is greater than permitted
Skipping molecule at index 2247 due to error: Explicit valence for atom # 41 B, 4, is greater than permitted
Skipping molecule at index 2248 due to error: Explicit valence for atom # 1 N, 4, is greater than permitted
Skipping molecule at index 2249 due to error: Explicit valence for atom # 1 N, 4, is greater than permitted
Skipping molecule at index 2250 due to error: Explicit valence for atom # 21 B, 4, is greater than permitted
Skipping molecule at index 2251 due to error: Explicit valence for atom # 91 B, 4, is greater than permitted

[10:29:02] Explicit valence for atom # 3 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:02] Explicit valence for atom # 4 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 0 O, 3, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 78 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 2 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 2 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 2 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 1 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 1 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 1 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 1 N, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 4 O, 3, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:02] Explicit valence for atom # 0 C, 6, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 3 N, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 63 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 97 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 3 N, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 7 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 7 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 4 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 13 O, 3, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 3 O, 3, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 41 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 1 N, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 1 N, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 21 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 91 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 81 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 73 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 3 N, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 57 O, 3, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 0 Ga, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 4 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:02] Explicit valence for atom # 20 B, 6, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 47 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 52 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 52 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 47 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 22 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Can't kekulize mol.  Unkekulized atoms: 16 17 18 19 20 21 22 23 24
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 55 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Can't kekulize mol.  Unkekulized atoms: 53 54 57 59 61
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 39 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 0 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 9 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 0 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 3 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:02] Explicit valence for atom # 14 B, 4, is greater than permitted
[10:29:02] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 3 O, 3, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 3 O, 3, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:03] Explicit valence for atom # 4 C, 6, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:03] Explicit valence for atom # 12 C, 6, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 133 B, 4, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 244 B, 4, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:03] Explicit valence for atom # 10 B, 6, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 55 B, 4, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:03] Explicit valence for atom # 3 C, 6, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:03] Explicit valence for atom # 5 C, 6, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:03] Explicit valence for atom # 6 C, 6, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:03] Explicit valence for atom # 6 C, 6, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:03] Explicit valence for atom # 8 C, 6, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Can't kekulize mol.  Unkekulized atoms: 6 8 10 12 14
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 82 B, 4, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 8 B, 4, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 8 B, 4, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 8 B, 4, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 8 B, 4, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 8 B, 4, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 8 B, 4, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 8 B, 4, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 8 B, 4, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 8 B, 4, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 8 B, 4, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 2 O, 3, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 2 O, 3, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 1 B, 4, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 3 N, 4, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 2 N, 4, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 1 B, 4, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 1 B, 4, is greater than permitted

Skipping molecule at index 2252 due to error: Explicit valence for atom # 81 B, 4, is greater than permitted
Skipping molecule at index 2253 due to error: Explicit valence for atom # 73 B, 4, is greater than permitted
Skipping molecule at index 2254 due to error: Explicit valence for atom # 3 N, 4, is greater than permitted
Skipping molecule at index 2255 due to error: Explicit valence for atom # 57 O, 3, is greater than permitted
Skipping molecule at index 2256 due to error: Explicit valence for atom # 0 Ga, 4, is greater than permitted
Skipping molecule at index 2264 due to error: Explicit valence for atom # 4 B, 4, is greater than permitted
Skipping molecule at index 2265 due to error: Explicit valence for atom # 20 B, 6, is greater than permitted
Skipping molecule at index 2266 due to error: Explicit valence for atom # 47 B, 4, is greater than permitted
Skipping molecule at index 2268 due to error: Explicit valence for atom # 52 B, 4, is greater than permitted
Skipping molecule at index 2269 due to error: Explicit valence for atom # 52 B, 4, is greater than permitted
Skipping molecule at index 2270 due to error: Explicit valence for atom # 47 B, 4, is greater than permitted
Skipping molecule at index 2271 due to error: Explicit valence for atom # 22 B, 4, is greater than permitted
Skipping molecule at index 2272 due to error: Can't kekulize mol.  Unkekulized atoms: 16 17 18 19 20 21 22 23 24
Skipping molecule at index 2273 due to error: Explicit valence for atom # 55 B, 4, is greater than permitted
Skipping molecule at index 2276 due to error: Can't kekulize mol.  Unkekulized atoms: 53 54 57 59 61
Skipping molecule at index 2277 due to error: Explicit valence for atom # 39 B, 4, is greater than permitted
Skipping molecule at index 2278 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 2279 due to error: Explicit valence for atom # 9 B, 4, is greater than permitted
Skipping molecule at index 2280 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 2281 due to error: Explicit valence for atom # 3 B, 4, is greater than permitted
Skipping molecule at index 2282 due to error: Explicit valence for atom # 14 B, 4, is greater than permitted
Skipping molecule at index 2285 due to error: Explicit valence for atom # 3 O, 3, is greater than permitted
Skipping molecule at index 2286 due to error: Explicit valence for atom # 3 O, 3, is greater than permitted
Skipping molecule at index 2287 due to error: Explicit valence for atom # 4 C, 6, is greater than permitted
Skipping molecule at index 2288 due to error: Explicit valence for atom # 12 C, 6, is greater than permitted
Skipping molecule at index 2289 due to error: Explicit valence for atom # 133 B, 4, is greater than permitted
Skipping molecule at index 2294 due to error: Explicit valence for atom # 244 B, 4, is greater than permitted
Skipping molecule at index 2296 due to error: Explicit valence for atom # 10 B, 6, is greater than permitted
Skipping molecule at index 2297 due to error: Explicit valence for atom # 55 B, 4, is greater than permitted
Skipping molecule at index 2298 due to error: Explicit valence for atom # 3 C, 6, is greater than permitted
Skipping molecule at index 2299 due to error: Explicit valence for atom # 5 C, 6, is greater than permitted
Skipping molecule at index 2300 due to error: Explicit valence for atom # 6 C, 6, is greater than permitted
Skipping molecule at index 2301 due to error: Explicit valence for atom # 6 C, 6, is greater than permitted
Skipping molecule at index 2302 due to error: Explicit valence for atom # 8 C, 6, is greater than permitted
Skipping molecule at index 2305 due to error: Can't kekulize mol.  Unkekulized atoms: 6 8 10 12 14
Skipping molecule at index 2306 due to error: Explicit valence for atom # 82 B, 4, is greater than permitted
Skipping molecule at index 2307 due to error: Explicit valence for atom # 8 B, 4, is greater than permitted
Skipping molecule at index 2308 due to error: Explicit valence for atom # 8 B, 4, is greater than permitted
Skipping molecule at index 2309 due to error: Explicit valence for atom # 8 B, 4, is greater than permitted
Skipping molecule at index 2310 due to error: Explicit valence for atom # 8 B, 4, is greater than permitted
Skipping molecule at index 2311 due to error: Explicit valence for atom # 8 B, 4, is greater than permitted
Skipping molecule at index 2312 due to error: Explicit valence for atom # 8 B, 4, is greater than permitted
Skipping molecule at index 2313 due to error: Explicit valence for atom # 8 B, 4, is greater than permitted
Skipping molecule at index 2314 due to error: Explicit valence for atom # 8 B, 4, is greater than permitted
Skipping molecule at index 2315 due to error: Explicit valence for atom # 8 B, 4, is greater than permitted
Skipping molecule at index 2316 due to error: Explicit valence for atom # 8 B, 4, is greater than permitted
Skipping molecule at index 2322 due to error: Explicit valence for atom # 2 O, 3, is greater than permitted
Skipping molecule at index 2323 due to error: Explicit valence for atom # 2 O, 3, is greater than permitted
Skipping molecule at index 2324 due to error: Explicit valence for atom # 1 B, 4, is greater than permitted
Skipping molecule at index 2331 due to error: Explicit valence for atom # 3 N, 4, is greater than permitted
Skipping molecule at index 2332 due to error: Explicit valence for atom # 2 N, 4, is greater than permitted
Skipping molecule at index 2334 due to error: Explicit valence for atom # 1 B, 4, is greater than permitted
Skipping molecule at index 2335 due to error: Explicit valence for atom # 1 B, 4, is greater than permitted
Skipping molecule at index 2336 due to error: Explicit valence for atom # 0 Al, 4, is greater than permitted
Skipping molecule at index 2337 due to error: Explicit valence for atom # 0 Al, 4, is greater than permitted
Skipping molecule at index 2340 due to error: Explicit valence for atom # 2 B, 4, is greater than permitted
Skipping molecule at index 2341 due to error: Explicit valence for atom # 7 B, 4, is greater than permitted
Skipping molecule at index 2342 due to error: Explicit valence for atom # 10 B, 4, is greater than permitted
Skipping molecule at index 2343 due to error: Explicit valence for atom # 7 C, 6, is greater than permitted
Skipping molecule at index 2344 due to error: Explicit valence for atom # 8 C, 6, is greater than permitted
Skipping molecule at index 2345 due to error: Explicit valence for atom # 10 C, 6, is greater than permitted
Skipping molecule at index 2346 due to error: Explicit valence for atom # 88 F, 2, is greater than permitted
Skipping molecule at index 2351 due to error: Explicit valence for atom # 4 O, 3, is greater than permitted
Skipping molecule at index 2352 due to error: Explicit valence for atom # 4 O, 3, is greater than permitted
Skipping molecule at index 2353 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 2355 due to error: Explicit valence for atom # 1 B, 4, is greater than permitted
Skipping molecule at index 2356 due to error: Explicit valence for atom # 65 B, 4, is greater than permitted
Skipping molecule at index 2357 due to error: Explicit valence for atom # 2 O, 3, is greater than permitted
Skipping molecule at index 2358 due to error: Explicit valence for atom # 2 O, 3, is greater than permitted
Skipping molecule at index 2359 due to error: Explicit valence for atom # 5 N, 4, is greater than permitted
Skipping molecule at index 2360 due to error: Explicit valence for atom # 3 N, 4, is greater than permitted
Skipping molecule at index 2365 due to error: Explicit valence for atom # 9 B, 4, is greater than permitted
Skipping molecule at index 2366 due to error: Explicit valence for atom # 17 B, 4, is greater than permitted
Skipping molecule at index 2367 due to error: Explicit valence for atom # 17 B, 4, is greater than permitted
Skipping molecule at index 2368 due to error: Explicit valence for atom # 53 B, 4, is greater than permitted
Skipping molecule at index 2369 due to error: Explicit valence for atom # 53 B, 4, is greater than permitted
Skipping molecule at index 2370 due to error: Explicit valence for atom # 53 B, 4, is greater than permitted
Skipping molecule at index 2371 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 2372 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 2377 due to error: Explicit valence for atom # 0 Sn, 5, is greater than permitted
Skipping molecule at index 2379 due to error: Explicit valence for atom # 141 N, 4, is greater than permitted
Skipping molecule at index 2380 due to error: Explicit valence for atom # 1 O, 3, is greater than permitted
Skipping molecule at index 2381 due to error: Explicit valence for atom # 1 O, 3, is greater than permitted
Skipping molecule at index 2382 due to error: Explicit valence for atom # 6 C, 6, is greater than permitted
Skipping molecule at index 2383 due to error: Can't kekulize mol.  Unkekulized atoms: 0 1 3 5 7 8 9 11 13 15
Skipping molecule at index 2384 due to error: Explicit valence for atom # 3 C, 6, is greater than permitted
Skipping molecule at index 2385 due to error: Explicit valence for atom # 5 C, 6, is greater than permitted
Skipping molecule at index 2386 due to error: Explicit valence for atom # 4 C, 6, is greater than permitted
Skipping molecule at index 2387 due to error: Explicit valence for atom # 5 C, 6, is greater than permitted
Skipping molecule at index 2388 due to error: Explicit valence for atom # 76 B, 4, is greater than permitted
Skipping molecule at index 2389 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 2390 due to error: Explicit valence for atom # 3 B, 4, is greater than permitted
Skipping molecule at index 2391 due to error: Explicit valence for atom # 3 B, 4, is greater than permitted
Skipping molecule at index 2394 due to error: Can't kekulize mol.  Unkekulized atoms: 15 16 18 20 22 24 25 27 29 31 33 35 36 38 40 42
Skipping molecule at index 2395 due to error: Explicit valence for atom # 131 B, 4, is greater than permitted
Skipping molecule at index 2396 due to error: Explicit valence for atom # 129 B, 4, is greater than permitted
Skipping molecule at index 2401 due to error: Explicit valence for atom # 21 B, 4, is greater than permitted
Skipping molecule at index 2402 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 2403 due to error: Explicit valence for atom # 6 B, 4, is greater than permitted
Skipping molecule at index 2404 due to error: Explicit valence for atom # 1 B, 4, is greater than permitted
Skipping molecule at index 2407 due to error: Explicit valence for atom # 43 B, 4, is greater than permitted
Skipping molecule at index 2408 due to error: Explicit valence for atom # 16 B, 6, is greater than permitted
Skipping molecule at index 2409 due to error: Explicit valence for atom # 24 B, 6, is greater than permitted
Skipping molecule at index 2411 due to error: Explicit valence for atom # 38 B, 6, is greater than permitted
Skipping molecule at index 2413 due to error: Explicit valence for atom # 46 B, 6, is greater than permitted
Skipping molecule at index 2415 due to error: Explicit valence for atom # 39 B, 6, is greater than permitted
Skipping molecule at index 2416 due to error: Explicit valence for atom # 38 B, 6, is greater than permitted
Skipping molecule at index 2417 due to error: Explicit valence for atom # 10 C, 6, is greater than permitted
Skipping molecule at index 2418 due to error: Explicit valence for atom # 0 B, 6, is greater than permitted
Skipping molecule at index 2419 due to error: Explicit valence for atom # 0 B, 6, is greater than permitted
Skipping molecule at index 2420 due to error: Explicit valence for atom # 0 B, 6, is greater than permitted
Skipping molecule at index 2421 due to error: Explicit valence for atom # 0 B, 6, is greater than permitted
Skipping molecule at index 2422 due to error: Explicit valence for atom # 3 B, 6, is greater than permitted
Skipping molecule at index 2423 due to error: Explicit valence for atom # 6 B, 6, is greater than permitted
Skipping molecule at index 2426 due to error: Explicit valence for atom # 40 B, 4, is greater than permitted
Skipping molecule at index 2427 due to error: Explicit valence for atom # 6 C, 6, is greater than permitted
Skipping molecule at index 2428 due to error: Explicit valence for atom # 8 C, 6, is greater than permitted
Skipping molecule at index 2429 due to error: Explicit valence for atom # 1 O, 3, is greater than permitted
Skipping molecule at index 2430 due to error: Explicit valence for atom # 23 O, 3, is greater than permitted
Skipping molecule at index 2431 due to error: Explicit valence for atom # 1 O, 3, is greater than permitted
Skipping molecule at index 2432 due to error: Explicit valence for atom # 1 O, 3, is greater than permitted
Skipping molecule at index 2433 due to error: Explicit valence for atom # 11 C, 6, is greater than permitted
Skipping molecule at index 2434 due to error: Explicit valence for atom # 1 O, 3, is greater than permitted
Skipping molecule at index 2435 due to error: Explicit valence for atom # 1 N, 4, is greater than permitted
Skipping molecule at index 2436 due to error: Explicit valence for atom # 3 N, 4, is greater than permitted
Skipping molecule at index 2437 due to error: Explicit valence for atom # 2 B, 4, is greater than permitted
Skipping molecule at index 2438 due to error: Explicit valence for atom # 2 B, 4, is greater than permitted
Skipping molecule at index 2442 due to error: Explicit valence for atom # 3 O, 3, is greater than permitted
Skipping molecule at index 2443 due to error: Explicit valence for atom # 8 O, 3, is greater than permitted
Skipping molecule at index 2444 due to error: Explicit valence for atom # 2 B, 4, is greater than permitted
Skipping molecule at index 2445 due to error: Explicit valence for atom # 0 C, 6, is greater than permitted
Skipping molecule at index 2446 due to error: Explicit valence for atom # 0 C, 6, is greater than permitted
Skipping molecule at index 2447 due to error: Explicit valence for atom # 0 B, 6, is greater than permitted
Skipping molecule at index 2448 due to error: Explicit valence for atom # 3 C, 6, is greater than permitted
Skipping molecule at index 2449 due to error: Explicit valence for atom # 7 B, 6, is greater than permitted

[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 5 N, 4, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:03] Explicit valence for atom # 3 N, 4, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 9 B, 4, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 17 B, 4, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 17 B, 4, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 53 B, 4, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 53 B, 4, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 53 B, 4, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 0 B, 4, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 0 B, 4, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 0 Sn, 5, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 141 N, 4, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 1 O, 3, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 1 O, 3, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:03] Explicit valence for atom # 6 C, 6, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Can't kekulize mol.  Unkekulized atoms: 0 1 3 5 7 8 9 11 13 15
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:03] Explicit valence for atom # 3 C, 6, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:03] Explicit valence for atom # 5 C, 6, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:03] Explicit valence for atom # 4 C, 6, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:03] Explicit valence for atom # 5 C, 6, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 76 B, 4, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 0 B, 4, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 3 B, 4, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 3 B, 4, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Can't kekulize mol.  Unkekulized atoms: 15 16 18 20 22 24 25 27 29 31 33 35 36 38 40 42
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 131 B, 4, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 129 B, 4, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 21 B, 4, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 0 B, 4, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 6 B, 4, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 1 B, 4, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 43 B, 4, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:03] Explicit valence for atom # 16 B, 6, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:03] Explicit valence for atom # 24 B, 6, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:03] Explicit valence for atom # 38 B, 6, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:03] Explicit valence for atom # 46 B, 6, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:03] Explicit valence for atom # 39 B, 6, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:03] Explicit valence for atom # 38 B, 6, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:03] Explicit valence for atom # 10 C, 6, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:03] Explicit valence for atom # 0 B, 6, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:03] Explicit valence for atom # 0 B, 6, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:03] Explicit valence for atom # 0 B, 6, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:03] Explicit valence for atom # 0 B, 6, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:03] Explicit valence for atom # 3 B, 6, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:03] Explicit valence for atom # 6 B, 6, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 40 B, 4, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:03] Explicit valence for atom # 6 C, 6, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:03] Explicit valence for atom # 8 C, 6, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:03] Explicit valence for atom # 1 O, 3, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:03] Explicit valence for atom # 23 O, 3, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:03] Explicit valence for atom # 1 O, 3, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:03] Explicit valence for atom # 1 O, 3, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:03] Explicit valence for atom # 11 C, 6, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 1 O, 3, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 1 N, 4, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 3 N, 4, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 2 B, 4, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 2 B, 4, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 3 O, 3, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 8 O, 3, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 2 B, 4, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:03] Explicit valence for atom # 0 C, 6, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:03] Explicit valence for atom # 0 C, 6, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:03] Explicit valence for atom # 0 B, 6, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:03] Explicit valence for atom # 3 C, 6, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:03] Explicit valence for atom # 7 B, 6, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 82 B, 4, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 82 B, 4, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 59 B, 4, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 85 B, 4, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 62 B, 4, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 68 B, 4, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.

Skipping molecule at index 2450 due to error: Explicit valence for atom # 82 B, 4, is greater than permitted
Skipping molecule at index 2451 due to error: Explicit valence for atom # 82 B, 4, is greater than permitted
Skipping molecule at index 2452 due to error: Explicit valence for atom # 59 B, 4, is greater than permitted
Skipping molecule at index 2453 due to error: Explicit valence for atom # 85 B, 4, is greater than permitted
Skipping molecule at index 2454 due to error: Explicit valence for atom # 62 B, 4, is greater than permitted
Skipping molecule at index 2455 due to error: Explicit valence for atom # 68 B, 4, is greater than permitted
Skipping molecule at index 2459 due to error: Explicit valence for atom # 22 C, 5, is greater than permitted
Skipping molecule at index 2460 due to error: Explicit valence for atom # 7 C, 6, is greater than permitted
Skipping molecule at index 2461 due to error: Explicit valence for atom # 4 N, 4, is greater than permitted
Skipping molecule at index 2462 due to error: Explicit valence for atom # 5 C, 6, is greater than permitted
Skipping molecule at index 2463 due to error: Explicit valence for atom # 4 C, 6, is greater than permitted
Skipping molecule at index 2464 due to error: Explicit valence for atom # 5 C, 6, is greater than permitted
Skipping molecule at index 2465 due to error: Explicit valence for atom # 6 C, 6, is greater than permitted
Skipping molecule at index 2466 due to error: Explicit valence for atom # 6 C, 6, is greater than permitted
Skipping molecule at index 2467 due to error: Explicit valence for atom # 4 C, 6, is greater than permitted
Skipping molecule at index 2468 due to error: Explicit valence for atom # 5 C, 6, is greater than permitted
Skipping molecule at index 2469 due to error: Explicit valence for atom # 3 C, 6, is greater than permitted
Skipping molecule at index 2470 due to error: Explicit valence for atom # 6 C, 6, is greater than permitted
Skipping molecule at index 2471 due to error: Explicit valence for atom # 17 C, 6, is greater than permitted
Skipping molecule at index 2472 due to error: Explicit valence for atom # 14 B, 6, is greater than permitted
Skipping molecule at index 2473 due to error: Explicit valence for atom # 16 C, 6, is greater than permitted
Skipping molecule at index 2474 due to error: Explicit valence for atom # 11 C, 6, is greater than permitted
Skipping molecule at index 2475 due to error: Explicit valence for atom # 27 B, 6, is greater than permitted
Skipping molecule at index 2476 due to error: Explicit valence for atom # 10 C, 6, is greater than permitted
Skipping molecule at index 2477 due to error: Explicit valence for atom # 23 C, 6, is greater than permitted
Skipping molecule at index 2478 due to error: Explicit valence for atom # 0 C, 6, is greater than permitted
Skipping molecule at index 2479 due to error: Explicit valence for atom # 4 C, 6, is greater than permitted
Skipping molecule at index 2481 due to error: Explicit valence for atom # 1 B, 4, is greater than permitted
Skipping molecule at index 2482 due to error: Explicit valence for atom # 91 H, 2, is greater than permitted
Skipping molecule at index 2487 due to error: Explicit valence for atom # 8 B, 4, is greater than permitted
Skipping molecule at index 2488 due to error: Explicit valence for atom # 9 C, 6, is greater than permitted
Skipping molecule at index 2490 due to error: Explicit valence for atom # 17 O, 3, is greater than permitted
Skipping molecule at index 2491 due to error: Explicit valence for atom # 6 O, 3, is greater than permitted
Skipping molecule at index 2492 due to error: Explicit valence for atom # 3 O, 3, is greater than permitted
Skipping molecule at index 2493 due to error: Explicit valence for atom # 9 N, 4, is greater than permitted
Skipping molecule at index 2494 due to error: Can't kekulize mol.  Unkekulized atoms: 19 20 21 22 23 36 37 38 39 40
Skipping molecule at index 2495 due to error: Explicit valence for atom # 0 Si, 5, is greater than permitted
Skipping molecule at index 2496 due to error: Explicit valence for atom # 0 Si, 6, is greater than permitted
Skipping molecule at index 2497 due to error: Explicit valence for atom # 5 B, 4, is greater than permitted
Skipping molecule at index 2498 due to error: Explicit valence for atom # 2 N, 4, is greater than permitted
Skipping molecule at index 2499 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 2500 due to error: Explicit valence for atom # 2 O, 3, is greater than permitted
Skipping molecule at index 2501 due to error: Explicit valence for atom # 0 C, 6, is greater than permitted
Skipping molecule at index 2503 due to error: Explicit valence for atom # 9 B, 4, is greater than permitted
Skipping molecule at index 2504 due to error: Explicit valence for atom # 32 B, 4, is greater than permitted
Skipping molecule at index 2506 due to error: Explicit valence for atom # 32 B, 4, is greater than permitted
Skipping molecule at index 2508 due to error: Explicit valence for atom # 11 N, 4, is greater than permitted
Skipping molecule at index 2510 due to error: Explicit valence for atom # 10 N, 4, is greater than permitted
Skipping molecule at index 2512 due to error: Explicit valence for atom # 2 B, 4, is greater than permitted
Skipping molecule at index 2513 due to error: Explicit valence for atom # 4 N, 4, is greater than permitted
Skipping molecule at index 2514 due to error: Explicit valence for atom # 47 B, 4, is greater than permitted
Skipping molecule at index 2515 due to error: Can't kekulize mol.  Unkekulized atoms: 9 10 11 18 19 20
Skipping molecule at index 2516 due to error: Explicit valence for atom # 77 B, 4, is greater than permitted
Skipping molecule at index 2517 due to error: Explicit valence for atom # 23 C, 6, is greater than permitted
Skipping molecule at index 2522 due to error: Explicit valence for atom # 188 N, 4, is greater than permitted
Skipping molecule at index 2523 due to error: Explicit valence for atom # 18 B, 4, is greater than permitted
Skipping molecule at index 2524 due to error: Explicit valence for atom # 56 C, 9, is greater than permitted
Skipping molecule at index 2527 due to error: Explicit valence for atom # 5 B, 5, is greater than permitted
Skipping molecule at index 2528 due to error: Explicit valence for atom # 61 B, 4, is greater than permitted
Skipping molecule at index 2530 due to error: Explicit valence for atom # 1 B, 6, is greater than permitted
Skipping molecule at index 2531 due to error: Explicit valence for atom # 1 B, 6, is greater than permitted
Skipping molecule at index 2532 due to error: Explicit valence for atom # 25 B, 6, is greater than permitted
Skipping molecule at index 2533 due to error: Explicit valence for atom # 4 N, 4, is greater than permitted
Skipping molecule at index 2534 due to error: Explicit valence for atom # 55 B, 4, is greater than permitted
Skipping molecule at index 2535 due to error: Explicit valence for atom # 2 B, 4, is greater than permitted
Skipping molecule at index 2536 due to error: Explicit valence for atom # 4 B, 4, is greater than permitted
Skipping molecule at index 2539 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 2540 due to error: Explicit valence for atom # 104 B, 4, is greater than permitted
Skipping molecule at index 2541 due to error: Explicit valence for atom # 4 C, 6, is greater than permitted
Skipping molecule at index 2542 due to error: Explicit valence for atom # 4 B, 4, is greater than permitted
Skipping molecule at index 2543 due to error: Explicit valence for atom # 14 B, 4, is greater than permitted
Skipping molecule at index 2544 due to error: Explicit valence for atom # 2 N, 4, is greater than permitted
Skipping molecule at index 2545 due to error: Explicit valence for atom # 140 F, 2, is greater than permitted
Skipping molecule at index 2546 due to error: Can't kekulize mol.  Unkekulized atoms: 72 74 76 78 80
Skipping molecule at index 2548 due to error: Can't kekulize mol.  Unkekulized atoms: 130 132 134 136 138
Skipping molecule at index 2550 due to error: Explicit valence for atom # 8 O, 3, is greater than permitted
Skipping molecule at index 2551 due to error: Explicit valence for atom # 0 C, 6, is greater than permitted
Skipping molecule at index 2552 due to error: Can't kekulize mol.  Unkekulized atoms: 6 7 9 11 13
Skipping molecule at index 2553 due to error: Explicit valence for atom # 61 B, 4, is greater than permitted
Skipping molecule at index 2554 due to error: Explicit valence for atom # 4 O, 3, is greater than permitted
Skipping molecule at index 2555 due to error: Explicit valence for atom # 1 N, 4, is greater than permitted
Skipping molecule at index 2558 due to error: Explicit valence for atom # 22 N, 4, is greater than permitted
Skipping molecule at index 2559 due to error: Explicit valence for atom # 25 B, 4, is greater than permitted
Skipping molecule at index 2560 due to error: Explicit valence for atom # 25 B, 4, is greater than permitted
Skipping molecule at index 2561 due to error: Explicit valence for atom # 56 B, 4, is greater than permitted
Skipping molecule at index 2566 due to error: Explicit valence for atom # 40 B, 4, is greater than permitted
Skipping molecule at index 2567 due to error: Explicit valence for atom # 2 B, 4, is greater than permitted
Skipping molecule at index 2568 due to error: Explicit valence for atom # 79 H, 2, is greater than permitted
Skipping molecule at index 2569 due to error: Explicit valence for atom # 79 H, 2, is greater than permitted
Skipping molecule at index 2570 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 2571 due to error: Explicit valence for atom # 69 B, 4, is greater than permitted
Skipping molecule at index 2573 due to error: Explicit valence for atom # 18 C, 6, is greater than permitted
Skipping molecule at index 2574 due to error: Explicit valence for atom # 8 C, 6, is greater than permitted
Skipping molecule at index 2575 due to error: Explicit valence for atom # 1 N, 4, is greater than permitted
Skipping molecule at index 2576 due to error: Explicit valence for atom # 41 B, 4, is greater than permitted
Skipping molecule at index 2577 due to error: Explicit valence for atom # 5 N, 6, is greater than permitted
Skipping molecule at index 2578 due to error: Explicit valence for atom # 3 C, 6, is greater than permitted
Skipping molecule at index 2580 due to error: Explicit valence for atom # 46 B, 4, is greater than permitted
Skipping molecule at index 2584 due to error: Explicit valence for atom # 3 B, 4, is greater than permitted
Skipping molecule at index 2587 due to error: Explicit valence for atom # 88 B, 4, is greater than permitted
Skipping molecule at index 2588 due to error: Explicit valence for atom # 9 C, 6, is greater than permitted
Skipping molecule at index 2589 due to error: Can't kekulize mol.  Unkekulized atoms: 118 119 121 123 125
Skipping molecule at index 2591 due to error: Explicit valence for atom # 114 B, 4, is greater than permitted
Skipping molecule at index 2592 due to error: Explicit valence for atom # 114 B, 4, is greater than permitted
Skipping molecule at index 2594 due to error: Explicit valence for atom # 2 B, 4, is greater than permitted
Skipping molecule at index 2595 due to error: Explicit valence for atom # 2 B, 4, is greater than permitted
Skipping molecule at index 2596 due to error: Explicit valence for atom # 4 B, 6, is greater than permitted
Skipping molecule at index 2597 due to error: Explicit valence for atom # 14 B, 4, is greater than permitted
Skipping molecule at index 2600 due to error: Explicit valence for atom # 42 B, 4, is greater than permitted
Skipping molecule at index 2601 due to error: Explicit valence for atom # 21 B, 4, is greater than permitted
Skipping molecule at index 2602 due to error: Explicit valence for atom # 38 B, 4, is greater than permitted
Skipping molecule at index 2603 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 2604 due to error: Explicit valence for atom # 5 N, 4, is greater than permitted
Skipping molecule at index 2605 due to error: Explicit valence for atom # 10 N, 4, is greater than permitted
Skipping molecule at index 2606 due to error: Explicit valence for atom # 1 B, 4, is greater than permitted
Skipping molecule at index 2607 due to error: Explicit valence for atom # 7 N, 4, is greater than permitted
Skipping molecule at index 2610 due to error: Explicit valence for atom # 1 B, 5, is greater than permitted
Skipping molecule at index 2611 due to error: Explicit valence for atom # 1 N, 4, is greater than permitted
Skipping molecule at index 2612 due to error: Explicit valence for atom # 1 B, 5, is greater than permitted
Skipping molecule at index 2615 due to error: Explicit valence for atom # 7 B, 4, is greater than permitted
Skipping molecule at index 2616 due to error: Explicit valence for atom # 1 B, 4, is greater than permitted
Skipping molecule at index 2617 due to error: Explicit valence for atom # 1 N, 4, is greater than permitted
Skipping molecule at index 2618 due to error: Explicit valence for atom # 1 N, 4, is greater than permitted
Skipping molecule at index 2619 due to error: Explicit valence for atom # 1 B, 4, is greater than permitted
Skipping molecule at index 2620 due to error: Explicit valence for atom # 1 N, 4, is greater than permitted
Skipping molecule at index 2621 due to error: Explicit valence for atom # 1 B, 4, is greater than permitted
Skipping molecule at index 2622 due to error: Explicit valence for atom # 1 B, 4, is greater than permitted

[10:29:03] Explicit valence for atom # 46 B, 4, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 3 B, 4, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 88 B, 4, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:03] Explicit valence for atom # 9 C, 6, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Can't kekulize mol.  Unkekulized atoms: 118 119 121 123 125
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 114 B, 4, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 114 B, 4, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 2 B, 4, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 2 B, 4, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:03] Explicit valence for atom # 4 B, 6, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:03] Explicit valence for atom # 14 B, 4, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 42 B, 4, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 21 B, 4, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 38 B, 4, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 0 B, 4, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 5 N, 4, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 10 N, 4, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 1 B, 4, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 7 N, 4, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 1 B, 5, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 1 N, 4, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 1 B, 5, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:03] Explicit valence for atom # 7 B, 4, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 1 B, 4, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 1 N, 4, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 1 N, 4, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 1 B, 4, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 1 N, 4, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:03] Explicit valence for atom # 1 B, 4, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 1 B, 4, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 1 N, 4, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 1 N, 4, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 1 B, 4, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 1 B, 4, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 1 B, 4, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 1 B, 4, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 10 O, 3, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 3 N, 4, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 1 H, 2, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 1 H, 2, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 1 H, 2, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 127 B, 4, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 1 H, 2, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 115 H, 2, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 1 H, 2, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 2 B, 4, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 2 B, 4, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 3 B, 4, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 0 B, 4, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 8 B, 4, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 60 B, 4, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 0 Al, 5, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 84 B, 4, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 77 B, 4, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:03] Explicit valence for atom # 9 B, 6, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 0 B, 4, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 13 N, 4, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 10 O, 3, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 3 B, 4, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 2 B, 4, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Can't kekulize mol.  Unkekulized atoms: 4
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Can't kekulize mol.  Unkekulized atoms: 5
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 50 B, 4, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 50 B, 4, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 15 B, 4, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 1 F, 2, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 96 B, 4, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 1 B, 4, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 0 Ga, 4, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 2 B, 4, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 1 B, 4, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 1 B, 4, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 17 N, 4, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 114 B, 4, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 113 B, 4, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 14 N, 4, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 2 Cl, 2, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 1 B, 4, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:03] Explicit valence for atom # 5 C, 5, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 6 O, 3, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 6 O, 3, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 6 O, 3, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 43 B, 4, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 72 B, 4, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 0 B, 4, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 55 B, 4, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Can't kekulize mol.  Unkekulized atoms: 10 15 18 39 51
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 9 O, 3, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 3 F, 2, is greater than permitted

Skipping molecule at index 2623 due to error: Explicit valence for atom # 1 N, 4, is greater than permitted
Skipping molecule at index 2624 due to error: Explicit valence for atom # 1 N, 4, is greater than permitted
Skipping molecule at index 2625 due to error: Explicit valence for atom # 1 B, 4, is greater than permitted
Skipping molecule at index 2626 due to error: Explicit valence for atom # 1 B, 4, is greater than permitted
Skipping molecule at index 2627 due to error: Explicit valence for atom # 1 B, 4, is greater than permitted
Skipping molecule at index 2628 due to error: Explicit valence for atom # 1 B, 4, is greater than permitted
Skipping molecule at index 2629 due to error: Explicit valence for atom # 10 O, 3, is greater than permitted
Skipping molecule at index 2630 due to error: Explicit valence for atom # 3 N, 4, is greater than permitted
Skipping molecule at index 2631 due to error: Explicit valence for atom # 1 H, 2, is greater than permitted
Skipping molecule at index 2632 due to error: Explicit valence for atom # 1 H, 2, is greater than permitted
Skipping molecule at index 2633 due to error: Explicit valence for atom # 1 H, 2, is greater than permitted
Skipping molecule at index 2634 due to error: Explicit valence for atom # 127 B, 4, is greater than permitted
Skipping molecule at index 2635 due to error: Explicit valence for atom # 1 H, 2, is greater than permitted
Skipping molecule at index 2636 due to error: Explicit valence for atom # 115 H, 2, is greater than permitted
Skipping molecule at index 2637 due to error: Explicit valence for atom # 1 H, 2, is greater than permitted
Skipping molecule at index 2638 due to error: Explicit valence for atom # 2 B, 4, is greater than permitted
Skipping molecule at index 2639 due to error: Explicit valence for atom # 2 B, 4, is greater than permitted
Skipping molecule at index 2640 due to error: Explicit valence for atom # 3 B, 4, is greater than permitted
Skipping molecule at index 2641 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 2642 due to error: Explicit valence for atom # 8 B, 4, is greater than permitted
Skipping molecule at index 2643 due to error: Explicit valence for atom # 60 B, 4, is greater than permitted
Skipping molecule at index 2644 due to error: Explicit valence for atom # 0 Al, 5, is greater than permitted
Skipping molecule at index 2645 due to error: Explicit valence for atom # 84 B, 4, is greater than permitted
Skipping molecule at index 2646 due to error: Explicit valence for atom # 77 B, 4, is greater than permitted
Skipping molecule at index 2647 due to error: Explicit valence for atom # 9 B, 6, is greater than permitted
Skipping molecule at index 2650 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 2651 due to error: Explicit valence for atom # 13 N, 4, is greater than permitted
Skipping molecule at index 2652 due to error: Explicit valence for atom # 10 O, 3, is greater than permitted
Skipping molecule at index 2653 due to error: Explicit valence for atom # 3 B, 4, is greater than permitted
Skipping molecule at index 2654 due to error: Explicit valence for atom # 2 B, 4, is greater than permitted
Skipping molecule at index 2658 due to error: Can't kekulize mol.  Unkekulized atoms: 4
Skipping molecule at index 2659 due to error: Can't kekulize mol.  Unkekulized atoms: 5
Skipping molecule at index 2660 due to error: Explicit valence for atom # 50 B, 4, is greater than permitted
Skipping molecule at index 2661 due to error: Explicit valence for atom # 50 B, 4, is greater than permitted
Skipping molecule at index 2662 due to error: Explicit valence for atom # 15 B, 4, is greater than permitted
Skipping molecule at index 2663 due to error: Explicit valence for atom # 1 F, 2, is greater than permitted
Skipping molecule at index 2664 due to error: Explicit valence for atom # 96 B, 4, is greater than permitted
Skipping molecule at index 2665 due to error: Explicit valence for atom # 1 B, 4, is greater than permitted
Skipping molecule at index 2666 due to error: Explicit valence for atom # 0 Ga, 4, is greater than permitted
Skipping molecule at index 2667 due to error: Explicit valence for atom # 2 B, 4, is greater than permitted
Skipping molecule at index 2668 due to error: Explicit valence for atom # 1 B, 4, is greater than permitted
Skipping molecule at index 2669 due to error: Explicit valence for atom # 1 B, 4, is greater than permitted
Skipping molecule at index 2670 due to error: Explicit valence for atom # 17 N, 4, is greater than permitted
Skipping molecule at index 2671 due to error: Explicit valence for atom # 114 B, 4, is greater than permitted
Skipping molecule at index 2672 due to error: Explicit valence for atom # 113 B, 4, is greater than permitted
Skipping molecule at index 2673 due to error: Explicit valence for atom # 14 N, 4, is greater than permitted
Skipping molecule at index 2674 due to error: Explicit valence for atom # 2 Cl, 2, is greater than permitted
Skipping molecule at index 2681 due to error: Explicit valence for atom # 1 B, 4, is greater than permitted
Skipping molecule at index 2682 due to error: Explicit valence for atom # 5 C, 5, is greater than permitted
Skipping molecule at index 2683 due to error: Explicit valence for atom # 6 O, 3, is greater than permitted
Skipping molecule at index 2684 due to error: Explicit valence for atom # 6 O, 3, is greater than permitted
Skipping molecule at index 2685 due to error: Explicit valence for atom # 6 O, 3, is greater than permitted
Skipping molecule at index 2686 due to error: Explicit valence for atom # 43 B, 4, is greater than permitted
Skipping molecule at index 2687 due to error: Explicit valence for atom # 72 B, 4, is greater than permitted
Skipping molecule at index 2688 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 2691 due to error: Explicit valence for atom # 55 B, 4, is greater than permitted
Skipping molecule at index 2692 due to error: Can't kekulize mol.  Unkekulized atoms: 10 15 18 39 51
Skipping molecule at index 2693 due to error: Explicit valence for atom # 9 O, 3, is greater than permitted
Skipping molecule at index 2694 due to error: Explicit valence for atom # 3 F, 2, is greater than permitted
Skipping molecule at index 2695 due to error: Can't kekulize mol.  Unkekulized atoms: 8 9 10 17 18 19
Skipping molecule at index 2696 due to error: Explicit valence for atom # 84 B, 4, is greater than permitted
Skipping molecule at index 2697 due to error: Explicit valence for atom # 34 C, 6, is greater than permitted
Skipping molecule at index 2699 due to error: Explicit valence for atom # 2 C, 6, is greater than permitted
Skipping molecule at index 2701 due to error: Explicit valence for atom # 0 Sn, 5, is greater than permitted
Skipping molecule at index 2704 due to error: Explicit valence for atom # 5 B, 4, is greater than permitted
Skipping molecule at index 2714 due to error: Explicit valence for atom # 0 C, 5, is greater than permitted
Skipping molecule at index 2715 due to error: Explicit valence for atom # 4 N, 4, is greater than permitted
Skipping molecule at index 2716 due to error: Explicit valence for atom # 1 C, 6, is greater than permitted
Skipping molecule at index 2717 due to error: Explicit valence for atom # 1 C, 6, is greater than permitted
Skipping molecule at index 2718 due to error: Explicit valence for atom # 89 O, 3, is greater than permitted
Skipping molecule at index 2722 due to error: Explicit valence for atom # 0 Al, 4, is greater than permitted
Skipping molecule at index 2723 due to error: Explicit valence for atom # 152 Al, 4, is greater than permitted
Skipping molecule at index 2724 due to error: Explicit valence for atom # 0 Al, 4, is greater than permitted
Skipping molecule at index 2725 due to error: Explicit valence for atom # 0 Al, 4, is greater than permitted
Skipping molecule at index 2726 due to error: Explicit valence for atom # 1 Al, 4, is greater than permitted
Skipping molecule at index 2727 due to error: Explicit valence for atom # 22 B, 4, is greater than permitted
Skipping molecule at index 2728 due to error: Explicit valence for atom # 16 B, 4, is greater than permitted
Skipping molecule at index 2729 due to error: Explicit valence for atom # 4 B, 4, is greater than permitted
Skipping molecule at index 2730 due to error: Explicit valence for atom # 6 B, 4, is greater than permitted
Skipping molecule at index 2731 due to error: Explicit valence for atom # 2 N, 4, is greater than permitted
Skipping molecule at index 2736 due to error: Explicit valence for atom # 2 B, 4, is greater than permitted
Skipping molecule at index 2737 due to error: Explicit valence for atom # 44 B, 3, is greater than permitted
Skipping molecule at index 2738 due to error: Explicit valence for atom # 11 H, 2, is greater than permitted
Skipping molecule at index 2739 due to error: Explicit valence for atom # 8 H, 2, is greater than permitted
Skipping molecule at index 2740 due to error: Explicit valence for atom # 6 N, 4, is greater than permitted
Skipping molecule at index 2743 due to error: Explicit valence for atom # 5 N, 4, is greater than permitted
Skipping molecule at index 2744 due to error: Explicit valence for atom # 29 B, 4, is greater than permitted
Skipping molecule at index 2745 due to error: Explicit valence for atom # 57 B, 4, is greater than permitted
Skipping molecule at index 2746 due to error: Explicit valence for atom # 4 B, 6, is greater than permitted
Skipping molecule at index 2747 due to error: Explicit valence for atom # 27 C, 6, is greater than permitted
Skipping molecule at index 2748 due to error: Explicit valence for atom # 21 B, 6, is greater than permitted
Skipping molecule at index 2750 due to error: Explicit valence for atom # 77 B, 4, is greater than permitted
Skipping molecule at index 2751 due to error: Can't kekulize mol.  Unkekulized atoms: 15 17 19 20 22
Skipping molecule at index 2752 due to error: Can't kekulize mol.  Unkekulized atoms: 9 11 12 14 16
Skipping molecule at index 2753 due to error: Explicit valence for atom # 5 C, 6, is greater than permitted
Skipping molecule at index 2754 due to error: Explicit valence for atom # 1 N, 4, is greater than permitted
Skipping molecule at index 2755 due to error: Explicit valence for atom # 1 B, 4, is greater than permitted
Skipping molecule at index 2756 due to error: Explicit valence for atom # 1 B, 4, is greater than permitted
Skipping molecule at index 2758 due to error: Explicit valence for atom # 56 B, 4, is greater than permitted
Skipping molecule at index 2759 due to error: Explicit valence for atom # 5 N, 4, is greater than permitted
Skipping molecule at index 2761 due to error: Explicit valence for atom # 5 C, 6, is greater than permitted
Skipping molecule at index 2762 due to error: Explicit valence for atom # 6 C, 6, is greater than permitted
Skipping molecule at index 2763 due to error: Explicit valence for atom # 4 C, 6, is greater than permitted
Skipping molecule at index 2764 due to error: Explicit valence for atom # 4 C, 6, is greater than permitted
Skipping molecule at index 2766 due to error: Explicit valence for atom # 8 B, 4, is greater than permitted
Skipping molecule at index 2767 due to error: Explicit valence for atom # 0 C, 6, is greater than permitted
Skipping molecule at index 2768 due to error: Explicit valence for atom # 0 C, 6, is greater than permitted
Skipping molecule at index 2771 due to error: Explicit valence for atom # 73 C, 6, is greater than permitted
Skipping molecule at index 2773 due to error: Explicit valence for atom # 2 C, 6, is greater than permitted
Skipping molecule at index 2774 due to error: Explicit valence for atom # 1 N, 4, is greater than permitted

[10:29:03] Explicit valence for atom # 152 Al, 4, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 0 Al, 4, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 0 Al, 4, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 1 Al, 4, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 22 B, 4, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 16 B, 4, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 4 B, 4, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 6 B, 4, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 2 N, 4, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 2 B, 4, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 44 B, 3, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 11 H, 2, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 8 H, 2, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 6 N, 4, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 5 N, 4, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 29 B, 4, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 57 B, 4, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:03] Explicit valence for atom # 4 B, 6, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:03] Explicit valence for atom # 27 C, 6, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:03] Explicit valence for atom # 21 B, 6, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 77 B, 4, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Can't kekulize mol.  Unkekulized atoms: 15 17 19 20 22
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Can't kekulize mol.  Unkekulized atoms: 9 11 12 14 16
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:03] Explicit valence for atom # 5 C, 6, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 1 N, 4, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 1 B, 4, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 1 B, 4, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 56 B, 4, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 5 N, 4, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:03] Explicit valence for atom # 5 C, 6, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:03] Explicit valence for atom # 6 C, 6, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:03] Explicit valence for atom # 4 C, 6, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:03] Explicit valence for atom # 4 C, 6, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 8 B, 4, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:03] Explicit valence for atom # 0 C, 6, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:03] Explicit valence for atom # 0 C, 6, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:03] Explicit valence for atom # 73 C, 6, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:03] Explicit valence for atom # 2 C, 6, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 1 N, 4, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 30 B, 4, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 0 B, 4, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 3 N, 4, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 2 O, 3, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 2 O, 3, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 2 O, 3, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 8 O, 3, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 53 O, 3, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 51 B, 4, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 0 B, 4, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:03] Explicit valence for atom # 2 O, 3, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 1 O, 3, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:03] Explicit valence for atom # 5 B, 6, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 3 B, 4, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 142 B, 4, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 2 O, 3, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 21 B, 4, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 88 B, 4, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 2 B, 4, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 21 B, 4, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 3 Al, 4, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 0 B, 4, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Can't kekulize mol.  Unkekulized atoms: 2 4 6 8 10
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 1 B, 4, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 70 B, 4, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 70 B, 4, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 14 B, 4, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 1 B, 4, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 72 B, 4, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 0 B, 4, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 3 B, 4, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:03] Explicit valence for atom # 4 C, 6, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:03] Explicit valence for atom # 6 C, 6, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:03] Explicit valence for atom # 0 Al, 6, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:03] Explicit valence for atom # 0 Al, 6, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:03] Explicit valence for atom # 0 Al, 6, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:03] Explicit valence for atom # 0 Al, 6, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 37 B, 4, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 37 B, 4, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 8 B, 4, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 12 O, 3, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.

Skipping molecule at index 2776 due to error: Explicit valence for atom # 30 B, 4, is greater than permitted
Skipping molecule at index 2778 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 2779 due to error: Explicit valence for atom # 3 N, 4, is greater than permitted
Skipping molecule at index 2780 due to error: Explicit valence for atom # 2 O, 3, is greater than permitted
Skipping molecule at index 2781 due to error: Explicit valence for atom # 2 O, 3, is greater than permitted
Skipping molecule at index 2782 due to error: Explicit valence for atom # 2 O, 3, is greater than permitted
Skipping molecule at index 2783 due to error: Explicit valence for atom # 8 O, 3, is greater than permitted
Skipping molecule at index 2784 due to error: Explicit valence for atom # 53 O, 3, is greater than permitted
Skipping molecule at index 2785 due to error: Explicit valence for atom # 51 B, 4, is greater than permitted
Skipping molecule at index 2786 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 2795 due to error: Explicit valence for atom # 2 O, 3, is greater than permitted
Skipping molecule at index 2796 due to error: Explicit valence for atom # 1 O, 3, is greater than permitted
Skipping molecule at index 2797 due to error: Explicit valence for atom # 5 B, 6, is greater than permitted
Skipping molecule at index 2798 due to error: Explicit valence for atom # 3 B, 4, is greater than permitted
Skipping molecule at index 2799 due to error: Explicit valence for atom # 142 B, 4, is greater than permitted
Skipping molecule at index 2800 due to error: Explicit valence for atom # 2 O, 3, is greater than permitted
Skipping molecule at index 2801 due to error: Explicit valence for atom # 21 B, 4, is greater than permitted
Skipping molecule at index 2802 due to error: Explicit valence for atom # 88 B, 4, is greater than permitted
Skipping molecule at index 2803 due to error: Explicit valence for atom # 2 B, 4, is greater than permitted
Skipping molecule at index 2804 due to error: Explicit valence for atom # 21 B, 4, is greater than permitted
Skipping molecule at index 2805 due to error: Explicit valence for atom # 3 Al, 4, is greater than permitted
Skipping molecule at index 2806 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 2807 due to error: Can't kekulize mol.  Unkekulized atoms: 2 4 6 8 10
Skipping molecule at index 2808 due to error: Explicit valence for atom # 1 B, 4, is greater than permitted
Skipping molecule at index 2810 due to error: Explicit valence for atom # 70 B, 4, is greater than permitted
Skipping molecule at index 2811 due to error: Explicit valence for atom # 70 B, 4, is greater than permitted
Skipping molecule at index 2812 due to error: Explicit valence for atom # 14 B, 4, is greater than permitted
Skipping molecule at index 2813 due to error: Explicit valence for atom # 1 B, 4, is greater than permitted
Skipping molecule at index 2814 due to error: Explicit valence for atom # 72 B, 4, is greater than permitted
Skipping molecule at index 2815 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 2816 due to error: Explicit valence for atom # 3 B, 4, is greater than permitted
Skipping molecule at index 2817 due to error: Explicit valence for atom # 4 C, 6, is greater than permitted
Skipping molecule at index 2818 due to error: Explicit valence for atom # 6 C, 6, is greater than permitted
Skipping molecule at index 2819 due to error: Explicit valence for atom # 0 Al, 6, is greater than permitted
Skipping molecule at index 2820 due to error: Explicit valence for atom # 0 Al, 6, is greater than permitted
Skipping molecule at index 2821 due to error: Explicit valence for atom # 0 Al, 6, is greater than permitted
Skipping molecule at index 2822 due to error: Explicit valence for atom # 0 Al, 6, is greater than permitted
Skipping molecule at index 2825 due to error: Explicit valence for atom # 37 B, 4, is greater than permitted
Skipping molecule at index 2826 due to error: Explicit valence for atom # 37 B, 4, is greater than permitted
Skipping molecule at index 2829 due to error: Explicit valence for atom # 8 B, 4, is greater than permitted
Skipping molecule at index 2830 due to error: Explicit valence for atom # 12 O, 3, is greater than permitted
Skipping molecule at index 2832 due to error: Explicit valence for atom # 94 B, 4, is greater than permitted
Skipping molecule at index 2834 due to error: Explicit valence for atom # 3 B, 6, is greater than permitted
Skipping molecule at index 2835 due to error: Explicit valence for atom # 0 O, 3, is greater than permitted
Skipping molecule at index 2836 due to error: Explicit valence for atom # 43 B, 5, is greater than permitted
Skipping molecule at index 2837 due to error: Explicit valence for atom # 46 B, 5, is greater than permitted
Skipping molecule at index 2838 due to error: Explicit valence for atom # 42 B, 5, is greater than permitted
Skipping molecule at index 2839 due to error: Explicit valence for atom # 47 B, 5, is greater than permitted
Skipping molecule at index 2841 due to error: Explicit valence for atom # 81 B, 4, is greater than permitted
Skipping molecule at index 2842 due to error: Explicit valence for atom # 2 B, 4, is greater than permitted
Skipping molecule at index 2843 due to error: Explicit valence for atom # 28 B, 4, is greater than permitted
Skipping molecule at index 2848 due to error: Explicit valence for atom # 50 C, 6, is greater than permitted
Skipping molecule at index 2849 due to error: Explicit valence for atom # 20 B, 4, is greater than permitted
Skipping molecule at index 2850 due to error: Explicit valence for atom # 10 B, 4, is greater than permitted
Skipping molecule at index 2851 due to error: Explicit valence for atom # 4 B, 6, is greater than permitted
Skipping molecule at index 2852 due to error: Explicit valence for atom # 4 B, 4, is greater than permitted
Skipping molecule at index 2853 due to error: Explicit valence for atom # 5 H, 2, is greater than permitted
Skipping molecule at index 2854 due to error: Explicit valence for atom # 140 H, 2, is greater than permitted
Skipping molecule at index 2855 due to error: Explicit valence for atom # 154 H, 2, is greater than permitted
Skipping molecule at index 2856 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 2858 due to error: Explicit valence for atom # 13 B, 4, is greater than permitted
Skipping molecule at index 2859 due to error: Explicit valence for atom # 103 B, 4, is greater than permitted
Skipping molecule at index 2860 due to error: Explicit valence for atom # 90 B, 4, is greater than permitted
Skipping molecule at index 2861 due to error: Explicit valence for atom # 82 B, 4, is greater than permitted
Skipping molecule at index 2862 due to error: Explicit valence for atom # 54 B, 4, is greater than permitted
Skipping molecule at index 2863 due to error: Can't kekulize mol.  Unkekulized atoms: 137 150 151 152 157
Skipping molecule at index 2864 due to error: Explicit valence for atom # 3 Al, 4, is greater than permitted
Skipping molecule at index 2867 due to error: Explicit valence for atom # 22 C, 6, is greater than permitted
Skipping molecule at index 2869 due to error: Explicit valence for atom # 37 B, 4, is greater than permitted
Skipping molecule at index 2870 due to error: Explicit valence for atom # 85 B, 4, is greater than permitted
Skipping molecule at index 2871 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 2872 due to error: Can't kekulize mol.  Unkekulized atoms: 0 1 3 5 7
Skipping molecule at index 2873 due to error: Explicit valence for atom # 85 B, 4, is greater than permitted
Skipping molecule at index 2875 due to error: Explicit valence for atom # 2 N, 4, is greater than permitted
Skipping molecule at index 2876 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 2877 due to error: Explicit valence for atom # 11 N, 4, is greater than permitted
Skipping molecule at index 2878 due to error: Explicit valence for atom # 6 N, 4, is greater than permitted
Skipping molecule at index 2879 due to error: Explicit valence for atom # 13 N, 4, is greater than permitted
Skipping molecule at index 2880 due to error: Explicit valence for atom # 39 F, 2, is greater than permitted
Skipping molecule at index 2881 due to error: Explicit valence for atom # 0 Si, 5, is greater than permitted
Skipping molecule at index 2882 due to error: Explicit valence for atom # 7 C, 6, is greater than permitted
Skipping molecule at index 2883 due to error: Explicit valence for atom # 7 B, 6, is greater than permitted
Skipping molecule at index 2884 due to error: Explicit valence for atom # 7 C, 6, is greater than permitted
Skipping molecule at index 2885 due to error: Explicit valence for atom # 1 B, 4, is greater than permitted
Skipping molecule at index 2886 due to error: Explicit valence for atom # 0 Si, 5, is greater than permitted
Skipping molecule at index 2888 due to error: Can't kekulize mol.  Unkekulized atoms: 58 60 62 64 66
Skipping molecule at index 2889 due to error: Explicit valence for atom # 85 C, 6, is greater than permitted
Skipping molecule at index 2890 due to error: Explicit valence for atom # 78 C, 6, is greater than permitted
Skipping molecule at index 2891 due to error: Explicit valence for atom # 68 C, 6, is greater than permitted
Skipping molecule at index 2892 due to error: Explicit valence for atom # 97 C, 6, is greater than permitted
Skipping molecule at index 2893 due to error: Explicit valence for atom # 33 C, 6, is greater than permitted
Skipping molecule at index 2894 due to error: Explicit valence for atom # 85 C, 6, is greater than permitted
Skipping molecule at index 2895 due to error: Explicit valence for atom # 85 C, 6, is greater than permitted
Skipping molecule at index 2896 due to error: Explicit valence for atom # 57 C, 6, is greater than permitted
Skipping molecule at index 2897 due to error: Explicit valence for atom # 95 C, 6, is greater than permitted

[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:03] Explicit valence for atom # 85 C, 6, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:03] Explicit valence for atom # 78 C, 6, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:03] Explicit valence for atom # 68 C, 6, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:03] Explicit valence for atom # 97 C, 6, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:03] Explicit valence for atom # 33 C, 6, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:03] Explicit valence for atom # 85 C, 6, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:03] Explicit valence for atom # 85 C, 6, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:03] Explicit valence for atom # 57 C, 6, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:03] Explicit valence for atom # 95 C, 6, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:03] Explicit valence for atom # 84 C, 6, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:03] Explicit valence for atom # 67 C, 6, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:03] Explicit valence for atom # 56 C, 6, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:03] Explicit valence for atom # 68 C, 6, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:03] Explicit valence for atom # 76 C, 6, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:03] Explicit valence for atom # 68 C, 6, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:03] Explicit valence for atom # 84 C, 6, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:03] Explicit valence for atom # 79 C, 6, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:03] Explicit valence for atom # 92 C, 6, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:03] Explicit valence for atom # 53 C, 6, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Can't kekulize mol.  Unkekulized atoms: 5 9 11 14 17
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 17 B, 4, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 17 B, 4, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 17 B, 4, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 30 B, 4, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 2 N, 4, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:03] Explicit valence for atom # 21 C, 6, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:03] Explicit valence for atom # 41 C, 6, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 0 B, 4, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 0 B, 4, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 0 B, 4, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 0 B, 4, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 0 B, 4, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 0 B, 4, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 0 B, 4, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 0 B, 4, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 4 B, 4, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 26 O, 3, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 107 O, 3, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 103 O, 3, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 26 O, 3, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 4 O, 3, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 4 O, 3, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 5 O, 3, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 5 O, 3, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 66 B, 4, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 148 B, 4, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 0 Ga, 4, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 0 In, 4, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 0 In, 4, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 2 B, 4, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 1 B, 4, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:03] Explicit valence for atom # 5 C, 6, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:03] Explicit valence for atom # 2 C, 6, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 5 N, 4, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 2 N, 4, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 4 N, 4, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 1 N, 4, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 0 Si, 5, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 84 B, 4, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 0 B, 4, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 9 O, 3, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 53 N, 4, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 0 N, 4, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:03] Explicit valence for atom # 15 B, 5, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:03] Explicit valence for atom # 4 C, 6, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 1 O, 3, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 1 O, 3, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 1 O, 3, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 0 Al, 4, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 53 O, 3, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 2 B, 4, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 2 B, 4, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 2 B, 4, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 4 B, 4, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 6 B, 4, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 3 F, 2, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 5 B, 4, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:03] Explicit valence for atom # 1 Si, 4, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 7 Al, 4, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:03] Explicit valence for atom # 7 O, 3, is greater than permitted
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:03] Explicit valence for atom # 70 B, 4, is greater than permitted

Skipping molecule at index 2898 due to error: Explicit valence for atom # 84 C, 6, is greater than permitted
Skipping molecule at index 2899 due to error: Explicit valence for atom # 67 C, 6, is greater than permitted
Skipping molecule at index 2900 due to error: Explicit valence for atom # 56 C, 6, is greater than permitted
Skipping molecule at index 2901 due to error: Explicit valence for atom # 68 C, 6, is greater than permitted
Skipping molecule at index 2902 due to error: Explicit valence for atom # 76 C, 6, is greater than permitted
Skipping molecule at index 2903 due to error: Explicit valence for atom # 68 C, 6, is greater than permitted
Skipping molecule at index 2904 due to error: Explicit valence for atom # 84 C, 6, is greater than permitted
Skipping molecule at index 2905 due to error: Explicit valence for atom # 79 C, 6, is greater than permitted
Skipping molecule at index 2906 due to error: Explicit valence for atom # 92 C, 6, is greater than permitted
Skipping molecule at index 2907 due to error: Explicit valence for atom # 53 C, 6, is greater than permitted
Skipping molecule at index 2908 due to error: Can't kekulize mol.  Unkekulized atoms: 5 9 11 14 17
Skipping molecule at index 2911 due to error: Explicit valence for atom # 17 B, 4, is greater than permitted
Skipping molecule at index 2912 due to error: Explicit valence for atom # 17 B, 4, is greater than permitted
Skipping molecule at index 2913 due to error: Explicit valence for atom # 17 B, 4, is greater than permitted
Skipping molecule at index 2914 due to error: Explicit valence for atom # 30 B, 4, is greater than permitted
Skipping molecule at index 2915 due to error: Explicit valence for atom # 2 N, 4, is greater than permitted
Skipping molecule at index 2916 due to error: Explicit valence for atom # 21 C, 6, is greater than permitted
Skipping molecule at index 2917 due to error: Explicit valence for atom # 41 C, 6, is greater than permitted
Skipping molecule at index 2919 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 2922 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 2924 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 2926 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 2928 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 2930 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 2932 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 2933 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 2934 due to error: Explicit valence for atom # 4 B, 4, is greater than permitted
Skipping molecule at index 2939 due to error: Explicit valence for atom # 26 O, 3, is greater than permitted
Skipping molecule at index 2940 due to error: Explicit valence for atom # 107 O, 3, is greater than permitted
Skipping molecule at index 2941 due to error: Explicit valence for atom # 103 O, 3, is greater than permitted
Skipping molecule at index 2942 due to error: Explicit valence for atom # 26 O, 3, is greater than permitted
Skipping molecule at index 2943 due to error: Explicit valence for atom # 4 O, 3, is greater than permitted
Skipping molecule at index 2944 due to error: Explicit valence for atom # 4 O, 3, is greater than permitted
Skipping molecule at index 2945 due to error: Explicit valence for atom # 5 O, 3, is greater than permitted
Skipping molecule at index 2946 due to error: Explicit valence for atom # 5 O, 3, is greater than permitted
Skipping molecule at index 2947 due to error: Explicit valence for atom # 66 B, 4, is greater than permitted
Skipping molecule at index 2948 due to error: Explicit valence for atom # 148 B, 4, is greater than permitted
Skipping molecule at index 2949 due to error: Explicit valence for atom # 0 Ga, 4, is greater than permitted
Skipping molecule at index 2950 due to error: Explicit valence for atom # 0 In, 4, is greater than permitted
Skipping molecule at index 2951 due to error: Explicit valence for atom # 0 In, 4, is greater than permitted
Skipping molecule at index 2952 due to error: Explicit valence for atom # 2 B, 4, is greater than permitted
Skipping molecule at index 2953 due to error: Explicit valence for atom # 1 B, 4, is greater than permitted
Skipping molecule at index 2954 due to error: Explicit valence for atom # 5 C, 6, is greater than permitted
Skipping molecule at index 2955 due to error: Explicit valence for atom # 2 C, 6, is greater than permitted
Skipping molecule at index 2958 due to error: Explicit valence for atom # 5 N, 4, is greater than permitted
Skipping molecule at index 2960 due to error: Explicit valence for atom # 2 N, 4, is greater than permitted
Skipping molecule at index 2962 due to error: Explicit valence for atom # 4 N, 4, is greater than permitted
Skipping molecule at index 2964 due to error: Explicit valence for atom # 1 N, 4, is greater than permitted
Skipping molecule at index 2965 due to error: Explicit valence for atom # 0 Si, 5, is greater than permitted
Skipping molecule at index 2966 due to error: Explicit valence for atom # 84 B, 4, is greater than permitted
Skipping molecule at index 2967 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 2968 due to error: Explicit valence for atom # 9 O, 3, is greater than permitted
Skipping molecule at index 2969 due to error: Explicit valence for atom # 53 N, 4, is greater than permitted
Skipping molecule at index 2970 due to error: Explicit valence for atom # 0 N, 4, is greater than permitted
Skipping molecule at index 2971 due to error: Explicit valence for atom # 15 B, 5, is greater than permitted
Skipping molecule at index 2972 due to error: Explicit valence for atom # 4 C, 6, is greater than permitted
Skipping molecule at index 2973 due to error: Explicit valence for atom # 1 O, 3, is greater than permitted
Skipping molecule at index 2974 due to error: Explicit valence for atom # 1 O, 3, is greater than permitted
Skipping molecule at index 2975 due to error: Explicit valence for atom # 1 O, 3, is greater than permitted
Skipping molecule at index 2976 due to error: Explicit valence for atom # 0 Al, 4, is greater than permitted
Skipping molecule at index 2977 due to error: Explicit valence for atom # 53 O, 3, is greater than permitted
Skipping molecule at index 2978 due to error: Explicit valence for atom # 2 B, 4, is greater than permitted
Skipping molecule at index 2979 due to error: Explicit valence for atom # 2 B, 4, is greater than permitted
Skipping molecule at index 2980 due to error: Explicit valence for atom # 2 B, 4, is greater than permitted
Skipping molecule at index 2981 due to error: Explicit valence for atom # 4 B, 4, is greater than permitted
Skipping molecule at index 2982 due to error: Explicit valence for atom # 6 B, 4, is greater than permitted
Skipping molecule at index 2984 due to error: Explicit valence for atom # 3 F, 2, is greater than permitted
Skipping molecule at index 2985 due to error: Explicit valence for atom # 5 B, 4, is greater than permitted
Skipping molecule at index 2986 due to error: Explicit valence for atom # 1 Si, 4, is greater than permitted
Skipping molecule at index 2988 due to error: Explicit valence for atom # 7 Al, 4, is greater than permitted
Skipping molecule at index 2990 due to error: Explicit valence for atom # 7 O, 3, is greater than permitted
Skipping molecule at index 2998 due to error: Explicit valence for atom # 70 B, 4, is greater than permitted
Skipping molecule at index 2999 due to error: Explicit valence for atom # 0 B, 6, is greater than permitted
Skipping molecule at index 3000 due to error: Explicit valence for atom # 0 B, 6, is greater than permitted
Skipping molecule at index 3001 due to error: Explicit valence for atom # 5 C, 6, is greater than permitted
Skipping molecule at index 3002 due to error: Explicit valence for atom # 86 B, 4, is greater than permitted
Skipping molecule at index 3004 due to error: Explicit valence for atom # 17 O, 3, is greater than permitted
Skipping molecule at index 3005 due to error: Explicit valence for atom # 4 N, 4, is greater than permitted
Skipping molecule at index 3006 due to error: Explicit valence for atom # 6 N, 4, is greater than permitted
Skipping molecule at index 3007 due to error: Explicit valence for atom # 8 B, 4, is greater than permitted
Skipping molecule at index 3009 due to error: Explicit valence for atom # 0 N, 4, is greater than permitted
Skipping molecule at index 3010 due to error: Explicit valence for atom # 1 B, 4, is greater than permitted
Skipping molecule at index 3011 due to error: Explicit valence for atom # 10 B, 4, is greater than permitted
Skipping molecule at index 3015 due to error: Explicit valence for atom # 3 B, 4, is greater than permitted
Skipping molecule at index 3016 due to error: Explicit valence for atom # 4 O, 3, is greater than permitted
Skipping molecule at index 3017 due to error: Explicit valence for atom # 6 O, 3, is greater than permitted
Skipping molecule at index 3019 due to error: Explicit valence for atom # 92 O, 3, is greater than permitted
Skipping molecule at index 3020 due to error: Can't kekulize mol.  Unkekulized atoms: 42 43 45 46 47 49 51 52 54 56 58
Skipping molecule at index 3021 due to error: Explicit valence for atom # 31 O, 3, is greater than permitted
Skipping molecule at index 3023 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 3024 due to error: Explicit valence for atom # 7 B, 4, is greater than permitted
Skipping molecule at index 3025 due to error: Explicit valence for atom # 1 O, 3, is greater than permitted
Skipping molecule at index 3026 due to error: Explicit valence for atom # 102 B, 5, is greater than permitted
Skipping molecule at index 3027 due to error: Explicit valence for atom # 23 B, 4, is greater than permitted
Skipping molecule at index 3028 due to error: Explicit valence for atom # 29 B, 4, is greater than permitted
Skipping molecule at index 3029 due to error: Explicit valence for atom # 29 B, 4, is greater than permitted
Skipping molecule at index 3030 due to error: Explicit valence for atom # 29 B, 4, is greater than permitted
Skipping molecule at index 3031 due to error: Explicit valence for atom # 8 C, 5, is greater than permitted
Skipping molecule at index 3032 due to error: Explicit valence for atom # 1 B, 4, is greater than permitted
Skipping molecule at index 3033 due to error: Explicit valence for atom # 13 O, 3, is greater than permitted
Skipping molecule at index 3034 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 3035 due to error: Explicit valence for atom # 6 N, 4, is greater than permitted
Skipping molecule at index 3036 due to error: Explicit valence for atom # 29 B, 4, is greater than permitted
Skipping molecule at index 3037 due to error: Explicit valence for atom # 1 C, 6, is greater than permitted
Skipping molecule at index 3038 due to error: Explicit valence for atom # 2 N, 4, is greater than permitted
Skipping molecule at index 3039 due to error: Explicit valence for atom # 33 B, 4, is greater than permitted
Skipping molecule at index 3040 due to error: Explicit valence for atom # 25 B, 6, is greater than permitted
Skipping molecule at index 3041 due to error: Explicit valence for atom # 4 C, 6, is greater than permitted
Skipping molecule at index 3042 due to error: Explicit valence for atom # 20 C, 6, is greater than permitted
Skipping molecule at index 3043 due to error: Explicit valence for atom # 7 N, 4, is greater than permitted
Skipping molecule at index 3044 due to error: Explicit valence for atom # 6 N, 4, is greater than permitted
Skipping molecule at index 3045 due to error: Can't kekulize mol.  Unkekulized atoms: 1 109
Skipping molecule at index 3046 due to error: Can't kekulize mol.  Unkekulized atoms: 7
Skipping molecule at index 3047 due to error: Can't kekulize mol.  Unkekulized atoms: 6
Skipping molecule at index 3049 due to error: Can't kekulize mol.  Unkekulized atoms: 69
Skipping molecule at index 3054 due to error: Explicit valence for atom # 10 N, 4, is greater than permitted
Skipping molecule at index 3060 due to error: Explicit valence for atom # 1 B, 4, is greater than permitted
Skipping molecule at index 3062 due to error: Explicit valence for atom # 22 O, 3, is greater than permitted
Skipping molecule at index 3065 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 3066 due to error: Explicit valence for atom # 5 N, 4, is greater than permitted
Skipping molecule at index 3067 due to error: Explicit valence for atom # 1 H, 2, is greater than permitted
Skipping molecule at index 3072 due to error: Explicit valence for atom # 1 B, 4, is greater than permitted
Skipping molecule at index 3073 due to error: Explicit valence for atom # 1 O, 11, is greater than permitted
Skipping molecule at index 3075 due to error: Explicit valence for atom # 97 B, 4, is greater than permitted
Skipping molecule at index 3076 due to error: Explicit valence for atom # 12 B, 5, is greater than permitted
Skipping molecule at index 3077 due to error: Explicit valence for atom # 0 Ga, 6, is greater than permitted
Skipping molecule at index 3078 due to error: Explicit valence for atom # 10 B, 4, is greater than permitted
Skipping molecule at index 3079 due to error: Explicit valence for atom # 1 B, 4, is greater than permitted
Skipping molecule at index 3080 due to error: Explicit valence for atom # 1 B, 4, is greater than permitted
Skipping molecule at index 3081 due to error: Explicit valence for atom # 21 B, 4, is greater than permitted
Skipping molecule at index 3082 due to error: Explicit valence for atom # 18 B, 4, is greater than permitted
Skipping molecule at index 3084 due to error: Explicit valence for atom # 1 N, 4, is greater than permitted
Skipping molecule at index 3085 due to error: Explicit valence for atom # 1 B, 4, is greater than permitted
Skipping molecule at index 3086 due to error: Explicit valence for atom # 1 B, 4, is greater than permitted
Skipping molecule at index 3087 due to error: Explicit valence for atom # 1 B, 4, is greater than permitted
Skipping molecule at index 3088 due to error: Explicit valence for atom # 1 B, 4, is greater than permitted
Skipping molecule at index 3089 due to error: Explicit valence for atom # 0 Sn, 5, is greater than permitted
Skipping molecule at index 3090 due to error: Explicit valence for atom # 4 O, 3, is greater than permitted
Skipping molecule at index 3091 due to error: Explicit valence for atom # 2 O, 3, is greater than permitted
Skipping molecule at index 3092 due to error: Explicit valence for atom # 6 O, 3, is greater than permitted
Skipping molecule at index 3093 due to error: Explicit valence for atom # 8 O, 3, is greater than permitted
Skipping molecule at index 3094 due to error: Explicit valence for atom # 11 O, 3, is greater than permitted
Skipping molecule at index 3095 due to error: Explicit valence for atom # 8 O, 3, is greater than permitted
Skipping molecule at index 3096 due to error: Explicit valence for atom # 11 O, 3, is greater than permitted
Skipping molecule at index 3097 due to error: Explicit valence for atom # 4 C, 6, is greater than permitted
Skipping molecule at index 3098 due to error: Explicit valence for atom # 10 B, 4, is greater than permitted
Skipping molecule at index 3099 due to error: Explicit valence for atom # 2 B, 4, is greater than permitted
Skipping molecule at index 3100 due to error: Explicit valence for atom # 9 O, 3, is greater than permitted
Skipping molecule at index 3101 due to error: Explicit valence for atom # 2 B, 4, is greater than permitted
Skipping molecule at index 3102 due to error: Explicit valence for atom # 2 B, 4, is greater than permitted
Skipping molecule at index 3103 due to error: Explicit valence for atom # 3 B, 4, is greater than permitted
Skipping molecule at index 3104 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 3105 due to error: Explicit valence for atom # 23 B, 4, is greater than permitted
Skipping molecule at index 3106 due to error: Explicit valence for atom # 9 C, 6, is greater than permitted
Skipping molecule at index 3107 due to error: Explicit valence for atom # 9 C, 6, is greater than permitted

[10:29:04] Explicit valence for atom # 10 N, 4, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 1 B, 4, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 22 O, 3, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 0 B, 4, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 5 N, 4, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 1 H, 2, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 1 B, 4, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:04] Explicit valence for atom # 1 O, 11, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 97 B, 4, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 12 B, 5, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 0 Ga, 6, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 10 B, 4, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 1 B, 4, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 1 B, 4, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 21 B, 4, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 18 B, 4, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 1 N, 4, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 1 B, 4, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 1 B, 4, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 1 B, 4, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 1 B, 4, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 0 Sn, 5, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 4 O, 3, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 2 O, 3, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 6 O, 3, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 8 O, 3, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 11 O, 3, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 8 O, 3, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 11 O, 3, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:04] Explicit valence for atom # 4 C, 6, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 10 B, 4, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 2 B, 4, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 9 O, 3, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:04] Explicit valence for atom # 2 B, 4, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:04] Explicit valence for atom # 2 B, 4, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 3 B, 4, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 0 B, 4, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 23 B, 4, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:04] Explicit valence for atom # 9 C, 6, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:04] Explicit valence for atom # 9 C, 6, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 5 B, 4, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 2 O, 3, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 6 B, 5, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 19 B, 5, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 14 N, 4, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 45 B, 4, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 4 O, 3, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 5 O, 3, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 19 O, 3, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 16 O, 3, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 16 O, 3, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 17 O, 3, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:04] Explicit valence for atom # 35 C, 6, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 9 N, 4, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 82 B, 4, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 39 B, 4, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 34 B, 4, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:04] Explicit valence for atom # 7 N, 4, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 21 B, 4, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 24 B, 4, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 46 B, 4, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 0 B, 4, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 119 B, 4, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 62 B, 4, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 0 B, 4, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 6 O, 3, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 62 B, 4, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 41 B, 4, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:04] Explicit valence for atom # 3 B, 6, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:04] Explicit valence for atom # 4 C, 6, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:04] Explicit valence for atom # 6 C, 6, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:04] Explicit valence for atom # 0 B, 6, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:04] Explicit valence for atom # 0 B, 6, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:04] Explicit valence for atom # 11 C, 6, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Can't kekulize mol.  Unkekulized atoms: 10 12 14 16 18
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:04] Explicit valence for atom # 7 C, 6, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:04] Explicit valence for atom # 2 C, 6, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 3 B, 4, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Can't kekulize mol.  Unkekulized atoms: 10 11 13 18 20 21 22 24 26 28 29 30 32 37 39
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:04] Explicit valence for atom # 5 C, 6, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:04] Explicit valence for atom # 8 C, 6, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 106 B, 4, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.

Skipping molecule at index 3111 due to error: Explicit valence for atom # 5 B, 4, is greater than permitted
Skipping molecule at index 3112 due to error: Explicit valence for atom # 2 O, 3, is greater than permitted
Skipping molecule at index 3113 due to error: Explicit valence for atom # 6 B, 5, is greater than permitted
Skipping molecule at index 3114 due to error: Explicit valence for atom # 19 B, 5, is greater than permitted
Skipping molecule at index 3115 due to error: Explicit valence for atom # 14 N, 4, is greater than permitted
Skipping molecule at index 3116 due to error: Explicit valence for atom # 45 B, 4, is greater than permitted
Skipping molecule at index 3117 due to error: Explicit valence for atom # 4 O, 3, is greater than permitted
Skipping molecule at index 3118 due to error: Explicit valence for atom # 5 O, 3, is greater than permitted
Skipping molecule at index 3119 due to error: Explicit valence for atom # 19 O, 3, is greater than permitted
Skipping molecule at index 3120 due to error: Explicit valence for atom # 16 O, 3, is greater than permitted
Skipping molecule at index 3121 due to error: Explicit valence for atom # 16 O, 3, is greater than permitted
Skipping molecule at index 3122 due to error: Explicit valence for atom # 17 O, 3, is greater than permitted
Skipping molecule at index 3123 due to error: Explicit valence for atom # 35 C, 6, is greater than permitted
Skipping molecule at index 3124 due to error: Explicit valence for atom # 9 N, 4, is greater than permitted
Skipping molecule at index 3127 due to error: Explicit valence for atom # 82 B, 4, is greater than permitted
Skipping molecule at index 3128 due to error: Explicit valence for atom # 39 B, 4, is greater than permitted
Skipping molecule at index 3129 due to error: Explicit valence for atom # 34 B, 4, is greater than permitted
Skipping molecule at index 3131 due to error: Explicit valence for atom # 7 N, 4, is greater than permitted
Skipping molecule at index 3132 due to error: Explicit valence for atom # 21 B, 4, is greater than permitted
Skipping molecule at index 3133 due to error: Explicit valence for atom # 24 B, 4, is greater than permitted
Skipping molecule at index 3134 due to error: Explicit valence for atom # 46 B, 4, is greater than permitted
Skipping molecule at index 3135 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 3136 due to error: Explicit valence for atom # 119 B, 4, is greater than permitted
Skipping molecule at index 3137 due to error: Explicit valence for atom # 62 B, 4, is greater than permitted
Skipping molecule at index 3138 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 3139 due to error: Explicit valence for atom # 6 O, 3, is greater than permitted
Skipping molecule at index 3142 due to error: Explicit valence for atom # 62 B, 4, is greater than permitted
Skipping molecule at index 3143 due to error: Explicit valence for atom # 41 B, 4, is greater than permitted
Skipping molecule at index 3148 due to error: Explicit valence for atom # 3 B, 6, is greater than permitted
Skipping molecule at index 3149 due to error: Explicit valence for atom # 4 C, 6, is greater than permitted
Skipping molecule at index 3150 due to error: Explicit valence for atom # 6 C, 6, is greater than permitted
Skipping molecule at index 3151 due to error: Explicit valence for atom # 0 B, 6, is greater than permitted
Skipping molecule at index 3152 due to error: Explicit valence for atom # 0 B, 6, is greater than permitted
Skipping molecule at index 3153 due to error: Explicit valence for atom # 11 C, 6, is greater than permitted
Skipping molecule at index 3155 due to error: Can't kekulize mol.  Unkekulized atoms: 10 12 14 16 18
Skipping molecule at index 3156 due to error: Explicit valence for atom # 7 C, 6, is greater than permitted
Skipping molecule at index 3157 due to error: Explicit valence for atom # 2 C, 6, is greater than permitted
Skipping molecule at index 3158 due to error: Explicit valence for atom # 3 B, 4, is greater than permitted
Skipping molecule at index 3159 due to error: Can't kekulize mol.  Unkekulized atoms: 10 11 13 18 20 21 22 24 26 28 29 30 32 37 39
Skipping molecule at index 3160 due to error: Explicit valence for atom # 5 C, 6, is greater than permitted
Skipping molecule at index 3161 due to error: Explicit valence for atom # 8 C, 6, is greater than permitted
Skipping molecule at index 3162 due to error: Explicit valence for atom # 106 B, 4, is greater than permitted
Skipping molecule at index 3163 due to error: Can't kekulize mol.  Unkekulized atoms: 0 2 4 6 8 9 10 12 28 30 32
Skipping molecule at index 3164 due to error: Explicit valence for atom # 5 N, 4, is greater than permitted
Skipping molecule at index 3166 due to error: Explicit valence for atom # 42 B, 4, is greater than permitted
Skipping molecule at index 3167 due to error: Explicit valence for atom # 2 B, 4, is greater than permitted
Skipping molecule at index 3168 due to error: Explicit valence for atom # 23 B, 4, is greater than permitted
Skipping molecule at index 3169 due to error: Explicit valence for atom # 8 B, 4, is greater than permitted
Skipping molecule at index 3170 due to error: Explicit valence for atom # 8 B, 4, is greater than permitted
Skipping molecule at index 3171 due to error: Explicit valence for atom # 10 B, 4, is greater than permitted
Skipping molecule at index 3172 due to error: Explicit valence for atom # 5 N, 4, is greater than permitted
Skipping molecule at index 3174 due to error: Explicit valence for atom # 3 B, 4, is greater than permitted
Skipping molecule at index 3175 due to error: Explicit valence for atom # 3 B, 4, is greater than permitted
Skipping molecule at index 3176 due to error: Explicit valence for atom # 2 B, 4, is greater than permitted
Skipping molecule at index 3177 due to error: Explicit valence for atom # 5 B, 4, is greater than permitted
Skipping molecule at index 3178 due to error: Explicit valence for atom # 38 B, 4, is greater than permitted
Skipping molecule at index 3179 due to error: Explicit valence for atom # 9 C, 6, is greater than permitted
Skipping molecule at index 3180 due to error: Explicit valence for atom # 10 C, 6, is greater than permitted
Skipping molecule at index 3181 due to error: Explicit valence for atom # 6 C, 6, is greater than permitted
Skipping molecule at index 3182 due to error: Explicit valence for atom # 6 C, 6, is greater than permitted
Skipping molecule at index 3183 due to error: Explicit valence for atom # 20 B, 4, is greater than permitted
Skipping molecule at index 3184 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 3185 due to error: Explicit valence for atom # 2 N, 4, is greater than permitted
Skipping molecule at index 3186 due to error: Explicit valence for atom # 33 B, 4, is greater than permitted
Skipping molecule at index 3187 due to error: Explicit valence for atom # 7 C, 6, is greater than permitted
Skipping molecule at index 3188 due to error: Explicit valence for atom # 7 C, 6, is greater than permitted
Skipping molecule at index 3189 due to error: Explicit valence for atom # 32 B, 4, is greater than permitted
Skipping molecule at index 3190 due to error: Explicit valence for atom # 8 B, 4, is greater than permitted
Skipping molecule at index 3191 due to error: Explicit valence for atom # 50 B, 4, is greater than permitted
Skipping molecule at index 3192 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 3193 due to error: Explicit valence for atom # 37 B, 4, is greater than permitted
Skipping molecule at index 3194 due to error: Explicit valence for atom # 14 B, 4, is greater than permitted
Skipping molecule at index 3195 due to error: Explicit valence for atom # 48 B, 4, is greater than permitted
Skipping molecule at index 3196 due to error: Explicit valence for atom # 80 H, 2, is greater than permitted
Skipping molecule at index 3197 due to error: Explicit valence for atom # 80 H, 2, is greater than permitted
Skipping molecule at index 3198 due to error: Explicit valence for atom # 79 H, 2, is greater than permitted
Skipping molecule at index 3199 due to error: Explicit valence for atom # 5 N, 4, is greater than permitted
Skipping molecule at index 3200 due to error: Explicit valence for atom # 0 O, 3, is greater than permitted
Skipping molecule at index 3202 due to error: Explicit valence for atom # 11 N, 4, is greater than permitted
Skipping molecule at index 3204 due to error: Explicit valence for atom # 82 B, 4, is greater than permitted
Skipping molecule at index 3205 due to error: Explicit valence for atom # 83 B, 4, is greater than permitted
Skipping molecule at index 3206 due to error: Explicit valence for atom # 32 B, 4, is greater than permitted
Skipping molecule at index 3207 due to error: Explicit valence for atom # 102 B, 4, is greater than permitted
Skipping molecule at index 3208 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 3209 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 3210 due to error: Explicit valence for atom # 1 N, 6, is greater than permitted
Skipping molecule at index 3211 due to error: Explicit valence for atom # 92 B, 4, is greater than permitted
Skipping molecule at index 3212 due to error: Explicit valence for atom # 45 B, 4, is greater than permitted
Skipping molecule at index 3213 due to error: Explicit valence for atom # 82 B, 4, is greater than permitted
Skipping molecule at index 3214 due to error: Explicit valence for atom # 78 B, 4, is greater than permitted
Skipping molecule at index 3215 due to error: Explicit valence for atom # 42 B, 4, is greater than permitted
Skipping molecule at index 3216 due to error: Explicit valence for atom # 2 N, 5, is greater than permitted
Skipping molecule at index 3222 due to error: Explicit valence for atom # 83 B, 4, is greater than permitted
Skipping molecule at index 3224 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 3226 due to error: Explicit valence for atom # 53 N, 4, is greater than permitted
Skipping molecule at index 3227 due to error: Explicit valence for atom # 7 C, 6, is greater than permitted
Skipping molecule at index 3228 due to error: Explicit valence for atom # 9 C, 6, is greater than permitted
Skipping molecule at index 3229 due to error: Explicit valence for atom # 12 C, 6, is greater than permitted
Skipping molecule at index 3230 due to error: Explicit valence for atom # 6 C, 6, is greater than permitted
Skipping molecule at index 3231 due to error: Explicit valence for atom # 11 C, 6, is greater than permitted
Skipping molecule at index 3233 due to error: Can't kekulize mol.  Unkekulized atoms: 17 18 20 22 23
Skipping molecule at index 3234 due to error: Can't kekulize mol.  Unkekulized atoms: 5 7 8 10 11
Skipping molecule at index 3235 due to error: Can't kekulize mol.  Unkekulized atoms: 6 8 9 11 12
Skipping molecule at index 3236 due to error: Can't kekulize mol.  Unkekulized atoms: 8 10 11 13 14 31 33 34 36 37
Skipping molecule at index 3237 due to error: Explicit valence for atom # 4 C, 6, is greater than permitted
Skipping molecule at index 3239 due to error: Explicit valence for atom # 16 O, 3, is greater than permitted
Skipping molecule at index 3240 due to error: Explicit valence for atom # 28 N, 4, is greater than permitted
Skipping molecule at index 3242 due to error: Explicit valence for atom # 11 N, 4, is greater than permitted
Skipping molecule at index 3243 due to error: Explicit valence for atom # 1 Cl, 2, is greater than permitted
Skipping molecule at index 3244 due to error: Explicit valence for atom # 46 B, 4, is greater than permitted
Skipping molecule at index 3245 due to error: Explicit valence for atom # 23 B, 4, is greater than permitted
Skipping molecule at index 3246 due to error: Explicit valence for atom # 23 B, 4, is greater than permitted
Skipping molecule at index 3247 due to error: Explicit valence for atom # 26 B, 4, is greater than permitted
Skipping molecule at index 3248 due to error: Explicit valence for atom # 26 B, 4, is greater than permitted
Skipping molecule at index 3249 due to error: Explicit valence for atom # 35 B, 4, is greater than permitted
Skipping molecule at index 3250 due to error: Explicit valence for atom # 2 O, 3, is greater than permitted
Skipping molecule at index 3251 due to error: Explicit valence for atom # 99 B, 4, is greater than permitted
Skipping molecule at index 3252 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 3258 due to error: Explicit valence for atom # 4 F, 2, is greater than permitted
Skipping molecule at index 3259 due to error: Explicit valence for atom # 66 B, 4, is greater than permitted
Skipping molecule at index 3260 due to error: Explicit valence for atom # 7 O, 3, is greater than permitted
Skipping molecule at index 3261 due to error: Explicit valence for atom # 5 O, 3, is greater than permitted
Skipping molecule at index 3262 due to error: Explicit valence for atom # 5 N, 4, is greater than permitted
Skipping molecule at index 3263 due to error: Explicit valence for atom # 142 B, 4, is greater than permitted
Skipping molecule at index 3264 due to error: Explicit valence for atom # 142 B, 4, is greater than permitted
Skipping molecule at index 3265 due to error: Explicit valence for atom # 143 B, 4, is greater than permitted
Skipping molecule at index 3266 due to error: Explicit valence for atom # 144 B, 4, is greater than permitted
Skipping molecule at index 3269 due to error: Explicit valence for atom # 16 O, 3, is greater than permitted
Skipping molecule at index 3270 due to error: Explicit valence for atom # 13 B, 4, is greater than permitted
Skipping molecule at index 3271 due to error: Explicit valence for atom # 26 B, 5, is greater than permitted
Skipping molecule at index 3272 due to error: Explicit valence for atom # 4 O, 3, is greater than permitted
Skipping molecule at index 3274 due to error: Explicit valence for atom # 3 O, 3, is greater than permitted
Skipping molecule at index 3276 due to error: Explicit valence for atom # 4 O, 3, is greater than permitted
Skipping molecule at index 3278 due to error: Explicit valence for atom # 4 O, 3, is greater than permitted
Skipping molecule at index 3280 due to error: Explicit valence for atom # 3 O, 3, is greater than permitted
Skipping molecule at index 3282 due to error: Explicit valence for atom # 76 B, 4, is greater than permitted
Skipping molecule at index 3283 due to error: Explicit valence for atom # 181 B, 4, is greater than permitted
Skipping molecule at index 3284 due to error: Explicit valence for atom # 1 B, 4, is greater than permitted
Skipping molecule at index 3285 due to error: Explicit valence for atom # 1 B, 4, is greater than permitted
Skipping molecule at index 3286 due to error: Explicit valence for atom # 1 B, 4, is greater than permitted
Skipping molecule at index 3287 due to error: Explicit valence for atom # 44 B, 4, is greater than permitted

[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Can't kekulize mol.  Unkekulized atoms: 17 18 20 22 23
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Can't kekulize mol.  Unkekulized atoms: 5 7 8 10 11
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Can't kekulize mol.  Unkekulized atoms: 6 8 9 11 12
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Can't kekulize mol.  Unkekulized atoms: 8 10 11 13 14 31 33 34 36 37
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:04] Explicit valence for atom # 4 C, 6, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 16 O, 3, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 28 N, 4, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 11 N, 4, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 1 Cl, 2, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 46 B, 4, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 23 B, 4, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 23 B, 4, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 26 B, 4, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 26 B, 4, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 35 B, 4, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:04] Explicit valence for atom # 2 O, 3, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 99 B, 4, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:04] Explicit valence for atom # 0 B, 4, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 4 F, 2, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 66 B, 4, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 7 O, 3, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 5 O, 3, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 5 N, 4, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 142 B, 4, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 142 B, 4, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 143 B, 4, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 144 B, 4, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 16 O, 3, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 13 B, 4, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:04] Explicit valence for atom # 26 B, 5, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 4 O, 3, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 3 O, 3, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 4 O, 3, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 4 O, 3, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 3 O, 3, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 76 B, 4, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 181 B, 4, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 1 B, 4, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 1 B, 4, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:04] Explicit valence for atom # 1 B, 4, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 44 B, 4, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 47 N, 4, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:04] Explicit valence for atom # 8 C, 6, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:04] Explicit valence for atom # 9 C, 6, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:04] Explicit valence for atom # 6 C, 6, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 1 N, 4, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 3 N, 4, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 2 N, 4, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 104 N, 4, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 29 N, 4, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 3 N, 4, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:04] Explicit valence for atom # 4 C, 6, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:04] Explicit valence for atom # 4 B, 6, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 0 B, 4, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 0 B, 4, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:04] Explicit valence for atom # 7 C, 6, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 6 N, 4, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 2 H, 2, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Can't kekulize mol.  Unkekulized atoms: 3 5 7 8 10
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 75 N, 4, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Can't kekulize mol.  Unkekulized atoms: 11 12 13 14 15 18 37 38 39
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 82 B, 4, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 8 B, 4, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:04] Explicit valence for atom # 7 C, 6, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 0 B, 4, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 0 B, 4, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 22 O, 3, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 63 B, 4, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Can't kekulize mol.  Unkekulized atoms: 31 33 34 36 38 56 57 59 61 62
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Can't kekulize mol.  Unkekulized atoms: 40 42 44 46 48 49 68 70 72 92
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Can't kekulize mol.  Unkekulized atoms: 40 42 59 61 63 64 65 67 69 86
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Can't kekulize mol.  Unkekulized atoms: 40 42 59 61 63 64 65 67 69 86
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 0 B, 4, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 0 B, 4, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:04] Explicit valence for atom # 2 N, 4, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:04] Explicit valence for atom # 6 N, 4, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:04] Explicit valence for atom # 1 N, 4, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:04] Explicit valence for atom # 1 N, 4, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 43 B, 4, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 72 B, 4, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 72 B, 4, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 72 B, 4, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 72 B, 4, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 72 B, 4, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 43 B, 4, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 72 B, 4, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 43 B, 4, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.

Skipping molecule at index 3289 due to error: Explicit valence for atom # 47 N, 4, is greater than permitted
Skipping molecule at index 3290 due to error: Explicit valence for atom # 8 C, 6, is greater than permitted
Skipping molecule at index 3291 due to error: Explicit valence for atom # 9 C, 6, is greater than permitted
Skipping molecule at index 3292 due to error: Explicit valence for atom # 6 C, 6, is greater than permitted
Skipping molecule at index 3293 due to error: Explicit valence for atom # 1 N, 4, is greater than permitted
Skipping molecule at index 3294 due to error: Explicit valence for atom # 3 N, 4, is greater than permitted
Skipping molecule at index 3295 due to error: Explicit valence for atom # 2 N, 4, is greater than permitted
Skipping molecule at index 3296 due to error: Explicit valence for atom # 104 N, 4, is greater than permitted
Skipping molecule at index 3297 due to error: Explicit valence for atom # 29 N, 4, is greater than permitted
Skipping molecule at index 3298 due to error: Explicit valence for atom # 3 N, 4, is greater than permitted
Skipping molecule at index 3300 due to error: Explicit valence for atom # 4 C, 6, is greater than permitted
Skipping molecule at index 3301 due to error: Explicit valence for atom # 4 B, 6, is greater than permitted
Skipping molecule at index 3302 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 3303 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 3305 due to error: Explicit valence for atom # 7 C, 6, is greater than permitted
Skipping molecule at index 3306 due to error: Explicit valence for atom # 6 N, 4, is greater than permitted
Skipping molecule at index 3307 due to error: Explicit valence for atom # 2 H, 2, is greater than permitted
Skipping molecule at index 3308 due to error: Can't kekulize mol.  Unkekulized atoms: 3 5 7 8 10
Skipping molecule at index 3310 due to error: Explicit valence for atom # 75 N, 4, is greater than permitted
Skipping molecule at index 3311 due to error: Can't kekulize mol.  Unkekulized atoms: 11 12 13 14 15 18 37 38 39
Skipping molecule at index 3312 due to error: Explicit valence for atom # 82 B, 4, is greater than permitted
Skipping molecule at index 3315 due to error: Explicit valence for atom # 8 B, 4, is greater than permitted
Skipping molecule at index 3317 due to error: Explicit valence for atom # 7 C, 6, is greater than permitted
Skipping molecule at index 3318 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 3319 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 3320 due to error: Explicit valence for atom # 22 O, 3, is greater than permitted
Skipping molecule at index 3321 due to error: Explicit valence for atom # 63 B, 4, is greater than permitted
Skipping molecule at index 3322 due to error: Can't kekulize mol.  Unkekulized atoms: 31 33 34 36 38 56 57 59 61 62
Skipping molecule at index 3323 due to error: Can't kekulize mol.  Unkekulized atoms: 40 42 44 46 48 49 68 70 72 92
Skipping molecule at index 3324 due to error: Can't kekulize mol.  Unkekulized atoms: 40 42 59 61 63 64 65 67 69 86
Skipping molecule at index 3325 due to error: Can't kekulize mol.  Unkekulized atoms: 40 42 59 61 63 64 65 67 69 86
Skipping molecule at index 3326 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 3327 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 3329 due to error: Explicit valence for atom # 2 N, 4, is greater than permitted
Skipping molecule at index 3330 due to error: Explicit valence for atom # 6 N, 4, is greater than permitted
Skipping molecule at index 3332 due to error: Explicit valence for atom # 1 N, 4, is greater than permitted
Skipping molecule at index 3333 due to error: Explicit valence for atom # 1 N, 4, is greater than permitted
Skipping molecule at index 3334 due to error: Explicit valence for atom # 43 B, 4, is greater than permitted
Skipping molecule at index 3335 due to error: Explicit valence for atom # 72 B, 4, is greater than permitted
Skipping molecule at index 3336 due to error: Explicit valence for atom # 72 B, 4, is greater than permitted
Skipping molecule at index 3337 due to error: Explicit valence for atom # 72 B, 4, is greater than permitted
Skipping molecule at index 3338 due to error: Explicit valence for atom # 72 B, 4, is greater than permitted
Skipping molecule at index 3339 due to error: Explicit valence for atom # 72 B, 4, is greater than permitted
Skipping molecule at index 3340 due to error: Explicit valence for atom # 43 B, 4, is greater than permitted
Skipping molecule at index 3341 due to error: Explicit valence for atom # 72 B, 4, is greater than permitted
Skipping molecule at index 3342 due to error: Explicit valence for atom # 43 B, 4, is greater than permitted
Skipping molecule at index 3343 due to error: Explicit valence for atom # 2 B, 4, is greater than permitted
Skipping molecule at index 3344 due to error: Explicit valence for atom # 2 B, 4, is greater than permitted
Skipping molecule at index 3345 due to error: Explicit valence for atom # 2 B, 4, is greater than permitted
Skipping molecule at index 3346 due to error: Explicit valence for atom # 43 B, 4, is greater than permitted
Skipping molecule at index 3347 due to error: Explicit valence for atom # 0 O, 3, is greater than permitted
Skipping molecule at index 3348 due to error: Explicit valence for atom # 0 O, 3, is greater than permitted
Skipping molecule at index 3349 due to error: Explicit valence for atom # 5 C, 6, is greater than permitted
Skipping molecule at index 3350 due to error: Explicit valence for atom # 4 C, 6, is greater than permitted
Skipping molecule at index 3351 due to error: Explicit valence for atom # 5 C, 6, is greater than permitted
Skipping molecule at index 3352 due to error: Explicit valence for atom # 12 C, 6, is greater than permitted
Skipping molecule at index 3354 due to error: Explicit valence for atom # 17 N, 4, is greater than permitted
Skipping molecule at index 3358 due to error: Explicit valence for atom # 39 B, 4, is greater than permitted
Skipping molecule at index 3359 due to error: Explicit valence for atom # 18 B, 4, is greater than permitted
Skipping molecule at index 3360 due to error: Explicit valence for atom # 124 B, 4, is greater than permitted
Skipping molecule at index 3361 due to error: Explicit valence for atom # 253 B, 4, is greater than permitted
Skipping molecule at index 3362 due to error: Explicit valence for atom # 258 B, 4, is greater than permitted
Skipping molecule at index 3363 due to error: Explicit valence for atom # 1 N, 4, is greater than permitted
Skipping molecule at index 3365 due to error: Explicit valence for atom # 2 B, 4, is greater than permitted
Skipping molecule at index 3366 due to error: Explicit valence for atom # 57 B, 4, is greater than permitted
Skipping molecule at index 3367 due to error: Explicit valence for atom # 90 C, 6, is greater than permitted
Skipping molecule at index 3368 due to error: Explicit valence for atom # 12 N, 4, is greater than permitted
Skipping molecule at index 3369 due to error: Explicit valence for atom # 1 C, 6, is greater than permitted
Skipping molecule at index 3370 due to error: Explicit valence for atom # 2 B, 4, is greater than permitted
Skipping molecule at index 3371 due to error: Explicit valence for atom # 13 O, 3, is greater than permitted
Skipping molecule at index 3372 due to error: Explicit valence for atom # 84 B, 4, is greater than permitted
Skipping molecule at index 3373 due to error: Explicit valence for atom # 127 B, 4, is greater than permitted
Skipping molecule at index 3374 due to error: Explicit valence for atom # 6 C, 6, is greater than permitted
Skipping molecule at index 3375 due to error: Explicit valence for atom # 13 O, 3, is greater than permitted
Skipping molecule at index 3376 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 3377 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 3378 due to error: Explicit valence for atom # 87 B, 4, is greater than permitted
Skipping molecule at index 3379 due to error: Explicit valence for atom # 16 N, 4, is greater than permitted
Skipping molecule at index 3380 due to error: Explicit valence for atom # 64 B, 4, is greater than permitted
Skipping molecule at index 3381 due to error: Explicit valence for atom # 67 B, 4, is greater than permitted
Skipping molecule at index 3382 due to error: Explicit valence for atom # 70 B, 4, is greater than permitted
Skipping molecule at index 3383 due to error: Explicit valence for atom # 98 B, 4, is greater than permitted
Skipping molecule at index 3387 due to error: Can't kekulize mol.  Unkekulized atoms: 24 25 27 28 30 117 118 120 121 123
Skipping molecule at index 3389 due to error: Explicit valence for atom # 0 B, 6, is greater than permitted
Skipping molecule at index 3393 due to error: Explicit valence for atom # 3 C, 6, is greater than permitted
Skipping molecule at index 3394 due to error: Explicit valence for atom # 3 C, 5, is greater than permitted
Skipping molecule at index 3395 due to error: Explicit valence for atom # 38 C, 6, is greater than permitted
Skipping molecule at index 3400 due to error: Explicit valence for atom # 3 B, 4, is greater than permitted
Skipping molecule at index 3401 due to error: Explicit valence for atom # 48 B, 4, is greater than permitted
Skipping molecule at index 3403 due to error: Explicit valence for atom # 6 C, 6, is greater than permitted
Skipping molecule at index 3404 due to error: Explicit valence for atom # 6 C, 6, is greater than permitted
Skipping molecule at index 3405 due to error: Explicit valence for atom # 5 C, 6, is greater than permitted
Skipping molecule at index 3406 due to error: Explicit valence for atom # 7 C, 6, is greater than permitted
Skipping molecule at index 3407 due to error: Explicit valence for atom # 7 C, 6, is greater than permitted
Skipping molecule at index 3408 due to error: Explicit valence for atom # 7 C, 6, is greater than permitted
Skipping molecule at index 3409 due to error: Explicit valence for atom # 7 C, 6, is greater than permitted
Skipping molecule at index 3410 due to error: Explicit valence for atom # 6 C, 6, is greater than permitted
Skipping molecule at index 3411 due to error: Explicit valence for atom # 8 C, 6, is greater than permitted
Skipping molecule at index 3412 due to error: Explicit valence for atom # 6 C, 6, is greater than permitted
Skipping molecule at index 3413 due to error: Can't kekulize mol.  Unkekulized atoms: 24 25 27 29 31 56 57 59 61 63
Skipping molecule at index 3414 due to error: Can't kekulize mol.  Unkekulized atoms: 23 24 25 32 33 34 41 42 43
Skipping molecule at index 3415 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 3418 due to error: Explicit valence for atom # 20 B, 4, is greater than permitted
Skipping molecule at index 3422 due to error: Explicit valence for atom # 50 B, 4, is greater than permitted
Skipping molecule at index 3423 due to error: Explicit valence for atom # 12 B, 4, is greater than permitted
Skipping molecule at index 3424 due to error: Explicit valence for atom # 15 B, 4, is greater than permitted
Skipping molecule at index 3425 due to error: Explicit valence for atom # 40 B, 4, is greater than permitted
Skipping molecule at index 3426 due to error: Explicit valence for atom # 0 C, 6, is greater than permitted
Skipping molecule at index 3429 due to error: Explicit valence for atom # 30 B, 4, is greater than permitted
Skipping molecule at index 3430 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 3431 due to error: Explicit valence for atom # 138 B, 4, is greater than permitted
Skipping molecule at index 3432 due to error: Explicit valence for atom # 95 B, 4, is greater than permitted
Skipping molecule at index 3433 due to error: Can't kekulize mol.  Unkekulized atoms: 54 56 58 60 62 64 66 68 70
Skipping molecule at index 3434 due to error: Can't kekulize mol.  Unkekulized atoms: 22 24 26 28 30 32 63 65 67
Skipping molecule at index 3435 due to error: Explicit valence for atom # 30 B, 4, is greater than permitted
Skipping molecule at index 3436 due to error: Can't kekulize mol.  Unkekulized atoms: 100 102 104 106 108 110 112 114 116
Skipping molecule at index 3437 due to error: Explicit valence for atom # 25 B, 4, is greater than permitted
Skipping molecule at index 3438 due to error: Explicit valence for atom # 23 B, 4, is greater than permitted
Skipping molecule at index 3439 due to error: Explicit valence for atom # 43 B, 4, is greater than permitted
Skipping molecule at index 3440 due to error: Explicit valence for atom # 42 B, 4, is greater than permitted
Skipping molecule at index 3441 due to error: Explicit valence for atom # 40 B, 4, is greater than permitted
Skipping molecule at index 3442 due to error: Explicit valence for atom # 68 B, 4, is greater than permitted
Skipping molecule at index 3443 due to error: Explicit valence for atom # 11 B, 6, is greater than permitted
Skipping molecule at index 3444 due to error: Explicit valence for atom # 10 C, 6, is greater than permitted
Skipping molecule at index 3445 due to error: Explicit valence for atom # 18 C, 6, is greater than permitted

[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 50 B, 4, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 12 B, 4, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 15 B, 4, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 40 B, 4, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:04] Explicit valence for atom # 0 C, 6, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 30 B, 4, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 0 B, 4, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 138 B, 4, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 95 B, 4, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Can't kekulize mol.  Unkekulized atoms: 54 56 58 60 62 64 66 68 70
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Can't kekulize mol.  Unkekulized atoms: 22 24 26 28 30 32 63 65 67
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 30 B, 4, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Can't kekulize mol.  Unkekulized atoms: 100 102 104 106 108 110 112 114 116
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 25 B, 4, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 23 B, 4, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 43 B, 4, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 42 B, 4, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 40 B, 4, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 68 B, 4, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:04] Explicit valence for atom # 11 B, 6, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:04] Explicit valence for atom # 10 C, 6, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:04] Explicit valence for atom # 18 C, 6, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:04] Explicit valence for atom # 7 C, 6, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:04] Explicit valence for atom # 7 C, 6, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:04] Explicit valence for atom # 22 C, 6, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:04] Explicit valence for atom # 15 C, 6, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 27 B, 4, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 7 N, 5, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:04] Explicit valence for atom # 6 C, 6, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 8 B, 4, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 17 B, 4, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Can't kekulize mol.  Unkekulized atoms: 17 18 19 22 23 24 38 39 40
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 130 O, 3, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 130 O, 3, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 130 O, 3, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Can't kekulize mol.  Unkekulized atoms: 18 19 20 21 25 27 29 36
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:04] Explicit valence for atom # 1 H, 2, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:04] Explicit valence for atom # 44 B, 6, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:04] Explicit valence for atom # 1 H, 2, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:04] Explicit valence for atom # 63 B, 6, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:04] Explicit valence for atom # 65 B, 6, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:04] Explicit valence for atom # 6 C, 5, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:04] Explicit valence for atom # 0 Pb, 11, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:04] Explicit valence for atom # 3 B, 6, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 1 B, 4, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 9 N, 4, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 10 N, 4, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 10 N, 4, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 9 N, 4, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:04] Explicit valence for atom # 26 B, 6, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 1 Si, 6, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 1 Si, 6, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 1 Si, 6, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 19 B, 4, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 84 B, 4, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 61 B, 4, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 93 B, 4, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 7 O, 3, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 9 O, 3, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 6 O, 3, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 7 H, 2, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Can't kekulize mol.  Unkekulized atoms: 9 35
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 0 B, 4, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 0 B, 4, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 0 B, 4, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 1 N, 4, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 2 F, 2, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 4 N, 4, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 106 B, 4, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 48 B, 4, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 60 B, 4, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 77 B, 4, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:04] Explicit valence for atom # 24 C, 6, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 37 B, 4, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:04] Explicit valence for atom # 24 C, 6, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 25 B, 4, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 5 O, 3, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 2 O, 3, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:04] Explicit valence for atom # 2 B, 5, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 90 B, 4, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 85 B, 4, is greater than permitted

Skipping molecule at index 3446 due to error: Explicit valence for atom # 7 C, 6, is greater than permitted
Skipping molecule at index 3447 due to error: Explicit valence for atom # 7 C, 6, is greater than permitted
Skipping molecule at index 3448 due to error: Explicit valence for atom # 22 C, 6, is greater than permitted
Skipping molecule at index 3449 due to error: Explicit valence for atom # 15 C, 6, is greater than permitted
Skipping molecule at index 3450 due to error: Explicit valence for atom # 27 B, 4, is greater than permitted
Skipping molecule at index 3452 due to error: Explicit valence for atom # 7 N, 5, is greater than permitted
Skipping molecule at index 3454 due to error: Explicit valence for atom # 6 C, 6, is greater than permitted
Skipping molecule at index 3455 due to error: Explicit valence for atom # 8 B, 4, is greater than permitted
Skipping molecule at index 3456 due to error: Explicit valence for atom # 17 B, 4, is greater than permitted
Skipping molecule at index 3457 due to error: Can't kekulize mol.  Unkekulized atoms: 17 18 19 22 23 24 38 39 40
Skipping molecule at index 3459 due to error: Explicit valence for atom # 130 O, 3, is greater than permitted
Skipping molecule at index 3460 due to error: Explicit valence for atom # 130 O, 3, is greater than permitted
Skipping molecule at index 3461 due to error: Explicit valence for atom # 130 O, 3, is greater than permitted
Skipping molecule at index 3462 due to error: Can't kekulize mol.  Unkekulized atoms: 18 19 20 21 25 27 29 36
Skipping molecule at index 3463 due to error: Explicit valence for atom # 1 H, 2, is greater than permitted
Skipping molecule at index 3464 due to error: Explicit valence for atom # 44 B, 6, is greater than permitted
Skipping molecule at index 3465 due to error: Explicit valence for atom # 1 H, 2, is greater than permitted
Skipping molecule at index 3466 due to error: Explicit valence for atom # 63 B, 6, is greater than permitted
Skipping molecule at index 3467 due to error: Explicit valence for atom # 65 B, 6, is greater than permitted
Skipping molecule at index 3471 due to error: Explicit valence for atom # 6 C, 5, is greater than permitted
Skipping molecule at index 3472 due to error: Explicit valence for atom # 0 Pb, 11, is greater than permitted
Skipping molecule at index 3474 due to error: Explicit valence for atom # 3 B, 6, is greater than permitted
Skipping molecule at index 3475 due to error: Explicit valence for atom # 1 B, 4, is greater than permitted
Skipping molecule at index 3476 due to error: Explicit valence for atom # 9 N, 4, is greater than permitted
Skipping molecule at index 3477 due to error: Explicit valence for atom # 10 N, 4, is greater than permitted
Skipping molecule at index 3478 due to error: Explicit valence for atom # 10 N, 4, is greater than permitted
Skipping molecule at index 3479 due to error: Explicit valence for atom # 9 N, 4, is greater than permitted
Skipping molecule at index 3480 due to error: Explicit valence for atom # 26 B, 6, is greater than permitted
Skipping molecule at index 3481 due to error: Explicit valence for atom # 1 Si, 6, is greater than permitted
Skipping molecule at index 3482 due to error: Explicit valence for atom # 1 Si, 6, is greater than permitted
Skipping molecule at index 3483 due to error: Explicit valence for atom # 1 Si, 6, is greater than permitted
Skipping molecule at index 3484 due to error: Explicit valence for atom # 19 B, 4, is greater than permitted
Skipping molecule at index 3486 due to error: Explicit valence for atom # 84 B, 4, is greater than permitted
Skipping molecule at index 3487 due to error: Explicit valence for atom # 61 B, 4, is greater than permitted
Skipping molecule at index 3488 due to error: Explicit valence for atom # 93 B, 4, is greater than permitted
Skipping molecule at index 3489 due to error: Explicit valence for atom # 7 O, 3, is greater than permitted
Skipping molecule at index 3490 due to error: Explicit valence for atom # 9 O, 3, is greater than permitted
Skipping molecule at index 3491 due to error: Explicit valence for atom # 6 O, 3, is greater than permitted
Skipping molecule at index 3496 due to error: Explicit valence for atom # 7 H, 2, is greater than permitted
Skipping molecule at index 3498 due to error: Can't kekulize mol.  Unkekulized atoms: 9 35
Skipping molecule at index 3499 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 3500 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 3501 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 3502 due to error: Explicit valence for atom # 1 N, 4, is greater than permitted
Skipping molecule at index 3505 due to error: Explicit valence for atom # 2 F, 2, is greater than permitted
Skipping molecule at index 3508 due to error: Explicit valence for atom # 4 N, 4, is greater than permitted
Skipping molecule at index 3510 due to error: Explicit valence for atom # 106 B, 4, is greater than permitted
Skipping molecule at index 3511 due to error: Explicit valence for atom # 48 B, 4, is greater than permitted
Skipping molecule at index 3512 due to error: Explicit valence for atom # 60 B, 4, is greater than permitted
Skipping molecule at index 3513 due to error: Explicit valence for atom # 77 B, 4, is greater than permitted
Skipping molecule at index 3514 due to error: Explicit valence for atom # 24 C, 6, is greater than permitted
Skipping molecule at index 3515 due to error: Explicit valence for atom # 37 B, 4, is greater than permitted
Skipping molecule at index 3516 due to error: Explicit valence for atom # 24 C, 6, is greater than permitted
Skipping molecule at index 3517 due to error: Explicit valence for atom # 25 B, 4, is greater than permitted
Skipping molecule at index 3518 due to error: Explicit valence for atom # 5 O, 3, is greater than permitted
Skipping molecule at index 3519 due to error: Explicit valence for atom # 2 O, 3, is greater than permitted
Skipping molecule at index 3520 due to error: Explicit valence for atom # 2 B, 5, is greater than permitted
Skipping molecule at index 3521 due to error: Explicit valence for atom # 90 B, 4, is greater than permitted
Skipping molecule at index 3522 due to error: Explicit valence for atom # 85 B, 4, is greater than permitted
Skipping molecule at index 3523 due to error: Explicit valence for atom # 93 B, 4, is greater than permitted
Skipping molecule at index 3524 due to error: Explicit valence for atom # 2 O, 3, is greater than permitted
Skipping molecule at index 3525 due to error: Explicit valence for atom # 2 B, 6, is greater than permitted
Skipping molecule at index 3526 due to error: Explicit valence for atom # 18 C, 5, is greater than permitted
Skipping molecule at index 3527 due to error: Explicit valence for atom # 1 B, 4, is greater than permitted
Skipping molecule at index 3528 due to error: Explicit valence for atom # 8 B, 4, is greater than permitted
Skipping molecule at index 3529 due to error: Explicit valence for atom # 35 B, 4, is greater than permitted
Skipping molecule at index 3530 due to error: Can't kekulize mol.  Unkekulized atoms: 11 12 13 20 21 22 29 30 31
Skipping molecule at index 3531 due to error: Explicit valence for atom # 72 B, 4, is greater than permitted
Skipping molecule at index 3532 due to error: Can't kekulize mol.  Unkekulized atoms: 21 22 23 30 31 32 39 40 41
Skipping molecule at index 3533 due to error: Explicit valence for atom # 17 B, 4, is greater than permitted
Skipping molecule at index 3534 due to error: Explicit valence for atom # 17 B, 4, is greater than permitted
Skipping molecule at index 3535 due to error: Can't kekulize mol.  Unkekulized atoms: 23 24 25 32 33 34 41 42 43
Skipping molecule at index 3536 due to error: Explicit valence for atom # 2 O, 3, is greater than permitted
Skipping molecule at index 3537 due to error: Explicit valence for atom # 2 O, 3, is greater than permitted
Skipping molecule at index 3539 due to error: Explicit valence for atom # 137 B, 4, is greater than permitted
Skipping molecule at index 3541 due to error: Explicit valence for atom # 6 C, 6, is greater than permitted
Skipping molecule at index 3542 due to error: Explicit valence for atom # 5 B, 4, is greater than permitted
Skipping molecule at index 3543 due to error: Explicit valence for atom # 1 B, 4, is greater than permitted
Skipping molecule at index 3544 due to error: Explicit valence for atom # 15 B, 4, is greater than permitted
Skipping molecule at index 3545 due to error: Explicit valence for atom # 3 B, 4, is greater than permitted
Skipping molecule at index 3552 due to error: Explicit valence for atom # 11 B, 4, is greater than permitted
Skipping molecule at index 3557 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 3561 due to error: Explicit valence for atom # 1 C, 6, is greater than permitted
Skipping molecule at index 3562 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 3563 due to error: Explicit valence for atom # 4 N, 4, is greater than permitted
Skipping molecule at index 3564 due to error: Explicit valence for atom # 3 B, 5, is greater than permitted
Skipping molecule at index 3565 due to error: Explicit valence for atom # 4 O, 3, is greater than permitted
Skipping molecule at index 3566 due to error: Explicit valence for atom # 7 O, 3, is greater than permitted
Skipping molecule at index 3567 due to error: Explicit valence for atom # 32 B, 4, is greater than permitted
Skipping molecule at index 3568 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 3569 due to error: Explicit valence for atom # 2 O, 3, is greater than permitted
Skipping molecule at index 3570 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 3571 due to error: Explicit valence for atom # 19 B, 4, is greater than permitted
Skipping molecule at index 3572 due to error: Explicit valence for atom # 17 B, 5, is greater than permitted
Skipping molecule at index 3573 due to error: Explicit valence for atom # 103 B, 5, is greater than permitted
Skipping molecule at index 3574 due to error: Explicit valence for atom # 0 B, 5, is greater than permitted
Skipping molecule at index 3575 due to error: Explicit valence for atom # 6 C, 6, is greater than permitted
Skipping molecule at index 3577 due to error: Explicit valence for atom # 2 B, 4, is greater than permitted
Skipping molecule at index 3581 due to error: Explicit valence for atom # 4 O, 3, is greater than permitted
Skipping molecule at index 3584 due to error: Explicit valence for atom # 67 B, 4, is greater than permitted
Skipping molecule at index 3585 due to error: Explicit valence for atom # 0 Al, 4, is greater than permitted
Skipping molecule at index 3586 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 3587 due to error: Explicit valence for atom # 111 B, 4, is greater than permitted
Skipping molecule at index 3588 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 3589 due to error: Explicit valence for atom # 1 B, 4, is greater than permitted
Skipping molecule at index 3590 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 3591 due to error: Explicit valence for atom # 18 N, 4, is greater than permitted
Skipping molecule at index 3592 due to error: Explicit valence for atom # 3 N, 4, is greater than permitted
Skipping molecule at index 3594 due to error: Explicit valence for atom # 38 B, 4, is greater than permitted
Skipping molecule at index 3595 due to error: Explicit valence for atom # 88 B, 4, is greater than permitted
Skipping molecule at index 3598 due to error: Explicit valence for atom # 4 B, 4, is greater than permitted
Skipping molecule at index 3599 due to error: Explicit valence for atom # 4 O, 3, is greater than permitted

[10:29:04] Explicit valence for atom # 19 B, 4, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:04] Explicit valence for atom # 17 B, 5, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 103 B, 5, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 0 B, 5, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:04] Explicit valence for atom # 6 C, 6, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 2 B, 4, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 4 O, 3, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 67 B, 4, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 0 Al, 4, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 0 B, 4, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 111 B, 4, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 0 B, 4, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 1 B, 4, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 0 B, 4, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 18 N, 4, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 3 N, 4, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 38 B, 4, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 88 B, 4, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 4 B, 4, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 4 O, 3, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 2 O, 3, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:04] Explicit valence for atom # 7 O, 3, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 0 O, 3, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 52 B, 4, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 16 B, 4, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 22 B, 4, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:04] Explicit valence for atom # 93 C, 6, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:04] Explicit valence for atom # 101 C, 6, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 1 B, 4, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 0 Pb, 8, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 44 B, 4, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 25 B, 4, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 25 B, 4, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 70 B, 4, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 70 B, 4, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Can't kekulize mol.  Unkekulized atoms: 5 9 13 16 19
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 0 O, 3, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 10 B, 4, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 2 B, 4, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 20 B, 4, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 2 B, 4, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 15 B, 4, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 8 B, 4, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 1 F, 2, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 96 B, 4, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:04] Explicit valence for atom # 6 B, 6, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:04] Explicit valence for atom # 12 C, 6, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 54 B, 4, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 6 B, 4, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 1 O, 3, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 0 B, 4, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 1 B, 4, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 3 O, 3, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 19 B, 4, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 93 B, 4, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 4 B, 4, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 2 O, 3, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 85 B, 4, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 181 B, 4, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 0 B, 4, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 45 B, 4, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 62 B, 4, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 1 O, 3, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 1 O, 3, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 1 O, 3, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:04] Explicit valence for atom # 3 B, 6, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 2 B, 4, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 14 O, 2, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:04] Explicit valence for atom # 0 C, 5, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:04] Explicit valence for atom # 43 B, 5, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:04] Explicit valence for atom # 0 C, 5, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 80 B, 4, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 80 B, 4, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:04] Explicit valence for atom # 7 C, 6, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:04] Explicit valence for atom # 5 C, 5, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 4 N, 4, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 3 N, 4, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 12 N, 4, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 26 N, 4, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 22 N, 4, is greater than permitted

Skipping molecule at index 3605 due to error: Explicit valence for atom # 2 O, 3, is greater than permitted
Skipping molecule at index 3607 due to error: Explicit valence for atom # 7 O, 3, is greater than permitted
Skipping molecule at index 3608 due to error: Explicit valence for atom # 0 O, 3, is greater than permitted
Skipping molecule at index 3609 due to error: Explicit valence for atom # 52 B, 4, is greater than permitted
Skipping molecule at index 3610 due to error: Explicit valence for atom # 16 B, 4, is greater than permitted
Skipping molecule at index 3611 due to error: Explicit valence for atom # 22 B, 4, is greater than permitted
Skipping molecule at index 3612 due to error: Explicit valence for atom # 93 C, 6, is greater than permitted
Skipping molecule at index 3613 due to error: Explicit valence for atom # 101 C, 6, is greater than permitted
Skipping molecule at index 3615 due to error: Explicit valence for atom # 1 B, 4, is greater than permitted
Skipping molecule at index 3616 due to error: Explicit valence for atom # 0 Pb, 8, is greater than permitted
Skipping molecule at index 3617 due to error: Explicit valence for atom # 44 B, 4, is greater than permitted
Skipping molecule at index 3619 due to error: Explicit valence for atom # 25 B, 4, is greater than permitted
Skipping molecule at index 3620 due to error: Explicit valence for atom # 25 B, 4, is greater than permitted
Skipping molecule at index 3621 due to error: Explicit valence for atom # 70 B, 4, is greater than permitted
Skipping molecule at index 3622 due to error: Explicit valence for atom # 70 B, 4, is greater than permitted
Skipping molecule at index 3623 due to error: Can't kekulize mol.  Unkekulized atoms: 5 9 13 16 19
Skipping molecule at index 3624 due to error: Explicit valence for atom # 0 O, 3, is greater than permitted
Skipping molecule at index 3625 due to error: Explicit valence for atom # 10 B, 4, is greater than permitted
Skipping molecule at index 3626 due to error: Explicit valence for atom # 2 B, 4, is greater than permitted
Skipping molecule at index 3627 due to error: Explicit valence for atom # 20 B, 4, is greater than permitted
Skipping molecule at index 3628 due to error: Explicit valence for atom # 2 B, 4, is greater than permitted
Skipping molecule at index 3630 due to error: Explicit valence for atom # 15 B, 4, is greater than permitted
Skipping molecule at index 3631 due to error: Explicit valence for atom # 8 B, 4, is greater than permitted
Skipping molecule at index 3634 due to error: Explicit valence for atom # 1 F, 2, is greater than permitted
Skipping molecule at index 3635 due to error: Explicit valence for atom # 96 B, 4, is greater than permitted
Skipping molecule at index 3636 due to error: Explicit valence for atom # 6 B, 6, is greater than permitted
Skipping molecule at index 3637 due to error: Explicit valence for atom # 12 C, 6, is greater than permitted
Skipping molecule at index 3638 due to error: Explicit valence for atom # 54 B, 4, is greater than permitted
Skipping molecule at index 3639 due to error: Explicit valence for atom # 6 B, 4, is greater than permitted
Skipping molecule at index 3640 due to error: Explicit valence for atom # 1 O, 3, is greater than permitted
Skipping molecule at index 3641 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 3643 due to error: Explicit valence for atom # 1 B, 4, is greater than permitted
Skipping molecule at index 3644 due to error: Explicit valence for atom # 3 O, 3, is greater than permitted
Skipping molecule at index 3646 due to error: Explicit valence for atom # 19 B, 4, is greater than permitted
Skipping molecule at index 3647 due to error: Explicit valence for atom # 93 B, 4, is greater than permitted
Skipping molecule at index 3648 due to error: Explicit valence for atom # 4 B, 4, is greater than permitted
Skipping molecule at index 3649 due to error: Explicit valence for atom # 2 O, 3, is greater than permitted
Skipping molecule at index 3650 due to error: Explicit valence for atom # 85 B, 4, is greater than permitted
Skipping molecule at index 3651 due to error: Explicit valence for atom # 181 B, 4, is greater than permitted
Skipping molecule at index 3652 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 3653 due to error: Explicit valence for atom # 45 B, 4, is greater than permitted
Skipping molecule at index 3655 due to error: Explicit valence for atom # 62 B, 4, is greater than permitted
Skipping molecule at index 3656 due to error: Explicit valence for atom # 1 O, 3, is greater than permitted
Skipping molecule at index 3657 due to error: Explicit valence for atom # 1 O, 3, is greater than permitted
Skipping molecule at index 3658 due to error: Explicit valence for atom # 1 O, 3, is greater than permitted
Skipping molecule at index 3659 due to error: Explicit valence for atom # 3 B, 6, is greater than permitted
Skipping molecule at index 3674 due to error: Explicit valence for atom # 2 B, 4, is greater than permitted
Skipping molecule at index 3675 due to error: Explicit valence for atom # 14 O, 2, is greater than permitted
Skipping molecule at index 3676 due to error: Explicit valence for atom # 0 C, 5, is greater than permitted
Skipping molecule at index 3677 due to error: Explicit valence for atom # 43 B, 5, is greater than permitted
Skipping molecule at index 3678 due to error: Explicit valence for atom # 0 C, 5, is greater than permitted
Skipping molecule at index 3679 due to error: Explicit valence for atom # 80 B, 4, is greater than permitted
Skipping molecule at index 3680 due to error: Explicit valence for atom # 80 B, 4, is greater than permitted
Skipping molecule at index 3681 due to error: Explicit valence for atom # 7 C, 6, is greater than permitted
Skipping molecule at index 3682 due to error: Explicit valence for atom # 5 C, 5, is greater than permitted
Skipping molecule at index 3683 due to error: Explicit valence for atom # 4 N, 4, is greater than permitted
Skipping molecule at index 3684 due to error: Explicit valence for atom # 3 N, 4, is greater than permitted
Skipping molecule at index 3685 due to error: Explicit valence for atom # 12 N, 4, is greater than permitted
Skipping molecule at index 3686 due to error: Explicit valence for atom # 26 N, 4, is greater than permitted
Skipping molecule at index 3687 due to error: Explicit valence for atom # 22 N, 4, is greater than permitted
Skipping molecule at index 3688 due to error: Explicit valence for atom # 26 N, 4, is greater than permitted
Skipping molecule at index 3689 due to error: Explicit valence for atom # 9 Cl, 6, is greater than permitted
Skipping molecule at index 3690 due to error: Explicit valence for atom # 38 B, 4, is greater than permitted
Skipping molecule at index 3691 due to error: Explicit valence for atom # 5 N, 4, is greater than permitted
Skipping molecule at index 3693 due to error: Explicit valence for atom # 47 B, 4, is greater than permitted
Skipping molecule at index 3695 due to error: Explicit valence for atom # 3 B, 4, is greater than permitted
Skipping molecule at index 3696 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 3697 due to error: Explicit valence for atom # 5 B, 4, is greater than permitted
Skipping molecule at index 3698 due to error: Explicit valence for atom # 0 C, 5, is greater than permitted
Skipping molecule at index 3699 due to error: Explicit valence for atom # 71 B, 4, is greater than permitted
Skipping molecule at index 3700 due to error: Explicit valence for atom # 1 H, 2, is greater than permitted
Skipping molecule at index 3701 due to error: Explicit valence for atom # 5 B, 4, is greater than permitted
Skipping molecule at index 3702 due to error: Explicit valence for atom # 94 B, 4, is greater than permitted
Skipping molecule at index 3703 due to error: Explicit valence for atom # 208 B, 4, is greater than permitted
Skipping molecule at index 3704 due to error: Explicit valence for atom # 87 B, 4, is greater than permitted
Skipping molecule at index 3705 due to error: Explicit valence for atom # 4 N, 4, is greater than permitted
Skipping molecule at index 3706 due to error: Explicit valence for atom # 4 N, 4, is greater than permitted
Skipping molecule at index 3707 due to error: Explicit valence for atom # 5 N, 4, is greater than permitted
Skipping molecule at index 3708 due to error: Explicit valence for atom # 0 O, 3, is greater than permitted
Skipping molecule at index 3709 due to error: Explicit valence for atom # 0 O, 3, is greater than permitted
Skipping molecule at index 3710 due to error: Explicit valence for atom # 0 O, 3, is greater than permitted
Skipping molecule at index 3712 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 3713 due to error: Explicit valence for atom # 23 B, 4, is greater than permitted
Skipping molecule at index 3714 due to error: Explicit valence for atom # 12 B, 4, is greater than permitted
Skipping molecule at index 3717 due to error: Explicit valence for atom # 8 O, 3, is greater than permitted
Skipping molecule at index 3718 due to error: Explicit valence for atom # 8 O, 3, is greater than permitted
Skipping molecule at index 3719 due to error: Explicit valence for atom # 8 O, 3, is greater than permitted
Skipping molecule at index 3720 due to error: Explicit valence for atom # 0 Sn, 5, is greater than permitted
Skipping molecule at index 3721 due to error: Explicit valence for atom # 53 B, 6, is greater than permitted
Skipping molecule at index 3722 due to error: Explicit valence for atom # 96 B, 5, is greater than permitted
Skipping molecule at index 3723 due to error: Explicit valence for atom # 120 B, 5, is greater than permitted
Skipping molecule at index 3724 due to error: Explicit valence for atom # 4 N, 4, is greater than permitted
Skipping molecule at index 3725 due to error: Explicit valence for atom # 1 O, 3, is greater than permitted
Skipping molecule at index 3726 due to error: Explicit valence for atom # 3 C, 6, is greater than permitted
Skipping molecule at index 3727 due to error: Explicit valence for atom # 0 B, 6, is greater than permitted
Skipping molecule at index 3728 due to error: Explicit valence for atom # 6 C, 6, is greater than permitted
Skipping molecule at index 3729 due to error: Explicit valence for atom # 75 B, 4, is greater than permitted
Skipping molecule at index 3731 due to error: Can't kekulize mol.  Unkekulized atoms: 118 121 122 127 128
Skipping molecule at index 3733 due to error: Explicit valence for atom # 0 C, 6, is greater than permitted
Skipping molecule at index 3734 due to error: Explicit valence for atom # 0 C, 6, is greater than permitted
Skipping molecule at index 3735 due to error: Explicit valence for atom # 0 C, 6, is greater than permitted
Skipping molecule at index 3736 due to error: Explicit valence for atom # 63 B, 4, is greater than permitted
Skipping molecule at index 3737 due to error: Explicit valence for atom # 40 B, 4, is greater than permitted
Skipping molecule at index 3738 due to error: Explicit valence for atom # 126 B, 4, is greater than permitted
Skipping molecule at index 3739 due to error: Explicit valence for atom # 55 B, 4, is greater than permitted
Skipping molecule at index 3749 due to error: Explicit valence for atom # 33 B, 5, is greater than permitted
Skipping molecule at index 3750 due to error: Explicit valence for atom # 7 C, 6, is greater than permitted

[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:04] Explicit valence for atom # 3 C, 6, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:04] Explicit valence for atom # 0 B, 6, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:04] Explicit valence for atom # 6 C, 6, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 75 B, 4, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Can't kekulize mol.  Unkekulized atoms: 118 121 122 127 128
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:04] Explicit valence for atom # 0 C, 6, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:04] Explicit valence for atom # 0 C, 6, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:04] Explicit valence for atom # 0 C, 6, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 63 B, 4, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 40 B, 4, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 126 B, 4, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 55 B, 4, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:04] Explicit valence for atom # 33 B, 5, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:04] Explicit valence for atom # 7 C, 6, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Explicit valence for atom # 77 B, 4, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:04] Explicit valence for atom # 13 C, 6, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] Can't kekulize mol.  Unkekulized atoms: 161 162 163 164 166
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:04] Explicit valence for atom # 5 C, 6, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:04] Explicit valence for atom # 6 C, 6, is greater than permitted
[10:29:04] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:04] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:05] Explicit valence for atom # 5 C, 6, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:05] Explicit valence for atom # 5 C, 6, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 1 B, 4, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Can't kekulize mol.  Unkekulized atoms: 5 6 8 9 11 89 90 92 93 95
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Can't kekulize mol.  Unkekulized atoms: 5 8 9 11 89 92 93 95
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 44 B, 4, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 0 B, 4, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 0 B, 4, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 0 B, 4, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 0 B, 4, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 0 B, 4, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 0 B, 4, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 0 B, 4, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 13 N, 4, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 10 N, 4, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 108 B, 4, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 108 B, 4, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:05] Explicit valence for atom # 1 C, 6, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 43 B, 4, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 1 B, 4, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 1 B, 4, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 6 O, 3, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 90 B, 4, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 2 N, 4, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 2 N, 4, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 24 N, 4, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 6 O, 3, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 7 O, 3, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 184 B, 4, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Can't kekulize mol.  Unkekulized atoms: 23 24 26 28 29 31 35 36 37 38 39 40 75 77 79 80 82 86 87 88 89 90 91 115 116 118 120 121 123 127 128 129 130 131 132 167 169 171 172 174 178 179 180 181 182 183
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 96 B, 4, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 25 B, 4, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 2 B, 4, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 11 O, 3, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 2 O, 3, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 2 O, 3, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 2 B, 4, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 3 B, 4, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 40 B, 4, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 12 B, 4, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 13 B, 4, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 34 B, 4, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 2 N, 4, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 39 B, 4, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 41 B, 4, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 0 B, 4, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Can't kekulize mol.  Unkekulized atoms: 12 19 22 25 27
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Can't kekulize mol.  Unkekulized atoms: 71 81 89 93 101
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 1 B, 4, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 3 B, 4, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:05] Explicit valence for atom # 44 C, 6, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 57 B, 4, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 57 B, 4, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 57 B, 4, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 29 B, 4, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 58 B, 4, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 2 N, 4, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 36 B, 4, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 186 B, 4, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:05] Explicit valence for atom # 2 N, 4, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 126 B, 4, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 134 B, 4, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 0 B, 4, is greater than permitted

Skipping molecule at index 3751 due to error: Explicit valence for atom # 77 B, 4, is greater than permitted
Skipping molecule at index 3753 due to error: Explicit valence for atom # 13 C, 6, is greater than permitted
Skipping molecule at index 3754 due to error: Can't kekulize mol.  Unkekulized atoms: 161 162 163 164 166
Skipping molecule at index 3755 due to error: Explicit valence for atom # 5 C, 6, is greater than permitted
Skipping molecule at index 3756 due to error: Explicit valence for atom # 6 C, 6, is greater than permitted
Skipping molecule at index 3757 due to error: Explicit valence for atom # 5 C, 6, is greater than permitted
Skipping molecule at index 3758 due to error: Explicit valence for atom # 5 C, 6, is greater than permitted
Skipping molecule at index 3759 due to error: Explicit valence for atom # 1 B, 4, is greater than permitted
Skipping molecule at index 3764 due to error: Can't kekulize mol.  Unkekulized atoms: 5 6 8 9 11 89 90 92 93 95
Skipping molecule at index 3765 due to error: Can't kekulize mol.  Unkekulized atoms: 5 8 9 11 89 92 93 95
Skipping molecule at index 3766 due to error: Explicit valence for atom # 44 B, 4, is greater than permitted
Skipping molecule at index 3767 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 3768 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 3769 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 3770 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 3772 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 3773 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 3774 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 3776 due to error: Explicit valence for atom # 13 N, 4, is greater than permitted
Skipping molecule at index 3777 due to error: Explicit valence for atom # 10 N, 4, is greater than permitted
Skipping molecule at index 3778 due to error: Explicit valence for atom # 108 B, 4, is greater than permitted
Skipping molecule at index 3779 due to error: Explicit valence for atom # 108 B, 4, is greater than permitted
Skipping molecule at index 3780 due to error: Explicit valence for atom # 1 C, 6, is greater than permitted
Skipping molecule at index 3781 due to error: Explicit valence for atom # 43 B, 4, is greater than permitted
Skipping molecule at index 3782 due to error: Explicit valence for atom # 1 B, 4, is greater than permitted
Skipping molecule at index 3783 due to error: Explicit valence for atom # 1 B, 4, is greater than permitted
Skipping molecule at index 3787 due to error: Explicit valence for atom # 6 O, 3, is greater than permitted
Skipping molecule at index 3788 due to error: Explicit valence for atom # 90 B, 4, is greater than permitted
Skipping molecule at index 3790 due to error: Explicit valence for atom # 2 N, 4, is greater than permitted
Skipping molecule at index 3791 due to error: Explicit valence for atom # 2 N, 4, is greater than permitted
Skipping molecule at index 3796 due to error: Explicit valence for atom # 24 N, 4, is greater than permitted
Skipping molecule at index 3797 due to error: Explicit valence for atom # 6 O, 3, is greater than permitted
Skipping molecule at index 3798 due to error: Explicit valence for atom # 7 O, 3, is greater than permitted
Skipping molecule at index 3800 due to error: Explicit valence for atom # 184 B, 4, is greater than permitted
Skipping molecule at index 3802 due to error: Can't kekulize mol.  Unkekulized atoms: 23 24 26 28 29 31 35 36 37 38 39 40 75 77 79 80 82 86 87 88 89 90 91 115 116 118 120 121 123 127 128 129 130 131 132 167 169 171 172 174 178 179 180 181 182 183
Skipping molecule at index 3803 due to error: Explicit valence for atom # 96 B, 4, is greater than permitted
Skipping molecule at index 3804 due to error: Explicit valence for atom # 25 B, 4, is greater than permitted
Skipping molecule at index 3805 due to error: Explicit valence for atom # 2 B, 4, is greater than permitted
Skipping molecule at index 3806 due to error: Explicit valence for atom # 11 O, 3, is greater than permitted
Skipping molecule at index 3807 due to error: Explicit valence for atom # 2 O, 3, is greater than permitted
Skipping molecule at index 3808 due to error: Explicit valence for atom # 2 O, 3, is greater than permitted
Skipping molecule at index 3809 due to error: Explicit valence for atom # 2 B, 4, is greater than permitted
Skipping molecule at index 3810 due to error: Explicit valence for atom # 3 B, 4, is greater than permitted
Skipping molecule at index 3811 due to error: Explicit valence for atom # 40 B, 4, is greater than permitted
Skipping molecule at index 3812 due to error: Explicit valence for atom # 12 B, 4, is greater than permitted
Skipping molecule at index 3813 due to error: Explicit valence for atom # 13 B, 4, is greater than permitted
Skipping molecule at index 3814 due to error: Explicit valence for atom # 34 B, 4, is greater than permitted
Skipping molecule at index 3815 due to error: Explicit valence for atom # 2 N, 4, is greater than permitted
Skipping molecule at index 3816 due to error: Explicit valence for atom # 39 B, 4, is greater than permitted
Skipping molecule at index 3817 due to error: Explicit valence for atom # 41 B, 4, is greater than permitted
Skipping molecule at index 3818 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 3819 due to error: Can't kekulize mol.  Unkekulized atoms: 12 19 22 25 27
Skipping molecule at index 3820 due to error: Can't kekulize mol.  Unkekulized atoms: 71 81 89 93 101
Skipping molecule at index 3822 due to error: Explicit valence for atom # 1 B, 4, is greater than permitted
Skipping molecule at index 3823 due to error: Explicit valence for atom # 3 B, 4, is greater than permitted
Skipping molecule at index 3825 due to error: Explicit valence for atom # 44 C, 6, is greater than permitted
Skipping molecule at index 3826 due to error: Explicit valence for atom # 57 B, 4, is greater than permitted
Skipping molecule at index 3827 due to error: Explicit valence for atom # 57 B, 4, is greater than permitted
Skipping molecule at index 3829 due to error: Explicit valence for atom # 57 B, 4, is greater than permitted
Skipping molecule at index 3830 due to error: Explicit valence for atom # 29 B, 4, is greater than permitted
Skipping molecule at index 3831 due to error: Explicit valence for atom # 58 B, 4, is greater than permitted
Skipping molecule at index 3833 due to error: Explicit valence for atom # 2 N, 4, is greater than permitted
Skipping molecule at index 3834 due to error: Explicit valence for atom # 36 B, 4, is greater than permitted
Skipping molecule at index 3835 due to error: Explicit valence for atom # 186 B, 4, is greater than permitted
Skipping molecule at index 3836 due to error: Explicit valence for atom # 2 N, 4, is greater than permitted
Skipping molecule at index 3838 due to error: Explicit valence for atom # 126 B, 4, is greater than permitted
Skipping molecule at index 3839 due to error: Explicit valence for atom # 134 B, 4, is greater than permitted
Skipping molecule at index 3841 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 3842 due to error: Explicit valence for atom # 2 B, 4, is greater than permitted
Skipping molecule at index 3843 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 3844 due to error: Explicit valence for atom # 142 O, 3, is greater than permitted
Skipping molecule at index 3845 due to error: Explicit valence for atom # 4 C, 5, is greater than permitted
Skipping molecule at index 3846 due to error: Explicit valence for atom # 2 C, 5, is greater than permitted
Skipping molecule at index 3847 due to error: Explicit valence for atom # 27 C, 6, is greater than permitted
Skipping molecule at index 3848 due to error: Explicit valence for atom # 1 B, 4, is greater than permitted
Skipping molecule at index 3849 due to error: Explicit valence for atom # 1 B, 4, is greater than permitted
Skipping molecule at index 3850 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 3851 due to error: Explicit valence for atom # 16 C, 6, is greater than permitted
Skipping molecule at index 3853 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 3854 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 3855 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 3856 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 3857 due to error: Explicit valence for atom # 6 O, 3, is greater than permitted
Skipping molecule at index 3858 due to error: Explicit valence for atom # 1 O, 3, is greater than permitted
Skipping molecule at index 3859 due to error: Explicit valence for atom # 1 O, 3, is greater than permitted
Skipping molecule at index 3860 due to error: Explicit valence for atom # 1 B, 4, is greater than permitted
Skipping molecule at index 3862 due to error: Explicit valence for atom # 1 B, 4, is greater than permitted
Skipping molecule at index 3864 due to error: Explicit valence for atom # 1 B, 4, is greater than permitted
Skipping molecule at index 3866 due to error: Explicit valence for atom # 54 B, 4, is greater than permitted
Skipping molecule at index 3867 due to error: Explicit valence for atom # 47 B, 4, is greater than permitted
Skipping molecule at index 3868 due to error: Explicit valence for atom # 1 N, 4, is greater than permitted
Skipping molecule at index 3869 due to error: Explicit valence for atom # 204 B, 4, is greater than permitted
Skipping molecule at index 3870 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 3871 due to error: Explicit valence for atom # 3 N, 4, is greater than permitted
Skipping molecule at index 3872 due to error: Explicit valence for atom # 14 N, 4, is greater than permitted
Skipping molecule at index 3875 due to error: Explicit valence for atom # 1 B, 4, is greater than permitted
Skipping molecule at index 3876 due to error: Explicit valence for atom # 7 C, 6, is greater than permitted
Skipping molecule at index 3877 due to error: Explicit valence for atom # 7 C, 6, is greater than permitted
Skipping molecule at index 3878 due to error: Explicit valence for atom # 7 C, 6, is greater than permitted
Skipping molecule at index 3879 due to error: Can't kekulize mol.  Unkekulized atoms: 5 6 7 8 9 10 11 12 13 14 15 19 20 21 22 23 24 25 26 27 28 29
Skipping molecule at index 3883 due to error: Can't kekulize mol.  Unkekulized atoms: 32 33 35 37 39
Skipping molecule at index 3886 due to error: Explicit valence for atom # 6 B, 6, is greater than permitted
Skipping molecule at index 3887 due to error: Explicit valence for atom # 6 B, 6, is greater than permitted
Skipping molecule at index 3888 due to error: Explicit valence for atom # 4 O, 3, is greater than permitted
Skipping molecule at index 3889 due to error: Explicit valence for atom # 1 B, 4, is greater than permitted
Skipping molecule at index 3891 due to error: Explicit valence for atom # 5 C, 6, is greater than permitted
Skipping molecule at index 3892 due to error: Explicit valence for atom # 22 C, 6, is greater than permitted
Skipping molecule at index 3893 due to error: Explicit valence for atom # 2 B, 6, is greater than permitted
Skipping molecule at index 3894 due to error: Explicit valence for atom # 88 B, 4, is greater than permitted
Skipping molecule at index 3895 due to error: Explicit valence for atom # 74 B, 4, is greater than permitted
Skipping molecule at index 3896 due to error: Explicit valence for atom # 9 B, 4, is greater than permitted
Skipping molecule at index 3897 due to error: Explicit valence for atom # 33 B, 4, is greater than permitted
Skipping molecule at index 3898 due to error: Explicit valence for atom # 20 B, 4, is greater than permitted
Skipping molecule at index 3899 due to error: Explicit valence for atom # 13 B, 4, is greater than permitted
Skipping molecule at index 3904 due to error: Explicit valence for atom # 19 N, 4, is greater than permitted
Skipping molecule at index 3905 due to error: Explicit valence for atom # 57 N, 4, is greater than permitted
Skipping molecule at index 3909 due to error: Explicit valence for atom # 6 N, 4, is greater than permitted
Skipping molecule at index 3910 due to error: Explicit valence for atom # 2 B, 4, is greater than permitted
Skipping molecule at index 3911 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 3912 due to error: Explicit valence for atom # 1 B, 4, is greater than permitted
Skipping molecule at index 3913 due to error: Explicit valence for atom # 2 B, 4, is greater than permitted
Skipping molecule at index 3914 due to error: Explicit valence for atom # 10 B, 4, is greater than permitted
Skipping molecule at index 3915 due to error: Can't kekulize mol.  Unkekulized atoms: 4 6 8 10 12
Skipping molecule at index 3916 due to error: Explicit valence for atom # 42 B, 4, is greater than permitted
Skipping molecule at index 3917 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 3920 due to error: Explicit valence for atom # 1 B, 4, is greater than permitted
Skipping molecule at index 3921 due to error: Explicit valence for atom # 1 B, 4, is greater than permitted
Skipping molecule at index 3922 due to error: Explicit valence for atom # 38 B, 5, is greater than permitted
Skipping molecule at index 3923 due to error: Explicit valence for atom # 38 B, 5, is greater than permitted
Skipping molecule at index 3924 due to error: Explicit valence for atom # 35 B, 4, is greater than permitted
Skipping molecule at index 3925 due to error: Explicit valence for atom # 70 B, 4, is greater than permitted
Skipping molecule at index 3926 due to error: Explicit valence for atom # 56 B, 4, is greater than permitted
Skipping molecule at index 3927 due to error: Explicit valence for atom # 111 B, 4, is greater than permitted
Skipping molecule at index 3928 due to error: Explicit valence for atom # 76 B, 4, is greater than permitted
Skipping molecule at index 3929 due to error: Explicit valence for atom # 56 B, 4, is greater than permitted
Skipping molecule at index 3930 due to error: Explicit valence for atom # 22 B, 4, is greater than permitted
Skipping molecule at index 3931 due to error: Explicit valence for atom # 22 B, 4, is greater than permitted
Skipping molecule at index 3932 due to error: Can't kekulize mol.  Unkekulized atoms: 80 84 90 93 99

[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 88 B, 4, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 74 B, 4, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 9 B, 4, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 33 B, 4, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 20 B, 4, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 13 B, 4, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 19 N, 4, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 57 N, 4, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:05] Explicit valence for atom # 6 N, 4, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 2 B, 4, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 0 B, 4, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 1 B, 4, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 2 B, 4, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 10 B, 4, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Can't kekulize mol.  Unkekulized atoms: 4 6 8 10 12
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 42 B, 4, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 0 B, 4, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 1 B, 4, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 1 B, 4, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:05] Explicit valence for atom # 38 B, 5, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:05] Explicit valence for atom # 38 B, 5, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 35 B, 4, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 70 B, 4, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 56 B, 4, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 111 B, 4, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 76 B, 4, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 56 B, 4, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 22 B, 4, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 22 B, 4, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Can't kekulize mol.  Unkekulized atoms: 80 84 90 93 99
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 0 Bi, 7, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 133 B, 4, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 48 B, 4, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:05] Explicit valence for atom # 68 C, 5, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:05] Explicit valence for atom # 68 C, 5, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:05] Explicit valence for atom # 68 C, 6, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:05] Explicit valence for atom # 3 C, 6, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:05] Explicit valence for atom # 110 F, 2, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Can't kekulize mol.  Unkekulized atoms: 9 17 19 21 27
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 3 F, 2, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 25 N, 4, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 1 B, 4, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 7 B, 4, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 54 B, 4, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 2 B, 4, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 9 B, 4, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 40 B, 4, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:05] Explicit valence for atom # 0 C, 6, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:05] Explicit valence for atom # 2 C, 6, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:05] Explicit valence for atom # 1 C, 6, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:05] Explicit valence for atom # 3 C, 6, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:05] Explicit valence for atom # 4 C, 6, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:05] Explicit valence for atom # 4 C, 6, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:05] Explicit valence for atom # 3 C, 6, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:05] Explicit valence for atom # 6 C, 6, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:05] Explicit valence for atom # 1 C, 6, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:05] Explicit valence for atom # 3 C, 6, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 0 B, 4, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 108 B, 4, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 4 B, 4, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 8 B, 4, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 6 B, 4, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 19 F, 2, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 248 B, 4, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 13 N, 4, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:05] Explicit valence for atom # 58 B, 5, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 92 B, 4, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 92 B, 4, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Can't kekulize mol.  Unkekulized atoms: 5 7 9 11 13 14 16 18 20 22 23 25 27 29 31
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 0 B, 4, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:05] Explicit valence for atom # 3 B, 5, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 18 B, 4, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 45 B, 4, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 5 B, 4, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 12 B, 4, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 9 B, 4, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 75 B, 4, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 4 B, 4, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.

Skipping molecule at index 3933 due to error: Explicit valence for atom # 0 Bi, 7, is greater than permitted
Skipping molecule at index 3935 due to error: Explicit valence for atom # 133 B, 4, is greater than permitted
Skipping molecule at index 3936 due to error: Explicit valence for atom # 48 B, 4, is greater than permitted
Skipping molecule at index 3937 due to error: Explicit valence for atom # 68 C, 5, is greater than permitted
Skipping molecule at index 3938 due to error: Explicit valence for atom # 68 C, 5, is greater than permitted
Skipping molecule at index 3939 due to error: Explicit valence for atom # 68 C, 6, is greater than permitted
Skipping molecule at index 3942 due to error: Explicit valence for atom # 3 C, 6, is greater than permitted
Skipping molecule at index 3943 due to error: Explicit valence for atom # 110 F, 2, is greater than permitted
Skipping molecule at index 3944 due to error: Can't kekulize mol.  Unkekulized atoms: 9 17 19 21 27
Skipping molecule at index 3955 due to error: Explicit valence for atom # 3 F, 2, is greater than permitted
Skipping molecule at index 3956 due to error: Explicit valence for atom # 25 N, 4, is greater than permitted
Skipping molecule at index 3957 due to error: Explicit valence for atom # 1 B, 4, is greater than permitted
Skipping molecule at index 3960 due to error: Explicit valence for atom # 7 B, 4, is greater than permitted
Skipping molecule at index 3962 due to error: Explicit valence for atom # 54 B, 4, is greater than permitted
Skipping molecule at index 3963 due to error: Explicit valence for atom # 2 B, 4, is greater than permitted
Skipping molecule at index 3964 due to error: Explicit valence for atom # 9 B, 4, is greater than permitted
Skipping molecule at index 3965 due to error: Explicit valence for atom # 40 B, 4, is greater than permitted
Skipping molecule at index 3966 due to error: Explicit valence for atom # 0 C, 6, is greater than permitted
Skipping molecule at index 3967 due to error: Explicit valence for atom # 2 C, 6, is greater than permitted
Skipping molecule at index 3968 due to error: Explicit valence for atom # 1 C, 6, is greater than permitted
Skipping molecule at index 3969 due to error: Explicit valence for atom # 3 C, 6, is greater than permitted
Skipping molecule at index 3970 due to error: Explicit valence for atom # 4 C, 6, is greater than permitted
Skipping molecule at index 3971 due to error: Explicit valence for atom # 4 C, 6, is greater than permitted
Skipping molecule at index 3972 due to error: Explicit valence for atom # 3 C, 6, is greater than permitted
Skipping molecule at index 3973 due to error: Explicit valence for atom # 6 C, 6, is greater than permitted
Skipping molecule at index 3974 due to error: Explicit valence for atom # 1 C, 6, is greater than permitted
Skipping molecule at index 3975 due to error: Explicit valence for atom # 3 C, 6, is greater than permitted
Skipping molecule at index 3977 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 3978 due to error: Explicit valence for atom # 108 B, 4, is greater than permitted
Skipping molecule at index 3979 due to error: Explicit valence for atom # 4 B, 4, is greater than permitted
Skipping molecule at index 3980 due to error: Explicit valence for atom # 8 B, 4, is greater than permitted
Skipping molecule at index 3981 due to error: Explicit valence for atom # 6 B, 4, is greater than permitted
Skipping molecule at index 3982 due to error: Explicit valence for atom # 19 F, 2, is greater than permitted
Skipping molecule at index 3983 due to error: Explicit valence for atom # 248 B, 4, is greater than permitted
Skipping molecule at index 3985 due to error: Explicit valence for atom # 13 N, 4, is greater than permitted
Skipping molecule at index 3986 due to error: Explicit valence for atom # 58 B, 5, is greater than permitted
Skipping molecule at index 3987 due to error: Explicit valence for atom # 92 B, 4, is greater than permitted
Skipping molecule at index 3988 due to error: Explicit valence for atom # 92 B, 4, is greater than permitted
Skipping molecule at index 3992 due to error: Can't kekulize mol.  Unkekulized atoms: 5 7 9 11 13 14 16 18 20 22 23 25 27 29 31
Skipping molecule at index 3993 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 3994 due to error: Explicit valence for atom # 3 B, 5, is greater than permitted
Skipping molecule at index 3996 due to error: Explicit valence for atom # 18 B, 4, is greater than permitted
Skipping molecule at index 3997 due to error: Explicit valence for atom # 45 B, 4, is greater than permitted
Skipping molecule at index 3998 due to error: Explicit valence for atom # 5 B, 4, is greater than permitted
Skipping molecule at index 3999 due to error: Explicit valence for atom # 12 B, 4, is greater than permitted
Skipping molecule at index 4000 due to error: Explicit valence for atom # 9 B, 4, is greater than permitted
Skipping molecule at index 4001 due to error: Explicit valence for atom # 75 B, 4, is greater than permitted
Skipping molecule at index 4002 due to error: Explicit valence for atom # 4 B, 4, is greater than permitted
Skipping molecule at index 4003 due to error: Explicit valence for atom # 4 B, 4, is greater than permitted
Skipping molecule at index 4005 due to error: Explicit valence for atom # 8 B, 4, is greater than permitted
Skipping molecule at index 4006 due to error: Explicit valence for atom # 102 B, 4, is greater than permitted
Skipping molecule at index 4007 due to error: Explicit valence for atom # 63 B, 4, is greater than permitted
Skipping molecule at index 4008 due to error: Explicit valence for atom # 72 B, 4, is greater than permitted
Skipping molecule at index 4012 due to error: Explicit valence for atom # 6 B, 4, is greater than permitted
Skipping molecule at index 4017 due to error: Explicit valence for atom # 1 B, 4, is greater than permitted
Skipping molecule at index 4020 due to error: Explicit valence for atom # 147 B, 4, is greater than permitted
Skipping molecule at index 4022 due to error: Explicit valence for atom # 91 B, 4, is greater than permitted
Skipping molecule at index 4023 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 4024 due to error: Explicit valence for atom # 111 B, 4, is greater than permitted
Skipping molecule at index 4025 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 4026 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 4027 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 4028 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 4029 due to error: Explicit valence for atom # 83 B, 4, is greater than permitted
Skipping molecule at index 4034 due to error: Explicit valence for atom # 6 B, 4, is greater than permitted
Skipping molecule at index 4037 due to error: Explicit valence for atom # 2 B, 4, is greater than permitted
Skipping molecule at index 4038 due to error: Explicit valence for atom # 5 B, 4, is greater than permitted
Skipping molecule at index 4045 due to error: Explicit valence for atom # 0 C, 6, is greater than permitted
Skipping molecule at index 4046 due to error: Explicit valence for atom # 0 C, 5, is greater than permitted
Skipping molecule at index 4047 due to error: Explicit valence for atom # 0 B, 6, is greater than permitted
Skipping molecule at index 4048 due to error: Explicit valence for atom # 0 C, 6, is greater than permitted
Skipping molecule at index 4049 due to error: Explicit valence for atom # 32 O, 3, is greater than permitted
Skipping molecule at index 4050 due to error: Explicit valence for atom # 6 B, 4, is greater than permitted
Skipping molecule at index 4052 due to error: Explicit valence for atom # 17 C, 5, is greater than permitted
Skipping molecule at index 4053 due to error: Explicit valence for atom # 17 C, 5, is greater than permitted
Skipping molecule at index 4058 due to error: Can't kekulize mol.  Unkekulized atoms: 4 27 38 53 71
Skipping molecule at index 4061 due to error: Explicit valence for atom # 0 Sn, 5, is greater than permitted
Skipping molecule at index 4062 due to error: Can't kekulize mol.  Unkekulized atoms: 7 8 9 13 15 17 19 21 22 23 25 27 29 31 32 33 75 76 77 80 82 84 86 88 89 90 92 94 96 98 99 100
Skipping molecule at index 4063 due to error: Explicit valence for atom # 150 B, 4, is greater than permitted
Skipping molecule at index 4064 due to error: Explicit valence for atom # 6 C, 6, is greater than permitted
Skipping molecule at index 4065 due to error: Explicit valence for atom # 1 C, 6, is greater than permitted
Skipping molecule at index 4066 due to error: Explicit valence for atom # 2 C, 6, is greater than permitted
Skipping molecule at index 4067 due to error: Explicit valence for atom # 7 C, 6, is greater than permitted
Skipping molecule at index 4068 due to error: Explicit valence for atom # 9 B, 4, is greater than permitted
Skipping molecule at index 4069 due to error: Explicit valence for atom # 9 Cl, 6, is greater than permitted
Skipping molecule at index 4070 due to error: Explicit valence for atom # 2 O, 3, is greater than permitted
Skipping molecule at index 4071 due to error: Explicit valence for atom # 17 B, 4, is greater than permitted
Skipping molecule at index 4072 due to error: Explicit valence for atom # 3 B, 4, is greater than permitted
Skipping molecule at index 4073 due to error: Explicit valence for atom # 14 C, 6, is greater than permitted
Skipping molecule at index 4074 due to error: Explicit valence for atom # 11 C, 6, is greater than permitted
Skipping molecule at index 4075 due to error: Explicit valence for atom # 7 C, 6, is greater than permitted
Skipping molecule at index 4076 due to error: Explicit valence for atom # 19 C, 6, is greater than permitted
Skipping molecule at index 4077 due to error: Explicit valence for atom # 8 C, 6, is greater than permitted
Skipping molecule at index 4079 due to error: Explicit valence for atom # 1 B, 4, is greater than permitted
Skipping molecule at index 4080 due to error: Explicit valence for atom # 1 B, 4, is greater than permitted
Skipping molecule at index 4081 due to error: Explicit valence for atom # 7 C, 6, is greater than permitted
Skipping molecule at index 4082 due to error: Explicit valence for atom # 7 C, 6, is greater than permitted
Skipping molecule at index 4084 due to error: Explicit valence for atom # 6 O, 3, is greater than permitted
Skipping molecule at index 4085 due to error: Explicit valence for atom # 6 O, 3, is greater than permitted
Skipping molecule at index 4086 due to error: Explicit valence for atom # 90 B, 4, is greater than permitted
Skipping molecule at index 4087 due to error: Explicit valence for atom # 4 N, 4, is greater than permitted
Skipping molecule at index 4088 due to error: Explicit valence for atom # 1 B, 4, is greater than permitted
Skipping molecule at index 4089 due to error: Explicit valence for atom # 4 N, 4, is greater than permitted
Skipping molecule at index 4090 due to error: Explicit valence for atom # 39 B, 4, is greater than permitted
Skipping molecule at index 4091 due to error: Explicit valence for atom # 2 N, 4, is greater than permitted
Skipping molecule at index 4094 due to error: Explicit valence for atom # 24 F, 2, is greater than permitted

[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 17 C, 5, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Can't kekulize mol.  Unkekulized atoms: 4 27 38 53 71
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 0 Sn, 5, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Can't kekulize mol.  Unkekulized atoms: 7 8 9 13 15 17 19 21 22 23 25 27 29 31 32 33 75 76 77 80 82 84 86 88 89 90 92 94 96 98 99 100
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 150 B, 4, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:05] Explicit valence for atom # 6 C, 6, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:05] Explicit valence for atom # 1 C, 6, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:05] Explicit valence for atom # 2 C, 6, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:05] Explicit valence for atom # 7 C, 6, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 9 B, 4, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 9 Cl, 6, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 2 O, 3, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 17 B, 4, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 3 B, 4, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:05] Explicit valence for atom # 14 C, 6, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:05] Explicit valence for atom # 11 C, 6, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:05] Explicit valence for atom # 7 C, 6, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:05] Explicit valence for atom # 19 C, 6, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:05] Explicit valence for atom # 8 C, 6, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 1 B, 4, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 1 B, 4, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:05] Explicit valence for atom # 7 C, 6, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:05] Explicit valence for atom # 7 C, 6, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:05] Explicit valence for atom # 6 O, 3, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 6 O, 3, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 90 B, 4, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 4 N, 4, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 1 B, 4, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 4 N, 4, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 39 B, 4, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:05] Explicit valence for atom # 2 N, 4, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 24 F, 2, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 12 F, 2, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 37 N, 4, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Can't kekulize mol.  Unkekulized atoms: 51 53 54 57 69 84 85 153 156
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 0 B, 4, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 33 B, 4, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 85 B, 4, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 85 B, 4, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 85 B, 4, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 33 B, 4, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 85 B, 4, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 33 B, 4, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 85 B, 4, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 33 B, 4, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 33 B, 4, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 85 B, 4, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 0 B, 4, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 9 B, 4, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 71 B, 5, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:05] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:05] Can't kekulize mol.  Unkekulized atoms: 30 31 32 33 34
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 27 B, 4, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 39 B, 4, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 44 B, 4, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 1 H, 2, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 0 B, 4, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 0 B, 4, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Can't kekulize mol.  Unkekulized atoms: 11 12 18 19 27 31 36 38 40 48
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Can't kekulize mol.  Unkekulized atoms: 31 32 34 36 38 40 41 43 45 47
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Can't kekulize mol.  Unkekulized atoms: 31 32 34 36 38 40 41 43 45 47
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 10 B, 4, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 39 F, 2, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 41 F, 2, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 42 B, 4, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:05] Explicit valence for atom # 0 C, 6, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 50 B, 4, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 116 B, 4, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 8 N, 4, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 55 B, 4, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 81 F, 2, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 1 N, 4, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 22 F, 2, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 0 B, 4, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:05] Explicit valence for atom # 4 C, 6, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:05] Explicit valence for atom # 7 C, 6, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:05] Explicit valence for atom # 9 C, 6, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:05] Explicit valence for atom # 2 B, 5, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 58 B, 4, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 4 F, 2, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 116 B, 4, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 56 B, 4, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 124 H, 2, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 2 F, 2, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 0 Si, 7, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 10 F, 2, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 0 Ga, 4, is greater than permitted

Skipping molecule at index 4095 due to error: Explicit valence for atom # 12 F, 2, is greater than permitted
Skipping molecule at index 4097 due to error: Explicit valence for atom # 37 N, 4, is greater than permitted
Skipping molecule at index 4100 due to error: Can't kekulize mol.  Unkekulized atoms: 51 53 54 57 69 84 85 153 156
Skipping molecule at index 4101 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 4102 due to error: Explicit valence for atom # 33 B, 4, is greater than permitted
Skipping molecule at index 4103 due to error: Explicit valence for atom # 85 B, 4, is greater than permitted
Skipping molecule at index 4104 due to error: Explicit valence for atom # 85 B, 4, is greater than permitted
Skipping molecule at index 4105 due to error: Explicit valence for atom # 85 B, 4, is greater than permitted
Skipping molecule at index 4106 due to error: Explicit valence for atom # 33 B, 4, is greater than permitted
Skipping molecule at index 4107 due to error: Explicit valence for atom # 85 B, 4, is greater than permitted
Skipping molecule at index 4108 due to error: Explicit valence for atom # 33 B, 4, is greater than permitted
Skipping molecule at index 4109 due to error: Explicit valence for atom # 85 B, 4, is greater than permitted
Skipping molecule at index 4110 due to error: Explicit valence for atom # 33 B, 4, is greater than permitted
Skipping molecule at index 4111 due to error: Explicit valence for atom # 33 B, 4, is greater than permitted
Skipping molecule at index 4112 due to error: Explicit valence for atom # 85 B, 4, is greater than permitted
Skipping molecule at index 4113 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 4114 due to error: Explicit valence for atom # 9 B, 4, is greater than permitted
Skipping molecule at index 4115 due to error: Explicit valence for atom # 71 B, 5, is greater than permitted
Skipping molecule at index 4116 due to error: Can't kekulize mol.  Unkekulized atoms: 30 31 32 33 34
Skipping molecule at index 4117 due to error: Explicit valence for atom # 27 B, 4, is greater than permitted
Skipping molecule at index 4118 due to error: Explicit valence for atom # 39 B, 4, is greater than permitted
Skipping molecule at index 4119 due to error: Explicit valence for atom # 44 B, 4, is greater than permitted
Skipping molecule at index 4120 due to error: Explicit valence for atom # 1 H, 2, is greater than permitted
Skipping molecule at index 4121 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 4122 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 4123 due to error: Can't kekulize mol.  Unkekulized atoms: 11 12 18 19 27 31 36 38 40 48
Skipping molecule at index 4124 due to error: Can't kekulize mol.  Unkekulized atoms: 31 32 34 36 38 40 41 43 45 47
Skipping molecule at index 4125 due to error: Can't kekulize mol.  Unkekulized atoms: 31 32 34 36 38 40 41 43 45 47
Skipping molecule at index 4126 due to error: Explicit valence for atom # 10 B, 4, is greater than permitted
Skipping molecule at index 4127 due to error: Explicit valence for atom # 39 F, 2, is greater than permitted
Skipping molecule at index 4128 due to error: Explicit valence for atom # 41 F, 2, is greater than permitted
Skipping molecule at index 4129 due to error: Explicit valence for atom # 42 B, 4, is greater than permitted
Skipping molecule at index 4131 due to error: Explicit valence for atom # 0 C, 6, is greater than permitted
Skipping molecule at index 4132 due to error: Explicit valence for atom # 50 B, 4, is greater than permitted
Skipping molecule at index 4133 due to error: Explicit valence for atom # 116 B, 4, is greater than permitted
Skipping molecule at index 4134 due to error: Explicit valence for atom # 8 N, 4, is greater than permitted
Skipping molecule at index 4135 due to error: Explicit valence for atom # 55 B, 4, is greater than permitted
Skipping molecule at index 4136 due to error: Explicit valence for atom # 81 F, 2, is greater than permitted
Skipping molecule at index 4137 due to error: Explicit valence for atom # 1 N, 4, is greater than permitted
Skipping molecule at index 4138 due to error: Explicit valence for atom # 22 F, 2, is greater than permitted
Skipping molecule at index 4139 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 0 due to error: Explicit valence for atom # 4 C, 6, is greater than permitted
Skipping molecule at index 1 due to error: Explicit valence for atom # 7 C, 6, is greater than permitted
Skipping molecule at index 2 due to error: Explicit valence for atom # 9 C, 6, is greater than permitted
Skipping molecule at index 4 due to error: Explicit valence for atom # 2 B, 5, is greater than permitted
Skipping molecule at index 5 due to error: Explicit valence for atom # 58 B, 4, is greater than permitted
Skipping molecule at index 6 due to error: Explicit valence for atom # 4 F, 2, is greater than permitted
Skipping molecule at index 7 due to error: Explicit valence for atom # 116 B, 4, is greater than permitted
Skipping molecule at index 8 due to error: Explicit valence for atom # 56 B, 4, is greater than permitted
Skipping molecule at index 9 due to error: Explicit valence for atom # 124 H, 2, is greater than permitted
Skipping molecule at index 10 due to error: Explicit valence for atom # 2 F, 2, is greater than permitted
Skipping molecule at index 11 due to error: Explicit valence for atom # 0 Si, 7, is greater than permitted
Skipping molecule at index 12 due to error: Explicit valence for atom # 10 F, 2, is greater than permitted
Skipping molecule at index 13 due to error: Explicit valence for atom # 0 Ga, 4, is greater than permitted
Skipping molecule at index 14 due to error: Explicit valence for atom # 1 B, 4, is greater than permitted
Skipping molecule at index 15 due to error: Explicit valence for atom # 1 H, 3, is greater than permitted
Skipping molecule at index 16 due to error: Explicit valence for atom # 1 H, 3, is greater than permitted
Skipping molecule at index 17 due to error: Explicit valence for atom # 1 H, 3, is greater than permitted
Skipping molecule at index 18 due to error: Explicit valence for atom # 1 H, 3, is greater than permitted
Skipping molecule at index 19 due to error: Explicit valence for atom # 1 H, 3, is greater than permitted
Skipping molecule at index 20 due to error: Explicit valence for atom # 1 H, 3, is greater than permitted
Skipping molecule at index 21 due to error: Explicit valence for atom # 110 B, 4, is greater than permitted
Skipping molecule at index 22 due to error: Explicit valence for atom # 1 B, 4, is greater than permitted
Skipping molecule at index 23 due to error: Explicit valence for atom # 113 B, 4, is greater than permitted
Skipping molecule at index 24 due to error: Explicit valence for atom # 119 B, 4, is greater than permitted
Skipping molecule at index 25 due to error: Explicit valence for atom # 1 C, 5, is greater than permitted
Skipping molecule at index 26 due to error: Explicit valence for atom # 0 C, 5, is greater than permitted
Skipping molecule at index 33 due to error: Explicit valence for atom # 7 H, 2, is greater than permitted
Skipping molecule at index 34 due to error: Explicit valence for atom # 29 C, 5, is greater than permitted
Skipping molecule at index 35 due to error: Explicit valence for atom # 2 H, 2, is greater than permitted
Skipping molecule at index 36 due to error: Explicit valence for atom # 12 H, 2, is greater than permitted
Skipping molecule at index 37 due to error: Explicit valence for atom # 2 B, 4, is greater than permitted
Skipping molecule at index 38 due to error: Explicit valence for atom # 2 H, 2, is greater than permitted
Skipping molecule at index 40 due to error: Explicit valence for atom # 4 H, 2, is greater than permitted
Skipping molecule at index 41 due to error: Explicit valence for atom # 4 H, 3, is greater than permitted
Skipping molecule at index 44 due to error: Explicit valence for atom # 7 O, 5, is greater than permitted
Skipping molecule at index 45 due to error: Explicit valence for atom # 6 C, 6, is greater than permitted
Skipping molecule at index 46 due to error: Explicit valence for atom # 6 O, 3, is greater than permitted
Skipping molecule at index 47 due to error: Explicit valence for atom # 5 C, 5, is greater than permitted
Skipping molecule at index 48 due to error: Explicit valence for atom # 5 C, 5, is greater than permitted
Skipping molecule at index 49 due to error: Explicit valence for atom # 9 C, 6, is greater than permitted
Skipping molecule at index 50 due to error: Explicit valence for atom # 5 C, 6, is greater than permitted
Skipping molecule at index 51 due to error: Explicit valence for atom # 56 B, 6, is greater than permitted
Skipping molecule at index 52 due to error: Can't kekulize mol.  Unkekulized atoms: 12 13 15 66 67
Skipping molecule at index 53 due to error: Explicit valence for atom # 4 O, 3, is greater than permitted
Skipping molecule at index 54 due to error: Explicit valence for atom # 1 C, 5, is greater than permitted
Skipping molecule at index 55 due to error: Explicit valence for atom # 5 B, 6, is greater than permitted
Skipping molecule at index 56 due to error: Explicit valence for atom # 50 B, 4, is greater than permitted
Skipping molecule at index 58 due to error: Explicit valence for atom # 5 O, 3, is greater than permitted
Skipping molecule at index 59 due to error: Explicit valence for atom # 5 O, 3, is greater than permitted
Skipping molecule at index 60 due to error: Explicit valence for atom # 2 B, 5, is greater than permitted
Skipping molecule at index 61 due to error: Explicit valence for atom # 2 B, 5, is greater than permitted
Skipping molecule at index 62 due to error: Explicit valence for atom # 6 O, 3, is greater than permitted
Skipping molecule at index 63 due to error: Explicit valence for atom # 5 F, 2, is greater than permitted
Skipping molecule at index 64 due to error: Explicit valence for atom # 33 F, 2, is greater than permitted
Skipping molecule at index 65 due to error: Explicit valence for atom # 3 B, 4, is greater than permitted
Skipping molecule at index 68 due to error: Explicit valence for atom # 105 O, 3, is greater than permitted
Skipping molecule at index 71 due to error: Explicit valence for atom # 3 O, 3, is greater than permitted
Skipping molecule at index 72 due to error: Explicit valence for atom # 2 H, 2, is greater than permitted
Skipping molecule at index 73 due to error: Explicit valence for atom # 1 H, 2, is greater than permitted
Skipping molecule at index 74 due to error: Explicit valence for atom # 84 B, 6, is greater than permitted
Skipping molecule at index 77 due to error: Explicit valence for atom # 35 C, 6, is greater than permitted
Skipping molecule at index 78 due to error: Explicit valence for atom # 0 B, 6, is greater than permitted
Skipping molecule at index 79 due to error: Explicit valence for atom # 0 B, 6, is greater than permitted
Skipping molecule at index 80 due to error: Explicit valence for atom # 31 C, 6, is greater than permitted
Skipping molecule at index 81 due to error: Explicit valence for atom # 0 B, 6, is greater than permitted
Skipping molecule at index 82 due to error: Explicit valence for atom # 0 B, 6, is greater than permitted
Skipping molecule at index 83 due to error: Explicit valence for atom # 0 B, 6, is greater than permitted
Skipping molecule at index 84 due to error: Explicit valence for atom # 29 N, 4, is greater than permitted
Skipping molecule at index 86 due to error: Explicit valence for atom # 3 O, 3, is greater than permitted
Skipping molecule at index 87 due to error: Explicit valence for atom # 3 C, 5, is greater than permitted
Skipping molecule at index 89 due to error: Explicit valence for atom # 2 B, 4, is greater than permitted
Skipping molecule at index 90 due to error: Explicit valence for atom # 7 O, 3, is greater than permitted
Skipping molecule at index 91 due to error: Explicit valence for atom # 7 O, 3, is greater than permitted
Skipping molecule at index 94 due to error: Explicit valence for atom # 1 C, 5, is greater than permitted
Skipping molecule at index 95 due to error: Explicit valence for atom # 28 B, 4, is greater than permitted
Skipping molecule at index 96 due to error: Explicit valence for atom # 1 O, 3, is greater than permitted
Skipping molecule at index 97 due to error: Explicit valence for atom # 2 O, 3, is greater than permitted
Skipping molecule at index 98 due to error: Explicit valence for atom # 2 O, 3, is greater than permitted
Skipping molecule at index 100 due to error: Explicit valence for atom # 1 B, 4, is greater than permitted
Skipping molecule at index 107 due to error: Explicit valence for atom # 71 N, 4, is greater than permitted
Skipping molecule at index 113 due to error: Explicit valence for atom # 5 O, 3, is greater than permitted
Skipping molecule at index 114 due to error: Explicit valence for atom # 15 B, 4, is greater than permitted
Skipping molecule at index 115 due to error: Explicit valence for atom # 0 C, 6, is greater than permitted
Skipping molecule at index 118 due to error: Explicit valence for atom # 4 B, 5, is greater than permitted
Skipping molecule at index 119 due to error: Explicit valence for atom # 78 B, 6, is greater than permitted
Skipping molecule at index 120 due to error: Explicit valence for atom # 5 O, 3, is greater than permitted
Skipping molecule at index 121 due to error: Explicit valence for atom # 28 O, 3, is greater than permitted
Skipping molecule at index 122 due to error: Explicit valence for atom # 4 B, 5, is greater than permitted
Skipping molecule at index 123 due to error: Explicit valence for atom # 2 O, 3, is greater than permitted
Skipping molecule at index 124 due to error: Explicit valence for atom # 3 B, 4, is greater than permitted

[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 29 N, 4, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 3 O, 3, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:05] Explicit valence for atom # 3 C, 5, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 2 B, 4, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 7 O, 3, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 7 O, 3, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:05] Explicit valence for atom # 1 C, 5, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 28 B, 4, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:05] Explicit valence for atom # 1 O, 3, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:05] Explicit valence for atom # 2 O, 3, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:05] Explicit valence for atom # 2 O, 3, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 1 B, 4, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 71 N, 4, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:05] Explicit valence for atom # 5 O, 3, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 15 B, 4, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:05] Explicit valence for atom # 0 C, 6, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:05] Explicit valence for atom # 4 B, 5, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:05] Explicit valence for atom # 78 B, 6, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 5 O, 3, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 28 O, 3, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 4 B, 5, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 2 O, 3, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 3 B, 4, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 6 B, 4, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:05] Explicit valence for atom # 6 C, 6, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:05] Explicit valence for atom # 8 C, 6, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:05] Explicit valence for atom # 16 C, 6, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:05] Explicit valence for atom # 16 C, 6, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:05] Explicit valence for atom # 7 O, 3, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:05] Explicit valence for atom # 7 O, 3, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:05] Explicit valence for atom # 8 C, 6, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:05] Explicit valence for atom # 51 O, 3, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:05] Explicit valence for atom # 51 O, 3, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:05] Explicit valence for atom # 6 C, 6, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:05] Explicit valence for atom # 6 C, 6, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:05] Explicit valence for atom # 6 C, 6, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:05] Explicit valence for atom # 6 C, 6, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:05] Explicit valence for atom # 6 C, 6, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:05] Explicit valence for atom # 1 C, 6, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:05] Explicit valence for atom # 1 C, 6, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:05] Explicit valence for atom # 1 C, 6, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 79 O, 3, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 5 B, 4, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 89 B, 4, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 1 B, 4, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 4 B, 4, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:05] Explicit valence for atom # 3 B, 5, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:05] Explicit valence for atom # 3 B, 5, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:05] Explicit valence for atom # 3 B, 5, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:05] Explicit valence for atom # 7 B, 5, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:05] Explicit valence for atom # 69 B, 5, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 68 B, 4, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:05] Explicit valence for atom # 0 C, 6, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:05] Explicit valence for atom # 3 B, 6, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:05] Explicit valence for atom # 0 C, 6, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 0 B, 6, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 1 B, 5, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 2 B, 4, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 2 B, 4, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 1 B, 4, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 6 B, 4, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 3 O, 3, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:05] Explicit valence for atom # 4 C, 6, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 5 B, 4, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 103 B, 4, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 3 B, 4, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 4 B, 4, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:05] Explicit valence for atom # 1 B, 6, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:05] Explicit valence for atom # 1 B, 6, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:05] Explicit valence for atom # 2 B, 6, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 3 B, 5, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.

Skipping molecule at index 125 due to error: Explicit valence for atom # 6 B, 4, is greater than permitted
Skipping molecule at index 126 due to error: Explicit valence for atom # 6 C, 6, is greater than permitted
Skipping molecule at index 127 due to error: Explicit valence for atom # 8 C, 6, is greater than permitted
Skipping molecule at index 128 due to error: Explicit valence for atom # 16 C, 6, is greater than permitted
Skipping molecule at index 129 due to error: Explicit valence for atom # 16 C, 6, is greater than permitted
Skipping molecule at index 130 due to error: Explicit valence for atom # 7 O, 3, is greater than permitted
Skipping molecule at index 131 due to error: Explicit valence for atom # 7 O, 3, is greater than permitted
Skipping molecule at index 132 due to error: Explicit valence for atom # 8 C, 6, is greater than permitted
Skipping molecule at index 133 due to error: Explicit valence for atom # 51 O, 3, is greater than permitted
Skipping molecule at index 134 due to error: Explicit valence for atom # 51 O, 3, is greater than permitted
Skipping molecule at index 135 due to error: Explicit valence for atom # 6 C, 6, is greater than permitted
Skipping molecule at index 136 due to error: Explicit valence for atom # 6 C, 6, is greater than permitted
Skipping molecule at index 137 due to error: Explicit valence for atom # 6 C, 6, is greater than permitted
Skipping molecule at index 138 due to error: Explicit valence for atom # 6 C, 6, is greater than permitted
Skipping molecule at index 139 due to error: Explicit valence for atom # 6 C, 6, is greater than permitted
Skipping molecule at index 140 due to error: Explicit valence for atom # 1 C, 6, is greater than permitted
Skipping molecule at index 141 due to error: Explicit valence for atom # 1 C, 6, is greater than permitted
Skipping molecule at index 142 due to error: Explicit valence for atom # 1 C, 6, is greater than permitted
Skipping molecule at index 144 due to error: Explicit valence for atom # 79 O, 3, is greater than permitted
Skipping molecule at index 147 due to error: Explicit valence for atom # 5 B, 4, is greater than permitted
Skipping molecule at index 148 due to error: Explicit valence for atom # 89 B, 4, is greater than permitted
Skipping molecule at index 149 due to error: Explicit valence for atom # 1 B, 4, is greater than permitted
Skipping molecule at index 150 due to error: Explicit valence for atom # 4 B, 4, is greater than permitted
Skipping molecule at index 151 due to error: Explicit valence for atom # 3 B, 5, is greater than permitted
Skipping molecule at index 152 due to error: Explicit valence for atom # 3 B, 5, is greater than permitted
Skipping molecule at index 153 due to error: Explicit valence for atom # 3 B, 5, is greater than permitted
Skipping molecule at index 154 due to error: Explicit valence for atom # 7 B, 5, is greater than permitted
Skipping molecule at index 155 due to error: Explicit valence for atom # 69 B, 5, is greater than permitted
Skipping molecule at index 156 due to error: Explicit valence for atom # 68 B, 4, is greater than permitted
Skipping molecule at index 157 due to error: Explicit valence for atom # 0 C, 6, is greater than permitted
Skipping molecule at index 158 due to error: Explicit valence for atom # 3 B, 6, is greater than permitted
Skipping molecule at index 159 due to error: Explicit valence for atom # 0 C, 6, is greater than permitted
Skipping molecule at index 160 due to error: Explicit valence for atom # 0 B, 6, is greater than permitted
Skipping molecule at index 161 due to error: Explicit valence for atom # 1 B, 5, is greater than permitted
Skipping molecule at index 162 due to error: Explicit valence for atom # 2 B, 4, is greater than permitted
Skipping molecule at index 163 due to error: Explicit valence for atom # 2 B, 4, is greater than permitted
Skipping molecule at index 164 due to error: Explicit valence for atom # 1 B, 4, is greater than permitted
Skipping molecule at index 165 due to error: Explicit valence for atom # 6 B, 4, is greater than permitted
Skipping molecule at index 166 due to error: Explicit valence for atom # 3 O, 3, is greater than permitted
Skipping molecule at index 167 due to error: Explicit valence for atom # 4 C, 6, is greater than permitted
Skipping molecule at index 168 due to error: Explicit valence for atom # 5 B, 4, is greater than permitted
Skipping molecule at index 169 due to error: Explicit valence for atom # 103 B, 4, is greater than permitted
Skipping molecule at index 170 due to error: Explicit valence for atom # 3 B, 4, is greater than permitted
Skipping molecule at index 171 due to error: Explicit valence for atom # 4 B, 4, is greater than permitted
Skipping molecule at index 172 due to error: Explicit valence for atom # 1 B, 6, is greater than permitted
Skipping molecule at index 173 due to error: Explicit valence for atom # 1 B, 6, is greater than permitted
Skipping molecule at index 174 due to error: Explicit valence for atom # 2 B, 6, is greater than permitted
Skipping molecule at index 175 due to error: Explicit valence for atom # 3 B, 5, is greater than permitted
Skipping molecule at index 177 due to error: Explicit valence for atom # 14 N, 4, is greater than permitted
Skipping molecule at index 178 due to error: Explicit valence for atom # 0 B, 6, is greater than permitted
Skipping molecule at index 179 due to error: Explicit valence for atom # 2 O, 3, is greater than permitted
Skipping molecule at index 180 due to error: Explicit valence for atom # 81 B, 4, is greater than permitted
Skipping molecule at index 181 due to error: Explicit valence for atom # 19 B, 6, is greater than permitted
Skipping molecule at index 182 due to error: Explicit valence for atom # 20 B, 6, is greater than permitted
Skipping molecule at index 183 due to error: Explicit valence for atom # 7 B, 6, is greater than permitted
Skipping molecule at index 186 due to error: Explicit valence for atom # 1 C, 5, is greater than permitted
Skipping molecule at index 187 due to error: Explicit valence for atom # 1 C, 5, is greater than permitted
Skipping molecule at index 188 due to error: Explicit valence for atom # 1 C, 5, is greater than permitted
Skipping molecule at index 189 due to error: Explicit valence for atom # 8 C, 5, is greater than permitted
Skipping molecule at index 190 due to error: Explicit valence for atom # 8 C, 5, is greater than permitted
Skipping molecule at index 191 due to error: Explicit valence for atom # 6 O, 3, is greater than permitted
Skipping molecule at index 192 due to error: Explicit valence for atom # 6 O, 3, is greater than permitted
Skipping molecule at index 193 due to error: Explicit valence for atom # 7 B, 4, is greater than permitted
Skipping molecule at index 194 due to error: Explicit valence for atom # 2 O, 3, is greater than permitted
Skipping molecule at index 195 due to error: Explicit valence for atom # 1 C, 6, is greater than permitted
Skipping molecule at index 196 due to error: Explicit valence for atom # 2 O, 3, is greater than permitted
Skipping molecule at index 198 due to error: Explicit valence for atom # 77 B, 4, is greater than permitted
Skipping molecule at index 199 due to error: Explicit valence for atom # 52 B, 4, is greater than permitted
Skipping molecule at index 201 due to error: Explicit valence for atom # 123 B, 5, is greater than permitted
Skipping molecule at index 202 due to error: Explicit valence for atom # 12 B, 4, is greater than permitted
Skipping molecule at index 203 due to error: Explicit valence for atom # 15 C, 6, is greater than permitted
Skipping molecule at index 207 due to error: Explicit valence for atom # 3 B, 6, is greater than permitted
Skipping molecule at index 208 due to error: Explicit valence for atom # 7 B, 5, is greater than permitted
Skipping molecule at index 209 due to error: Explicit valence for atom # 3 N, 4, is greater than permitted
Skipping molecule at index 210 due to error: Explicit valence for atom # 2 N, 4, is greater than permitted
Skipping molecule at index 211 due to error: Explicit valence for atom # 1 B, 6, is greater than permitted
Skipping molecule at index 212 due to error: Explicit valence for atom # 4 B, 4, is greater than permitted
Skipping molecule at index 213 due to error: Explicit valence for atom # 50 N, 4, is greater than permitted
Skipping molecule at index 214 due to error: Explicit valence for atom # 4 N, 4, is greater than permitted
Skipping molecule at index 215 due to error: Explicit valence for atom # 4 N, 4, is greater than permitted
Skipping molecule at index 217 due to error: Explicit valence for atom # 4 C, 5, is greater than permitted
Skipping molecule at index 218 due to error: Explicit valence for atom # 28 B, 11, is greater than permitted
Skipping molecule at index 219 due to error: Explicit valence for atom # 2 Cl, 2, is greater than permitted
Skipping molecule at index 220 due to error: Explicit valence for atom # 5 Cl, 2, is greater than permitted
Skipping molecule at index 221 due to error: Explicit valence for atom # 40 B, 5, is greater than permitted
Skipping molecule at index 223 due to error: Explicit valence for atom # 62 B, 5, is greater than permitted
Skipping molecule at index 224 due to error: Explicit valence for atom # 2 B, 4, is greater than permitted
Skipping molecule at index 225 due to error: Explicit valence for atom # 5 O, 3, is greater than permitted
Skipping molecule at index 226 due to error: Explicit valence for atom # 8 B, 5, is greater than permitted
Skipping molecule at index 227 due to error: Explicit valence for atom # 1 B, 6, is greater than permitted
Skipping molecule at index 228 due to error: Explicit valence for atom # 8 B, 6, is greater than permitted
Skipping molecule at index 230 due to error: Explicit valence for atom # 2 B, 6, is greater than permitted
Skipping molecule at index 233 due to error: Explicit valence for atom # 10 N, 4, is greater than permitted
Skipping molecule at index 234 due to error: Explicit valence for atom # 6 C, 5, is greater than permitted
Skipping molecule at index 235 due to error: Explicit valence for atom # 6 C, 5, is greater than permitted
Skipping molecule at index 236 due to error: Explicit valence for atom # 2 H, 2, is greater than permitted
Skipping molecule at index 237 due to error: Explicit valence for atom # 7 N, 4, is greater than permitted
Skipping molecule at index 238 due to error: Explicit valence for atom # 8 B, 4, is greater than permitted
Skipping molecule at index 239 due to error: Explicit valence for atom # 41 B, 4, is greater than permitted
Skipping molecule at index 240 due to error: Explicit valence for atom # 1 Cl, 2, is greater than permitted
Skipping molecule at index 241 due to error: Explicit valence for atom # 8 B, 4, is greater than permitted
Skipping molecule at index 246 due to error: Explicit valence for atom # 3 B, 5, is greater than permitted
Skipping molecule at index 247 due to error: Explicit valence for atom # 5 O, 3, is greater than permitted
Skipping molecule at index 248 due to error: Explicit valence for atom # 3 O, 3, is greater than permitted
Skipping molecule at index 249 due to error: Explicit valence for atom # 26 C, 5, is greater than permitted
Skipping molecule at index 250 due to error: Explicit valence for atom # 10 C, 5, is greater than permitted
Skipping molecule at index 251 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 252 due to error: Explicit valence for atom # 2 B, 4, is greater than permitted
Skipping molecule at index 253 due to error: Explicit valence for atom # 1 B, 4, is greater than permitted
Skipping molecule at index 254 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 255 due to error: Explicit valence for atom # 1 B, 4, is greater than permitted
Skipping molecule at index 256 due to error: Explicit valence for atom # 11 O, 3, is greater than permitted
Skipping molecule at index 257 due to error: Explicit valence for atom # 6 C, 5, is greater than permitted
Skipping molecule at index 258 due to error: Explicit valence for atom # 3 C, 4, is greater than permitted
Skipping molecule at index 259 due to error: Explicit valence for atom # 7 B, 4, is greater than permitted
Skipping molecule at index 260 due to error: Explicit valence for atom # 1 B, 5, is greater than permitted
Skipping molecule at index 261 due to error: Explicit valence for atom # 1 B, 5, is greater than permitted
Skipping molecule at index 262 due to error: Explicit valence for atom # 4 C, 6, is greater than permitted
Skipping molecule at index 263 due to error: Explicit valence for atom # 4 C, 6, is greater than permitted
Skipping molecule at index 264 due to error: Explicit valence for atom # 30 B, 5, is greater than permitted
Skipping molecule at index 265 due to error: Explicit valence for atom # 3 O, 4, is greater than permitted
Skipping molecule at index 266 due to error: Explicit valence for atom # 4 O, 4, is greater than permitted
Skipping molecule at index 268 due to error: Explicit valence for atom # 8 C, 6, is greater than permitted
Skipping molecule at index 269 due to error: Explicit valence for atom # 4 C, 6, is greater than permitted
Skipping molecule at index 270 due to error: Explicit valence for atom # 6 C, 6, is greater than permitted
Skipping molecule at index 271 due to error: Explicit valence for atom # 4 C, 6, is greater than permitted
Skipping molecule at index 272 due to error: Explicit valence for atom # 8 C, 6, is greater than permitted
Skipping molecule at index 273 due to error: Explicit valence for atom # 84 B, 4, is greater than permitted
Skipping molecule at index 274 due to error: Explicit valence for atom # 94 B, 4, is greater than permitted
Skipping molecule at index 275 due to error: Explicit valence for atom # 64 B, 4, is greater than permitted
Skipping molecule at index 276 due to error: Explicit valence for atom # 74 B, 4, is greater than permitted
Skipping molecule at index 278 due to error: Explicit valence for atom # 48 B, 4, is greater than permitted
Skipping molecule at index 279 due to error: Explicit valence for atom # 61 B, 4, is greater than permitted
Skipping molecule at index 280 due to error: Explicit valence for atom # 2 B, 5, is greater than permitted
Skipping molecule at index 281 due to error: Explicit valence for atom # 3 O, 3, is greater than permitted
Skipping molecule at index 282 due to error: Explicit valence for atom # 6 B, 4, is greater than permitted
Skipping molecule at index 283 due to error: Explicit valence for atom # 4 C, 6, is greater than permitted

[10:29:05] Explicit valence for atom # 4 C, 6, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:05] Explicit valence for atom # 30 B, 5, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 3 O, 4, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 4 O, 4, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:05] Explicit valence for atom # 8 C, 6, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:05] Explicit valence for atom # 4 C, 6, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:05] Explicit valence for atom # 6 C, 6, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:05] Explicit valence for atom # 4 C, 6, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:05] Explicit valence for atom # 8 C, 6, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 84 B, 4, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 94 B, 4, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 64 B, 4, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 74 B, 4, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 48 B, 4, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 61 B, 4, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:05] Explicit valence for atom # 2 B, 5, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:05] Explicit valence for atom # 3 O, 3, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 6 B, 4, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:05] Explicit valence for atom # 4 C, 6, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:05] Explicit valence for atom # 13 C, 7, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 85 H, 2, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 6 B, 4, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 184 B, 4, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 11 B, 4, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:05] Explicit valence for atom # 123 B, 5, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:05] Explicit valence for atom # 4 C, 6, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:05] Explicit valence for atom # 3 C, 6, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:05] Explicit valence for atom # 3 C, 6, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:05] Explicit valence for atom # 4 C, 6, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 5 B, 4, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 111 B, 4, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:05] Explicit valence for atom # 1 C, 5, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:05] Explicit valence for atom # 1 C, 6, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 64 B, 4, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 64 B, 4, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:05] Explicit valence for atom # 5 C, 6, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 3 O, 3, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 4 B, 4, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:05] Explicit valence for atom # 7 C, 5, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:05] Explicit valence for atom # 0 C, 5, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:05] Explicit valence for atom # 0 C, 5, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 236 B, 4, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:05] Explicit valence for atom # 3 O, 3, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:05] Explicit valence for atom # 38 B, 6, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 3 O, 3, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 3 O, 3, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 3 O, 3, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 3 O, 3, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:05] Explicit valence for atom # 12 C, 5, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:05] Explicit valence for atom # 7 B, 6, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 3 O, 3, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 3 O, 3, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:05] Explicit valence for atom # 7 N, 4, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:05] Explicit valence for atom # 5 N, 4, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:05] Explicit valence for atom # 6 N, 4, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:05] Explicit valence for atom # 0 B, 6, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 7 N, 4, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 55 B, 4, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 53 B, 4, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:05] Explicit valence for atom # 1 C, 6, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 2 B, 4, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 7 B, 4, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 7 B, 4, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 137 B, 4, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Explicit valence for atom # 95 B, 4, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:05] Explicit valence for atom # 3 C, 6, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:05] Explicit valence for atom # 3 C, 6, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:05] Explicit valence for atom # 3 B, 5, is greater than permitted
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:05] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:06] Explicit valence for atom # 3 C, 6, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:06] Explicit valence for atom # 6 C, 6, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Explicit valence for atom # 10 O, 3, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Explicit valence for atom # 4 O, 3, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Explicit valence for atom # 8 O, 3, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Explicit valence for atom # 8 O, 3, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Explicit valence for atom # 105 B, 4, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.

Skipping molecule at index 284 due to error: Explicit valence for atom # 13 C, 7, is greater than permitted
Skipping molecule at index 287 due to error: Explicit valence for atom # 85 H, 2, is greater than permitted
Skipping molecule at index 290 due to error: Explicit valence for atom # 6 B, 4, is greater than permitted
Skipping molecule at index 291 due to error: Explicit valence for atom # 184 B, 4, is greater than permitted
Skipping molecule at index 292 due to error: Explicit valence for atom # 11 B, 4, is greater than permitted
Skipping molecule at index 300 due to error: Explicit valence for atom # 123 B, 5, is greater than permitted
Skipping molecule at index 301 due to error: Explicit valence for atom # 4 C, 6, is greater than permitted
Skipping molecule at index 302 due to error: Explicit valence for atom # 3 C, 6, is greater than permitted
Skipping molecule at index 303 due to error: Explicit valence for atom # 3 C, 6, is greater than permitted
Skipping molecule at index 304 due to error: Explicit valence for atom # 4 C, 6, is greater than permitted
Skipping molecule at index 305 due to error: Explicit valence for atom # 5 B, 4, is greater than permitted
Skipping molecule at index 306 due to error: Explicit valence for atom # 111 B, 4, is greater than permitted
Skipping molecule at index 307 due to error: Explicit valence for atom # 1 C, 5, is greater than permitted
Skipping molecule at index 308 due to error: Explicit valence for atom # 1 C, 6, is greater than permitted
Skipping molecule at index 309 due to error: Explicit valence for atom # 64 B, 4, is greater than permitted
Skipping molecule at index 310 due to error: Explicit valence for atom # 64 B, 4, is greater than permitted
Skipping molecule at index 311 due to error: Explicit valence for atom # 5 C, 6, is greater than permitted
Skipping molecule at index 312 due to error: Explicit valence for atom # 3 O, 3, is greater than permitted
Skipping molecule at index 313 due to error: Explicit valence for atom # 4 B, 4, is greater than permitted
Skipping molecule at index 314 due to error: Explicit valence for atom # 7 C, 5, is greater than permitted
Skipping molecule at index 315 due to error: Explicit valence for atom # 0 C, 5, is greater than permitted
Skipping molecule at index 316 due to error: Explicit valence for atom # 0 C, 5, is greater than permitted
Skipping molecule at index 317 due to error: Explicit valence for atom # 236 B, 4, is greater than permitted
Skipping molecule at index 318 due to error: Explicit valence for atom # 3 O, 3, is greater than permitted
Skipping molecule at index 319 due to error: Explicit valence for atom # 38 B, 6, is greater than permitted
Skipping molecule at index 321 due to error: Explicit valence for atom # 3 O, 3, is greater than permitted
Skipping molecule at index 322 due to error: Explicit valence for atom # 3 O, 3, is greater than permitted
Skipping molecule at index 323 due to error: Explicit valence for atom # 3 O, 3, is greater than permitted
Skipping molecule at index 324 due to error: Explicit valence for atom # 3 O, 3, is greater than permitted
Skipping molecule at index 325 due to error: Explicit valence for atom # 12 C, 5, is greater than permitted
Skipping molecule at index 326 due to error: Explicit valence for atom # 7 B, 6, is greater than permitted
Skipping molecule at index 327 due to error: Explicit valence for atom # 3 O, 3, is greater than permitted
Skipping molecule at index 328 due to error: Explicit valence for atom # 3 O, 3, is greater than permitted
Skipping molecule at index 329 due to error: Explicit valence for atom # 7 N, 4, is greater than permitted
Skipping molecule at index 330 due to error: Explicit valence for atom # 5 N, 4, is greater than permitted
Skipping molecule at index 331 due to error: Explicit valence for atom # 6 N, 4, is greater than permitted
Skipping molecule at index 332 due to error: Explicit valence for atom # 0 B, 6, is greater than permitted
Skipping molecule at index 333 due to error: Explicit valence for atom # 7 N, 4, is greater than permitted
Skipping molecule at index 334 due to error: Explicit valence for atom # 55 B, 4, is greater than permitted
Skipping molecule at index 335 due to error: Explicit valence for atom # 53 B, 4, is greater than permitted
Skipping molecule at index 337 due to error: Explicit valence for atom # 1 C, 6, is greater than permitted
Skipping molecule at index 338 due to error: Explicit valence for atom # 2 B, 4, is greater than permitted
Skipping molecule at index 340 due to error: Explicit valence for atom # 7 B, 4, is greater than permitted
Skipping molecule at index 341 due to error: Explicit valence for atom # 7 B, 4, is greater than permitted
Skipping molecule at index 342 due to error: Explicit valence for atom # 137 B, 4, is greater than permitted
Skipping molecule at index 343 due to error: Explicit valence for atom # 95 B, 4, is greater than permitted
Skipping molecule at index 344 due to error: Explicit valence for atom # 3 C, 6, is greater than permitted
Skipping molecule at index 345 due to error: Explicit valence for atom # 3 C, 6, is greater than permitted
Skipping molecule at index 346 due to error: Explicit valence for atom # 3 B, 5, is greater than permitted
Skipping molecule at index 351 due to error: Explicit valence for atom # 3 C, 6, is greater than permitted
Skipping molecule at index 352 due to error: Explicit valence for atom # 6 C, 6, is greater than permitted
Skipping molecule at index 353 due to error: Explicit valence for atom # 10 O, 3, is greater than permitted
Skipping molecule at index 354 due to error: Explicit valence for atom # 4 O, 3, is greater than permitted
Skipping molecule at index 355 due to error: Explicit valence for atom # 8 O, 3, is greater than permitted
Skipping molecule at index 356 due to error: Explicit valence for atom # 8 O, 3, is greater than permitted
Skipping molecule at index 357 due to error: Explicit valence for atom # 105 B, 4, is greater than permitted
Skipping molecule at index 358 due to error: Explicit valence for atom # 12 O, 3, is greater than permitted
Skipping molecule at index 359 due to error: Explicit valence for atom # 20 O, 3, is greater than permitted
Skipping molecule at index 362 due to error: Explicit valence for atom # 6 C, 6, is greater than permitted
Skipping molecule at index 363 due to error: Explicit valence for atom # 6 C, 6, is greater than permitted
Skipping molecule at index 364 due to error: Explicit valence for atom # 5 C, 6, is greater than permitted
Skipping molecule at index 365 due to error: Explicit valence for atom # 17 B, 4, is greater than permitted
Skipping molecule at index 369 due to error: Explicit valence for atom # 6 C, 5, is greater than permitted
Skipping molecule at index 370 due to error: Explicit valence for atom # 17 O, 3, is greater than permitted
Skipping molecule at index 371 due to error: Explicit valence for atom # 1 B, 4, is greater than permitted
Skipping molecule at index 372 due to error: Explicit valence for atom # 1 C, 5, is greater than permitted
Skipping molecule at index 373 due to error: Explicit valence for atom # 0 C, 5, is greater than permitted
Skipping molecule at index 374 due to error: Explicit valence for atom # 0 C, 5, is greater than permitted
Skipping molecule at index 375 due to error: Explicit valence for atom # 0 C, 5, is greater than permitted
Skipping molecule at index 376 due to error: Explicit valence for atom # 1 C, 5, is greater than permitted
Skipping molecule at index 377 due to error: Explicit valence for atom # 3 C, 6, is greater than permitted
Skipping molecule at index 378 due to error: Explicit valence for atom # 7 C, 6, is greater than permitted
Skipping molecule at index 379 due to error: Explicit valence for atom # 0 B, 6, is greater than permitted
Skipping molecule at index 380 due to error: Explicit valence for atom # 7 C, 6, is greater than permitted
Skipping molecule at index 381 due to error: Explicit valence for atom # 14 C, 6, is greater than permitted
Skipping molecule at index 382 due to error: Explicit valence for atom # 5 B, 6, is greater than permitted
Skipping molecule at index 383 due to error: Explicit valence for atom # 3 B, 4, is greater than permitted
Skipping molecule at index 384 due to error: Explicit valence for atom # 2 B, 4, is greater than permitted
Skipping molecule at index 385 due to error: Explicit valence for atom # 3 B, 4, is greater than permitted
Skipping molecule at index 386 due to error: Explicit valence for atom # 6 C, 6, is greater than permitted
Skipping molecule at index 387 due to error: Explicit valence for atom # 7 C, 6, is greater than permitted
Skipping molecule at index 388 due to error: Explicit valence for atom # 4 C, 6, is greater than permitted
Skipping molecule at index 389 due to error: Explicit valence for atom # 1 H, 2, is greater than permitted
Skipping molecule at index 390 due to error: Explicit valence for atom # 0 C, 6, is greater than permitted
Skipping molecule at index 392 due to error: Explicit valence for atom # 2 B, 4, is greater than permitted
Skipping molecule at index 393 due to error: Explicit valence for atom # 3 B, 4, is greater than permitted
Skipping molecule at index 394 due to error: Explicit valence for atom # 7 O, 3, is greater than permitted
Skipping molecule at index 396 due to error: Explicit valence for atom # 9 O, 3, is greater than permitted
Skipping molecule at index 398 due to error: Explicit valence for atom # 14 C, 5, is greater than permitted
Skipping molecule at index 399 due to error: Explicit valence for atom # 2 O, 3, is greater than permitted
Skipping molecule at index 400 due to error: Explicit valence for atom # 119 B, 4, is greater than permitted
Skipping molecule at index 401 due to error: Explicit valence for atom # 4 B, 8, is greater than permitted
Skipping molecule at index 402 due to error: Explicit valence for atom # 62 B, 6, is greater than permitted
Skipping molecule at index 403 due to error: Explicit valence for atom # 3 B, 5, is greater than permitted
Skipping molecule at index 404 due to error: Explicit valence for atom # 3 B, 4, is greater than permitted
Skipping molecule at index 405 due to error: Explicit valence for atom # 6 B, 4, is greater than permitted
Skipping molecule at index 406 due to error: Explicit valence for atom # 4 O, 3, is greater than permitted
Skipping molecule at index 407 due to error: Explicit valence for atom # 1 H, 2, is greater than permitted
Skipping molecule at index 408 due to error: Explicit valence for atom # 7 H, 2, is greater than permitted
Skipping molecule at index 409 due to error: Explicit valence for atom # 5 O, 3, is greater than permitted
Skipping molecule at index 410 due to error: Explicit valence for atom # 0 C, 6, is greater than permitted
Skipping molecule at index 411 due to error: Explicit valence for atom # 22 O, 3, is greater than permitted
Skipping molecule at index 412 due to error: Explicit valence for atom # 5 B, 5, is greater than permitted
Skipping molecule at index 415 due to error: Explicit valence for atom # 42 H, 2, is greater than permitted
Skipping molecule at index 416 due to error: Explicit valence for atom # 131 H, 2, is greater than permitted
Skipping molecule at index 418 due to error: Explicit valence for atom # 4 O, 3, is greater than permitted
Skipping molecule at index 419 due to error: Explicit valence for atom # 3 C, 6, is greater than permitted
Skipping molecule at index 421 due to error: Explicit valence for atom # 3 O, 3, is greater than permitted
Skipping molecule at index 422 due to error: Explicit valence for atom # 7 O, 3, is greater than permitted

[10:29:06] Explicit valence for atom # 6 C, 6, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:06] Explicit valence for atom # 5 C, 6, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Explicit valence for atom # 17 B, 4, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:06] Explicit valence for atom # 6 C, 5, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Explicit valence for atom # 17 O, 3, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Explicit valence for atom # 1 B, 4, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:06] Explicit valence for atom # 1 C, 5, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:06] Explicit valence for atom # 0 C, 5, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:06] Explicit valence for atom # 0 C, 5, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:06] Explicit valence for atom # 0 C, 5, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:06] Explicit valence for atom # 1 C, 5, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:06] Explicit valence for atom # 3 C, 6, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:06] Explicit valence for atom # 7 C, 6, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:06] Explicit valence for atom # 0 B, 6, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:06] Explicit valence for atom # 7 C, 6, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:06] Explicit valence for atom # 14 C, 6, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:06] Explicit valence for atom # 5 B, 6, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Explicit valence for atom # 3 B, 4, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Explicit valence for atom # 2 B, 4, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Explicit valence for atom # 3 B, 4, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:06] Explicit valence for atom # 6 C, 6, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:06] Explicit valence for atom # 7 C, 6, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:06] Explicit valence for atom # 4 C, 6, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Explicit valence for atom # 1 H, 2, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:06] Explicit valence for atom # 0 C, 6, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Explicit valence for atom # 2 B, 4, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Explicit valence for atom # 3 B, 4, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:06] Explicit valence for atom # 7 O, 3, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:06] Explicit valence for atom # 9 O, 3, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:06] Explicit valence for atom # 14 C, 5, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:06] Explicit valence for atom # 2 O, 3, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Explicit valence for atom # 119 B, 4, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:06] Explicit valence for atom # 4 B, 8, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:06] Explicit valence for atom # 62 B, 6, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Explicit valence for atom # 3 B, 5, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Explicit valence for atom # 3 B, 4, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Explicit valence for atom # 6 B, 4, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:06] Explicit valence for atom # 4 O, 3, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:06] Explicit valence for atom # 1 H, 2, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:06] Explicit valence for atom # 7 H, 2, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:06] Explicit valence for atom # 5 O, 3, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:06] Explicit valence for atom # 0 C, 6, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Explicit valence for atom # 22 O, 3, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Explicit valence for atom # 5 B, 5, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Explicit valence for atom # 42 H, 2, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Explicit valence for atom # 131 H, 2, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:06] Explicit valence for atom # 4 O, 3, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:06] Explicit valence for atom # 3 C, 6, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Explicit valence for atom # 3 O, 3, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Explicit valence for atom # 7 O, 3, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Explicit valence for atom # 122 H, 2, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Explicit valence for atom # 122 H, 2, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Explicit valence for atom # 1 H, 2, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:06] Explicit valence for atom # 4 C, 11, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:06] Explicit valence for atom # 4 C, 11, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:06] Explicit valence for atom # 6 C, 6, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:06] Explicit valence for atom # 6 O, 3, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Explicit valence for atom # 81 B, 4, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Explicit valence for atom # 42 B, 4, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Explicit valence for atom # 19 B, 4, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Explicit valence for atom # 81 H, 2, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Explicit valence for atom # 125 H, 2, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Explicit valence for atom # 2 B, 4, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:06] Explicit valence for atom # 1 C, 5, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:06] Explicit valence for atom # 1 C, 5, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Explicit valence for atom # 0 Cl, 3, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:06] Explicit valence for atom # 10 B, 6, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:06] Explicit valence for atom # 3 B, 6, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:06] Explicit valence for atom # 4 C, 6, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:06] Explicit valence for atom # 4 C, 6, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:06] Explicit valence for atom # 1 Sn, 6, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:06] Explicit valence for atom # 0 Sn, 5, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:06] Explicit valence for atom # 0 Sn, 6, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:06] Explicit valence for atom # 0 Sn, 5, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:06] Explicit valence for atom # 0 Sn, 7, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.

Skipping molecule at index 423 due to error: Explicit valence for atom # 122 H, 2, is greater than permitted
Skipping molecule at index 424 due to error: Explicit valence for atom # 122 H, 2, is greater than permitted
Skipping molecule at index 425 due to error: Explicit valence for atom # 1 H, 2, is greater than permitted
Skipping molecule at index 426 due to error: Explicit valence for atom # 4 C, 11, is greater than permitted
Skipping molecule at index 427 due to error: Explicit valence for atom # 4 C, 11, is greater than permitted
Skipping molecule at index 428 due to error: Explicit valence for atom # 6 C, 6, is greater than permitted
Skipping molecule at index 429 due to error: Explicit valence for atom # 6 O, 3, is greater than permitted
Skipping molecule at index 430 due to error: Explicit valence for atom # 81 B, 4, is greater than permitted
Skipping molecule at index 431 due to error: Explicit valence for atom # 42 B, 4, is greater than permitted
Skipping molecule at index 432 due to error: Explicit valence for atom # 19 B, 4, is greater than permitted
Skipping molecule at index 433 due to error: Explicit valence for atom # 81 H, 2, is greater than permitted
Skipping molecule at index 434 due to error: Explicit valence for atom # 125 H, 2, is greater than permitted
Skipping molecule at index 435 due to error: Explicit valence for atom # 2 B, 4, is greater than permitted
Skipping molecule at index 437 due to error: Explicit valence for atom # 1 C, 5, is greater than permitted
Skipping molecule at index 438 due to error: Explicit valence for atom # 1 C, 5, is greater than permitted
Skipping molecule at index 439 due to error: Explicit valence for atom # 0 Cl, 3, is greater than permitted
Skipping molecule at index 440 due to error: Explicit valence for atom # 10 B, 6, is greater than permitted
Skipping molecule at index 441 due to error: Explicit valence for atom # 3 B, 6, is greater than permitted
Skipping molecule at index 442 due to error: Explicit valence for atom # 4 C, 6, is greater than permitted
Skipping molecule at index 443 due to error: Explicit valence for atom # 4 C, 6, is greater than permitted
Skipping molecule at index 444 due to error: Explicit valence for atom # 1 Sn, 6, is greater than permitted
Skipping molecule at index 445 due to error: Explicit valence for atom # 0 Sn, 5, is greater than permitted
Skipping molecule at index 446 due to error: Explicit valence for atom # 0 Sn, 6, is greater than permitted
Skipping molecule at index 447 due to error: Explicit valence for atom # 0 Sn, 5, is greater than permitted
Skipping molecule at index 448 due to error: Explicit valence for atom # 0 Sn, 7, is greater than permitted
Skipping molecule at index 449 due to error: Explicit valence for atom # 0 Sn, 6, is greater than permitted
Skipping molecule at index 450 due to error: Explicit valence for atom # 14 B, 4, is greater than permitted
Skipping molecule at index 451 due to error: Explicit valence for atom # 8 B, 4, is greater than permitted
Skipping molecule at index 452 due to error: Explicit valence for atom # 1 H, 2, is greater than permitted
Skipping molecule at index 453 due to error: Explicit valence for atom # 4 O, 3, is greater than permitted
Skipping molecule at index 454 due to error: Explicit valence for atom # 4 O, 3, is greater than permitted
Skipping molecule at index 456 due to error: Explicit valence for atom # 18 H, 2, is greater than permitted
Skipping molecule at index 457 due to error: Explicit valence for atom # 1 Ge, 6, is greater than permitted
Skipping molecule at index 458 due to error: Explicit valence for atom # 0 B, 6, is greater than permitted
Skipping molecule at index 459 due to error: Explicit valence for atom # 5 B, 6, is greater than permitted
Skipping molecule at index 460 due to error: Explicit valence for atom # 0 Sn, 7, is greater than permitted
Skipping molecule at index 461 due to error: Explicit valence for atom # 0 Sn, 7, is greater than permitted
Skipping molecule at index 462 due to error: Explicit valence for atom # 2 O, 3, is greater than permitted
Skipping molecule at index 463 due to error: Explicit valence for atom # 124 B, 4, is greater than permitted
Skipping molecule at index 464 due to error: Explicit valence for atom # 6 B, 4, is greater than permitted
Skipping molecule at index 465 due to error: Explicit valence for atom # 2 B, 6, is greater than permitted
Skipping molecule at index 469 due to error: Explicit valence for atom # 57 H, 2, is greater than permitted
Skipping molecule at index 470 due to error: Explicit valence for atom # 1 B, 4, is greater than permitted
Skipping molecule at index 471 due to error: Explicit valence for atom # 132 B, 4, is greater than permitted
Skipping molecule at index 472 due to error: Explicit valence for atom # 3 C, 6, is greater than permitted
Skipping molecule at index 473 due to error: Explicit valence for atom # 14 O, 3, is greater than permitted
Skipping molecule at index 474 due to error: Explicit valence for atom # 5 O, 3, is greater than permitted
Skipping molecule at index 475 due to error: Explicit valence for atom # 82 B, 4, is greater than permitted
Skipping molecule at index 476 due to error: Explicit valence for atom # 82 B, 4, is greater than permitted
Skipping molecule at index 477 due to error: Explicit valence for atom # 40 O, 3, is greater than permitted
Skipping molecule at index 478 due to error: Explicit valence for atom # 44 B, 6, is greater than permitted
Skipping molecule at index 479 due to error: Explicit valence for atom # 41 B, 6, is greater than permitted
Skipping molecule at index 480 due to error: Explicit valence for atom # 4 O, 3, is greater than permitted
Skipping molecule at index 481 due to error: Explicit valence for atom # 1 C, 6, is greater than permitted
Skipping molecule at index 482 due to error: Explicit valence for atom # 1 C, 5, is greater than permitted
Skipping molecule at index 483 due to error: Explicit valence for atom # 1 C, 5, is greater than permitted
Skipping molecule at index 484 due to error: Explicit valence for atom # 1 C, 5, is greater than permitted
Skipping molecule at index 485 due to error: Explicit valence for atom # 5 B, 5, is greater than permitted
Skipping molecule at index 486 due to error: Explicit valence for atom # 4 N, 4, is greater than permitted
Skipping molecule at index 489 due to error: Explicit valence for atom # 3 B, 4, is greater than permitted
Skipping molecule at index 490 due to error: Explicit valence for atom # 8 B, 4, is greater than permitted
Skipping molecule at index 491 due to error: Explicit valence for atom # 8 B, 4, is greater than permitted
Skipping molecule at index 492 due to error: Explicit valence for atom # 21 H, 3, is greater than permitted
Skipping molecule at index 493 due to error: Explicit valence for atom # 2 O, 3, is greater than permitted
Skipping molecule at index 494 due to error: Explicit valence for atom # 43 B, 4, is greater than permitted
Skipping molecule at index 501 due to error: Explicit valence for atom # 3 B, 4, is greater than permitted
Skipping molecule at index 502 due to error: Explicit valence for atom # 12 O, 3, is greater than permitted
Skipping molecule at index 503 due to error: Explicit valence for atom # 4 O, 3, is greater than permitted
Skipping molecule at index 504 due to error: Explicit valence for atom # 4 B, 6, is greater than permitted
Skipping molecule at index 505 due to error: Explicit valence for atom # 0 B, 6, is greater than permitted
Skipping molecule at index 506 due to error: Explicit valence for atom # 23 C, 6, is greater than permitted
Skipping molecule at index 507 due to error: Explicit valence for atom # 11 C, 6, is greater than permitted
Skipping molecule at index 508 due to error: Explicit valence for atom # 17 C, 6, is greater than permitted
Skipping molecule at index 511 due to error: Explicit valence for atom # 39 F, 2, is greater than permitted
Skipping molecule at index 512 due to error: Explicit valence for atom # 41 F, 2, is greater than permitted
Skipping molecule at index 513 due to error: Explicit valence for atom # 4 F, 2, is greater than permitted
Skipping molecule at index 514 due to error: Explicit valence for atom # 8 O, 3, is greater than permitted
Skipping molecule at index 515 due to error: Explicit valence for atom # 70 O, 3, is greater than permitted
Skipping molecule at index 516 due to error: Explicit valence for atom # 93 B, 6, is greater than permitted
Skipping molecule at index 517 due to error: Explicit valence for atom # 3 N, 4, is greater than permitted
Skipping molecule at index 518 due to error: Explicit valence for atom # 1 B, 4, is greater than permitted
Skipping molecule at index 519 due to error: Explicit valence for atom # 3 N, 4, is greater than permitted
Skipping molecule at index 520 due to error: Explicit valence for atom # 2 N, 4, is greater than permitted
Skipping molecule at index 521 due to error: Explicit valence for atom # 3 N, 4, is greater than permitted
Skipping molecule at index 522 due to error: Explicit valence for atom # 1 H, 2, is greater than permitted
Skipping molecule at index 523 due to error: Explicit valence for atom # 4 C, 6, is greater than permitted
Skipping molecule at index 524 due to error: Explicit valence for atom # 5 O, 3, is greater than permitted
Skipping molecule at index 525 due to error: Explicit valence for atom # 2 B, 4, is greater than permitted
Skipping molecule at index 526 due to error: Explicit valence for atom # 1 B, 4, is greater than permitted
Skipping molecule at index 527 due to error: Explicit valence for atom # 62 B, 4, is greater than permitted
Skipping molecule at index 528 due to error: Explicit valence for atom # 20 H, 2, is greater than permitted
Skipping molecule at index 529 due to error: Explicit valence for atom # 9 B, 6, is greater than permitted
Skipping molecule at index 530 due to error: Explicit valence for atom # 9 B, 6, is greater than permitted
Skipping molecule at index 531 due to error: Explicit valence for atom # 1 B, 4, is greater than permitted
Skipping molecule at index 532 due to error: Explicit valence for atom # 4 B, 4, is greater than permitted
Skipping molecule at index 535 due to error: Can't kekulize mol.  Unkekulized atoms: 13 15 17 19 21
Skipping molecule at index 536 due to error: Can't kekulize mol.  Unkekulized atoms: 4 6 8 10 12
Skipping molecule at index 546 due to error: Explicit valence for atom # 4 B, 4, is greater than permitted
Skipping molecule at index 553 due to error: Explicit valence for atom # 6 C, 5, is greater than permitted
Skipping molecule at index 554 due to error: Explicit valence for atom # 7 O, 3, is greater than permitted
Skipping molecule at index 556 due to error: Explicit valence for atom # 7 N, 4, is greater than permitted
Skipping molecule at index 557 due to error: Explicit valence for atom # 2 B, 5, is greater than permitted
Skipping molecule at index 558 due to error: Explicit valence for atom # 140 H, 2, is greater than permitted
Skipping molecule at index 559 due to error: Explicit valence for atom # 79 H, 2, is greater than permitted
Skipping molecule at index 560 due to error: Explicit valence for atom # 6 O, 3, is greater than permitted
Skipping molecule at index 561 due to error: Explicit valence for atom # 13 C, 6, is greater than permitted
Skipping molecule at index 562 due to error: Explicit valence for atom # 10 C, 6, is greater than permitted
Skipping molecule at index 563 due to error: Explicit valence for atom # 47 B, 5, is greater than permitted
Skipping molecule at index 564 due to error: Explicit valence for atom # 6 B, 7, is greater than permitted
Skipping molecule at index 565 due to error: Explicit valence for atom # 2 O, 3, is greater than permitted
Skipping molecule at index 566 due to error: Explicit valence for atom # 7 O, 3, is greater than permitted

[10:29:06] Explicit valence for atom # 41 F, 2, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Explicit valence for atom # 4 F, 2, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Explicit valence for atom # 8 O, 3, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:06] Explicit valence for atom # 70 O, 3, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:06] Explicit valence for atom # 93 B, 6, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Explicit valence for atom # 3 N, 4, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Explicit valence for atom # 1 B, 4, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Explicit valence for atom # 3 N, 4, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Explicit valence for atom # 2 N, 4, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Explicit valence for atom # 3 N, 4, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:06] Explicit valence for atom # 1 H, 2, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:06] Explicit valence for atom # 4 C, 6, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:06] Explicit valence for atom # 5 O, 3, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Explicit valence for atom # 2 B, 4, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Explicit valence for atom # 1 B, 4, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Explicit valence for atom # 62 B, 4, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:06] Explicit valence for atom # 20 H, 2, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:06] Explicit valence for atom # 9 B, 6, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:06] Explicit valence for atom # 9 B, 6, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Explicit valence for atom # 1 B, 4, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Explicit valence for atom # 4 B, 4, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Can't kekulize mol.  Unkekulized atoms: 13 15 17 19 21
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Can't kekulize mol.  Unkekulized atoms: 4 6 8 10 12
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Explicit valence for atom # 4 B, 4, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Explicit valence for atom # 6 C, 5, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Explicit valence for atom # 7 O, 3, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Explicit valence for atom # 7 N, 4, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Explicit valence for atom # 2 B, 5, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Explicit valence for atom # 140 H, 2, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Explicit valence for atom # 79 H, 2, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Explicit valence for atom # 6 O, 3, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:06] Explicit valence for atom # 13 C, 6, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:06] Explicit valence for atom # 10 C, 6, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:06] Explicit valence for atom # 47 B, 5, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:06] Explicit valence for atom # 6 B, 7, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Explicit valence for atom # 2 O, 3, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Explicit valence for atom # 7 O, 3, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Explicit valence for atom # 42 B, 4, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Explicit valence for atom # 11 B, 4, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:06] Explicit valence for atom # 11 C, 5, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Explicit valence for atom # 53 H, 2, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Explicit valence for atom # 2 B, 4, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Explicit valence for atom # 3 C, 6, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Explicit valence for atom # 55 B, 4, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Explicit valence for atom # 43 B, 4, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Explicit valence for atom # 2 B, 4, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Explicit valence for atom # 2 B, 4, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Explicit valence for atom # 2 B, 4, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Explicit valence for atom # 3 H, 2, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Explicit valence for atom # 4 H, 2, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Explicit valence for atom # 2 H, 2, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Explicit valence for atom # 3 H, 2, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Explicit valence for atom # 1 B, 4, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Explicit valence for atom # 1 B, 4, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Explicit valence for atom # 1 B, 4, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Explicit valence for atom # 4 O, 3, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Explicit valence for atom # 7 B, 4, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Explicit valence for atom # 7 B, 4, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:06] Explicit valence for atom # 4 C, 6, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:06] Explicit valence for atom # 20 B, 6, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:06] Explicit valence for atom # 5 B, 6, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Explicit valence for atom # 0 B, 6, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Explicit valence for atom # 5 B, 4, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Can't kekulize mol.  Unkekulized atoms: 0 2 4 6 8
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:06] Explicit valence for atom # 10 B, 6, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Explicit valence for atom # 1 B, 4, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:06] Explicit valence for atom # 2 C, 5, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Explicit valence for atom # 7 B, 4, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Explicit valence for atom # 3 O, 3, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Explicit valence for atom # 5 B, 4, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Explicit valence for atom # 4 O, 3, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Explicit valence for atom # 4 O, 3, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Explicit valence for atom # 2 B, 4, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:06] Explicit valence for atom # 8 B, 6, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:06] Explicit valence for atom # 4 C, 6, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Can't kekulize mol.  Unkekulized atoms: 0 1 3 5 7 8 9 11 13 15
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Can't kekulize mol.  Unkekulized atoms: 3 4 6 7 9
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:06] Explicit valence for atom # 3 O, 3, is greater than permitted

Skipping molecule at index 567 due to error: Explicit valence for atom # 42 B, 4, is greater than permitted
Skipping molecule at index 569 due to error: Explicit valence for atom # 11 B, 4, is greater than permitted
Skipping molecule at index 570 due to error: Explicit valence for atom # 11 C, 5, is greater than permitted
Skipping molecule at index 571 due to error: Explicit valence for atom # 53 H, 2, is greater than permitted
Skipping molecule at index 576 due to error: Explicit valence for atom # 2 B, 4, is greater than permitted
Skipping molecule at index 577 due to error: Explicit valence for atom # 3 C, 6, is greater than permitted
Skipping molecule at index 578 due to error: Explicit valence for atom # 55 B, 4, is greater than permitted
Skipping molecule at index 579 due to error: Explicit valence for atom # 43 B, 4, is greater than permitted
Skipping molecule at index 580 due to error: Explicit valence for atom # 2 B, 4, is greater than permitted
Skipping molecule at index 581 due to error: Explicit valence for atom # 2 B, 4, is greater than permitted
Skipping molecule at index 584 due to error: Explicit valence for atom # 2 B, 4, is greater than permitted
Skipping molecule at index 585 due to error: Explicit valence for atom # 3 H, 2, is greater than permitted
Skipping molecule at index 586 due to error: Explicit valence for atom # 4 H, 2, is greater than permitted
Skipping molecule at index 589 due to error: Explicit valence for atom # 2 H, 2, is greater than permitted
Skipping molecule at index 590 due to error: Explicit valence for atom # 3 H, 2, is greater than permitted
Skipping molecule at index 591 due to error: Explicit valence for atom # 1 B, 4, is greater than permitted
Skipping molecule at index 592 due to error: Explicit valence for atom # 1 B, 4, is greater than permitted
Skipping molecule at index 593 due to error: Explicit valence for atom # 1 B, 4, is greater than permitted
Skipping molecule at index 594 due to error: Explicit valence for atom # 4 O, 3, is greater than permitted
Skipping molecule at index 595 due to error: Explicit valence for atom # 7 B, 4, is greater than permitted
Skipping molecule at index 596 due to error: Explicit valence for atom # 7 B, 4, is greater than permitted
Skipping molecule at index 598 due to error: Explicit valence for atom # 4 C, 6, is greater than permitted
Skipping molecule at index 599 due to error: Explicit valence for atom # 20 B, 6, is greater than permitted
Skipping molecule at index 600 due to error: Explicit valence for atom # 5 B, 6, is greater than permitted
Skipping molecule at index 601 due to error: Explicit valence for atom # 0 B, 6, is greater than permitted
Skipping molecule at index 602 due to error: Explicit valence for atom # 5 B, 4, is greater than permitted
Skipping molecule at index 603 due to error: Can't kekulize mol.  Unkekulized atoms: 0 2 4 6 8
Skipping molecule at index 604 due to error: Explicit valence for atom # 10 B, 6, is greater than permitted
Skipping molecule at index 605 due to error: Explicit valence for atom # 1 B, 4, is greater than permitted
Skipping molecule at index 607 due to error: Explicit valence for atom # 2 C, 5, is greater than permitted
Skipping molecule at index 608 due to error: Explicit valence for atom # 7 B, 4, is greater than permitted
Skipping molecule at index 609 due to error: Explicit valence for atom # 3 O, 3, is greater than permitted
Skipping molecule at index 610 due to error: Explicit valence for atom # 5 B, 4, is greater than permitted
Skipping molecule at index 611 due to error: Explicit valence for atom # 4 O, 3, is greater than permitted
Skipping molecule at index 612 due to error: Explicit valence for atom # 4 O, 3, is greater than permitted
Skipping molecule at index 613 due to error: Explicit valence for atom # 2 B, 4, is greater than permitted
Skipping molecule at index 614 due to error: Explicit valence for atom # 8 B, 6, is greater than permitted
Skipping molecule at index 615 due to error: Explicit valence for atom # 4 C, 6, is greater than permitted
Skipping molecule at index 616 due to error: Can't kekulize mol.  Unkekulized atoms: 0 1 3 5 7 8 9 11 13 15
Skipping molecule at index 617 due to error: Can't kekulize mol.  Unkekulized atoms: 3 4 6 7 9
Skipping molecule at index 618 due to error: Explicit valence for atom # 3 O, 3, is greater than permitted
Skipping molecule at index 619 due to error: Explicit valence for atom # 6 O, 3, is greater than permitted
Skipping molecule at index 620 due to error: Explicit valence for atom # 5 O, 3, is greater than permitted
Skipping molecule at index 621 due to error: Explicit valence for atom # 5 O, 3, is greater than permitted
Skipping molecule at index 622 due to error: Explicit valence for atom # 5 O, 3, is greater than permitted
Skipping molecule at index 623 due to error: Explicit valence for atom # 0 O, 3, is greater than permitted
Skipping molecule at index 624 due to error: Explicit valence for atom # 10 C, 6, is greater than permitted
Skipping molecule at index 625 due to error: Can't kekulize mol.  Unkekulized atoms: 1 2 7 9 11 13 26 28 30 32 34
Skipping molecule at index 626 due to error: Explicit valence for atom # 4 C, 6, is greater than permitted
Skipping molecule at index 627 due to error: Explicit valence for atom # 7 B, 5, is greater than permitted
Skipping molecule at index 628 due to error: Explicit valence for atom # 4 O, 3, is greater than permitted
Skipping molecule at index 629 due to error: Explicit valence for atom # 4 O, 3, is greater than permitted
Skipping molecule at index 630 due to error: Explicit valence for atom # 4 O, 3, is greater than permitted
Skipping molecule at index 631 due to error: Explicit valence for atom # 3 O, 3, is greater than permitted
Skipping molecule at index 632 due to error: Explicit valence for atom # 8 O, 3, is greater than permitted
Skipping molecule at index 633 due to error: Explicit valence for atom # 7 B, 6, is greater than permitted
Skipping molecule at index 634 due to error: Explicit valence for atom # 1 B, 5, is greater than permitted
Skipping molecule at index 635 due to error: Explicit valence for atom # 82 B, 4, is greater than permitted
Skipping molecule at index 636 due to error: Explicit valence for atom # 82 B, 4, is greater than permitted
Skipping molecule at index 637 due to error: Explicit valence for atom # 59 B, 4, is greater than permitted
Skipping molecule at index 638 due to error: Explicit valence for atom # 85 B, 4, is greater than permitted
Skipping molecule at index 639 due to error: Explicit valence for atom # 62 B, 4, is greater than permitted
Skipping molecule at index 640 due to error: Explicit valence for atom # 68 B, 4, is greater than permitted
Skipping molecule at index 641 due to error: Explicit valence for atom # 2 B, 4, is greater than permitted
Skipping molecule at index 642 due to error: Explicit valence for atom # 4 C, 6, is greater than permitted
Skipping molecule at index 643 due to error: Explicit valence for atom # 22 C, 5, is greater than permitted
Skipping molecule at index 644 due to error: Explicit valence for atom # 5 B, 6, is greater than permitted
Skipping molecule at index 645 due to error: Can't kekulize mol.  Unkekulized atoms: 19 20 21 22 23 36 37 38 39 40
Skipping molecule at index 647 due to error: Explicit valence for atom # 4 O, 3, is greater than permitted
Skipping molecule at index 648 due to error: Explicit valence for atom # 6 O, 3, is greater than permitted
Skipping molecule at index 649 due to error: Explicit valence for atom # 56 C, 9, is greater than permitted
Skipping molecule at index 650 due to error: Explicit valence for atom # 34 C, 5, is greater than permitted
Skipping molecule at index 651 due to error: Explicit valence for atom # 7 O, 3, is greater than permitted
Skipping molecule at index 652 due to error: Explicit valence for atom # 8 O, 3, is greater than permitted
Skipping molecule at index 653 due to error: Explicit valence for atom # 0 C, 6, is greater than permitted
Skipping molecule at index 654 due to error: Explicit valence for atom # 0 C, 6, is greater than permitted
Skipping molecule at index 655 due to error: Explicit valence for atom # 0 C, 6, is greater than permitted
Skipping molecule at index 656 due to error: Explicit valence for atom # 0 C, 6, is greater than permitted
Skipping molecule at index 657 due to error: Explicit valence for atom # 1 H, 3, is greater than permitted
Skipping molecule at index 660 due to error: Explicit valence for atom # 8 O, 3, is greater than permitted
Skipping molecule at index 661 due to error: Explicit valence for atom # 3 B, 6, is greater than permitted
Skipping molecule at index 663 due to error: Explicit valence for atom # 3 O, 3, is greater than permitted
Skipping molecule at index 664 due to error: Explicit valence for atom # 3 O, 3, is greater than permitted
Skipping molecule at index 665 due to error: Explicit valence for atom # 5 O, 3, is greater than permitted
Skipping molecule at index 666 due to error: Explicit valence for atom # 2 O, 3, is greater than permitted
Skipping molecule at index 667 due to error: Explicit valence for atom # 2 O, 3, is greater than permitted
Skipping molecule at index 668 due to error: Explicit valence for atom # 3 B, 4, is greater than permitted
Skipping molecule at index 669 due to error: Explicit valence for atom # 5 O, 3, is greater than permitted
Skipping molecule at index 670 due to error: Explicit valence for atom # 5 B, 6, is greater than permitted
Skipping molecule at index 671 due to error: Explicit valence for atom # 5 B, 6, is greater than permitted
Skipping molecule at index 672 due to error: Explicit valence for atom # 3 B, 6, is greater than permitted
Skipping molecule at index 673 due to error: Explicit valence for atom # 5 B, 6, is greater than permitted
Skipping molecule at index 675 due to error: Explicit valence for atom # 0 B, 6, is greater than permitted
Skipping molecule at index 676 due to error: Explicit valence for atom # 9 B, 4, is greater than permitted
Skipping molecule at index 680 due to error: Explicit valence for atom # 89 O, 3, is greater than permitted
Skipping molecule at index 681 due to error: Can't kekulize mol.  Unkekulized atoms: 5 26 43 69 78
Skipping molecule at index 682 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 683 due to error: Explicit valence for atom # 88 B, 4, is greater than permitted
Skipping molecule at index 687 due to error: Explicit valence for atom # 3 B, 6, is greater than permitted
Skipping molecule at index 694 due to error: Explicit valence for atom # 0 B, 5, is greater than permitted
Skipping molecule at index 695 due to error: Explicit valence for atom # 6 C, 5, is greater than permitted
Skipping molecule at index 696 due to error: Explicit valence for atom # 2 O, 3, is greater than permitted
Skipping molecule at index 697 due to error: Explicit valence for atom # 8 O, 3, is greater than permitted
Skipping molecule at index 698 due to error: Explicit valence for atom # 53 O, 3, is greater than permitted
Skipping molecule at index 699 due to error: Explicit valence for atom # 7 C, 6, is greater than permitted
Skipping molecule at index 700 due to error: Explicit valence for atom # 7 C, 6, is greater than permitted
Skipping molecule at index 703 due to error: Explicit valence for atom # 3 C, 5, is greater than permitted
Skipping molecule at index 704 due to error: Explicit valence for atom # 1 C, 5, is greater than permitted
Skipping molecule at index 705 due to error: Explicit valence for atom # 4 O, 3, is greater than permitted
Skipping molecule at index 706 due to error: Explicit valence for atom # 4 O, 3, is greater than permitted
Skipping molecule at index 710 due to error: Explicit valence for atom # 2 H, 2, is greater than permitted
Skipping molecule at index 711 due to error: Explicit valence for atom # 8 B, 4, is greater than permitted
Skipping molecule at index 712 due to error: Explicit valence for atom # 81 B, 4, is greater than permitted
Skipping molecule at index 713 due to error: Explicit valence for atom # 96 B, 4, is greater than permitted
Skipping molecule at index 715 due to error: Explicit valence for atom # 19 B, 4, is greater than permitted
Skipping molecule at index 716 due to error: Explicit valence for atom # 5 O, 3, is greater than permitted
Skipping molecule at index 717 due to error: Explicit valence for atom # 12 In, 5, is greater than permitted
Skipping molecule at index 718 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 720 due to error: Explicit valence for atom # 62 B, 4, is greater than permitted
Skipping molecule at index 721 due to error: Explicit valence for atom # 0 C, 6, is greater than permitted
Skipping molecule at index 722 due to error: Explicit valence for atom # 4 O, 3, is greater than permitted
Skipping molecule at index 723 due to error: Explicit valence for atom # 2 O, 3, is greater than permitted
Skipping molecule at index 724 due to error: Explicit valence for atom # 2 B, 4, is greater than permitted
Skipping molecule at index 725 due to error: Explicit valence for atom # 1 B, 4, is greater than permitted
Skipping molecule at index 726 due to error: Explicit valence for atom # 16 B, 4, is greater than permitted
Skipping molecule at index 727 due to error: Explicit valence for atom # 115 B, 4, is greater than permitted
Skipping molecule at index 728 due to error: Explicit valence for atom # 83 B, 6, is greater than permitted
Skipping molecule at index 729 due to error: Explicit valence for atom # 105 B, 4, is greater than permitted
Skipping molecule at index 730 due to error: Explicit valence for atom # 5 B, 6, is greater than permitted
Skipping molecule at index 731 due to error: Explicit valence for atom # 5 B, 6, is greater than permitted
Skipping molecule at index 732 due to error: Explicit valence for atom # 4 C, 6, is greater than permitted
Skipping molecule at index 733 due to error: Explicit valence for atom # 4 C, 6, is greater than permitted
Skipping molecule at index 735 due to error: Explicit valence for atom # 2 O, 3, is greater than permitted
Skipping molecule at index 736 due to error: Explicit valence for atom # 7 Al, 4, is greater than permitted
Skipping molecule at index 738 due to error: Explicit valence for atom # 5 O, 3, is greater than permitted
Skipping molecule at index 739 due to error: Explicit valence for atom # 7 O, 3, is greater than permitted
Skipping molecule at index 740 due to error: Explicit valence for atom # 11 B, 4, is greater than permitted
Skipping molecule at index 741 due to error: Explicit valence for atom # 6 B, 4, is greater than permitted
Skipping molecule at index 742 due to error: Explicit valence for atom # 2 B, 6, is greater than permitted
Skipping molecule at index 743 due to error: Explicit valence for atom # 4 B, 4, is greater than permitted
Skipping molecule at index 744 due to error: Explicit valence for atom # 77 B, 4, is greater than permitted
Skipping molecule at index 745 due to error: Explicit valence for atom # 10 B, 4, is greater than permitted
Skipping molecule at index 746 due to error: Explicit valence for atom # 3 B, 4, is greater than permitted
Skipping molecule at index 748 due to error: Explicit valence for atom # 92 O, 3, is greater than permitted
Skipping molecule at index 749 due to error: Explicit valence for atom # 31 O, 3, is greater than permitted

[10:29:06] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:06] Explicit valence for atom # 0 C, 6, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:06] Explicit valence for atom # 0 C, 6, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:06] Explicit valence for atom # 0 C, 6, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Explicit valence for atom # 1 H, 3, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:06] Explicit valence for atom # 8 O, 3, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:06] Explicit valence for atom # 3 B, 6, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:06] Explicit valence for atom # 3 O, 3, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Explicit valence for atom # 3 O, 3, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:06] Explicit valence for atom # 5 O, 3, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:06] Explicit valence for atom # 2 O, 3, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:06] Explicit valence for atom # 2 O, 3, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Explicit valence for atom # 3 B, 4, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:06] Explicit valence for atom # 5 O, 3, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:06] Explicit valence for atom # 5 B, 6, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:06] Explicit valence for atom # 5 B, 6, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:06] Explicit valence for atom # 3 B, 6, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:06] Explicit valence for atom # 5 B, 6, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:06] Explicit valence for atom # 0 B, 6, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Explicit valence for atom # 9 B, 4, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Explicit valence for atom # 89 O, 3, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Can't kekulize mol.  Unkekulized atoms: 5 26 43 69 78
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Explicit valence for atom # 0 B, 4, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Explicit valence for atom # 88 B, 4, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:06] Explicit valence for atom # 3 B, 6, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Explicit valence for atom # 0 B, 5, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:06] Explicit valence for atom # 6 C, 5, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Explicit valence for atom # 2 O, 3, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Explicit valence for atom # 8 O, 3, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Explicit valence for atom # 53 O, 3, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:06] Explicit valence for atom # 7 C, 6, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:06] Explicit valence for atom # 7 C, 6, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:06] Explicit valence for atom # 3 C, 5, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:06] Explicit valence for atom # 1 C, 5, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Explicit valence for atom # 4 O, 3, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Explicit valence for atom # 4 O, 3, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Explicit valence for atom # 2 H, 2, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Explicit valence for atom # 8 B, 4, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Explicit valence for atom # 81 B, 4, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Explicit valence for atom # 96 B, 4, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Explicit valence for atom # 19 B, 4, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Explicit valence for atom # 5 O, 3, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Explicit valence for atom # 12 In, 5, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Explicit valence for atom # 0 B, 4, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Explicit valence for atom # 62 B, 4, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:06] Explicit valence for atom # 0 C, 6, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Explicit valence for atom # 4 O, 3, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Explicit valence for atom # 2 O, 3, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Explicit valence for atom # 2 B, 4, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Explicit valence for atom # 1 B, 4, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Explicit valence for atom # 16 B, 4, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Explicit valence for atom # 115 B, 4, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:06] Explicit valence for atom # 83 B, 6, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Explicit valence for atom # 105 B, 4, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:06] Explicit valence for atom # 5 B, 6, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:06] Explicit valence for atom # 5 B, 6, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:06] Explicit valence for atom # 4 C, 6, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:06] Explicit valence for atom # 4 C, 6, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Explicit valence for atom # 2 O, 3, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Explicit valence for atom # 7 Al, 4, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:06] Explicit valence for atom # 5 O, 3, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:06] Explicit valence for atom # 7 O, 3, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Explicit valence for atom # 11 B, 4, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Explicit valence for atom # 6 B, 4, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:06] Explicit valence for atom # 2 B, 6, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Explicit valence for atom # 4 B, 4, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Explicit valence for atom # 77 B, 4, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Explicit valence for atom # 10 B, 4, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Explicit valence for atom # 3 B, 4, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Explicit valence for atom # 92 O, 3, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Explicit valence for atom # 31 O, 3, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Explicit valence for atom # 1 O, 3, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Explicit valence for atom # 2 O, 3, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:06] Explicit valence for atom # 1 C, 6, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Explicit valence for atom # 33 B, 4, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.

Skipping molecule at index 750 due to error: Explicit valence for atom # 1 O, 3, is greater than permitted
Skipping molecule at index 751 due to error: Explicit valence for atom # 2 O, 3, is greater than permitted
Skipping molecule at index 752 due to error: Explicit valence for atom # 1 C, 6, is greater than permitted
Skipping molecule at index 753 due to error: Explicit valence for atom # 33 B, 4, is greater than permitted
Skipping molecule at index 756 due to error: Explicit valence for atom # 3 O, 3, is greater than permitted
Skipping molecule at index 757 due to error: Explicit valence for atom # 3 O, 3, is greater than permitted
Skipping molecule at index 758 due to error: Explicit valence for atom # 6 C, 4, is greater than permitted
Skipping molecule at index 759 due to error: Explicit valence for atom # 9 C, 4, is greater than permitted
Skipping molecule at index 760 due to error: Explicit valence for atom # 6 C, 6, is greater than permitted
Skipping molecule at index 761 due to error: Explicit valence for atom # 41 B, 6, is greater than permitted
Skipping molecule at index 762 due to error: Explicit valence for atom # 1 H, 2, is greater than permitted
Skipping molecule at index 766 due to error: Explicit valence for atom # 10 B, 4, is greater than permitted
Skipping molecule at index 767 due to error: Explicit valence for atom # 97 B, 4, is greater than permitted
Skipping molecule at index 768 due to error: Explicit valence for atom # 40 O, 3, is greater than permitted
Skipping molecule at index 770 due to error: Explicit valence for atom # 6 B, 6, is greater than permitted
Skipping molecule at index 771 due to error: Explicit valence for atom # 57 B, 6, is greater than permitted
Skipping molecule at index 772 due to error: Explicit valence for atom # 43 B, 6, is greater than permitted
Skipping molecule at index 773 due to error: Explicit valence for atom # 5 B, 4, is greater than permitted
Skipping molecule at index 774 due to error: Explicit valence for atom # 6 O, 3, is greater than permitted
Skipping molecule at index 775 due to error: Explicit valence for atom # 109 B, 4, is greater than permitted
Skipping molecule at index 776 due to error: Explicit valence for atom # 119 B, 4, is greater than permitted
Skipping molecule at index 777 due to error: Explicit valence for atom # 1 H, 2, is greater than permitted
Skipping molecule at index 778 due to error: Explicit valence for atom # 3 O, 3, is greater than permitted
Skipping molecule at index 782 due to error: Explicit valence for atom # 0 B, 5, is greater than permitted
Skipping molecule at index 783 due to error: Explicit valence for atom # 0 B, 6, is greater than permitted
Skipping molecule at index 784 due to error: Explicit valence for atom # 3 B, 4, is greater than permitted
Skipping molecule at index 785 due to error: Explicit valence for atom # 9 C, 6, is greater than permitted
Skipping molecule at index 786 due to error: Explicit valence for atom # 3 O, 3, is greater than permitted
Skipping molecule at index 787 due to error: Explicit valence for atom # 6 O, 3, is greater than permitted
Skipping molecule at index 790 due to error: Explicit valence for atom # 5 O, 3, is greater than permitted
Skipping molecule at index 791 due to error: Explicit valence for atom # 7 C, 6, is greater than permitted
Skipping molecule at index 792 due to error: Explicit valence for atom # 7 C, 6, is greater than permitted
Skipping molecule at index 793 due to error: Explicit valence for atom # 9 C, 6, is greater than permitted
Skipping molecule at index 794 due to error: Explicit valence for atom # 7 C, 6, is greater than permitted
Skipping molecule at index 795 due to error: Explicit valence for atom # 7 O, 3, is greater than permitted
Skipping molecule at index 796 due to error: Explicit valence for atom # 7 C, 5, is greater than permitted
Skipping molecule at index 797 due to error: Explicit valence for atom # 4 O, 3, is greater than permitted
Skipping molecule at index 798 due to error: Explicit valence for atom # 2 C, 6, is greater than permitted
Skipping molecule at index 799 due to error: Explicit valence for atom # 5 C, 6, is greater than permitted
Skipping molecule at index 800 due to error: Explicit valence for atom # 5 C, 6, is greater than permitted
Skipping molecule at index 801 due to error: Explicit valence for atom # 45 B, 4, is greater than permitted
Skipping molecule at index 802 due to error: Explicit valence for atom # 82 B, 4, is greater than permitted
Skipping molecule at index 815 due to error: Explicit valence for atom # 6 B, 4, is greater than permitted
Skipping molecule at index 816 due to error: Explicit valence for atom # 1 Sn, 6, is greater than permitted
Skipping molecule at index 817 due to error: Explicit valence for atom # 1 Sn, 6, is greater than permitted
Skipping molecule at index 818 due to error: Explicit valence for atom # 39 B, 6, is greater than permitted
Skipping molecule at index 819 due to error: Explicit valence for atom # 1 Sn, 6, is greater than permitted
Skipping molecule at index 820 due to error: Explicit valence for atom # 0 O, 3, is greater than permitted
Skipping molecule at index 822 due to error: Explicit valence for atom # 80 B, 4, is greater than permitted
Skipping molecule at index 825 due to error: Explicit valence for atom # 0 H, 2, is greater than permitted
Skipping molecule at index 826 due to error: Explicit valence for atom # 5 H, 2, is greater than permitted
Skipping molecule at index 827 due to error: Explicit valence for atom # 3 O, 3, is greater than permitted
Skipping molecule at index 828 due to error: Explicit valence for atom # 4 B, 7, is greater than permitted
Skipping molecule at index 829 due to error: Explicit valence for atom # 2 B, 4, is greater than permitted
Skipping molecule at index 830 due to error: Explicit valence for atom # 3 C, 5, is greater than permitted
Skipping molecule at index 831 due to error: Explicit valence for atom # 61 B, 4, is greater than permitted
Skipping molecule at index 832 due to error: Explicit valence for atom # 54 B, 4, is greater than permitted
Skipping molecule at index 833 due to error: Explicit valence for atom # 6 N, 4, is greater than permitted
Skipping molecule at index 834 due to error: Explicit valence for atom # 2 H, 2, is greater than permitted
Skipping molecule at index 835 due to error: Explicit valence for atom # 75 N, 4, is greater than permitted
Skipping molecule at index 838 due to error: Explicit valence for atom # 82 B, 4, is greater than permitted
Skipping molecule at index 840 due to error: Explicit valence for atom # 39 B, 4, is greater than permitted
Skipping molecule at index 841 due to error: Explicit valence for atom # 101 B, 4, is greater than permitted
Skipping molecule at index 842 due to error: Explicit valence for atom # 4 C, 6, is greater than permitted
Skipping molecule at index 846 due to error: Explicit valence for atom # 35 B, 4, is greater than permitted
Skipping molecule at index 847 due to error: Explicit valence for atom # 84 B, 6, is greater than permitted
Skipping molecule at index 848 due to error: Explicit valence for atom # 72 B, 6, is greater than permitted
Skipping molecule at index 849 due to error: Explicit valence for atom # 7 B, 6, is greater than permitted
Skipping molecule at index 850 due to error: Explicit valence for atom # 8 B, 6, is greater than permitted
Skipping molecule at index 851 due to error: Explicit valence for atom # 40 B, 4, is greater than permitted
Skipping molecule at index 852 due to error: Explicit valence for atom # 19 B, 4, is greater than permitted
Skipping molecule at index 853 due to error: Explicit valence for atom # 4 O, 3, is greater than permitted
Skipping molecule at index 854 due to error: Explicit valence for atom # 2 O, 3, is greater than permitted
Skipping molecule at index 855 due to error: Explicit valence for atom # 4 O, 3, is greater than permitted
Skipping molecule at index 860 due to error: Explicit valence for atom # 3 B, 4, is greater than permitted
Skipping molecule at index 861 due to error: Explicit valence for atom # 48 B, 4, is greater than permitted
Skipping molecule at index 862 due to error: Explicit valence for atom # 103 B, 4, is greater than permitted
Skipping molecule at index 863 due to error: Explicit valence for atom # 103 B, 4, is greater than permitted
Skipping molecule at index 864 due to error: Explicit valence for atom # 93 B, 4, is greater than permitted
Skipping molecule at index 865 due to error: Explicit valence for atom # 93 B, 4, is greater than permitted
Skipping molecule at index 866 due to error: Explicit valence for atom # 94 B, 4, is greater than permitted
Skipping molecule at index 867 due to error: Explicit valence for atom # 9 B, 4, is greater than permitted
Skipping molecule at index 868 due to error: Explicit valence for atom # 4 C, 6, is greater than permitted
Skipping molecule at index 870 due to error: Explicit valence for atom # 3 B, 4, is greater than permitted
Skipping molecule at index 871 due to error: Explicit valence for atom # 68 B, 4, is greater than permitted
Skipping molecule at index 872 due to error: Can't kekulize mol.  Unkekulized atoms: 18 19 20 21 25 27 29 36
Skipping molecule at index 873 due to error: Explicit valence for atom # 3 B, 4, is greater than permitted
Skipping molecule at index 875 due to error: Explicit valence for atom # 61 B, 4, is greater than permitted
Skipping molecule at index 877 due to error: Explicit valence for atom # 10 B, 4, is greater than permitted
Skipping molecule at index 878 due to error: Explicit valence for atom # 1 B, 4, is greater than permitted
Skipping molecule at index 879 due to error: Explicit valence for atom # 8 B, 4, is greater than permitted
Skipping molecule at index 880 due to error: Explicit valence for atom # 2 O, 3, is greater than permitted
Skipping molecule at index 881 due to error: Explicit valence for atom # 2 O, 3, is greater than permitted
Skipping molecule at index 882 due to error: Explicit valence for atom # 3 B, 6, is greater than permitted
Skipping molecule at index 883 due to error: Explicit valence for atom # 3 O, 3, is greater than permitted
Skipping molecule at index 884 due to error: Explicit valence for atom # 11 B, 6, is greater than permitted
Skipping molecule at index 886 due to error: Explicit valence for atom # 3 B, 5, is greater than permitted
Skipping molecule at index 887 due to error: Explicit valence for atom # 4 O, 3, is greater than permitted
Skipping molecule at index 888 due to error: Explicit valence for atom # 7 O, 3, is greater than permitted
Skipping molecule at index 889 due to error: Explicit valence for atom # 6 B, 6, is greater than permitted
Skipping molecule at index 890 due to error: Explicit valence for atom # 11 B, 5, is greater than permitted
Skipping molecule at index 891 due to error: Explicit valence for atom # 4 O, 3, is greater than permitted
Skipping molecule at index 892 due to error: Explicit valence for atom # 18 N, 4, is greater than permitted
Skipping molecule at index 894 due to error: Explicit valence for atom # 73 B, 5, is greater than permitted
Skipping molecule at index 895 due to error: Explicit valence for atom # 4 O, 3, is greater than permitted
Skipping molecule at index 896 due to error: Explicit valence for atom # 3 C, 5, is greater than permitted
Skipping molecule at index 897 due to error: Explicit valence for atom # 10 B, 4, is greater than permitted
Skipping molecule at index 898 due to error: Explicit valence for atom # 78 F, 2, is greater than permitted
Skipping molecule at index 899 due to error: Explicit valence for atom # 2 C, 5, is greater than permitted
Skipping molecule at index 900 due to error: Explicit valence for atom # 1 C, 5, is greater than permitted
Skipping molecule at index 901 due to error: Explicit valence for atom # 2 C, 5, is greater than permitted
Skipping molecule at index 902 due to error: Explicit valence for atom # 2 C, 5, is greater than permitted
Skipping molecule at index 903 due to error: Explicit valence for atom # 3 O, 3, is greater than permitted
Skipping molecule at index 904 due to error: Explicit valence for atom # 4 O, 3, is greater than permitted
Skipping molecule at index 907 due to error: Explicit valence for atom # 20 B, 4, is greater than permitted
Skipping molecule at index 908 due to error: Explicit valence for atom # 12 B, 4, is greater than permitted
Skipping molecule at index 909 due to error: Explicit valence for atom # 15 B, 4, is greater than permitted
Skipping molecule at index 910 due to error: Explicit valence for atom # 15 B, 4, is greater than permitted
Skipping molecule at index 911 due to error: Explicit valence for atom # 8 B, 4, is greater than permitted

[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Explicit valence for atom # 80 B, 4, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:06] Explicit valence for atom # 0 H, 2, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Explicit valence for atom # 5 H, 2, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Explicit valence for atom # 3 O, 3, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Explicit valence for atom # 4 B, 7, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Explicit valence for atom # 2 B, 4, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:06] Explicit valence for atom # 3 C, 5, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Explicit valence for atom # 61 B, 4, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Explicit valence for atom # 54 B, 4, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Explicit valence for atom # 6 N, 4, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Explicit valence for atom # 2 H, 2, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Explicit valence for atom # 75 N, 4, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Explicit valence for atom # 82 B, 4, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Explicit valence for atom # 39 B, 4, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Explicit valence for atom # 101 B, 4, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:06] Explicit valence for atom # 4 C, 6, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Explicit valence for atom # 35 B, 4, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:06] Explicit valence for atom # 84 B, 6, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:06] Explicit valence for atom # 72 B, 6, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:06] Explicit valence for atom # 7 B, 6, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:06] Explicit valence for atom # 8 B, 6, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Explicit valence for atom # 40 B, 4, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Explicit valence for atom # 19 B, 4, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:06] Explicit valence for atom # 4 O, 3, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:06] Explicit valence for atom # 2 O, 3, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:06] Explicit valence for atom # 4 O, 3, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Explicit valence for atom # 3 B, 4, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Explicit valence for atom # 48 B, 4, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Explicit valence for atom # 103 B, 4, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Explicit valence for atom # 103 B, 4, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Explicit valence for atom # 93 B, 4, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Explicit valence for atom # 93 B, 4, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Explicit valence for atom # 94 B, 4, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Explicit valence for atom # 9 B, 4, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:06] Explicit valence for atom # 4 C, 6, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Explicit valence for atom # 3 B, 4, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Explicit valence for atom # 68 B, 4, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Can't kekulize mol.  Unkekulized atoms: 18 19 20 21 25 27 29 36
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Explicit valence for atom # 3 B, 4, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Explicit valence for atom # 61 B, 4, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Explicit valence for atom # 10 B, 4, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Explicit valence for atom # 1 B, 4, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Explicit valence for atom # 8 B, 4, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Explicit valence for atom # 2 O, 3, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Explicit valence for atom # 2 O, 3, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:06] Explicit valence for atom # 3 B, 6, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:06] Explicit valence for atom # 3 O, 3, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:06] Explicit valence for atom # 11 B, 6, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Explicit valence for atom # 3 B, 5, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Explicit valence for atom # 4 O, 3, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Explicit valence for atom # 7 O, 3, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:06] Explicit valence for atom # 6 B, 6, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:06] Explicit valence for atom # 11 B, 5, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Explicit valence for atom # 4 O, 3, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Explicit valence for atom # 18 N, 4, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:06] Explicit valence for atom # 73 B, 5, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Explicit valence for atom # 4 O, 3, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:06] Explicit valence for atom # 3 C, 5, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Explicit valence for atom # 10 B, 4, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Explicit valence for atom # 78 F, 2, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:06] Explicit valence for atom # 2 C, 5, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:06] Explicit valence for atom # 1 C, 5, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:06] Explicit valence for atom # 2 C, 5, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:06] Explicit valence for atom # 2 C, 5, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Explicit valence for atom # 3 O, 3, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Explicit valence for atom # 4 O, 3, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Explicit valence for atom # 20 B, 4, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Explicit valence for atom # 12 B, 4, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Explicit valence for atom # 15 B, 4, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Explicit valence for atom # 15 B, 4, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Explicit valence for atom # 8 B, 4, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:06] Explicit valence for atom # 5 O, 3, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:06] Explicit valence for atom # 5 O, 3, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:06] Explicit valence for atom # 3 O, 3, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:06] Explicit valence for atom # 5 O, 3, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Explicit valence for atom # 8 Al, 4, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Explicit valence for atom # 3 O, 3, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Explicit valence for atom # 7 B, 4, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Explicit valence for atom # 1 B, 4, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.

Skipping molecule at index 912 due to error: Explicit valence for atom # 5 O, 3, is greater than permitted
Skipping molecule at index 913 due to error: Explicit valence for atom # 5 O, 3, is greater than permitted
Skipping molecule at index 914 due to error: Explicit valence for atom # 3 O, 3, is greater than permitted
Skipping molecule at index 915 due to error: Explicit valence for atom # 5 O, 3, is greater than permitted
Skipping molecule at index 917 due to error: Explicit valence for atom # 8 Al, 4, is greater than permitted
Skipping molecule at index 918 due to error: Explicit valence for atom # 3 O, 3, is greater than permitted
Skipping molecule at index 920 due to error: Explicit valence for atom # 7 B, 4, is greater than permitted
Skipping molecule at index 921 due to error: Explicit valence for atom # 1 B, 4, is greater than permitted
Skipping molecule at index 922 due to error: Explicit valence for atom # 0 C, 5, is greater than permitted
Skipping molecule at index 923 due to error: Explicit valence for atom # 0 C, 5, is greater than permitted
Skipping molecule at index 924 due to error: Explicit valence for atom # 4 B, 6, is greater than permitted
Skipping molecule at index 925 due to error: Explicit valence for atom # 7 B, 5, is greater than permitted
Skipping molecule at index 926 due to error: Explicit valence for atom # 5 O, 3, is greater than permitted
Skipping molecule at index 927 due to error: Explicit valence for atom # 41 B, 6, is greater than permitted
Skipping molecule at index 928 due to error: Explicit valence for atom # 0 C, 5, is greater than permitted
Skipping molecule at index 929 due to error: Explicit valence for atom # 4 O, 3, is greater than permitted
Skipping molecule at index 930 due to error: Explicit valence for atom # 70 B, 4, is greater than permitted
Skipping molecule at index 931 due to error: Explicit valence for atom # 5 B, 4, is greater than permitted
Skipping molecule at index 932 due to error: Explicit valence for atom # 80 B, 4, is greater than permitted
Skipping molecule at index 933 due to error: Explicit valence for atom # 91 B, 4, is greater than permitted
Skipping molecule at index 934 due to error: Explicit valence for atom # 84 B, 4, is greater than permitted
Skipping molecule at index 935 due to error: Explicit valence for atom # 5 B, 4, is greater than permitted
Skipping molecule at index 936 due to error: Explicit valence for atom # 1 H, 2, is greater than permitted
Skipping molecule at index 937 due to error: Explicit valence for atom # 0 C, 5, is greater than permitted
Skipping molecule at index 938 due to error: Explicit valence for atom # 2 B, 5, is greater than permitted
Skipping molecule at index 939 due to error: Explicit valence for atom # 1 B, 4, is greater than permitted
Skipping molecule at index 945 due to error: Explicit valence for atom # 1 B, 4, is greater than permitted
Skipping molecule at index 946 due to error: Explicit valence for atom # 90 B, 4, is greater than permitted
Skipping molecule at index 947 due to error: Explicit valence for atom # 4 C, 6, is greater than permitted
Skipping molecule at index 949 due to error: Explicit valence for atom # 4 B, 4, is greater than permitted
Skipping molecule at index 951 due to error: Explicit valence for atom # 6 C, 6, is greater than permitted
Skipping molecule at index 952 due to error: Explicit valence for atom # 6 C, 6, is greater than permitted
Skipping molecule at index 953 due to error: Explicit valence for atom # 6 C, 6, is greater than permitted
Skipping molecule at index 954 due to error: Explicit valence for atom # 6 C, 6, is greater than permitted
Skipping molecule at index 955 due to error: Explicit valence for atom # 11 O, 3, is greater than permitted
Skipping molecule at index 957 due to error: Explicit valence for atom # 3 C, 6, is greater than permitted
Skipping molecule at index 958 due to error: Explicit valence for atom # 67 O, 3, is greater than permitted
Skipping molecule at index 959 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 960 due to error: Explicit valence for atom # 27 C, 6, is greater than permitted
Skipping molecule at index 961 due to error: Explicit valence for atom # 41 C, 5, is greater than permitted
Skipping molecule at index 962 due to error: Explicit valence for atom # 41 C, 5, is greater than permitted
Skipping molecule at index 963 due to error: Explicit valence for atom # 40 H, 2, is greater than permitted
Skipping molecule at index 964 due to error: Explicit valence for atom # 74 B, 6, is greater than permitted
Skipping molecule at index 965 due to error: Explicit valence for atom # 69 B, 6, is greater than permitted
Skipping molecule at index 967 due to error: Explicit valence for atom # 80 B, 6, is greater than permitted
Skipping molecule at index 969 due to error: Explicit valence for atom # 0 C, 6, is greater than permitted
Skipping molecule at index 970 due to error: Explicit valence for atom # 0 C, 6, is greater than permitted
Skipping molecule at index 971 due to error: Explicit valence for atom # 9 C, 5, is greater than permitted
Skipping molecule at index 972 due to error: Can't kekulize mol.  Unkekulized atoms: 32 33 35 37 39
Skipping molecule at index 973 due to error: Explicit valence for atom # 5 C, 6, is greater than permitted
Skipping molecule at index 974 due to error: Explicit valence for atom # 0 C, 6, is greater than permitted
Skipping molecule at index 975 due to error: Explicit valence for atom # 5 B, 4, is greater than permitted
Skipping molecule at index 976 due to error: Explicit valence for atom # 4 O, 3, is greater than permitted
Skipping molecule at index 977 due to error: Explicit valence for atom # 8 O, 3, is greater than permitted
Skipping molecule at index 978 due to error: Explicit valence for atom # 11 B, 6, is greater than permitted
Skipping molecule at index 979 due to error: Explicit valence for atom # 6 O, 3, is greater than permitted
Skipping molecule at index 981 due to error: Explicit valence for atom # 6 O, 3, is greater than permitted
Skipping molecule at index 982 due to error: Explicit valence for atom # 4 O, 3, is greater than permitted
Skipping molecule at index 983 due to error: Explicit valence for atom # 3 O, 3, is greater than permitted
Skipping molecule at index 984 due to error: Can't kekulize mol.  Unkekulized atoms: 2 4 6 8 10
Skipping molecule at index 987 due to error: Explicit valence for atom # 81 B, 4, is greater than permitted
Skipping molecule at index 988 due to error: Explicit valence for atom # 3 C, 6, is greater than permitted
Skipping molecule at index 989 due to error: Explicit valence for atom # 110 F, 2, is greater than permitted
Skipping molecule at index 991 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 992 due to error: Explicit valence for atom # 77 B, 4, is greater than permitted
Skipping molecule at index 993 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 994 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 995 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 996 due to error: Explicit valence for atom # 0 B, 4, is greater than permitted
Skipping molecule at index 997 due to error: Explicit valence for atom # 1 H, 2, is greater than permitted
Skipping molecule at index 998 due to error: Explicit valence for atom # 2 B, 4, is greater than permitted
Skipping molecule at index 1001 due to error: Explicit valence for atom # 2 O, 3, is greater than permitted
Skipping molecule at index 1002 due to error: Explicit valence for atom # 1 C, 5, is greater than permitted
Skipping molecule at index 1003 due to error: Explicit valence for atom # 1 C, 5, is greater than permitted
Skipping molecule at index 1004 due to error: Explicit valence for atom # 4 C, 5, is greater than permitted
Skipping molecule at index 1005 due to error: Explicit valence for atom # 8 B, 4, is greater than permitted
Skipping molecule at index 1006 due to error: Explicit valence for atom # 6 B, 4, is greater than permitted
Skipping molecule at index 1007 due to error: Explicit valence for atom # 1 H, 2, is greater than permitted
Skipping molecule at index 1008 due to error: Explicit valence for atom # 5 O, 3, is greater than permitted
Skipping molecule at index 1009 due to error: Explicit valence for atom # 5 O, 3, is greater than permitted
Skipping molecule at index 1010 due to error: Explicit valence for atom # 4 B, 5, is greater than permitted
Skipping molecule at index 1011 due to error: Explicit valence for atom # 4 B, 5, is greater than permitted
Skipping molecule at index 1012 due to error: Explicit valence for atom # 4 O, 3, is greater than permitted
Skipping molecule at index 1013 due to error: Explicit valence for atom # 4 O, 3, is greater than permitted
Skipping molecule at index 1014 due to error: Explicit valence for atom # 1 B, 4, is greater than permitted
Skipping molecule at index 1016 due to error: Explicit valence for atom # 67 O, 3, is greater than permitted
Skipping molecule at index 1017 due to error: Explicit valence for atom # 2 H, 2, is greater than permitted
Skipping molecule at index 1018 due to error: Explicit valence for atom # 0 B, 6, is greater than permitted
Skipping molecule at index 1019 due to error: Explicit valence for atom # 1 B, 6, is greater than permitted
Skipping molecule at index 1020 due to error: Explicit valence for atom # 75 B, 4, is greater than permitted
Skipping molecule at index 1021 due to error: Explicit valence for atom # 4 B, 4, is greater than permitted
Skipping molecule at index 1022 due to error: Explicit valence for atom # 4 B, 4, is greater than permitted
Skipping molecule at index 1025 due to error: Explicit valence for atom # 1 C, 6, is greater than permitted
Skipping molecule at index 1026 due to error: Explicit valence for atom # 49 B, 5, is greater than permitted
Skipping molecule at index 1027 due to error: Explicit valence for atom # 13 B, 4, is greater than permitted
Skipping molecule at index 1032 due to error: Explicit valence for atom # 2 B, 5, is greater than permitted
Skipping molecule at index 1033 due to error: Can't kekulize mol.  Unkekulized atoms: 3 10 14 17 19
Skipping molecule at index 1034 due to error: Explicit valence for atom # 4 B, 6, is greater than permitted
Skipping molecule at index 1035 due to error: Explicit valence for atom # 3 O, 3, is greater than permitted
Skipping molecule at index 1037 due to error: Explicit valence for atom # 7 O, 3, is greater than permitted
Skipping molecule at index 1038 due to error: Explicit valence for atom # 31 B, 4, is greater than permitted

[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Explicit valence for atom # 81 B, 4, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:06] Explicit valence for atom # 3 C, 6, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:06] Explicit valence for atom # 110 F, 2, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Explicit valence for atom # 0 B, 4, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Explicit valence for atom # 77 B, 4, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Explicit valence for atom # 0 B, 4, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Explicit valence for atom # 0 B, 4, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Explicit valence for atom # 0 B, 4, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Explicit valence for atom # 0 B, 4, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Explicit valence for atom # 1 H, 2, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Explicit valence for atom # 2 B, 4, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:06] Explicit valence for atom # 2 O, 3, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:06] Explicit valence for atom # 1 C, 5, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:06] Explicit valence for atom # 1 C, 5, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:06] Explicit valence for atom # 4 C, 5, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Explicit valence for atom # 8 B, 4, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Explicit valence for atom # 6 B, 4, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Explicit valence for atom # 1 H, 2, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:06] Explicit valence for atom # 5 O, 3, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:06] Explicit valence for atom # 5 O, 3, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:06] Explicit valence for atom # 4 B, 5, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:06] Explicit valence for atom # 4 B, 5, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Explicit valence for atom # 4 O, 3, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Explicit valence for atom # 4 O, 3, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Explicit valence for atom # 1 B, 4, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Explicit valence for atom # 67 O, 3, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:06] Explicit valence for atom # 2 H, 2, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:06] Explicit valence for atom # 0 B, 6, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Explicit valence for atom # 1 B, 6, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Explicit valence for atom # 75 B, 4, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Explicit valence for atom # 4 B, 4, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Explicit valence for atom # 4 B, 4, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:06] Explicit valence for atom # 1 C, 6, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[10:29:06] Explicit valence for atom # 49 B, 5, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Explicit valence for atom # 13 B, 4, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Explicit valence for atom # 2 B, 5, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Can't kekulize mol.  Unkekulized atoms: 3 10 14 17 19
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Explicit valence for atom # 4 B, 6, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:06] Explicit valence for atom # 3 O, 3, is greater than permitted
[10:29:06] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:07] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:07] Explicit valence for atom # 7 O, 3, is greater than permitted
[10:29:07] Warning: molecule is tagged as 2D, but at least one Z coordinate is not zero. Marking the mol as 3D.
[10:29:07] Explicit valence for atom # 31 B, 4, is greater than permitted

In [4]:
df1

                                                 SMILES  Molecular Weight
0     [H]C([H])([H])C([H])([H])N(C([H])([H])C([H])([...        826.225725
1     [H]c1c([H])c([H])c(-c2c(-c3c([H])c([H])c(OC([H...       1716.944090
2     [H]C1=C([H])C2(C([H])=C([H])C1=O)c1c([H])c(OC(...       1700.912790
3     [H]C1=C([H])[Si@@]2(B3N(c4c(C([H])(C([H])([H])...        986.609048
4     [H]C1=C([H])[Si@@]23O[Si@]4(B5N(C(=C1C([H])(C(...        902.605677
...                                                 ...               ...
1016  [H]c1c([H])c(C([H])([H])[N+]([Na](<-O2C([H])([...       1391.194279
1017  [H]c1c([H])c(-c2n([B-](c3c(F)c(F)c(F)c(F)c3F)(...       1278.100593
1018  [H]c1c([H])c(-c2n([B-](c3c(F)c(F)c(F)c(F)c3F)(...       1225.037659
1019  [H]C1=C([H])N(C([H])([H])C([H])([H])C([H])([H]...        978.099850
1020  [H]OB(OC([H])([H])[H])c1c([H])c([H])c(F)c([H])...        490.203577

[1021 rows x 2 columns]

In [5]:
df2

                                                SMILES  Molecular Weight
0    [H]C([H])([H])C([H])([H])N(C([H])([H])C([H])([...        826.225725
1    [H]/C1=C(/c2c([H])c([H])c([H])c([H])c2[H])[C@]...       1868.069722
2    [H]/C1=C(/[H])[P+](c2c([H])c([H])c([H])c([H])c...       1324.205729
3    [H]C(/C([H])=C(\[H])[P+](c1c([H])c([H])c([H])c...       1170.200250
4    [H]C1=C(C2=C([H])[P+](c3c(C([H])([H])[H])c([H]...       1490.377880
..                                                 ...               ...
222  [H]C1=C([H])N(c2c(C([H])(C([H])([H])[H])C([H])...        892.531662
223  [H]C1=C([H])N(c2c(C([H])(C([H])([H])[H])C([H])...        864.536747
224  [H]C1=C([H])N(c2c(C([H])(C([H])([H])[H])C([H])...       1058.560905
225  [H]C1=C([H])N(c2c(C([H])(C([H])([H])[H])C([H])...       1144.735821
226  [H]c1c([H])c([H])c([PH](c2c([H])c([H])c([H])c(...        975.348785

[227 rows x 2 columns]

In [9]:
df1['count'] = df1.groupby(['SMILES','Molecular Weight']).cumcount()
df2['count'] = df2.groupby(['SMILES','Molecular Weight']).cumcount()

In [12]:
combined_df = pd.concat([df1, df2], ignore_index=False)

In [18]:
combined_df = combined_df.drop_duplicates()

In [19]:
combined_df = combined_df.drop(['count'], axis=1)

In [20]:
combined_df

                                                SMILES  Molecular Weight
0    [H]C([H])([H])C([H])([H])N(C([H])([H])C([H])([...        826.225725
1    [H]c1c([H])c([H])c(-c2c(-c3c([H])c([H])c(OC([H...       1716.944090
2    [H]C1=C([H])C2(C([H])=C([H])C1=O)c1c([H])c(OC(...       1700.912790
3    [H]C1=C([H])[Si@@]2(B3N(c4c(C([H])(C([H])([H])...        986.609048
4    [H]C1=C([H])[Si@@]23O[Si@]4(B5N(C(=C1C([H])(C(...        902.605677
..                                                 ...               ...
216  CC(C)[C@H]1OB(c2ccccc2)O[C@@H](C(C)C)[PH]1(c1c...        947.270841
217  [H]c1c([H])c([H])c([PH](c2c([H])c([H])c([H])c(...        959.223585
219  [H]O[B@-]12c3c([H])c([H])c([H])c([H])c3[PH](C(...        776.295394
221  [H]c1c([H])c([H])c([PH]2(c3c([H])c([H])c([H])c...       1596.440788
226  [H]c1c([H])c([H])c([PH](c2c([H])c([H])c([H])c(...        975.348785

[1158 rows x 2 columns]

In [21]:
#combined_df.to_pickle("data.pkl")